### ISSUE TITLE
Support Python >=3.10,<4

### ISSUE THREAD

**Issue by tachylatus** [sdv-dev/SDV#1000]
The package builds and runs with Python 3.10 (also in development mode). 
_Originally posted by @gboehl in https://github.com/sdv-dev/Copulas/issues/195#issuecomment-1013858553_

Python 3.10 was first released on 2021-10-04, and Python 3.11 is right around the corner.

You should either change the `python_requires` version constraint to `>=3.6,<4` or remove it entirely.
If it would ease the maintenance burden to drop support for Python 3.6, consider doing so as well, as it has not been supported for over a year now.

**Comment by amontanez24** [comment]
Resolved by #1179
