### ISSUE TITLE
How do you optimize the hyperparameters of the synthesizers in the library (and across datasets)?

### ISSUE THREAD

**Issue by farishaddad** [sdv-dev/SDV#1011]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:
* Python version:
* Operating System:

### Problem description

<Replace this with a description of the problem that you are trying to solve using SDV. If
possible, describe the data that you are using, or consider attaching some example data
that others can use to propose a working solution for your problem.>

### What I already tried

<Replace with a description of what you already tried and what is the behavior that you observe.
If possible, also add below the exact code that you are running.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @farishaddad, great question.

The default synthesizers for each of the models are meant to be a "good enough" starting point but they are not guaranteed to be optimized for every use case and dataset. There are eventually tradeoffs -- for eg. data quality, data privacy, modeling time, memory usage, etc.

I would recommend coming up with a success criteria based on your project requirements, and experimenting with different parameter values. There are some other open source solutions that automatically perform a search. One that I've seen users reference before is [BTB](https://github.com/MLBazaar/BTB).

If you are able to share more about a specific model and goals, I can point you in the right direction wrt parameters to test.

**Comment by npatki** [comment]
Hi @farishaddad, I'm closing this issue off since we answered your original question. If there are any follow ups, please feel free to respond and I'll reopen for investigation!
