### ISSUE TITLE
CTGAN & TVAE presented at NeurIPS 2019 (not 2020)

### ISSUE THREAD

**Issue by gabriel-berardi** [sdv-dev/SDV#1016]
### Problem Description

On the documentation pages for the [CTGAN](https://sdv.dev/SDV/user_guides/single_table/ctgan.html) and the [TVAE](https://sdv.dev/SDV/user_guides/single_table/tvae.html) models there seems to be a typo:

> The sdv.tabular.CTGAN model is based on the GAN-based Deep Learning data synthesizer which was presented at the NeurIPS **2020** conference by the paper titled [Modeling Tabular data using Conditional GAN](https://arxiv.org/abs/1907.00503).

> The sdv.tabular.TVAE model is based on the VAE-based Deep Learning data synthesizer which was presented at the NeurIPS **2020** conference by the paper titled [Modeling Tabular data using Conditional GAN](https://arxiv.org/abs/1907.00503).

If I look at the linked paper, it seems that it was accepted to the **2019** NeurIPS conference instead of the **2020** one. This also appears as an item on the schedule of the [NeurIPS conference in 2019](https://nips.cc/Conferences/2019/Schedule).

### Suggestion

Change the documentation pages for [CTGAN](https://sdv.dev/SDV/user_guides/single_table/ctgan.html) and [TVAE](https://sdv.dev/SDV/user_guides/single_table/tvae.html): "_...at the NeurIPS 2020..._" → "_...at the NeurIPS 2019..._"

**Comment by npatki** [comment]
Hi @gabriel-berardi, we now have a new [**SDV 1.0 (Beta!)**](https://docs.sdv.dev/sdv) release which comes with new documentation.

This issue has now been addressed in the new documentation. see new documentation for:
- [CTGANSynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer#fit)
- [TVAESynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/tvaesynthesizer#fit)

**Comment by limhasic** [comment]
is this same as TVAE(Triplet-based Variable AutoEncoders) and TVAE(Table VAE in Modeling Tabular Data using Conditional GAN
) ?
