### ISSUE TITLE
Min/Max values changing based on sample size or model?

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1025]
I have a single table data that has around 30 features and 60000 samples. With a trained model (say CTGAN), I generate two different sized dataset (say 1.000 and 100.000 samples). Do we have the knowledge that as the #of samples increase, the model generates more samples always distributed in between min and max values? Or does the model have the freedom to (i.e. 1000 sampled) move around some limited distribution range due to less #of samples? I mean, if we observe min and max values of the newly created dataset are not close to the original dataset (such as some missed/smoothed  outliers), is it related with being generated small #of samples (like 100 or 1000 samples)? Or is it the characteristic of the model?

_Originally posted by @handenurc in https://github.com/sdv-dev/SDV/issues/1022#issuecomment-1254624328_

**Comment by npatki** [comment]
Hi @handenurc, this is an interesting question. By default, models enforce that all values respect the min and max values observed in the real data. This guarantees 2 things:

1. Min value of synthetic data  ≥ the min value of the real data
2. Max value of synthetic data ≤ the max value of real data

As you point out, the range of synthetic data may be a smaller. For example if real data ranges from [0, 100], the synthetic data may range from [5, 95].

This can certainly be a result of the # of samples. At an extreme, if you only sample 2 synthetic rows, chances are that the range will be much smaller than the original. However, if you sample a very large number of rows (say 100x the original), it becomes unlikely that this is just a pure coincidence -- at that point it's likely based on the model.

A guaranteed answer may not be possible. With a GAN-based model (like CTGAN), it is difficult to know the exact information that the model learned. But with a statistical model, like [GaussianCopula](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html), the model explicitly computes & stores the distributions. 

Hope this helps!

**Comment by handenurc** [comment]
Thanks a lot for your answer, I'll continue to investigate on that issue. For now, things have been clarified enough for me. It's good to know that I can find the official support here if I have any other question :)

**Comment by npatki** [comment]
Sounds good! Always here to help.

I'll close this off as answered but feel free to reply is there are any follow-ups on this topic.
