### ISSUE TITLE
Rounding scheme cannot be turned off sometimes

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1040]
### Environment Details

* SDV version: 0.17.0
* Python version: 3.7
* Operating System: Linux

### Error Description

The `learn_rounding_scheme` parameter is available for all single table models. By default it is `True`.

When I specify the `learn_rounding_scheme=False`, the rounding scheme still gets enforced sometimes. In particular, it seems to happen when the original data has >14 digits.

### Steps to reproduce

```python
from sdv.tabular import GaussianCopula
import pandas as pd
import numpy as np

test_data = pd.DataFrame(data={
    'column': [0.123456789012345]*10
})

model = GaussianCopula(
    learn_rounding_scheme=False)

model.fit(test_data.round(4))
model.sample(num_rows=5)
```

All outputs have 4 digits even though I explicitly turned the rounding scheme off. Note that this is probably related to #1039

**Comment by sharisiri** [comment]
Hi there, I'm trying to run the FAST_ML preset in the [tabular model tutorial](https://sdv.dev/SDV/user_guides/single_table/tabular_preset.html) and I'm getting the same error: 

```
__init__() got an unexpected keyword argument 'learn_rounding_scheme'
```

Is it possible to pass in the ```enforce_rounding_scheme=False``` flag somewhere when using the FAST_ML preset?

Btw, huge fan of the project! Thanks for your all your efforts.

**Comment by npatki** [comment]
Hi @sharisiri, great to hear!

`FAST_ML` is designed to be lightweight model with no additional arguments (they are all preset). If you'd like to change the flags to customize your model, I'd recommend using the [GaussianCopula model](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html) instead.

Please note that the parameter is called `learn_rounding_scheme` (not `enforce_rounding_scheme`).

```python
from sdv.tabular import GaussianCopula

model = GaussianCopula(enforce_rounding_scheme=False)
model.fit(data)
synthetic_data = model.sample(num_rows=100)
```

**Comment by npatki** [comment]
Closing this off. The initial example only had a single, constant value. In this case, no rounding scheme is used -- the synthetic data just recreates the same value.

If you try the same example with multiple values, then you can see that the rounding scheme can be turned off.

```python
from sdv.tabular import GaussianCopula
import pandas as pd
import numpy as np

test_data = pd.DataFrame(data={
    'column': [0.123456789012345]*5 + [1.123456789012345]*5
})

model = GaussianCopula(
    learn_rounding_scheme=False)

model.fit(test_data.round(4))
model.sample(num_rows=5)
```
