### ISSUE TITLE
Constraint error

### ISSUE THREAD

**Issue by leelasaivoonna** [sdv-dev/SDV#1051]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:
* Python version:
* Operating System:

### Problem description

<Replace this with a description of the problem that you are trying to solve using SDV. If
possible, describe the data that you are using, or consider attaching some example data
that others can use to propose a working solution for your problem.>

### What I already tried

<Replace with a description of what you already tried and what is the behavior that you observe.
If possible, also add below the exact code that you are running.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by leelasaivoonna** [comment]
Data is not valid for the 'ScalarInequality' constraint:

Error is coming

**Comment by npatki** [comment]
Hi @leelasaivoonna, thanks for filing this issue.

The error message indicates that you are applying a `ScalarInequality` constraint, but the real data does not follow the constraint. For example, you may be specifying a `ScalarInequality` such as `age > 18` -- but your data may include a few rows where this is not true (`age <= 18`).

In the SDV, we expect that every row in your real data must follow the constraint. 

Could you check your real data to see if any rows violate the constraint you're providing? If you're able to share more details about your real data and what you want to accomplish using synthetic data, I can guide you to some other solutions.

**Comment by npatki** [comment]
Hi @leelasaivoonna, are you still encountering any problems with this?

I'll close this issue off since we've answered your initial question -- the constraints are only designed to work when every single row of the input data (real data) follow the constraint.

Please feel free to reply if you have any other thoughts or questions about this, and I can re-open the issue to discuss.
