### ISSUE TITLE
More details about FAST ML preset?

### ISSUE THREAD

**Issue by rangasayeek** [sdv-dev/SDV#1069]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: v0.17.1 - 2022-09-29
* Python version:
* Operating System: Windows

### Problem description
Can you please provide more information regarding the FAST ML preset for the TabularPreset synthetic data generation module? It would be really beneficial while writing papers that use the preset for synthetic data generation.

Appreciate the help in advance!

### What I already tried

Tried finding the details in the documentation.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @rangasayeek, nice to meet you.

More details about FAST ML are available in [this GitHub discussion](https://github.com/sdv-dev/SDV/discussions/786). If there are any particular questions that are not covered in the discussion, let me know.

**Comment by rangasayeek** [comment]
Thank you very much. That helps!

**Comment by npatki** [comment]
Great! I'll mark this issue as resolved. Feel free to reply if there are any more questions about FAST ML and I can reopen it.
