### ISSUE TITLE
Add sampling methods to PARSynthesizer

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#1083]
### Problem Description

_As a user, it would be helpful to have a clear understanding of how to sample sequential data whether I have to provide the context or not._

### Acceptance criteria

Add the following methods to the `PARSynthesizer`
- `sample`
    - Parameters:
        - (required) num_sequences(int): The number of sequences to sample
        - sequence_length(int): An integer that describes the length of every sequence
            - (default) None: The model will determine the length of every sequence
        - randomize_samples (bool):
            - True: Every sample() call will have randomly generated data that is different
            - (default) False: Every sample() call has the same data generated
- `sample_sequential_columns`
    - Parameters:
        - (required) context_columns (pandas.DataFrame): A DataFrame containing the rows for the unchanging context 
        - sequence_length (int): An integer that describes the length of every sequence
            - (default) None: The model will determine the length of every sequence
        - randomize_samples(bool):
            - True: Every sample() call will have randomly generated data that is different
            - (default) False: Every sample() call has the same data generated

### Expected behavior

```python
>>> synthesizer.sample(5, sequence_length=10, randomize_samples=True)
>>> context = pd.DataFrame({'name': ['sam', 'sam', 'sam']})
>>> synthesizer.sample_sequential_columns(context, 5, True)
```

### Additional context

- The current PAR model only has one sampling method with a bunch of different arguments. The functionality in that method can essentially be split up into the two methods above.

**Comment by npatki** [comment]
When doing this change, we can also fix #1052: In `sample_sequential_columns` the columns provided as `context_columns` can be in any order. (We can simply reorder them if as needed.)
