### ISSUE TITLE
Add multiple primary keys for a single table in the relational database

### ISSUE THREAD

**Issue by AbderrahimAl** [sdv-dev/SDV#1090]
### Problem Description

As a user, I need to specify multiple primary keys for one table in a relational database using `Metadata`.

### Criteria

Add the following parameter to `Metadata.add_table`:

*  `primary_keys` - (List[str]): A list of primary keys.

Add the following method to Metadata:

* `set_primary_keys`:

    *  Parameters:
         
        * `table_name`- (str): A table name which was already added to metadata.

         * `primary_keys` - (List[str]): A list of primary keys.

### Expected behavior

```python
>>>  from sdv import Metadata
>>>  metadata = Metadata()
>>>  metadata.add_table(name="table_1", data=table_1, primary_keys=["pk1", "pk2"])
```

```python
>>>  from sdv import Metadata
>>>  metadata = Metadata()
>>>  metadata.add_table(name="table_1",  data=table_1)
>>>  metadata.set_primary_keys(table_name="table_1", primary_keys=["pk1", "pk2", "pk3"])
```

### Additional context

* Currently, Metadata accept only one primary key for each table.

**Comment by npatki** [comment]
Hi @AbderrahimAl, nice to meet you.

We have an open feature request (#613) open for supporting composite keys. Does this cover your use case? In the issue, I have also proposed a workaround that you can use in the meantime.

**Comment by npatki** [comment]
Hi @AbderrahimAl, I'll close this issue off in favor of #613. If you have any related feedback, feel free to leave comments on that issue. If it's unrelated, you can respond here and I will reopen.
