### ISSUE TITLE
String field interpreted as integer

### ISSUE THREAD

**Issue by montasIET** [sdv-dev/SDV#1099]
### Environment details

* SDV version: 0.17.1
* Python version: 3.9.13
* Operating System: Windows 11 Pro

### Problem description

Hi, I don't know if it's a bug but I thing SDV interprets a string field as an integer.

In my case I have a field in metadata which type is **categorical** and it's a _id_ like '0311', but when I print generated results it gives me 311 for example.

Moreover, I don't know if it's linked to this, but the model chooses only between two values among more than 20 (I use HMA1 with standard config)

**Comment by npatki** [comment]
Hi @montasIET, nice to meet you and thanks for filing the issue. A `categorical` field can be stored in any way (as a string, integer, etc.), so your intended usage seems right.

The problem may be in how `pandas` is reading the data. If all the values are represented as integers, then `pandas` may be loading it as integers even before the `sdv` model gets a chance to run. For debugging, would be very helpful if you could provide the following:
1. Your metadata JSON file, so I can verify the structure of your tables and column types
2. The code you're using to load the data into Python (eg. from a CSV file, etc)

> but the model chooses only between two values among more than 20 (I use HMA1 with standard config)

If you're able to provide the metadata and pinpoint the column, I can take a look at this too!

**Comment by montasIET** [comment]
ok that was pandas actually, as you said @npatki.
Solved!

**Comment by npatki** [comment]
Great -- marking as resolved! Feel free to reply if there are any other issues related to this. I can reopen the issue as needed.
