### ISSUE TITLE
Wheel error when installing sdv

### ISSUE THREAD

**Issue by jaymc-betta** [sdv-dev/SDV#1116]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: None
* Python version: 3.10 
* Dependecies version: pandas==1.5.2, scipy==1.9.3, numpy==1.23.5, matplotlib==3.5.3
* Operating System: linux mint 20.2

### Problem description
I'm trying to install sdv by with `pip3 install sdv` and I'm getting errrors like:
```
ERROR: Failed building wheel for scipy
ERROR: Failed building wheel for pandas
ERROR: Failed building wheel for matplotlib
```

### What I already tried

Reinstalling packages, updating packages, trying with python 3.9

I am attaching log and error files 
[errfile.txt](https://github.com/sdv-dev/SDV/files/10079362/errfile.txt)
[logfile.txt](https://github.com/sdv-dev/SDV/files/10079363/logfile.txt)

**Comment by npatki** [comment]
Hi @jaymc-betta, thanks for the detailed error logs and files. From looking at the output, it appears that you have already have a version of the SDV that is cached on your machine:

```
Collecting sdv
  Using cached sdv-0.3.2-py2.py3-none-any.whl (31 kB)
```

This particular [version](https://github.com/sdv-dev/SDV/releases/tag/v0.3.2) is over 2 years old, so it's unsurprising that you're encountering some issues. I wonder if you can try ignoring the cache, or better yet directly requesting the install for a higher version of the SDV?
```
pip install sdv==0.17.1
```

**Important note:** We have yet to add support for Python 3.10. To install this latest version, I'd recommend creating a virtual environment with Python 3.9. (Support for 3.10 is on our roadmap, and should be available in future releases. You can follow the issue [here](https://github.com/sdv-dev/SDV/issues/939).)

**Comment by jaymc-betta** [comment]
Thank's @npatki, worked creating a clean environment with Python 3.8. Any clue on why did I have sdv installed? Any other ML package use it as a secondary library? Or maybe was "installed" to some point but unsuccessfully when in my previous attempts?

**Comment by npatki** [comment]
Glad it worked @jaymc-betta!

> Any clue on why did I have sdv installed?

Perhaps you had tried `pip install sdv` a few times before you logged and generated the error and log files? It seems that this version of SDV allowed anything over Python 3.5. So if you had Python 3.10, `pip` may have thought that this older version was the only compatible one.

 I'll close off this issue as resolved but feel free to reply if there's anything other follow up questions.
