### ISSUE TITLE
Upgrade `SDMetrics` requirement to 0.8.0 

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1125]
### Problem Description
The newest version of `SDMetrics` is not included with the SDV release, even though it's compatible. This prevents SDV users from using the newest features, such as the [Diagnostic Report](https://docs.sdv.dev/sdmetrics/reports/diagnostic-report)

### Expected behavior
Bump the requirement for `sdmetrics` to:

```
    'sdmetrics>=0.8.0,<0.9',
```

**Comment by amontanez24** [comment]
resolved by #1091
