### ISSUE TITLE
Mam I have to generate 4 dataset simultaneously by using GaussianCopula, CTGAN, TVAE,CopulaGAN in SDV  can you please tell me how I can achive this.

### ISSUE THREAD

**Issue by Abhishek967026** [sdv-dev/SDV#1146]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:
* Python version:
* Operating System:

### Problem description

<Replace this with a description of the problem that you are trying to solve using SDV. If
possible, describe the data that you are using, or consider attaching some example data
that others can use to propose a working solution for your problem.>

### What I already tried

<Replace with a description of what you already tried and what is the behavior that you observe.
If possible, also add below the exact code that you are running.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @Abhishek967026 I left a comment in the other issue (#1147) that covers the same topics. Let's close this thread and continue the conversation in the other issue.
