### ISSUE TITLE
I want to see that how we can generate data simultaneously by using GaussianCopula, CTGAN, TVAE and CopulaGAN and also can note time taken to generate data so that it'll be helpfull that which model is good for our data generation. Thank you. Hope you'll try to implement this

### ISSUE THREAD

**Issue by Abhishek967026** [sdv-dev/SDV#1147]
### Problem Description

<Replace this with a description of the problem that you think SDV should be able to solve and is not solving already>

### Expected behavior

<Replace this a clear and concise description of what you would expect SDV with regards with the described problem. If possible, explain how you would like to interact with SDV and what the outcome of this interaction would be.>

### Additional context

<Please provide any additional context that may be relevant to the issue here. If none, please remove this section.>

**Comment by npatki** [comment]
Hi @Abhishek967026, a good place to start will be the [User Guides](https://sdv.dev/SDV/user_guides/single_table/models.html) for single table models. Here, you can find instructions on how to create and sample from the different models -- for example [GaussianCopula](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html) or [CTGAN](https://sdv.dev/SDV/user_guides/single_table/ctgan.html).

As for noting time, there are many different ways you can accomplish this with Python. A simple solution is available [on StackOverflow](https://stackoverflow.com/questions/7370801/how-do-i-measure-elapsed-time-in-python/7370824#7370824).

Hope that helps get you started!

**Comment by npatki** [comment]
Hi @Abhishek967026, I'm closing the issue off since we've answered the original request. Please feel free to reply here if you have any further questions.
