### ISSUE TITLE
Constraints with Time series models 

### ISSUE THREAD

**Issue by Mohamed209** [sdv-dev/SDV#1155]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:0.17.2
* Python version:3.9.13
* Operating System: windows 10

### Problem description

<From documents https://sdv.dev/SDV/user_guides/single_table/handling_constraints.html#applying-the-constraints
Why can't use constraints with Time series models , for example PAR model constructor doesn't support constraints parameter >

### What I already tried

<Replace with a description of what you already tried and what is the behavior that you observe.
If possible, also add below the exact code that you are running.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @Mohamed209, constraints are not yet supported for the PAR sequential model. We have an outstanding feature request at #570. Feel free to follow along for updates.

I will close this issue as a duplicate. Feel free to add any relevant info to #570. For eg. You can help us prioritize by providing some info about your usage -- which constraints would you like to add? And how are you planning to use the synthetic data?
