### ISSUE TITLE
Gaussian Copula model generating only 1388 unique rows despite original set having more than 100K

### ISSUE THREAD

**Issue by Shandelier** [sdv-dev/SDV#1170]
### Environment Details

* SDV version: 0.17.1
* Python version: 3.6.15
* conda: 4.7.12
* Operating System: uname_result(system='Linux', node='ip-10-108-155-90', release='4.14.173-137.229.amzn2.x86_64', version='#1 SMP Wed Apr 1 18:06:08 UTC 2020', machine='x86_64', processor='x86_64')

### Error Description

Tried to model data of 5 tables with HMA1, but it can't finish fitting in 8+ hours (despite sampling every table to <100 rows). Joined all the tables and tried modeling with GaussianCopula. 200K rows with 150 columns take 1h to model and generate 200K new rows. The problem is, there are only 1388 rows with unique values like vehicle plate number, despite the fact I used faker provider _'license_plate'_.
Since the provider is using rand function to generate the plates I would expect majority of rows having unique value.

In metadata plates columns has this value:
```
VRM': {'type': 'categorical',
   'transformer': 'FrequencyEncoder_noised',
   'pii': True,
   'pii_category': 'license_plate'},
...
VRM.value': 'copulas.univariate.truncated_gaussian.TruncatedGaussian',
```

Do let me know if you need any more details and I'd be happy to add. Thanks!

**Comment by npatki** [comment]
Hi @Shandelier, nice to meet you.

 I can confirm that the `Faker` provider is capable of generating more than 1388 unique license plate values. It may be good to double-check the metadata definition. [Here](https://docs.sdv.dev/sdmetrics/getting-started/metadata/single-table-metadata) is a useful explanation of the allowed parameters.

From looking at your metadata, I'm a bit confused as it seems there are two column -- `'VRM'` and `'VRM.value'`. Where is the `'.value'` column coming from? Additionally, any transformer parameters should be specified in when you create the synthesizer, not in the metadata. 

Below is a toy example where I verified that you can create many license plate values. Perhaps you can use it as a starting point.

```python
import pandas as pd
from sdv.tabular import GaussianCopula

# create some dummy data
data = pd.DataFrame(data={
    'column_A': [float(i) for i in range(100)],
    'column_B': [str(i) for i in range(100)]
})

# write metadata according to the spec
metadata = {
    'fields': {
        'column_A': { 'type': 'numerical', 'subtype': 'float' },
        'column_B': { 'type': 'categorical', 'pii': True, 'pii_category': 'license_plate'}
    }
}

model = GaussianCopula(
  field_transformers={'column_B': 'LabelEncoder_noised'},
  table_metadata=metadata)
model.fit(data)
sampled = model.sample(200_000)
sampled.nunique()
```

**Comment by Shandelier** [comment]
Hi Neha, thanks for answer and testing faker

both fields are from metadata dictionary. The first one (VRM) is from 'fields' and second (VRM.value) is from 'model_kwargs'

I've tested generating data with custom made provider (for database IDs), but this exact number of unique values persists even in continous variables like 'cost'. There is one exception for column choosen to be a primary_key. The G_ID field has one unique value less = 1387

here's the code:
``` py
model = sdv.tabular.GaussianCopula(primary_key='G_ID',
                       anonymize_fields=anonymize_dict,
                       constraints=fix_constraints)
model.fit(fin_df)

metadata = model.get_metadata().to_dict()

for (key, val) in anonymize_dict.items():
    if val in ["company", "name"]:
        metadata['fields'][key]['pii_locales'] = ['en_GB']
        
model_locale = sdv.tabular.GaussianCopula(table_metadata=metadata)
model_locale.fit(fin_df)

newdata = model_locale.sample(200000)
```

also i'm using fix_constraints for linking the values of fields related to car brand, model etc. Is it possible this table is too large for the model and it somehow ends sampling after 1388 combinations?

**Comment by Shandelier** [comment]
This problem was completly separate from SDV. 
The issue was produced by platform save function which duplicated 1388x first rows and cut the rest. 

Nonetheless thanks!
