### ISSUE TITLE
Update `evaluate.py` to work with the new `metadata`

### ISSUE THREAD

**Issue by pvk-developer** [sdv-dev/SDV#1186]
### Problem Description

Currently `evaluate.py` is using the old metadata, in order for it to work with the new updates, this should be updated to use the new metadata objects.

### Expected Behavior
* `evaluate.py` uses the new `SingleTableMetadata` and `MultiTableMetadata`. 
* `evaluate` can be used with the new metadata objects to evaluate the synthetic data and real data.

**Comment by amontanez24** [comment]
Should be resolved with #1190
