### ISSUE TITLE
KeyError while sampling using freshly trained SDV model 

### ISSUE THREAD

**Issue by hrishabdey17** [sdv-dev/SDV#1187]
[SDV.zip](https://github.com/sdv-dev/SDV/files/10499109/SDV.zip)

**Environment Details**
Please indicate the following details about the environment in which you found the bug:

SDV version: 0.17.2
Python version: 3.8
Operating System: Windows 11

**Problem Details**
Error description
The key error is also being raised when trying to sample from a freshly-trained SDV model in v0.17.2.

I tried both passing the field types metadata and without it, nothing seems to help.

I printed the model metadata just to check if the model inferred properly the data types and everything seems correct.

Here I attach the error and ipynb file used just in case it helps (this is the last version used in which the model infers the field types):

KeyError Traceback (most recent call last) Input In [36], in <cell line: 1>() ----> 1 new_data = model.sample() File ~\Anaconda3\lib\site-packages\sdv\relational\base.py:185, in BaseRelationalModel.sample(self, table_name, num_rows, sample_children, reset_primary_keys) 182 if reset_primary_keys: 183 self._reset_primary_keys_generators() --> 185 return self._sample(table_name, num_rows, sample_children) File ~\Anaconda3\lib\site-packages\sdv\relational\hma.py:595, in HMA1._sample(self, table_name, num_rows, sample_children) 593 for table in self.metadata.get_tables(): 594 if not self.metadata.get_parents(table): --> 595 self._sample_table(table, num_rows, sampled_data=sampled_data) 597 return self._finalize(sampled_data) File ~\Anaconda3\lib\site-packages\sdv\relational\hma.py:554, in HMA1._sample_table(self, table_name, num_rows, sample_children, sampled_data) 551 sampled_data[table_name] = table_rows 553 if sample_children: --> 554 self._sample_children(table_name, sampled_data, table_rows) 556 return sampled_data File ~\Anaconda3\lib\site-packages\sdv\relational\hma.py:428, in HMA1._sample_children(self, table_name, sampled_data, table_rows) 425 for _, row in table_rows.iterrows(): 426 self._sample_child_rows(child_name, table_name, row, sampled_data) --> 428 child_rows = sampled_data[child_name] 429 self._sample_children(child_name, sampled_data, child_rows) KeyError: 'dim_hcp'

**Comment by npatki** [comment]
Hi @hrishabdey17, thanks for filing the issue and providing the detailed code.

It seems you have a simple 2-table schema with a parent and child table. There doesn't appear to problems with the code.

As next steps, it would be good to verify 2 things:

1. **Are all the references in the parent/child relationship known?** Verify that every foreign key value in the child table refers to a primary key that exists in the parent.

```python
primary_keys = set(tables['dim_ds']['DS_KEY'])
foreign_keys = set(tables['dim_hcp']['DS_KEY'])

unknown_references = foreign_keys - primary_keys

print('Number of unknown references:', len(unknown_references))
print('Unknown reference values:', unknown_references)
```

For a valid dataset, it should print out:

```
Number of unknown references: 0
Unknown reference values: set()
```

2. **Can you pass along your full metadata JSON file?** This will help us double check if anything is misconfigured. You can do this by dumping into a json.

```python
metadata_dict = metadata.to_dict()
with open('metadata.json', 'w') as f:
    json.dump(metadata_dict, f)
```

**Comment by npatki** [comment]
Hi @hrishabdey17, are you still having a problem with this?

I'll close off the issue since we were not able to replicate it. But if you are still encountering the KeyError and can provide more information, please feel free to reply here. We can always reopen the issue to continue the investigation.
