### ISSUE TITLE
Add evaluation methods to synthesizer

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#1190]
### Problem Description

_As a user, it would be useful to evaluate the synthetic data generated against the original data._

### Acceptance criteria

* Add a `evaluation` module and two submodules within it: `single_table` and `multi_table`
* Add the following methods to the `evaluation.single_table` module
    *  `evaluate_quality(real_data, synthetic_data, metadata, verbose)` - Wrapper around the initialization and evaluation of [this class](https://github.com/sdv-dev/SDMetrics/blob/956b9889408c520bebd5e76b026136c7b78225ae/sdmetrics/reports/single_table/quality_report.py#L57).
    * `run_diagnostic(real_data, synthetic_data, metadata, verbose)` - Wrapper around the initialization and evaluation of [this class](https://github.com/sdv-dev/SDMetrics/blob/956b9889408c520bebd5e76b026136c7b78225ae/sdmetrics/reports/single_table/diagnostic_report.py#L70).
    * `get_column_plot(real_data, synthetic_data, metadata, column_name)` - Wrapper around [sdmetrics.reports.utils.get_column_plot](https://github.com/sdv-dev/SDMetrics/blob/29a2ab37e3c81ee4af8604425881afe0fb2cb6ea/sdmetrics/reports/utils.py#L215)
    * `get_column_pair_plot(real_data, synthetic_data, metadata, column_names)` - Wrapper around [sdmetrics.reports.utils.get_column_pair_plot](https://github.com/sdv-dev/SDMetrics/blob/29a2ab37e3c81ee4af8604425881afe0fb2cb6ea/sdmetrics/reports/utils.py#L380)
  
* Add the following methods to the `evaluation.multi_table` module
    * `run_diagnostic(real_data ,synthetic_data, metadata, verbose)` - Wrapper around the initialization and evaluation of [this class](https://github.com/sdv-dev/SDMetrics/blob/956b9889408c520bebd5e76b026136c7b78225ae/sdmetrics/reports/multi_table/diagnostic_report.py#L23).
    * `evaluate_quality(real_data, synthetic_data, metadata, verbose)` - Wrapper around the initialization and evaluation of [this class](https://github.com/sdv-dev/SDMetrics/blob/956b9889408c520bebd5e76b026136c7b78225ae/sdmetrics/reports/multi_table/quality_report.py#L61).
    * `synthesizer.get_column_plot(real_data, synthetic_data, metadata, table_name, column_name)` - Wraps the same method as the single table case but requires the table name.
    * `synthesizer.get_column_pair_plot(real_data, synthetic_data, metadata, table_name, column_names)` - Wraps the same method as the single table case but requires the table name.

### Expected behavior

``` python
# Single table cases

quality_report = evaluate_quality(
  real_data=real_data, # DataFrame
  synthetic_data=synthetic_data, # DataFrame
  metadata=my_metadata, # SingleTableMetadata
  verbose=True
)
diagnostic_report = run_diagnostic(
  real_data=real_data, # DataFrame
  synthetic_data=synthetic_data, # DataFrame
  metadata=my_metadata, # SingleTableMetadata
  verbose=True
)
fig = get_column_plot(
  real_data=real_data, # DataFrame
  synthetic_data=synthetic_data, # DataFrame
  metadata=my_metadata, # SingleTableMetadata
  column_name='age'
)
fig = get_column_plot(
  real_data=real_data, # DataFrame
  synthetic_data=synthetic_data, # DataFrame
  metadata=my_metadata, # SingleTableMetadata
  column_names=['age', 'weight']
)

# Multi-table cases
quality_report = evaluate_quality(
  real_data=real_data, # dictionary
  synthetic_data=synthetic_data, # dictionary
  metadata=my_metadata, # MultiTableMetadata
  verbose=True
)
diagnostic_report = run_diagnostic(
  real_data=real_data, # dictionary
  synthetic_data=synthetic_data, # dictionary
  metadata=my_metadata, # MultiTableMetadata
  verbose=True
)
# Plot the 1D marginal distribution
fig = get_column_plot(
  real_data=real_data, # dictionary
  synthetic_data=synthetic_data, # dictionary
  metadata=my_metadata, # MultiTableMetadta
  table_name='users',
  column_name='age'
)
# Plot the 2D bivariate distribution
fig = get_column_plot(
  real_data=real_data, # dictionary
  synthetic_data=synthetic_data, # dictionary
  metadata=my_metadata, # MultitableMetadata
  table_name='users',
  column_names=['age', 'weight']
)
```

**Comment by npatki** [comment]
@amontanez24 @fealho I'm testing this out. It seems like `evaluate_quality` is actually returning the score.

The spec is to return the actual `QualityReport` object from SDMetrics. Shall we re-open this?

**Comment by fealho** [comment]
@npatki Oh, I thought it was supposed to be the score. Yes, this should be reopened and patched.
