### ISSUE TITLE
Remove `PARSynthesizer.get_learned_distributions` function

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1208]
### Problem Description
The `PARSynthesizer.get_learned_distributions` was in spec because the _context columns_ go through a Gaussian Copula process, and therefore have distributions available.

However, this is confusing in SDV 1.0 API. I am left wondering:

- Why am I only getting distributions for some columns and not others?
- If I am able to get the distributions (like in the Gaussian Copula), why am I not allowed to set them?

### Expected behavior

Until we figure out how best to communicate the above points, let's just remove the `get_learned_distributions` function to avoid any confusion.

**Comment by amontanez24** [comment]
This method never ended up being implemented
