### ISSUE TITLE
Tabular Model with constraints generate less sample if batch_size is not specified

### ISSUE THREAD

**Issue by davidegazze** [sdv-dev/SDV#1228]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.18.0
* Python version: 3.8
* Operating System: Windows 11

### Error Description
As described in the issue, I create a Tabular Preset model with some constraints: Unique, and FixedIncrements.
The model has been fitted correctly. When I call the method `sample` it returns back less rows if the batch size is not specified.
 
### Steps to reproduce

```
from sdv.constraints import FixedIncrements, Unique, ScalarRange

num_rows = 10000

unique_constraint = Unique(
                       column_names=['ID']
)

increment_constraint = FixedIncrements(
                       column_name='ID',
                       increment_value=1
)

range_constrain = ScalarRange(
    column_name='ID',
    low_value=0,
    high_value=num_rows,
    strict_boundaries=True
)

constraints = [unique_constraint, range_constrain]
constrained_model = TabularPreset(
            name='FAST_ML',
            constraints=constraints,
)

constrained_model.fit(accounts_df)

dataset = constrained_model.sample(num_rows=1000, batch_size=1)
print(dataset.shape) # (1000, 7)

dataset = constrained_model.sample(num_rows=1000, batch_size=None)
print(dataset.shape) # (1000, 7)

dataset = constrained_model.sample(num_rows=1000)
print(dataset.shape) # (19, 7)
```

**Comment by npatki** [comment]
Hi @davidegazze, nice to meet you. I recognize you may just be testing out the SDV, but our models aren't really designed to be used on only 1 column. Would it be possible to try this with a dataset of multiple columns? You can use the demo datasets from the guide as well.

On a more technical front: From looking at your code, it seems that you have a primary key `ID` that indexes your rows: `0, 1, 2, 3, ...`? 

In this case, you can supply it as a `"primary_key"` in the metadata.

```python
{
    "primary_key": "ID",
    "fields": {
        "ID": { "type": "id", "subtype": "integer" },
        "other_column_name": { "type": ... },
        ...
    }
}
```

For any integer primary keys, the SDV will ensure that:
1. The keys are unique
2. The first key starts at 0
3. They keys increment by 1 every time

No need to add a constraint, as they are not designed for primary keys.

**Comment by npatki** [comment]
Hi @davidegazze are you still running into this issue? I'll close it as resolved since setting as a integer primary key will achieve the desired effect.

However, I understand that the `Unique` constraint has issues when using batch sampling. I've filed some relevant issues at #1283 and #1284 to track. Feel free to reply to any of those issues if you have encountered something similar.

Alternatively if there's more to discuss here, you can also reply and I'll reopen the issue.
