### ISSUE TITLE
Assertion error when fitting CTGAN on dataset

### ISSUE THREAD

**Issue by dsu13** [sdv-dev/SDV#1231]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.18.0
* Python version: 3.7
* Operating System: Linux/ Conda

### Error Description

Assertion error when using CTGAN

### Steps to reproduce

Load the dataset, specify the schema of each column, call CTGAN and fit with the dataset

```
from sdv.tabular import CTGAN
df = pd.read_csv('dataset.csv')
discrete_dict = {'feature1': {'type': 'numerical',
  'subtype': 'integer'},
...}
model1 = CTGAN(epochs=10,cuda=True,verbose=True, batch_size=2048, field_types=discrete_dict, enforce_min_max_values=True)
mode1.fit()

AssertionError                            Traceback (most recent call last)
<ipython-input-27-7f28c4a8201c> in <module>
      5 
      6 
----> 7 model1.fit(dff)

/opt/conda/lib/python3.7/site-packages/sdv/tabular/base.py in fit(self, data)
    147             LOGGER.debug(
    148                 'Fitting %s model to table %s', self.__class__.__name__, self._metadata.name)
--> 149             self._fit(transformed)
    150 
    151     def get_metadata(self):

/opt/conda/lib/python3.7/site-packages/sdv/tabular/ctgan.py in _fit(self, table_data)
     57         self._model.fit(
     58             table_data,
---> 59             discrete_columns=categoricals
     60         )
     61 

/opt/conda/lib/python3.7/site-packages/ctgan/synthesizers/base.py in wrapper(self, *args, **kwargs)
     48     def wrapper(self, *args, **kwargs):
     49         if self.random_states is None:
---> 50             return function(self, *args, **kwargs)
     51 
     52         else:

/opt/conda/lib/python3.7/site-packages/ctgan/synthesizers/ctgan.py in fit(self, train_data, discrete_columns, epochs)
    375                         fake_cat = fakeact
    376 
--> 377                     y_fake = discriminator(fake_cat)
    378                     y_real = discriminator(real_cat)
    379 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/ctgan/synthesizers/ctgan.py in forward(self, input_)
     54     def forward(self, input_):
     55         """Apply the Discriminator to the `input_`."""
---> 56         assert input_.size()[0] % self.pac == 0
     57         return self.seq(input_.view(-1, self.pacdim))
     58 

AssertionError: 

```

**Comment by tarzs** [comment]
This happened to me when the number of rows in my dataset wasn't divisible by the 'batch_size' I'd set.

**Comment by npatki** [comment]
Hi @dsu13 nice to meet you.

As @tarzs mentioned, I'm able to replicate this error exactly when the total number of rows in the data is not divisible by `batch_size`. Requirements for `batch_size`:

1. Must be able to divide the total length of dataset. You can check that the following is an integer, with whatever data you are inputting into the `fit` call:
```python
print(len(df)/batch_size)
```

2. Must be an even number

If I update the `batch_size` according the requirements, then the error goes away for me. If you are still seeing it, could you provide more information to help me replicate?
- How many columns and rows are in your dataset?
- What are the types of each of the columns? (ideally a `metadata` dictionary would be great)

**Comment by npatki** [comment]
A quick update -- @dsu13, it seems as if the `batch_size` must also be divisible by the value of `pac`, which is set to 10 by default. So this is what's likely causing your error.

I believe your code should run if you set `batch_size=2040` instead of 2048. Let me know if this works for you.

In the meantime, I have filed #1269 for improved documentation of these parameters and their requirements.

**Comment by dsu13** [comment]
Hi @npatki, thanks for the response. I made the changes that you mentioned, changing  `batch_size=2040` and everything worked!

**Comment by npatki** [comment]
Great to hear @dsu13. I'll close this issue since we figured it out. Will follow up on #1269 once we have better documentation of this.
