### ISSUE TITLE
Relationship between primary keys crashes HMASynthesizer

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#1232]
Creating a relationship between two primary keys crashes the HMASynthesizer. @Neha I'm unsure if that's the expected behavior? If so, the error message should be improved.

```python3
    table = pd.DataFrame({'pk': list(range(100)), 'col1': np.random.random(100), 'col2': np.random.choice(['a', 'b', 'c'], 100)})
    data = {'table': table, 'table2': table}
    metadata = MultiTableMetadata()
    metadata.detect_table_from_dataframe('table', table)
    metadata.set_primary_key('table', 'pk')
    metadata.detect_table_from_dataframe('table2', table)
    metadata.set_primary_key('table2', 'pk')
    metadata.add_relationship('table', 'table2', 'pk', 'pk')
    synthesizer = HMASynthesizer(metadata)
    synthesizer.fit(data)
```

The above crashes with a `KeyError: pk`.

**Comment by npatki** [comment]
Relationships between primary keys are not supported. If you have a column that refers to another table, the column must e a _foreign key_, by definition.

Let's validate this in #1236 and close this issue off.
