### ISSUE TITLE
Add a red box redirecting users to the new documentation (in new branch)

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1243]
Version: SDV 1.0.0 (in progress)

### Text
The new version of SDV will have docs in a new URL but we will still keep the [old URL](https://sdv.dev/SDV/) up for some time, in case people still have projects using it.

However, we should add a **red danger box** to the top of each page of the old docs, suggesting that users visit the new docs. It can say something like this:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/3227804/217384435-8c0b60cb-32e7-49b4-9266-129e0c38821e.png">

Text is copied below for your reference. (Note that the URL is set, but is currently set to private mode.)

> You looking at the documentation for an older version of the SDV! We are no longer supporting or maintaining this version of the software.
>
> **[Click here to go to the new docs pages.](https://docs.sdv.dev/sdv)**

### Where to make changes?
The box should be shown on _all_ pages of the documentation. It should appear at the very top of each page.

### Other details
1. Create a new branch on top of the current _stable_ branch (old SDV)
2. Make these changes on the new branch
3. Do _not_ merge this branch.

**Comment by frances-h** [comment]
Change has been made in the `issue-1243-docs-warning` branch
