### ISSUE TITLE
Add visibility over the modeled parameters

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#129]
Add methods to explore the modeled parameters after modeling.

SDV should have a `visualize` or `explain` or `view` method to obtain details about the parameters learned during the modeling.

When possible, information should be obtained at a column level (univariate distribution) and at a table level (mutivariate distribution).

API and implementation details will be further discussed in this issue.

**Comment by npatki** [comment]
Closing this issue as resolved, as we now make it easy to access the learned distributions after fitting. 

- For a single table synthesizer, you can inspect the learned univariate distribution for each column [see API](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer#accessing-learned-distributions)
- For multi table synthesizers, this is nested by table [see API](https://docs.sdv.dev/sdv/multi-table-data/modeling/synthesizers/hmasynthesizer#accessing-learned-distributions).

We don't yet allow a convenience method for accessing the covariance matrix, but that doesn't seem to be a feature users are interested in. We can revisit that in the future.

_(Of course, this is only for parametric models. It would be hard to show the distribution from a GAN.)_
