### ISSUE TITLE
How to constrain multiple tables

### ISSUE THREAD

**Issue by montasIET** [sdv-dev/SDV#1292]
### Environment details

* SDV version: 0.17.2
* Python version: 3.8.0
* Operating System: Windows 11 Pro

### Question

Hi everyone, is it possible to write a constraint that involves multiple tables?
For example, I want that the field **table1.name** is equal to **table2.name** if **table1.key** is equal to **table2.key**

**Comment by npatki** [comment]
Hi @montasIET, currently the SDV does not support logical constraints that involve multiple tables -- but we are tracking a feature request for it in #1122 if you want to add your use case there.

In your case, I wonder if you may manually workaround this by dropping `table2.name` and recreating later based on the remaining columns.

**Comment by npatki** [comment]
Hi @montasIET, I'm closing this issue out in favor if #1122. Feel free to reply to the other issue if you have more thoughts about constraining multiple tables.

If there is anything more specific about your use case to discuss, you can also reply here and I will reopen the issue.
