### ISSUE TITLE
Does PAR need a certain amount of context ?

### ISSUE THREAD

**Issue by nelsonrogers** [sdv-dev/SDV#1313]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.18.0
* Python version: 3.7.15
* Operating System: Ubuntu Linux container running on Windows host

### Problem description

I'm fitting the PAR model on IoT data that simply has a datetime column and a values column. No entity columns, no other context. I have a relatively large amount of data (approx 20 000 data points). The results haven't really been satisfying at all, just a bunch of noise. 

It seemed to work ok with a small amount of data (~1 000 data points). While plotting, you see a similar profile to the original data. However, the amplitude is much smaller (real values are integers between 90 ansd 160, generated values are floats between 135 and 138).

### What I already tried

I figured more columns may be needed. I thought doing feature engineering (day of week, time of day, month, etc.) based on the datetime column might help but it doesn't seem relevant for the "entity columns" or "context columns" categories, so I don't really see the point for that with the PAR model.

Am I at an impasse?

**Comment by npatki** [comment]
Hi @nelsonrogers, the `PAR` algorithm is designed to work on **multi-sequence** data, where there are multiple sequences present in the same dataset. If you don't have any entity columns, it indicates that your entire dataset is only a **single sequence**, which is not quite suited for PAR.

For more information, I'd recommend you check out the new, [**SDV 1.0 (Beta!)** documentation](https://docs.sdv.dev/sdv/sequential-data/modeling/parsynthesizer). You can also see [this section](https://docs.sdv.dev/sdv/sequential-data/modeling/parsynthesizer#fit) for more of the technical details behind PAR.

**Comment by npatki** [comment]
Hi @nelsonrogers, I'm closing this issue since we've answered your question. Feel free to reply if you have any follow ups. We can always reopen for discussion.
