### ISSUE TITLE
CTGAN does not work in HMA - relational data synthesization

### ISSUE THREAD

**Issue by rahul-gupta2** [sdv-dev/SDV#1322]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.16.0
* Python version: 3.8.10
* Operating System: Windows 10

### Problem description

We are trying to use SDV's HMA class to synthesize relational data. It works for the default configuration of Gaussian Copula as the model. However, when we replace the model with CTGAN the model does not fit, as the code for HMA is based on parameters for the Gaussian Copula which CTGAN does not have. We also could not find any code to bypass this requirement for the purpose of using CTGAN as base model.

### What I already tried

We tried to send CTGAN as argument to HMA class. The dataset used was the same as used in your tutorials.

```
model= HMA1(metadata, model=CTGAN, model_kwargs={}) 
model.fit(tables)
```
![image](https://user-images.githubusercontent.com/40855167/226563409-2156817f-ade8-40b5-945a-bdfece8871f6.png)

**Comment by npatki** [comment]
Hi @rahul-gupta2, the HMA is only designed to work on parametric single table models (GaussianCopula). Parameters are a key to the HMA algorithm so supporting non-parametric models (such as CTGAN) would require a different algorithm entirely. 

We have an open issue #457 to support non-parametric models in multi-table settings. You are welcome to reference it and add your own needs/use cases for it. I'll close this issue off as a duplicate.

FYI we now have an [**SDV 1.0 (Beta!)**](https://docs.sdv.dev/sdv/multi-table-data/modeling/hmasynthesizer) release out, which provides more explanation and pointers as to how HMA works.
