### ISSUE TITLE
import sdv shows error: 

### ISSUE THREAD

**Issue by lk1983823** [sdv-dev/SDV#1329]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.0.0b0 
* Python version: 3.10
* Operating System: Ubuntu 18.04.

### Error Description
I have successfully installed sdv1.0.0b0 in python 3.10. 
When I run from sdv import load_demo, it shows: ImportError: cannot import name 'load_demo' from 'sdv'.
Actually, I cant import anything from sdv :(.

Anyone can help?

**Comment by npatki** [comment]
Hi @lk1983823, in the new SDV 1.0 Beta release, the API has changed. Instead of importing `load_demo`, the new API is:

```python
from sdv.datasets.demo import download_demo
```

For more information on the updated API and user guides, see our new [SDV 1.0 documentation site](https://docs.sdv.dev/sdv) and let us know if you're having any issues.
