### ISSUE TITLE
bug: loosen dependency versions

### ISSUE THREAD

**Issue by jaidisido** [sdv-dev/SDV#1349]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.0.0
* Python version: 3.8
* Operating System: Mac

### Error Description

Is there a particular reason why many of SDV dependency ranges are so tight and restrictive?
Python convention is to pin dependencies at major but to allow minor version upgrades.

In my case I am unable to install sdv in my environment because [ctgan](https://github.com/sdv-dev/SDV/blob/master/setup.py#L24) is pinned to a restrictive minor version 'ctgan>=0.7.1,<0.8'

This causes a dependency resolution hell with other packages. For instance, installing sdv with `black>=23.0` is causing the below:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/16362107/229123976-33e53072-cf04-47f5-9a7b-6f234d187bd1.png">

### Steps to reproduce
We use [poetry](https://python-poetry.org/) instead of pip for dependency management. Installing the latest version of sdv and black raises the above.

**Comment by jaidisido** [comment]
Thanks for the reply @npatki, I am glad to hear it's being worked on.

My team looks after the [AWS SDK for pandas](https://github.com/aws/aws-sdk-pandas) library. I was simply playing with SDV for now and when attempting to add it to our [pyproject.toml](https://github.com/aws/aws-sdk-pandas/blob/release-3.0.0/pyproject.toml) as an optional dependency, the error was raised by poetry.

Downgrading black might solve the issue. But even then the poetry resolver is taking too long to resolve the dependencies. This [comment](https://github.com/sdv-dev/SDV/issues/1345#issuecomment-1490410743) seem to mention the same issue but with pip. That being said, the long resolution time might be due to a different issue (resolution tree being too large perhaps).

I imagine these issues might be alleviated once you update your dependency strategy as you mentioned.

**Comment by npatki** [comment]
I'm closing this issue in favor of the [CTGAN issue](https://github.com/sdv-dev/CTGAN/issues/276). This will resolve the immediate conflict.

For the longer term strategy, I have filed #1368 for tracking purposes.
