### ISSUE TITLE
Installing SDV in Google Colab Notebook: `ERROR` in pip's dependency resolver

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1360]
### Environment Details

* SDV version: 1.0.0 (latest)
* Python version: 3.9 (Colab Notebook)
* Operating System: Linux (Colab Notebook)

### Error Description
When running `pip install sdv` in my Colab Notebook, I have now started seeing the following error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchtext 0.15.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchdata 0.6.0 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchaudio 2.0.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
```

This affects our demo notebooks, since they are all on Google Colab.

(However, the SDV still appears to run with out issues.)

### Root Cause

It appears that Google Colab made some updates as to which libraries are pre-installed.

- On 3/10: Google Colab updated to `Python 3.9`
- On 3/31: Google Colab updated to the latest versions of `torch` (2.0)

See [Google Colab release notes](https://colab.research.google.com/notebooks/relnotes.ipynb#scrollTo=wJLyPhu-XXov)

Can we update the versions of `torch`?

### Workaround
In the meantime, use the following steps to run the SDV on a Colab Notebook.

1. Install the SDV `pip install sdv` and **ignore any of the errors that get printed**
2. Restart the Kernel. In Colab, click `Runtime` in the top menu bar and then `Restart runtime` (see screenshot below)
3. Now you can continue with your code. Import SDV and use the features.

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/3227804/230629534-aa2a9fd4-29dd-412e-a02d-c811a67cca3b.png">

To see this in action, see [any of the demo notebooks](https://docs.sdv.dev/sdv/demos)

**Comment by DuelistJeff** [comment]
I have actually hit an error running SVD 
                     sdv_model = GaussianCopulaSynthesizer(metadata)
---> 57         sdv_model.fit(df)

ContextualVersionConflict: (torch 2.0.0+cu118 (/usr/local/lib/python3.9/dist-packages), Requirement.parse('torch<2,>=1.8.0; python_version < "3.10"'), {'deepecho', 'ctgan'})

my process has created several sets of data for me before I hit this, so it works to a point but then...

**Comment by npatki** [comment]
Hi @DuelistJeff -- did you restart the Kernel after installing the SDV? The steps would be:

1. Install the SDV `pip install sdv`
2. Restart the Kernel. In Colab, click `Runtime` in the top menu bar and then `Restart runtime` (see screenshot below)
3. Then you can import sdv and use the features

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/3227804/230629534-aa2a9fd4-29dd-412e-a02d-c811a67cca3b.png">

**Comment by DuelistJeff** [comment]
Hi @npatki,

Yes I did. As I mentioned although it may not have been clear, it was running through several iterations of creating artificial data for me. I have a dataset with large sample of some results and very small amounts of others, so I am using SDV to top up some of the low counts with artificial data to get better training results with my model.

It had made several thousand data samples when it suddenly crashed with the above error. Just out of curiosity I ran the exact same code again and this time it go through and finished all the samples I wanted so the error must have some random factor involved. But it does seem to be with the downgrading of Colab's torch version to install SDV.

**Comment by npatki** [comment]
Hi @DuelistJeff would you mind [filing a new issue](https://github.com/sdv-dev/SDV/issues/new/choose) related to your problem? The root cause may be related to this one, but it would be nice to have a separate thread to help you.

**Comment by DuelistJeff** [comment]
Hi @npatki,

I am not sure it is worth it. As I say I have managed to bypass the problem for now. I just wanted to let you know that when you said in the original post that SDV still runs without updating the pytorch version, there is at least one case when it did not.

I would imagine that there will be more people having the same problem running SDV on google colab in the near future until the pytorch version in SDV is updated.

Thanks

**Comment by shadab75** [comment]
@npatki 
Hi i have same problem but i could not fix that can you help me ?

**Comment by npatki** [comment]
Hi @shadab75, in the original comment I observed the error itself did not interfere with much of the functionality:

> the SDV still appears to run with out issues.

Have tried running any of the code in the SDV? If not, I'd try this first. If you observe any crashes or error when running any of the synthesizers then let us know.

**Comment by npatki** [comment]
Note that this issue will likely be resolved by #1365. But I can keep it open in case anyone wants to discuss workarounds in the meantime.

**Comment by PadariyaDebo** [comment]
Hi @npatki 

I am struggling with the sdv installation in Google Colab, as you suggested earlier, I restarted the runtime after installing sdv, and it showed the following error:
ModuleNotFoundError: No module named 'sdv.tabular'
Could you please advise on this?

**Comment by npatki** [comment]
Hi @PadariyaDebo, in your case I think the error is correct. If you are using the latest version of SDV, then there is no such module as `sdv.tabular`. We have renamed it to `sdv.single_table`. For more information about the API, the [SDV docs website](https://docs.sdv.dev/sdv).

**Comment by PadariyaDebo** [comment]
Hi @npatki.

Thank you for suggesting this; however, after installing the latest version of SDV I am getting the following error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
torchaudio 2.0.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchdata 0.6.0 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchtext 0.15.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchvision 0.15.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.

**Comment by npatki** [comment]
@PadariyaDebo the topmost comment of the issue addresses this error. You can also follow the instructions in any of the [demo notebooks](https://docs.sdv.dev/sdv/demos).

**Comment by PadariyaDebo** [comment]
> @PadariyaDebo the topmost comment of the issue addresses this error. You can also follow the instructions in any of the [demo notebooks](https://docs.sdv.dev/sdv/demos).

Thanks @npatki

**Comment by npatki** [comment]
Hi everyone, good news! 

Since we've upgraded the version of `torch` (in #1365), I can confirm that there is no longer a pip Error when using a Colab notebook. So I'm marking this issue as fixed!

_Note that Colab will still ask you to restart the Kernel, as there are still some packages that need to be overridden. However,  there are no longer any dependency conflicts._

**Comment by SKKhan** [comment]
Hi, I install the !pip install sdv on google colab. When I run the python script on google colab, I face following error. 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-9da0e4fddb71>](https://localhost:8080/#) in <cell line: 4>()
      2 import matplotlib.pyplot as plt
      3 import seaborn as sns
----> 4 from sdv.tabular import GaussianCopula
      5 from sklearn.metrics import mean_absolute_percentage_error
      6 from scipy.stats import ks_2samp

ModuleNotFoundError: No module named 'sdv.tabular'

**Comment by npatki** [comment]
Hi @SKKhan , the error state you are reporting is different from what this issue is describing. If you continue to have problems, I would recommend you to start a new issue.

Please note that there is no such module as `sdv.tabular`. Where are you finding instructions to do ` from sdv.tabular import GaussianCopula`? These instructions are for a version of SDV that is over 2 years old now.

I would recommend you to to follow the installation instructions [here](https://docs.sdv.dev/sdv/installation) and reference the [troubleshooting instructions on our website](https://docs.sdv.dev/sdv/reference/support-and-troubleshooting/support-for-installation#modulenotfounderror-or-attributeerror) if you are having problems.
