### ISSUE TITLE
ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM

### ISSUE THREAD

**Issue by R-Palazzo** [sdv-dev/SDV#1363]
### Problem Description

Running the `sdv/tests` with `pytests` raised the following warnings:

`ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.73.173', 60186), raddr=('52.216.129.131', 443)>`

`ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.73.173', 60180), raddr=('54.231.224.145', 443)>`

### Expected behavior

We want to modify the code to no longer get these warnings.

### Additional context

Here is given the code lines in `sdv` that raised the warnings. Because this list may be incomplete, it would be nice to check after the correction that the warnings are no longer in the `warning summary` of `pytests`.

#### Lines to be modified:

```
/tests/integration/datasets/test_demo.py:33
/tests/integration/datasets/test_demo.py:10
```

**Comment by amontanez24** [comment]
Seems that this is not reproducible or has already been fixed
