### ISSUE TITLE
DeprecationWarning: `covariance` will be renamed to `correlation` in v0.4.0   warnings.warn('`covariance` will be renamed to `correlation` in v0.4.0'

### ISSUE THREAD

**Issue by simonou99** [sdv-dev/SDV#1367]
### Environment Details

* SDV version: 1.0
* Python version: 3.9 (or whatever the version on Colab)
* Operating System: Colab Linux

### Error Description

Multiple rows of:  
```
.../python3.9/dist-packages/copulas/multivariate/gaussian.py:280: DeprecationWarning: `covariance` will be renamed to `correlation` in v0.4.0
  warnings.warn('`covariance` will be renamed to `correlation` in v0.4.0',
```

### Steps to reproduce

```
synthesizer = HMASynthesizer(metadata)
synthesizer.fit(data_collection)    # warnings at here
```

**Comment by npatki** [comment]
Hi @simonou99, this issue is already being worked on in the Copulas library and will be fixed in the upcoming release.

For more details, see [Copulas issue 343](https://github.com/sdv-dev/Copulas/issues/343)
