### ISSUE TITLE
Fix inaccurate metadata for demo `expedia_hotel_logs`

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1375]
### Environment Details
* SDV version: 1.0.0 

### Error Description
The demo dataset `expedia_hotel_logs` has inaccurate metadata. Since the metadata does not match the actual data, the SDV synthesizers are not able to model it.

### Steps to reproduce

```python
from sdv.datasets.demo import download_demo
from sdv.single_table import GaussianCopulaSynthesizer

data, metadata = download_demo(
    modality='single_table',
    dataset_name='expedia_hotel_logs'
)

synthesizer = GaussianCopulaSynthesizer(metadata)
synthesizer.fit(data)
```

This will crash with the following output:
```
InvalidDataError: The provided data does not match the metadata:

Invalid values found for boolean column 'is_mobile': [0, 1].
Invalid values found for boolean column 'is_package': [0, 1].
Invalid values found for boolean column 'is_booking': [0, 1].
Invalid values found for boolean column 'hotel_continent': [0, 2, 3, '+ 3 more'].
```

### How to Fix
All the columns should be listed as `categorical` instead of `boolean`.

Starting from SDV 1.0, `boolean` only refers to columns that have `True` or `False` values. If there are any other values present, it must be `categorical`.

**Comment by srinify** [comment]
Closing as Resolved
