### ISSUE TITLE
Fix inaccurate metadata for `census_extended`

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1378]
### Environment Details

* SDV version: 1.0.0

### Error Description

The demo dataset `census_extended` has inaccurate metadata. Since the metadata does not match the actual data, the SDV synthesizers are not able to model it.

### Steps to reproduce

```python
from sdv.datasets.demo import download_demo
from sdv.single_table import GaussianCopulaSynthesizer

data, metadata = download_demo(
    modality='single_table',
    dataset_name='census_extended'
)

synthesizer = GaussianCopulaSynthesizer(metadata)
synthesizer.fit(data)
```

Output:
```
InvalidDataError: The provided data does not match the metadata:
The columns ['id'] are not present in the metadata.
```

### How to Fix

1. Add the `'id'` column into the `columns` section of the metadata JSON
```json
"columns": {
    "id": { "sdtype": "id" }
}
```

2. Also add this column as a primary key in the top level
```json
{
    "primary_key": "id",
    "columns": {
        ...
    }
}
```

**Comment by pvk-developer** [comment]
The `census_extended` metadata has been successfully updated, and you can check it out [here](https://colab.research.google.com/drive/1aiFjKZ-30vn1fVCPAKHlyfSnQ3Y7Piz8?usp=sharing).
