### ISSUE TITLE
Unwanted negative numbers generated

### ISSUE THREAD

**Issue by wbarnsley** [sdv-dev/SDV#138]
* SDV version: 0.2.2
* Python version: 3.7.3
* Operating System: mac

### Description

I was trying to generate a synthetic version of a table. The table in question has two numeric columns, of which all of the entries are positive. After fitting the sdv object, I sampled and found that the two numeric columns contained negative values. After reading your paper from IEEE I was under the impression a truncated gaussian would be used and that this should not happen. 

### What I Did

```
import pandas as pd
from sdv import SDV, Metadata

df_data = pd.DataFrame(data = {'col_1':list(range(10))})

sdv = SDV()
table = {'data': df_data}
metadata = Metadata()
metadata.add_table('data', data=table['data'])
sdv.fit(metadata, table)
df_synth = sdv.sample_all(len(df_data.index))['data']

print(df_synth)
```

#### Output
```
   col_1
0     10
1     -3
2      0
3      8
4      3
5      9
6      6
7      8
8      4
9      7
```

**Comment by csala** [comment]
Hi @wbarnsley the truncated gaussian distribution was indeed not being used before.
We are currently doing some changes here and on the Copulas library that will make using the Truncated Gaussian distribution on SDV.
We will let you know here once the changes are all in and ready to use.
Stay tuned!

**Comment by csala** [comment]
This topic is being covered [in a newer issue](https://github.com/sdv-dev/SDV/issues/200), so I'm closing this to follow up in one place only.
