### ISSUE TITLE
HMASynthesizer Scale parameter does not work for really small values

### ISSUE THREAD

**Issue by VasudevTA** [sdv-dev/SDV#1390]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1
* Python version: 3.9.16
* Operating System: Colab

### Problem description
How does scale= work in `sample`?  For example on using scale=0.01, I get the following table lengths: (edited) 
![image](https://user-images.githubusercontent.com/42139698/234322491-78b71d54-b4ae-421d-a1ae-8dcaf42f804e.png)

This is my schema:
![image](https://user-images.githubusercontent.com/42139698/234322712-aca4d77a-84c6-4857-b1fa-3edf87407527.png)

**Comment by npatki** [comment]
Hi @VasudevTA, thanks for filing the issue. You can find the intended usage of the `scale` parameter [on the docs page](https://docs.sdv.dev/sdv/multi-table-data/sampling#sample).

In your example, `scale=0.01` is intended to create synthetic data that is roughly 1% of the size of the original input data. I'm curious why you only want to create 1% of the original?

### Detailed Findings
I was able to replicate this issue in the cases where the _scale is really small_. This seems like a bug, as the sampling falls back to the original table size.

Eg. if a table has 10 rows originally and you request `scale=0.01`, you are technically requesting 0.1 rows. This doesn't really make sense to it seems to fall back to the original size of the table (10 rows)

### Next Steps
The first question I'd ask is **why is it necessary to create data of such small sizes**?

I propose capping the minimum size of any root tables to 1 row. So in this case, if you said `scale=0.00001`, then 
- `product` should have 1 row
- `hh_demographic` should have 1 row
- `transaction` (child table) may have 0 or more rows, depending on what the model learned

Note that that if scale is so low, the cardinality will not be accurate. We should showing a warning if we ever have to bump the # of rows to 1 (the minimum cap is taking effect).

```
Warning: The 'scale' parameter it too small. Some tables may have only 0 or 1 rows. For better quality data,
please choose a larger scale.
```

**Comment by VasudevTA** [comment]
> why is it necessary to create data of such small sizes? 

The reason is that HMAsynthesizer is VERY slow (on Colab) for any reasonably sized dataset. I have been running several experiments (to understand a functionality or to find the best distribution for example) and it's difficult to keep track. And that is how I stumbled upon this issue when reducing the size of the data.

Are there any tips to speed up the HMAsynthesizer?

**Comment by npatki** [comment]
Hi @VasudevTA, it's my understanding that the modeling phase (`fit`) would actually take longer than the sampling phase (`sample`). So if you're able to get past modeling, it should be faster to sample. Is that not what you're observing?

I would suggestion using a larger value for scale. Since you only have 40 rows in `hh_demographics`, applying a scale that is too small will result the bug we described above. I would suggest trying a scale of `0.1` (=4 rows) or `0.05` (=2 rows).

Note that the HMASynthesizer is not suited for all kinds of dataset. You can find more information [here in the docs page](https://docs.sdv.dev/sdv/multi-table-data/modeling/hmasynthesizer) and follow the link to contact us.

**Comment by VasudevTA** [comment]
Hi @npatki. 
> it's my understanding that the modeling phase (fit) would actually take longer than the sampling phase (sample).
It's the sampling that takes longer, hence the scaling down. I am wondering if I am doing something wrong...

>Note that the HMASynthesizer is not suited for all kinds of dataset.
For reference, I am using the hh_demographics, product and transaction tables from this dataset: https://www.kaggle.com/datasets/frtgnn/dunnhumby-the-complete-journey This looks like the standard use-case for the HMA.

I had a question: The algorithm mentioned in your 2016 paper seems to be parallelizable. I know it doesn't use GPU, but Does HMA use all the available cores?

**Comment by npatki** [comment]
Hi @VasudevTA, let's keep this issue related to the scale parameter. We can keep it open to track the proposed fix [in this comment](https://github.com/sdv-dev/SDV/issues/1390#issuecomment-1522162375).

> I had a question: The algorithm mentioned in your 2016 paper seems to be parallelizable. I know it doesn't use GPU, but Does HMA use all the available cores?

I am not an expert in the infra or codebase. The code is available in [in our GitHub](https://github.com/sdv-dev/SDV) -- feel free to take a look!

**Comment by srinify** [comment]
Hey folks! I created this new bug report to capture this issue with Neha's proposed solution: https://github.com/sdv-dev/SDV/issues/2045

I'm going to close this issue out and mark as duplicate and we can discuss there further if needed!
