### ISSUE TITLE
synthetic time series

### ISSUE THREAD

**Issue by adwaitsharma** [sdv-dev/SDV#142]
I would be grateful if you could please suggest the suitability of SDV to synthesize a time series, given that I have some real data. If yes, can you please link to any documentation.

Thanks.

**Comment by csala** [comment]
Hi @adwaitsharma Unfortunately, SDV does not have specific support for time-series yet.
However, we plan on adding it in the near future, after some other changes that are required first.
We'll keep this issue open to keep track of this feature.

**Comment by tolandwehr** [comment]
I presume the feature is not yet included so far. Any advances in sight in near future ;-)?

**Comment by adamFinastra** [comment]
Is there an update on this release? Very interested
