### ISSUE TITLE
add_column() method does not have documentation for SingleTableMetadata and MultiTableMetadata

### ISSUE THREAD

**Issue by R-Palazzo** [sdv-dev/SDV#1425]
There is no documentation for the `add_column` method for the `SingleTableMetadata` and `MultiTableMetadata`.

**Comment by npatki** [comment]
This feature is not officially supported in the SDV library and therefore was not included in the documentation.

In practice, we only see this being used for creating dummy/demo datasets and there is another method [load_from_dict](https://docs.sdv.dev/sdv/single-table-data/data-preparation/single-table-metadata-api#load_from_dict) that can be used to achieve the same effect.

```python
# current usage that we see
metadata = SingleTableMetadata()
metadata.add_column(
  'A',
  sdtype='numerical'
)

# recommended method
metadata = SingleTableMetadata.load_from_dict({
  'columns': {
    'A': { 'sdtype': 'numerical' }
  }
})
```

Alternatively,  if you wish to add a new column ad-hoc (eg. if your schema has changed), you can:
- Go into the metadata JSON file and change it
- Auto-detect metadata again from the updated data
