### ISSUE TITLE
How are child table column distributions determined in HMA?

### ISSUE THREAD

**Issue by VasudevTA** [sdv-dev/SDV#1432]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.0.1
* Python version: 3.10.11
* Operating System: Linux (Google Colab)

### Problem description

I am trying to model a multi table dataset, which looks as follows:
![image](https://github.com/sdv-dev/SDV/assets/42139698/f2376294-c60b-48ac-869f-2ae5dc0cfce0)
This is a smaller subset of tables from this competition on [kaggle](https://www.kaggle.com/datasets/frtgnn/dunnhumby-the-complete-journey): 
`product` and `hh_demographics` are the parent tables and `transaction` is the child table. 
My question are:
1. I used the normal, truncated normal and beta distribution for the `transaction.SALES_VALUE` variable (via `synthesizer.set_table_parameters`), but it doesn't seem to affect the output distribution at all (if we fix the seeds, even the numbers generated are the same) as printed by `get_column_plot`
![image](https://github.com/sdv-dev/SDV/assets/42139698/7e48ee64-7b25-42f8-83a5-32438eefe408)
This is the case with other columns in the table too.
2. The distributions I tried are unimodal but the output is clearly not unimodal. 
3. My understanding from the [paper](https://dai.lids.mit.edu/wp-content/uploads/2018/03/SDV.pdf) is that for each primary key in a parent (say `hh_demographic`), the child rows in `transaction`  are modeled separately and the params stored in the parent. While generating data, these params are used. 
![image](https://github.com/sdv-dev/SDV/assets/42139698/1a719c36-7d1f-495d-b062-2f0d571951f0)
Is my understanding correct? If yes, then what is the distribution that `synthesizer.get_learned_distributions('transaction')` prints used for?

### What I already tried
1. Tried different distributions on the `transaction` table. Had no effect on the output whatsoever
2. Tried changing the default distribution in the parent tables - this has some effect on the `transaction` table columns (but it only makes them worse)

**Comment by npatki** [comment]
Hi @VasudevTA thanks for filing this. We'll take a look and can update with some findings.

In the meantime, I wonder if there is a possible data quality issue or bug. From looking at your distribution plot, I see the following note:

```
Missing Values: Real Data (0.0%), Synthetic Data (12.2%)
```

This is very unusual, as the SDV is only designed to create missing values if the input data has missing values. Can you check your data to verify?

```python
real_transactions = data['transactions']
print('Real Data')
print(real_transactions[pd.isnull(real_transactions['SALES_VALUES'])])

synthetic_transactions = synthetic_data['transactions']
print('Synthetic Data')
print(synthetic_transactions[pd.isnull(synthetic_transactions['SALES_VALUES'])])
```

Is there anything else that is special about the data? For example, you mention that is a smaller subset. When you took the subset, did you ensure that there is referential integrity? (i.e. every transactions links to a product and hh_demographic that exists in those tables)

**Comment by npatki** [comment]
Hi @VasudevTA, are you still looking into this issue? I'm not sure if you were able to look into why the synthesizer was creating missing values (even though the real data didn't have any). If you're still continuing to observe this, please let us know and we can treat this as a new bug.

Your understanding of the HMA algorithm seems correct. Learned distributions are not available for child tables.

I'm closing off this issue due to inactivity, but please feel free to reply if there's more to discuss or investigate. Thanks.
