### ISSUE TITLE
Synthetic data is giving NULL as column values

### ISSUE THREAD

**Issue by harsh-sengar** [sdv-dev/SDV#1447]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.0
* Python version: 3.9
* Operating System: Linux

### Error Description

Hi Team,
I am having a problem with the NULL values, My real data does not contain NULL values for a particular categorical column, but while synthesizer is giving some NULL values in that categorial column along with the categories. I have made metadata as categorical as suggested.

**Comment by npatki** [comment]
Hi @harsh-sengar thanks for filing this issue. I haven't been able to replicate it yet. Would you be able to provide some more information so we can look into it?

1. Your metadata JSON file, as the bug may only occur with certain combinations of columns/schemas
2. The name of the column that is giving you problems (and which table it is in)
3. As a sanity-check, run the diagnostic code below on your _fitted HMA synthesizer_ and let us know what is printed out

**Diagnostic Code** (replace the values as indicated):
```python
COLUMN_NAME = 'my_column_name' # replace with the name of the column that is giving you problems
TABLE_NAME = 'table' # replace with the name of the table that the column is in

# assume variable 'data' is your input data
print('Category values in real data:', data[TABLE_NAME][COLUMN_NAME].value_counts())

# assume variable 'synthetic_data' is the output, synthetic data
print('Category values in synthetic data:', synthetic_data[TABLE_NAME][COLUMN_NAME].value_counts())

# assume variable 'synthesizer' is your HMASynthesizer that is already fitted
all_transformers = synthesizer.get_transformers(table_name=TABLE_NAME)
transformer = all_transformers[COLUMN_NAME]

print('Transformer:', type(transformer).__name__)
try:
    print(transformer.categories_to_values)
except Exception as e:
    print('This transformer is not for categorical data')
```

**Comment by npatki** [comment]
Hi @harsh-sengar, are you still having this problem? I'm closing this issue off since it has been inactive for several weeks.

If you're still experiencing the problem, please feel free to reply and we can always reopen the issue. Running the code above and providing the results will allow us to replicate and identify any problems.
