### ISSUE TITLE
Incorrect distribution for uniform, datetime column

### ISSUE THREAD

**Issue by chernovoldv** [sdv-dev/SDV#1482]
### Problem Description
Sometimes I get wrong distribution for few columns (look at screenshot).
![newplot](https://github.com/sdv-dev/SDV/assets/129969688/167e9c60-dca3-44c8-a618-77563e017f47)
I trying all avaliable distributions and all synthesizers, but can't solve my problem.

### Expected behavior

Maybe this problem can be solved by seting parametres for distributions ('a' and 'b')  manualy or another way to control this parametres .

**Comment by npatki** [comment]
Hi @chernovoldv thanks for filing this issue.

I'm curious which synthesizer you are using? There are some, such as [GaussianCopulaSynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer#parameter-reference) where you can input the _type_ of distribution. So for this column, you can say it is uniform.

```python
from sdv.single_table import GaussianCopulaSynthesizer

synthesizer = GaussianCopulaSynthesizer(
  my_metadata
  numerical_distributions={
    'reg_date_mentee': 'uniform'
  }
)
synthesizer.fit(data)
```

This will likely give you a better fit for the data -- even without having to input the parameter.

### Related Issues
As an FYI

- [SDMetrics #302](https://github.com/sdv-dev/SDMetrics/issues/302): For uniform distributions, the visualization is not accurate at the edges. I think you are running into this with your graph.
- [SDV #1479](https://github.com/sdv-dev/SDV/issues/1479): If you are using CopulaGANSynthesizer, there may currently be an error when specifying numerical distributions. However, I know this feature works for GaussianCopulaSynthesizer.

**Comment by chernovoldv** [comment]
Thanks for answer! But I literaly make same thing.
![Screenshot 2023-06-29 181303](https://github.com/sdv-dev/SDV/assets/129969688/9f849779-3def-4d1a-b27e-4b334dedd082)
Interesting, that I got column with  similar data ('reg_date_mentor'). And there's no problem this column.

I have tryed GaussianCopulaSynthesizer with  uniform distribution for another sample from my data and get same result for column with dates.
![Screenshot 2023-06-29 182659](https://github.com/sdv-dev/SDV/assets/129969688/69e8db98-76f6-41c2-9623-1b2ce1aad1fd)

**Comment by chernovoldv** [comment]
I've founded why it's not working. Then I add for this column 'constraint_class': 'ScalarInequality' I get wrong distribution.
Maybe there's need to update docs with explanations how it's working.

**Comment by npatki** [comment]
@chernovoldv I'm glad it's working for you! I'm going to re-title this issue to be about uniform datetime distributions in general (I think the parameters `'a'` and `'b'` is one possible solution to it, but not the only solution).

Just to make sure I understand correctly: In the visualizations that you have shared above, were you using the `ScalarInequality` constraint? And then when you removed the constraint, the distribution was better?

**Comment by chernovoldv** [comment]
I checked my synthesizer parametres again.
Then I fit synthesizer  without any constraints distribution of new data (I make data with 2*sizes of original data) is right.
After I add constraints 'Inequality' for dates:
- 'reg_date_mentor' <= 'session_date_time';
- 'reg_date_mentee' <= 'session_date_time'.
After that I get wrong distribution (I left 'beta' distribution for this columns) :
![Screenshot 2023-06-30 131004](https://github.com/sdv-dev/SDV/assets/129969688/6cd975a3-7969-4825-b977-8c3dcd813fe0)
In this case it's be acceptable to let add new dates to synthetic data (it's better, cause data for longer time period is better for me).
To solve this problem I add 'ScalarInequality' for 'session_date_time' < = '2022-09-15'.
After that I get wrong distribution for 'reg_date_mentee' and 'mentee_id' (distribution  for 'reg_date_mentor' still is fine):
![Screenshot 2023-06-30 131828](https://github.com/sdv-dev/SDV/assets/129969688/64577eb6-1aea-49b7-b93b-7f68c6316822)
![Screenshot 2023-06-30 131755](https://github.com/sdv-dev/SDV/assets/129969688/0de60ad8-d1cb-46d1-a373-0a2e256ac5d4)

I think the best way to solve problem is make right distribution  for 'session_date_time' and keep constraints Inequality for dates.

**Comment by npatki** [comment]
Hi @chernovoldv are you still working on this project? Unfortunately, we have not been able to to replicate what you're seeing for the inequality constraint. Whenever I apply the inequality constraint, I seem to be getting reasonable data that is within the range.

Perhaps if you are able to share some columns of data, we could try to replicate? It may also be helpful to update to the latest version of the SDV. At the time this issue was filed, we were on 1.2.0. Now we are on 1.4.0 and I know we've fixed a few bugs specifically related to the Inequality constraint in that time frame.

I'm marking this issue as stale due to inactivity. But please feel free to reply if there is more to discuss. I'd be happy to reopen the issue.
