### ISSUE TITLE
Unable to run Getting started programs of SDV

### ISSUE THREAD

**Issue by Bharathsrinivasan** [sdv-dev/SDV#1491]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.2.0 
* Python version: python3.9
* Operating System: Mac OS M1 macbook pro

### Error Description

Was trying to get started on data generation using SDV by following the steps listed here. 
https://github.com/sdv-dev/SDV
It seems to work fine in python 3.10.8. 

### Steps to reproduce
https://github.com/sdv-dev/SDV
Create a conda environment as specified in the page above. i have mamba installed, not sure if the issue is because of that. 
Create a python file with following content
```
from sdv.datasets.demo import download_demo
real_data, metadata = download_demo(
    modality='single_table',
    dataset_name='fake_hotel_guests')
```

```
python filename.py
and got the following error. 
ModuleNotFoundError: No module named 'sdv.datasets'
```

**Comment by pvk-developer** [comment]
Hi @Bharathsrinivasan , nice to meet you! It may be helpful to review your conda environment to make sure that `sdv` is properly installed on your conda environment and that the `python` that is used to execute the code belongs to that environment.

#### List the installed packages on your conda environment
Running the following command will list all the installed packages in it:
```bash
conda list
```
If you don't see `sdv` in there, please re-install by running:

```bash
conda install -c pytorch -c conda-forge sdv
```

#### Check your conda environment / python 
If you do see `sdv` in that list, try running then `python filename.py`. If that doesn't work, check which `python` you are using, it has to be the same as the conda env:
```bash
which python
```
If the `python` is pointing to somewhere else but the environment folder for that conda env, re-create your `conda env` and re-install `sdv`.

**Comment by npatki** [comment]
Hi @Bharathsrinivasan, are you still having this problem?

As @pvk-developer mentioned above, a `ModuleNotFoundError` typically indicates an issue with installation. You can view our [Troubleshooting Guide](https://docs.sdv.dev/sdv/installation#modulenotfounderror-or-attributeerror) for more information

I'm closing this issue off since it has been inactive for a few weeks. If you are still encountering the problem, please feel free to reply here and we can always reopen to investigate. Thanks!
