### ISSUE TITLE
How to setup regex guidance

### ISSUE THREAD

**Issue by pvk-developer** [sdv-dev/SDV#1493]
### Problem Description

With generators of unique values being the main boundary towards generating new synthetic data, we should come up with the proper guidance towards writing a `regex` expression and if the number is too low warn the user that `SDV` will no be able to generate more rows than what the regex allows.

We have encountered such an issue with `fake_hotels` when trying to sample `1_000_000` new rows, the `HID_` is capped to `HID_999` because of the regex expression, therefore, it can't generate more than those 1000 unique hotels.

**Comment by npatki** [comment]
[RDT Issue 740](https://github.com/sdv-dev/RDT/issues/749) is now aimed at resolving this concern. We could always warn the user upfront, but the failsafe would be allowing the `RegexGenerator` transformer itself to create unlimited values. If it runs out of regexes, it can restart the sequence but add a suffix at the end. This would always ensure the values are unique -- even though they may not exactly follow the provided regex. (We'd warn the user too.)

**Comment by npatki** [comment]
The fix in [RDT 749](https://github.com/sdv-dev/RDT/issues/749) now resolves this issue: The transformer itself keeps track of when it's run out of regexes. Then, it continues to create new unique values by appending suffixes such as (1), then (2), ... This way, it will never run out and the user can continue to sample as much as they want.
