### ISSUE TITLE
TVAESynthesizer' object has no attribute '_model'

### ISSUE THREAD

**Issue by Travisma2233** [sdv-dev/SDV#1503]
![image](https://github.com/sdv-dev/SDV/assets/83893812/6c2e100d-2411-4fc5-9f73-848edf5c08b1)
Does anyone encounter this problem when using the TVAESynthesizer of single table?

**Comment by npatki** [comment]
Hi @Travisma2233, nice to meet you. I have not yet encountered this problem.

Would you be able to provide some more information about your setup? It would be helpful if you could share:

1. A code snippet showing your code, how you are creating your synthesizer and how you are sampling
2. Your metadata
3. Any other relevant info about your data that may be useful to help us replicate the issue

Thanks!

**Comment by npatki** [comment]
Hi @Travisma2233 are you still encountering this problem?

I'll close the issue off since it's been inactive for a few weeks. But please feel free to reply if you're still seeing this. We can always re-open to help you solve the problem.

**Comment by ArijitSinghEDA** [comment]
@npatki I am also facing this issue, even for CopulaGAN and CTGAN.

This is a sample of what I am doing:
```
from sdv.metadata import SingleTableMetadata
from sdv.single_table import CopulaGANSynthesizer

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data)
synth = CopulaGANSynthesizer(metadata, epochs=5)
synth.fit(data)
sample = synth.sample(num_rows=5)
```

I am passing a dataframe with single integer column

**Comment by npatki** [comment]
Hi @ArijitSinghEDA thanks for the details. I'll reopen the issue.

Could you also share your **metadata**? You can use `print(metadata)` to see it. You can also save it as a JSON file (`metadata.save_to_json(filepath='metadata.json')`).

**Comment by ArijitSinghEDA** [comment]
@npatki This is the metadata:
```
{
    "primary_key": "price",
    "columns": {
        "price": {
            "sdtype": "id"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
```

**Comment by ArijitSinghEDA** [comment]
@npatki Can this issue be because of Docker also? The error I am getting is when I run the code inside a docker; but when I am running the same code on my local system using WSL, everything is working fine.

**Comment by npatki** [comment]
Hi @ArijitSinghEDA, in this issue we are discussing the error for `TVAESynthesizer object has no attribute '_model'`.  I'm a bit confused because it seems like you are able to generate synthetic data after all. Are you still running into this error?

For the `'id'` problem, perhaps you can file a new issue with what you're observing. In the new issue, it would be helpful to give us as much technical detail as possible to help us replicate the issue. So we'd appreciate the **exact code** you are using to write metadata, create a TVAE synthesizer, and sample as well as the exact output you're getting (vs. what you expect). Thanks.

**Comment by npatki** [comment]
We have been able to replicate the issue in #1741 so I'm marking this one as a duplicate.

This seems to happen when the synthesizer has nothing to learn: Eg. if all columns are marked as ID, then the synthesizer's job is only to generate unique IDs. There is no distributions or data patterns to learn.

For more info, please see #1741, which also contains a workaround. Please feel free to reply there to continue the discussion. Thanks.
