### ISSUE TITLE
[Question] How to work with Multi-Tables (HMASynthesizer) parameters?

### ISSUE THREAD

**Issue by majidliaquat** [sdv-dev/SDV#1549]
Hi,

I am newely experiencing with Multi-tables Datasets to generate synthetic data.

## What I did previously?

I used CTGAN for single table datasets where I can easily change the hyperparameters to generate a good quality synthetic data which was more similar to real data.

## What I am looking for?

Actually, I am looking for help that is there any way by using HMASynthesizer to generate synthetic data by changing the parameters to improve the quality of generated data?

#What Currently I am following?

I am following the documentation which is given on website ( [HMASynthesizer](https://docs.sdv.dev/sdv/multi-table-data/modeling/synthesizers/hmasynthesizer) ).

My current metadata looks like : 

```
{ "tables": { "Table 1 account.csv": { "columns": { "account_id": { "sdtype": "id" }, "district_id": { "sdtype": "id" }, "frequency": { "sdtype": "categorical" }, "date": { "sdtype": "numerical" } }, "primary_key": "account_id" }, "Table 2 loan.csv": { "columns": { "loan_id": { "sdtype": "id" }, "account_id": { "sdtype": "id" }, "date": { "sdtype": "numerical" }, "amount": { "sdtype": "numerical" }, "duration": { "sdtype": "numerical" }, "payments": { "sdtype": "numerical" }, "status": { "sdtype": "categorical" } }, "primary_key": "loan_id" }, "Table 3 order.csv": { "columns": { "order_id": { "sdtype": "id" }, "account_id": { "sdtype": "id" }, "bank_to": { "sdtype": "categorical" }, "account_to": { "sdtype": "numerical" }, "amount": { "sdtype": "numerical" }, "k_symbol": { "sdtype": "categorical" } }, "primary_key": "order_id" } }, "relationships": [ { "parent_table_name": "Table 1 account.csv", "child_table_name": "Table 2 loan.csv", "parent_primary_key": "account_id", "child_foreign_key": "account_id" }, { "parent_table_name": "Table 1 account.csv", "child_table_name": "Table 3 order.csv", "parent_primary_key": "account_id", "child_foreign_key": "account_id" } ], "METADATA_SPEC_VERSION": "MULTI_TABLE_V1" }
```
Also I visulise it:
![image (4)](https://github.com/sdv-dev/SDV/assets/13814086/af77dc76-2e65-499b-9c25-19df4be519be)

## Do I need to change this section?

As there any parameters I can pass with metadata in HMASynthesizer or something else should I add?

```
from sdv.multi_table import HMASynthesizer

synthesizer = HMASynthesizer(metadata)
synthesizer.fit(real_data)  #Tables of real data in a dictionary

synthetic_data = synthesizer.sample()
```
I am getting the Quality Score around 0.50 as I tried [Quality Report SDMetrics](https://docs.sdv.dev/sdmetrics/reports/quality-report/multi-table-api).

Looking forward,
Many Thanks,

Majid

**Comment by npatki** [comment]
Hi @majidliaquat,

The first thing I would look into is what, precisely, is causing the quality score to be at 0.5. The quality score is comprised of individual column shapes (marginals) and column pair trends (correlations). Knowing which one is lower, and particularly which tables/columns have low scores will give you valuable information when customizing your HMASynthesizer. 

Were you able to look into this?

As for which customizations you can do, the later portions of the [API doc](https://docs.sdv.dev/sdv/multi-table-data/modeling/synthesizers/hmasynthesizer#set_table_parameters) explain how to use the `set_table_parameters` method, which you can use to configure individual tables. At this time, the HMASynthesizer uses the Gaussian Copula for each underlying, individual table.

**Comment by majidliaquat** [comment]
Hi @npatki,

Thank you for response. Yes I will further look into specific tables / columns scores. 
Thanks for sharing the document link of specific section that I was actully looking for. 

Many Thanks,
Majid

**Comment by npatki** [comment]
Great! I'm closing this issue off since we answered the question. If there are any follow-ups, please feel free to reply here and we can always reopen the issue.
