### ISSUE TITLE
Ability to set parameters/distributions (eg. Categorical Probability distribution)

### ISSUE THREAD

**Issue by Mrin7** [sdv-dev/SDV#1554]
### Problem Description

We cannot update learned parameters - Distributions(Upper bound, Lower bound, mean, Standard deviation), Categorical(Weights/Probability distribution)

### Expected behavior

We want to be able to update these learned paraments from user provided input/ manual inputs. We could not find options in constraint logic page.

### Additional context

Can you please share codes to updates these parameters and run GANs(Gaussian Copula) synthesizer?

**Comment by Mrin7** [comment]
Hi @npatki ,

Thanks for your response.

The purpose here is to create more representational data for marginalized groups. 
For example - Original sample has 20%(Female) and 80%(Male) with their salary distributions 1:1.6 ratio. In the synthesized data we want to show 60%(Female) and 40%(Male) with the same salary distribution 1:1.6 ratio. Here we want to keep other features with the same learned parameters, with an increase in sample size for a particular marginalized group.

Can you suggest a method of achieving this using SDV?

Best,
Mrin

**Comment by npatki** [comment]
Hi @Mrin7,

Got it. Thanks for describing your usage. To clarify there are 2 stages to using the SDV synthesizers.

### Stage 1: Training
During this phase, the SDV synthesizers will learn patterns from the real data. All parameters and constraints are in service of this goal: to learn from the real data, even if the real data contains biased patterns (eg. marginalized groups appear less frequently).

### Stage 2: Sampling
Once the synthesizer is done learning, you can use it to create synthetic data. 

If you'd like the synthetic data to have **different** properties from the real data, then you can use [Conditional Sampling](https://docs.sdv.dev/sdv/single-table-data/sampling/conditional-sampling) to request specific patterns (eg. 50/50 gender ratio). I would also recommend [going through this demo fully](https://colab.research.google.com/drive/1XCwu7NaCYXf3kkhlx4Iei4w2KrXzr1zo?usp=sharing), as it covers conditional sampling in detail.

The important distinction is that _training_ will always learn patterns from your real data, exactly as they appear. To purposefully disrupt those patterns (making the synthetic data different form real data), we recommend addressing it in the sampling phase.

**Comment by npatki** [comment]
Hi @Mrin7, did you have any follow ups? Since this issue has been inactive for a few weeks and we've answered the question, I'm going to mark it as resolved.

If there is more to discuss, feel free to reply and I can always reopen the issue. Thanks.
