### ISSUE TITLE
Address `SettingWithCopyWarning` (HMASynthesizer)

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1557]
### Environment Details

* SDV version: 1.4.0 (latest)
* Python version: 3.10 
* Operating System: Linux (Google Colab)

### Error Description
When sampling from the HMASynthesizer, I receive a `SettingWithCopyWarning` that is coming directly from pandas. We should update the code based on the pandas recommendations.

### Steps to reproduce

```python
from sdv.datasets.demo import download_demo
from sdv.multi_table import HMASynthesizer

real_data, metadata = download_demo(
    modality='multi_table',
    dataset_name='fake_hotels'
)

synthesizer = HMASynthesizer(metadata)
synthesizer.fit(real_data)
synthetic_data = synthesizer.sample(scale=2)
```

Output:
```
/usr/local/lib/python3.10/dist-packages/sdv/sampling/hierarchical_sampler.py:107: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sampled_rows[foreign_key] = parent_row[parent_key]
```

**Comment by npatki** [comment]
Confirming that this is also happening on the latest SDV, v1.6.0 that was just released today.

**Comment by pvk-developer** [comment]
@npatki I was not able to replicate it on this [google colab](https://colab.research.google.com/drive/1saxfZAwosuv33J7jBFeHG237kjuNYTTT?usp=sharing) could you share more details about your environment / colab notebook to replicate this?
