### ISSUE TITLE
Knowledge-based synthetizing

### ISSUE THREAD

**Issue by schupbachl** [sdv-dev/SDV#156]
* SDV version: 0.3.3
* Python version: 3.7
* Operating System: Windows 10

### Question

Hello, I see on the paper attached to this repo (https://dai.lids.mit.edu/wp-content/uploads/2018/03/SDV.pdf) that it is possible to generate knowledge-based data (C. API Endpoints: customer.synth_row()).

![image](https://user-images.githubusercontent.com/10773783/77456268-4a5c4000-6dfb-11ea-8292-8d2d26ce7838.png)

I searched in the documentation and code but didn't find this function. Is there a way to access this function or will it be implemented soon?

**Comment by csala** [comment]
Hello @schupbachl 

This was something that the original research prototype included, but which was later on put on hold to ensure consistency and robustness when the current open source version was implemented.

Expect this to be introduced as a new feature sometime in the near future.

We'll use this issue from now on to keep track of the development.

**Comment by csala** [comment]
This functionality is being covered as part of #316
