### ISSUE TITLE
import error on: from sdv.lite import SingleTablePreset

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [sdv-dev/SDV#1565]
Getting an import error:
`from sdv.lite import SingleTablePreset`

```
Cell In[2], line 1
----> 1 from sdv.lite import SingleTablePreset
      2 # import pandas as pd

File [c:\ProgramData\anaconda3\Lib\site-packages\sdv\__init__.py:18](file:///C:/ProgramData/anaconda3/Lib/site-packages/sdv/__init__.py:18)
     14 from operator import attrgetter
     16 from pkg_resources import iter_entry_points
---> 18 from sdv import (
     19     constraints, data_processing, datasets, evaluation, lite, metadata, metrics, multi_table,
     20     sampling, sequential, single_table)
     22 __all__ = [
     23     'constraints',
     24     'data_processing',
   (...)
     33     'single_table'
     34 ]
     37 def _get_addon_target(addon_path_name):

File [c:\ProgramData\anaconda3\Lib\site-packages\sdv\constraints\__init__.py:2](file:///C:/ProgramData/anaconda3/Lib/site-packages/sdv/constraints/__init__.py:2)
      1 """SDV Constraints module."""
----> 2 from sdv.constraints.base import Constraint
      3 from sdv.constraints.tabular import (
      4     FixedCombinations, FixedIncrements, Inequality, Negative, OneHotEncoding, Positive, Range,
...
     75 if module.__name__ == "psycopg2":
     76     # psycopg2 appends " (dt dec pq3 ext lo64)" to it's version
     77     version = version.split()[0]

ImportError: Can't determine version for bottleneck
```

* SDV version: 1.4.0
* Python version: 3.11.3
* Operating System: Windows 10

**Comment by npatki** [comment]
Hi @Karlheinzniebuhr, nice to meet you and thanks for filing the issue.

Unfortunately, I'm not able to replicate this using the same version of SDV and Python as reported. I am using anaconda as well, but on a Mac. I will ask someone on the SDV team to test this with Windows.

In the meantime, I'm curious if any of the following apply to your case:

1. Do you have anything else installed in the same environment as the SDV? I'm particularly interested in the `"psycopg2"` library that seems to be causing the error. As far as I'm aware, this library is not required for SDV to run (neither a direct nor indirect dependency). 
2. Could you try installing the SDV in a clean, fresh environment to see if it works there?
3. Are you able to install and use other data science libraries such as `pandas` or `numpy`? How about previous versions of the SDV?

The questions above will help us better understand what's happening. Let me know if you have any questions!

**Comment by npatki** [comment]
Glad to hear!
