### ISSUE TITLE
No way to fix the random seed?

### ISSUE THREAD

**Issue by oshev** [sdv-dev/SDV#157]
* SDV version: 0.3.2
* Python version: 3.6.6
* Operating System: Mac OS Mojave 10.14.6.

### Description

I'd like to set up some tests for the generated data in my project but I can't see any way to fix the random seed for the data sampling procedure in SDV. I'm not sure if there is any random factor in data model generation as well so I would need to fix the seed there too.

### What I Did

I tried to check the parameters in the methods in SDV - there is nothing about the seed.

I tried to fix the seed using standard Python and Numpy ways:
```
import numpy as np
import random

RANDOM_SEED = 0

np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)
```
SDV doesn't get affected by these. 

I tried to search for keywords "random" and "seed" in SDV project but I couldn't find anything. 

My guess is that randomization comes from some sub-dependencies of the project. I haven't managed to figure out from where exactly yet.

**Comment by csala** [comment]
This might be happening due to how Copulas is handling the random states. See /sdv-dev/Copulas/issues/113

**Comment by csala** [comment]
Recently introduced models are now properly affected by the numpy and torch seeds, as can be seen in issue #299 , so this can be already closed.
