### ISSUE TITLE
How to modify the model in order to get a higher quality score, especially for the columns pair trends?

### ISSUE THREAD

**Issue by wzker11** [sdv-dev/SDV#1590]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.3.0
* Python version: 3.11.3
* Operating System: Windows

### Problem description

I have tried models - GaussianCopula, CTGAN and TVAE, all of them give me a low score for column pair trends (30%) when I generate the quality report.

### What I already tried
I have tried reclean the origin data, increased the epochs, added the constraints, but still have a low score for column pair trends.

**Comment by npatki** [comment]
Hi @wzker11, good question.

There are few different factors you may want to look at:

1. **Dataset Source**: The SDV is designed for raw, real-world data that you may be collecting from users, customers, etc. If your dataset is hand-crafted using specific logic of formulas, it is not suitable for the SDV synthesizers. I'm curious what is the origin if your training data?
2. **Metadata**: Sometimes, a low score indicates that the sdtype in the metadata is incorrect. For example, some columns may be marked as "categorical" even they're actually numerical. You may want to manually double-check the metadata and update it to be accurate. Some resources: 
    - [Explanation of sdtypes](https://docs.sdv.dev/sdv/reference/metadata-spec/sdtypes)
    - [What is categorical data?](https://datacebo.com/blog/categorical-data/) -- some tricky cases around this
3. **Other Troubleshooting Tips**: The 30% score you see is the average across all correlations in your table. I would recommend getting more insights from the report
    - [get breakdowns](https://docs.sdv.dev/sdmetrics/reports/quality-report/single-table-api#get_details-property_name) to see which particular column(s) are most affected
    - [visualize the data in 2D](https://docs.sdv.dev/sdv/single-table-data/evaluation#get_column_pair_plot) to see the differences

Hopefully this gets you a bit further in your troubleshooting. If you notice anything during the investigation, feel free to reply here with your findings.

**Comment by npatki** [comment]
Hi @wzker11, are you still working on this project? I'm closing this issue off since we've provided some pointers. 

Feel free to reply if there are any follow ups to this, and I will reopen the issue.
