### ISSUE TITLE
Metadata invalid for nations_v1, Toxicology_v1 datasets

### ISSUE THREAD

**Issue by JanJacekJaniszewski** [sdv-dev/SDV#1606]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.4.0
* Python version: 3.9
* Operating System: MAC Venture 13.5.2 (22G91)

### Error Description
The metadata for nations_v1 is not valid since it connects a primary with a non-primary key. 

#### Input
```
from sdv.multi_table import HMASynthesizer
from sdv.datasets.demo import download_demo

real_data, real_metadata = download_demo(
    modality='multi_table',
    dataset_name='nations_v1'
)

synthesizer = HMASynthesizer(real_metadata)
```

#### Output
```
InvalidMetadataError: The metadata is not valid
Relationships:
Invalid relationship between table 'stat' and table 'country'. A relationship must connect a primary key with a non-primary key.
```

#### Input
```
from sdv.multi_table import HMASynthesizer
from sdv.datasets.demo import download_demo

real_data, real_metadata = download_demo(
    modality='multi_table',
    dataset_name='Toxicology_v1'
)

synthesizer = HMASynthesizer(real_metadata)
```

#### Output
```
InvalidDataError: The provided data does not match the metadata:
Relationships:
Error: foreign key column 'molecule_id' contains unknown references: (TR003, TR005, TR013, TR016, TR018, + more). All the values in this column must reference a primary key.
Error: foreign key column 'molecule_id' contains unknown references: (TR003, TR005, TR013, TR016, TR018, + more). All the values in this column must reference a primary key.
```

**Comment by npatki** [comment]
Hi @JanJacekJaniszewski, thanks for reporting.

Indeed, we are aware that there a few multi-table schemas that currently have invalid metadata. We're tracking this in issue #1297. I will mark this issue as a duplicate in favor of the existing one.

Note that this has not yet been prioritized, as most of users will (a) try out the [demo notebooks](https://docs.sdv.dev/sdv/demos), and (b) use the SDV on their own datasets. I'm curious if the `nations_v1` and `Toxicology_v1` datasets are useful for your project in some way? We prioritize these issues based on demand, so if you could describe a little more about what you're working on, that would be helpful. Thanks.
