### ISSUE TITLE
Referential Integrity is not supported properly

### ISSUE THREAD

**Issue by JagdishKolhe** [sdv-dev/SDV#161]
* SDV version: 0.3.3
* Python version: Python 3
* Operating System: Windows / Google Colab

### Description

Trying to generate Synthetic data for out database.

### What I Did

I used sdv.fit method, which gives validation error “Table {} has more than one parent.”  When a table has two FK. As per paper it should work for all relationships.

I think, as per research paper it should work on all type of RDBMS relationships like ONE-TO-ONE, ONE-TO-MANY, MANY-TO-MANY

How to Reproduce:

Well we can take any sample database, which has following things

1. A table is having multiple Foreign keys.  
2. A relationship table which has just two columns say (employee_id, department_id). both of them are foreign keys, and one employee can belongs to multiple departments. 

Now,  lets fit the SDV using fit method, it will give error(s).

**Comment by csala** [comment]
Hello @JagdishKolhe

As mentioned in #162, the current stable version of SDV does not support Multi-parent schemas yet, but development for this feature is currently underway and the next release (which will be out this week) will introduce support for it.

I'm labeling this as `duplicate` and closing, as it covers the same topic as #162, and we'll keep track of the development there.

**Comment by JagdishKolhe** [comment]
Thanks!
