### ISSUE TITLE
Documentation example of HMASynthesizer usage incorrect?

### ISSUE THREAD

**Issue by mcvincekova** [sdv-dev/SDV#1611]
### Problem description
[Minor documentation update request]

The [introductory example of HMASynthesizer usage](https://docs.sdv.dev/sdv/multi-table-data/modeling) in the official documentation seems to be incorrect, since it still references the (non-existent)`num_rows` parameter for the `sample` method.

SDV version used: `Version: 1.4.0`
Following the example:
```
# Step 1: Create the synthesizer
synthesizer = HMASynthesizer(metadata)

# Step 2: Train the synthesizer
synthesizer.fit(real_data)

# Step 3: Generate synthetic data
synthetic_data = synthesizer.sample(num_rows=100)
```

Will result in an error:

```TypeError: BaseMultiTableSynthesizer.sample() got an unexpected keyword argument 'num_rows'```

Would it be possible to update the docs? 
thanks

**Comment by npatki** [comment]
Hi @mcvincekova thanks for letting us know. The docs should be updated now. (The page may require a refresh depending on your cache settings.)

<img width="1485" alt="image" src="https://github.com/sdv-dev/SDV/assets/3227804/229c371c-80f6-4ad0-aae6-d07f92e4e646">
