### ISSUE TITLE
Multiple Parents

### ISSUE THREAD

**Issue by adamFinastra** [sdv-dev/SDV#162]
* SDV version: Latest
* Python version: 3.7
* Operating System: Mac OS

### Description
I have 3 Tables 

**Product**
ProductKey|P0|P1|P2 

**Account**
AccountKey|HouseholdKey|ProductKey|A0|A1

**Household**
HouseholdKey|H1|H2|H3|H4|H5 

The account key depends on both product and household tables. How can you define the account as having multiple parents? 

```
metadata = Metadata()
metadata.add_table('product', data=tables['product'], primary_key='ProductKey')
metadata.add_table('account', data=tables['account'], primary_key='AccountKey',foreign_key='ProductKey',parent='product')
```

The above works for 2 tables, but how can I include the household table since Account is a child of that as well?

**Edit:**
I have defined 

`account_fields = {
    'HouseholdKey': {
        'type': 'categorical',
        "ref": {
                  "field": "HouseholdKey",
                  "table": "household"
                    }
    },
    'ProductKey': {
      'type': 'categorical',
      "ref": {
                "field": "ProductKey",
                "table": "product"
                  }
    }
}`

and then ran

```
metadata = Metadata()
metadata.add_table('household', data=tables['household'], primary_key='HouseholdKey')
metadata.add_table('product', data=tables['product'], primary_key='ProductKey')
metadata.add_table('account',data=tables['account'],primary_key='AccountKey',fields_metadata=account_fields)
```

Does this seem to be the correct way to define this mullti-parent relationship? This does not seem to return the correct results or capture the relationships between the tables when .sample_all is called.

**Comment by csala** [comment]
Hello @adamFinastra, thanks for pointing this out.

As you noticed, the current stable version of SDV does not support Multi-parent schemas yet, but development for this feature is currently underway and the next release (which will be out this week) will introduce support for it.

I'm assigning this issue to the next milestone to properly keep track of this.

**Comment by adamFinastra** [comment]
Thank you! Looking forward to the next release!

**Comment by Gayathri-Gunasekar** [comment]
While creating metadata for synthetic data generation using file from local folder, the relationship returns a empty list ( "relationships": [ ])
how can i set relationships , I have used metadata.add_relationship() but it giving already we have  a primary key,
but not reflecting in final data

**Comment by Gayathri-Gunasekar** [comment]
InvalidMetadataError: Relationship between tables (CUSTOMERSs, ORDERSs) contains an unknown primary key {'CustomerID (PK)'}.
