### ISSUE TITLE
Old demo links on sdv.dev

### ISSUE THREAD

**Issue by jenno-verdonck** [sdv-dev/SDV#1620]
All 3 links for single table, multi table and sequential on the sdv.dev homepage still link to old colab pages.

Specifically these 3 buttons.
![image](https://github.com/sdv-dev/SDV/assets/42772246/811de440-4315-4c5d-b93c-2dfe9b1c4032)

**Comment by npatki** [comment]
Hi @jenno-verdonck, thanks so much for filing this. I'm marking this a documentation request. We'll fix this soon and use this issue to track it.

**Comment by npatki** [comment]
Hi @jenno-verdonck the links should now be fixed. (The page may require a refresh depending on your cache.)

Please let us know if it's not working -- or if you notice any other broken links. Thank you.
