### ISSUE TITLE
Issue in defining Composite key for child table in Relational Dataset SDV1.0

### ISSUE THREAD

**Issue by nishantkumarsinha** [sdv-dev/SDV#1622]
### Environment details

* SDV version: 1.0
* Python version: 3.9

### Problem description
I am working with a relational dataset scenario having two tables ACCOUNT  (parent table) and LOAN(child Table), 
ACCOUNT has primary key : USER_ID
LOAN has composite key : USER_ID, LOAN_NUMBER

### What I already tried
I have referred to SDV issue #894 and issue #890 and understand that the issue of defining composite key has been resolved but I am getting the following error:

metadata.detect_table_from_dataframe(table_name = 'ACCOUNT', data= Account_df)
metadata.update_column(table_name = 'ACCOUNT', column_name = 'USER_ID',sdtype = 'id')
metadata.set_primary_key(table_name = 'ACCOUNT', column_name = 'USER_ID')

metadata.detect_table_from_dataframe(table_name = 'LOAN', data= Loan_df)
metadata.update_column(table_name = 'LOAN', column_name = 'USER_ID',sdtype = 'id')
metadata.update_column(table_name = 'LOAN', column_name = 'LOAN_NUMBER',sdtype = 'id')
metadata.set_primary_key(table_name = 'LOAN', column_name = ('USER_ID','LOAN_NUMBER))
metadata.add_relationship(parent_table_name = 'ACCOUNT', child_table_name = 'LOAN', parent_primary_key = 'USER_ID',child_foreign_key = 'USER_iD')

I run into the below error:
Invalid relationship between table 'ACCOUNT' and table 'LOAN' . A relationship must connect a primary key with a non-primary key.

The moment I remove the USER_ID and LOAN_NUMBER from 'id' sdtype it runs into another error of setting it as id type. 

Can you help me with the correct steps here?

**Comment by npatki** [comment]
Hi @nishantkumarsinha, nice to meet you.

In the SDV, we recognize 2 types of keys:

1. **Primary key** is a single column that is meant to be a _unique identifier_ to the table. That means that every value in a primary key must be unique to the entire table.
2. **Foreign key** is a column that refers to the _primary key of another table_. So a value in a foreign key might repeat (for eg. if you have 2 loans associate with the same account).

Then the relationships you provide must link a foreign key to a primary key. Perhaps you will find [this documentation](https://docs.sdv.dev/sdv/multi-table-data/data-preparation) useful.

As mentioned in the API for [set_primary_key](https://docs.sdv.dev/sdv/multi-table-data/data-preparation/multi-table-metadata-api#set_primary_key), the SDV does not support composite keys right now. Adding support for composite keys is being tracked in #613. To help prioritize the issue, please feel free to respond more there with the details of your project and schema. (I think the issues you have linked are unrelated to composite keys.)

**Comment by nishantkumarsinha** [comment]
Hi @npatki  Thanks for your response.


Let me explain my scenario:

I have a MultiTable use case having ACCOUNT and LOAN Table.

1. ACCOUNT table having bank account details of a user (1 record per user). The columns are USER_ID, ACCOUNT_NO and OUTSTANDING_LOANBALANCE for an year.The table looks like:


USER_ID.     ACCOUNT_NO.   OUTSTANDING_LOANBALANCE     
ABC	             XYZ12                    60000

2. I have a child  LOAN Table linked to the ACCOUNT table having the details of loans taken by the user. A user can take multiple loans. So each row in LOAN table is uniquely identified by (USER_ID and LOAN_NUMBER) as a combination.The outstanding_loan_balance for the user here is spread across the loans taken by the user. The table looks like this:

USER_ID  LOAN_NUMBER OUTSTANDING_LOANBALANCE
ABC.             1                               15000
ABC              2                                20000
ABC.             3                                25000


I have two issues to be resolved:

1. How to define the primary key for LOAN Table having (USER_ID and LOAN_NUMBER) combination as the unique identifier of the row and link it to the parent ACCOUNT table.
2. The OUTSTANDING_LOANBALANCE in the ACCOUNT table is the sum of the OUTSTANDING_LOANBALANCE in the LOAN table for a USER_ID. Is there a way this pattern is learned and retained in synthetic data as well?

**Comment by npatki** [comment]
Hi @nishantkumarsinha, I'm curious where this data is coming from? I don't think the schema that you are describing is quite valid from the perspective of most SQL-based systems.

If an account is allowed to have multiple loans, then `LOANS.USER_ID` should be the foreign key that points to `ACCOUNTS.USER_ID` (primary key of accounts). Since `LOANS.USER_ID` is a foreign key, it cannot also be (part of) a primary key.

What is `LOANS.LOAN_NUMBER`? If this is a unique identifier, then `LOANS.LOAN_NUMBER` would be the sole primary key of this table.

**Comment by npatki** [comment]
Hi @nishantkumarsinha are you still working on this project? I'm closing out the issue since it's been inactive for a few weeks. But feel free to reply if you have any additional questions and we can aways reopen the issue to investigate.
