### ISSUE TITLE
Setting constraints on CTGAN

### ISSUE THREAD

**Issue by abuyousufabdullah** [sdv-dev/SDV#1624]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.4.0
* Python version: 3.10.12
* Operating System: Microsoft Windows 10 Enterprise

### Problem description

Hello,
I am trying to use the CTGAN to generate synthetic data values for my latitude and longitude values. However, I have tried the existing constraint options to impose a constraint on the synthesizer, to ensure that the values generated correspond to my geographic area. 

I am trying to use a pair of 4 latitude and longitude values to define the geographic bounds. These 4 points represent the extreme ends of my study area. So far, I have tried the scalarinequality range and a custom constraint. But none of them are working. 

Can you have a suggestion as to what I can use to get this done?

**Comment by npatki** [comment]
Hi @abuyousufabdullah, nice to meet you.

By default, the SDV should be able to learn the min/max values of your real data, and then ensure the min/max are being respected in the synthetic data. As an example, if the min of your latitude column is  `41.237964` and the max is `42.886589`, then the SDV will generate synthetic latitudes within that range. There should be no constraints needed.


Perhaps I am not understanding the extent of the problem very well. Could you provide a little more context as to what you want to achieve, what you tried, and why it is not working for you? Maybe some code snippets or a sample output would help to illustrate the point.
