### ISSUE TITLE
Unable to visualize metadata (`Error: bad label format` and `CalledProcessError`)

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1625]
### Environment Details
* SDV version: 1.4.0 (latest)
* Python version: 3.10
* Operating System: Linux (Colab Notebook)

### Error Description
When attempting to visualize my metadata for a single table, I am encountering a `CalledProcessError` from the underlying graphing library (graphviz). It appears that there is something misconfigured in the label as the first line is `Error: bad label format`.

### Steps to reproduce
Download the [Income dataset from Kaggle](https://www.kaggle.com/datasets/mastmustu/income). You can use the `train.csv` function to auto detect metadata and attempt to visualize it.

```python
import pandas as pd
from sdv.metadata import SingleTableMetadata

real_data = pd.read_csv('train.csv')
real_data['income_>50K'] = real_data['income_>50K'].astype(str)

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(real_data)

metadata.visualize()
```

Output:
```
Error: bad label format 
...
CalledProcessError: '[PosixPath('dot'), '-Kdot', '-Tsvg']' returned non-zero exit status 1. ...
```

Full stack trace is attached below.
[stack_trace.txt](https://github.com/sdv-dev/SDV/files/12863158/stack_trace.txt)

**Comment by FlyingDutchman26** [comment]
I have the same problem!
