### ISSUE TITLE
TVAE synthesizer incorrectly generate 2 columns with strings rather than numerical values

### ISSUE THREAD

**Issue by alextopology** [sdv-dev/SDV#1630]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:1.5.0
* Python version:3.10.12
* Operating System:linux, ubuntu 22/04

### Error Description

<I am tryng to replicate a large numerical database (more then 10.000 if columns) with TVAE synthesizer, and during sampling data 2 columns of the dataframe are generated with string data of this type:  'sdv-pii-6jwk1' with the last for charachters changing in different samples. I have to use the dataframe for a logistic regression that can only ptocess numerical data.

### Steps to reproduce

<i have only tried to generate different data, but any time the same 2 columns are created with string data. it is possible to have somme suggestions about this situation? my database is very large, and so i need >

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @alextopology, it would be helpful if you could share the code that you are using to load data, create metadata, and train the synthesizer. (You do not have to share your actual data.)

One idea: The issue might be in your metadata. To create synthetic data with high quality, **it is crucial that your metadata accuracy represents your data**. If a column is marked as "unknown", then the SDV is instructed to treat it as PII for security reasons. You may always visualize and update the metadata [following the Python API](https://docs.sdv.dev/sdv/single-table-data/data-preparation/single-table-metadata-api#update-api).

Let us know if you have any questions.

**Comment by alextopology** [comment]
from google.colab import files

# Mostra un pulsante per caricare il file Excel
uploaded = files.upload

data = pd.read_excel('feature_table_biopsy_AP.xlsx',index_col = 0)

from sdv.metadata import SingleTableMetadata
metadata = SingleTableMetadata()
metadata.validate--> i noticed that despite my columns being numerical, the metadata incorrectly signs categorical, but the 
                                    TVAE still created numerical data exept for those 2 columns
from sdv.single_table import TVAESynthesizer
synthesizer = TVAESynthesizer(metadata, enforce_min_max_values=True,enforce_rounding=True)
synthesizer.fit( data)
data = synthesizer.sample(num_rows = 13)

my dataset is 10.000 thousend columns long, i guess it could be quite messy to assign all those columns manually. moreover when i was on jupyter notebook the metadata hav been always detected exaclty, with all numerical columns, this problem is appearing know that i switched to google colab, for GPU purpose.

**Comment by alextopology** [comment]
You were right, those columns adapted as string were unkown in the
metadata, and i solved the issue. The other issue I have is that many
columns are signed as categorical despite being numerical, but the
synthesizer is correctly generating numerica data. How i can iterate the
code for update the metadata to numerica for those column? I guess it will
ve more than 1000.
Thanks for the support.

Il Lun 16 Ott 2023, 17:37 Neha Patki ***@***.***> ha scritto:

**Comment by npatki** [comment]
Hi @alextopology, I'm glad it worked out after you changed your metadata. If you have a working metadata, we strongly recommend **saving your metadata as a JSON file** so that you do not have to go through this process again.

```python
metadata.save_to_json(filename='my_metadata_filename.json')

# in the future, you can reload the metadata from json
metadata = SingleTableMetadata.load_from_json(filename='my_metadata_filename.json')
```

> columns are signed as categorical despite being numerical, but the
synthesizer is correctly generating numerica data

Could you explain more what this means? Just because a column is stored as an int/float does not necessarily mean the sdtype is numerical. It is possible to have int/float for a categorical column -- for eg. if the categories represent discrete concepts such as HTTP access codes (`404`, `200`, etc.). [This blog article](https://datacebo.com/blog/categorical-data/) provides a good overview of the concepts of "categorical" and "numerical".

**Comment by npatki** [comment]
> How it is possible for the column to be categorical if I have only numerica
data?

I would definitely recommend reading the blog article, as it answers this exact question. The concept of an sdtype (categorical, numerical, etc.) is different than the underlying data representation (int, float, string, etc.).

Definitely give the article a read, especially the section titled **Trap 2: Assuming numbers cannot be categorical**. Let me know if you have any questions. Pasting the article below again, for your reference:

https://datacebo.com/blog/categorical-data/

**Comment by alextopology** [comment]
Certainly i am going to read this, thanks for the support rally, and sorry
for all my requisiti, but I would like to ask another quick thing: i want
to synthesize data that are higher than the maximum value, but not lower
than zero, so when I set min_max_values, it goes below zero, so i thought
that i could use the constraint to mamtain positive the columns, the
problem is that i do not know how to adapt the code to make all my columns
(10.000) higher than zero, is there a chance that this could be possible?
Again, sorry for all those request, but my work of thesis is based on this,
and so i want to be sure to make the best work possible.
Thanks again

Il Mar 17 Ott 2023, 20:35 Neha Patki ***@***.***> ha scritto:

**Comment by npatki** [comment]
Hi @alextopology this question doesn't seem as related to the original problem. I can answer here but if it requires a broader discussion, perhaps it would be best to separate each theme/topic into a separate issue.

> i do not know how to adapt the code to make all my columns (10.000) higher than zero

Your approach seems correct. You'd have to do this by applying a separate constraint for each column. I'm not sure how your columns are named. I would use a for-loop to:
1. Iterate through all the column names
2. Create a dictionary for each constraint
3. At the end of the for-loop, add the list of constraints to your synthesizer

**Comment by npatki** [comment]
Hello, I'm closing this issue since it has been inactive for a few weeks. (I believe we solved the original problem by updating the metadata to be an accurate reflection of the data.)

If you have any other questions, bugs, or feature requests, please feel free to file a new issue for the new topic, and we'd be happy to discuss.
