### ISSUE TITLE
Add options to read CSV files

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1644]
### Problem Description
In older versions of SDV, it was possible to read a single CSV at a time and pass in extra parameters used to parse out the CSV. For example, perhaps the file was separated by tabs or pipes instead of commas.

Now, we have a method for reading a batch of CSVs at a time (every CSV within a particular folder):

```python
from sdv.datasets.local import load_csvs

datasets = load_csvs(folder_name='my_folder')
```

But I cannot pass in extra args for loading.

### Expected behavior
I expect that I should be able to add keyword args for reading the CSVs. We should accept a dictionary of args to be used by [pands.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

```python
from sdv.datasets.local import load_csvs

datasets = load_csvs(
    folder_name='my_folder/',
    read_csv_parameters={
        'sep': '\t', # separators are tabs instead of commas
        'skipinitialspace': True # skip spaces that are at the start of each value
    })
```

Note that this was the intended usage of the singular `load_csv` back when we supported this method.

### Additional context
All CSVs in the folder will be read in with the same arguments as `read_csv_parameters`. If users wish to use different parameters per CSV, then they could directly use the `pandas.read_csv` function.

**Comment by amontanez24** [comment]
@npatki One thing about this issue is that the parameters for [pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) are designed to read a single csv. When passing to a function like `load_csvs` that is meant for multiple, it isn't a direct 1-1 mapping because some of the parameters are things like `use_cols` which can take a list of column names to load. Those wouldn't make sense from a multi-table perspective

**Comment by npatki** [comment]
@amontanez24 it makes sense why you can't readily use those parameters. Ideally you'd use this for parameters that apply to every CSV file such as `sep` or `skipinitialspace`

Have we tested to see what happens if you use a data-specific parameter such as `use_cols`? Does the entire thing crash or does it simply skip over these instructions for the non-applicable CSVs?
