### ISSUE TITLE
Customized data

### ISSUE THREAD

**Issue by ZhuTouG** [sdv-dev/SDV#1659]
### Problem description
Hi, if I have 10 features of x1/x2/x3 etc, is it possible to customize x1 & x2 and then use CTGAN to fill in the remaining attributes?

**Comment by npatki** [comment]
Hi @ZhuTouG, nice to meet you.

Unfortunately, I am not able to understand the project fully. Asking some clarifying questions below. Perhaps if you are able to illustrate your problem with some data or examples, that would be helpful.

> if I have 10 features of x1/x2/x3 etc

Just wanted to confirm that each "feature" you are mentioning is a different column of a data table? So basically, each column is named x1, x2, x3, ... all the way to x10 for 10 features?

> is it possible to customize x1 & x2

What does it mean to "customize" a column? 

### Resources
The SDV is designed to input tabular data (rows and columns) and learn patterns. The synthetic data it produces will be in the same format -- i.e. it will have the same column names -- and data patterns. You can request any number of rows to be produced.

You will need to train an SDV synthesizer on a data table of full data. Afterwards, you can sample all the columns, or a subset of columns based on known values.

- [Demos](https://docs.sdv.dev/sdv/demos)
- [Sampling realistic data](https://docs.sdv.dev/sdv/single-table-data/sampling/sample-realistic-data) (all columns)
- [Conditional sampling](https://docs.sdv.dev/sdv/single-table-data/sampling/conditional-sampling) (a subset of columns)
