### ISSUE TITLE
Learning incorrect relationships for table columns (Country, City)

### ISSUE THREAD

**Issue by JagdishKolhe** [sdv-dev/SDV#166]
* SDV version: 0.3.4
* Python version: 3.6
* Operating System: Google Colab / Linux

### Description

Data generation for two (logically) related columns, is not working properly.

### What I Did

1) Trained SDV for the table with two columns (Country, City)
2) generated data using sample_all(10) method, this resulted in incorrect city/country combination. For eg. "New York" was generated for "France"

Any idea  why it happening so? Ideally SDV should learn the relationship between columns, isn't it?

**Comment by csala** [comment]
Hi @JagdishKolhe thanks for reporting this.

This can now be enforced by using [Constraints](https://sdv.dev/SDV/user_guides/single_table/constraints.html).
Also, the [GaussianCopula Model](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html) that was introduced a couple of releases ago should be able to capture this on its own when using OneHotEncoding transformation, so I'm closing this issue for now.
