### ISSUE TITLE
Sdtype Categorical generates NULL values 

### ISSUE THREAD

**Issue by dfosticupgrade** [sdv-dev/SDV#1689]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.6.0
* Python version: 3.9.6
* Operating System: macOS Ventura 13.6.1

### Error Description

Categorical Sdtype will generate null values

### Steps to reproduce
multi-table scenario

my metadata 
```
                "type": {
                    "sdtype": "categorical"
                },
```
i have 2 values: PUBLIC and PRIVATE
it is learning from a column with 980 records, none of the records has this value null (not null column).
my scale is 2.0
when i generate data it will produce 2 records with type NULL value
strange enough it is always record 886 & 887

i used exactly same script with same DB before, but with less records in the table, and did not run into this isse

**Comment by npatki** [comment]
Hi @dfosticupgrade, thanks for filing this issue. Would you be able to provide just a few more details about where this is happening to help us replicate this?

1. What is the full metadata? I'm curious whether this particular column is located in the parent table or a child table
2. Is it possible to share data/CSV files that would allow us to replicate?

### Checking Versions
A month ago, we noticed that a bug in our pre/post-processing library (RDT) was causing null values to appear on rare occasions. You can view the issue [here](https://github.com/sdv-dev/RDT/issues/719).

It was resolved in RDT v1.8.0 so one thing to sanity check would be the version of this library (it comes pre-installed with SDV).

```python
import rdt
print(rdt.__version__)
```
We expect 1.8.0 or higher.

**Comment by dfosticupgrade** [comment]
hi @npatki 
rdt version: 1.8.0
it is 2 level inheritance (i know HMASynthesizer is recommended for 1 level),
`table_a` parent for `table_b` parent for `table_c`, we are talking about parent_b int this model

**Comment by npatki** [comment]
I'm closing this issue off in favor of #1691, which we'll use to track the fix to the issue.
