### ISSUE TITLE
Adding constrains to PARSynthesizer 

### ISSUE THREAD

**Issue by Ng-ms** [sdv-dev/SDV#1690]
### Problem Description

<Replace this with a description of the problem that you think SDV should be able to solve and is not solving already>

### Expected behavior

<Replace this a clear and concise description of what you would expect SDV with regards with the described problem. If possible, explain how you would like to interact with SDV and what the outcome of this interaction would be.>

### Additional context

<Please provide any additional context that may be relevant to the issue here. If none, please remove this section.>

**Comment by npatki** [comment]
Hi @Ng-ms, looks like we already have a feature request for this in #570 so I'm going to mark this one as a duplicate.

It would be helpful if you could add a commend to #570 describing your particular project and use case. Are there any predefined constraints that your project needs? Which one(s)? What about custom constraints?
