### ISSUE TITLE
`InvalidDataError` for `Inequality` constraint (even though data is valid)

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1692]
### Environment Details

* SDV version: 1.7.0
* Python version: 3.10
* Operating System: Linux (Colab Notebook)

### Error Description
There are certain datetime formats that create an error every time I try to add an `Inequality` constraint. The synthesizer keeps telling me that the constraint is not valid, even though I can verify that it is valid for every single row.

### Steps to reproduce
```python
import pandas as pd

from sdv.metadata import SingleTableMetadata
from sdv.single_table import GaussianCopulaSynthesizer

data = pd.DataFrame(data={
    'low_col': ['21 Sep, 15', '23 Aug, 14', '29 May, 12'],
    'high_col': ['02 Nov, 15', '12 Oct, 14', '08 Jul, 12']
})

metadata = SingleTableMetadata.load_from_dict({
    'columns': {
        'low_col': { 'sdtype': 'datetime', 'datetime_format': '%d %b, %y' },
        'high_col': { 'sdtype': 'datetime', 'datetime_format': '%d %b, %y' }
    }
})

metadata.validate()
metadata.validate_data(data)

my_constraint = {
    "constraint_class":"Inequality",
    "constraint_parameters":{
        "low_column_name":"low_col",
        "high_column_name":"high_col",
        "strict_boundaries":False
    }
}

synth = GaussianCopulaSynthesizer(metadata)
synth.add_constraints([my_constraint])
synth.fit(data)
```

Output:
```
InvalidDataError: The provided data does not match the metadata:

Data is not valid for the 'Inequality' constraint:
      low_col    high_col
0  21 Sep, 15  02 Nov, 15
1  23 Aug, 14  12 Oct, 14
2  29 May, 12  08 Jul, 12
```

Note that everything being printed out is actually valid. (Each day in the `low_col` happens earlier than the day in the `high_col`). 

### Additional Context
This seems to happen when the datetime format string includes a `%y`, meaning the last 2 digits of a year (such as 02 for 2002 or 23 for 2023). According to [this reference](https://docs.python.org/3/library/time.html), Python's time module is supposed to interpret `%y` in the following way:
- Values 69–99 are mapped to 1969–1999
- Values 0–68 are mapped to 2000–2068

So there is nothing about the example code above that should be causing an issue. Since all year values are <69, the years should always be interpreted as part of the 2000s.

_[Edit] Upon further investigation, it appears that in the example above, the strings are being compared alpha-numerically. They do not seem to be converted to datetime._

Note that the issue goes away if you update the datetime format to `%Y`, meaning that you use all 4 digits of the year (2002 and 2023).

**Comment by npatki** [comment]
Additional context: Ideally the `Inequality` constraint should be able to access the metadata so it can figure out 
(a) what the column's sdtype is (eg. datetime or numerical) and
(b) if it's a datetime, what the user-provided `datetime_format` is 

Currently, we are estimating the above 2 items. And there are certain cases/formats where it is not possible for us to guess this. It is necessary to look at the metadata as the ground truth.

**Comment by amontanez24** [comment]
As a solution we may just need to pass the metadata to constraint instances. During their initialization, each constraint can store the information it needs (eg. datetime formats)

**Comment by vijayashree-kr** [comment]
Hello. I'm encountering same issue, even when the datetime is time zone unaware. Please suggest possible workaround:
**Dtypes of the data:**
number int64
date datetime64[ns]
checkin_utc datetime64[ns]
checkin_local datetime64[ns]
checkout_utc datetime64[ns]
checkout_local datetime64[ns]

**Error**:
InvalidDataError: The provided data does not match the metadata:

Both high and low must be datetime.

Both high and low must be datetime.

**Comment by npatki** [comment]
Hi @vijayashree-kr, could you please [file a new issue](https://github.com/sdv-dev/SDV/issues/new/choose) with what you're observing? It's not clear to me if this is immediately related to this current problem. Thanks.

FYI In order to replicate your problem, it will also be helpful if you could include more information in the new issue that you file:
- Your metadata dictionary
- The code you are using to create a synthesizer, add constraints etc.
- The full stack trace (everything printed out when you see the Error)
