### ISSUE TITLE
Why FastML works differently when run locally than when run in streamlit app hosted online? 

### ISSUE THREAD

**Issue by joshmwolff** [sdv-dev/SDV#1715]
When I run the following lines of code locally on my computer, I get expected synthetic data, even for PII fields. However, when I run online via a streamlit app, I get masked synethetic PII: sdv-pii-2df67. Why is that? I'm using the same SDV version in each case. 

`metadata = SingleTableMetadata();
 metadata.detect_from_dataframe(data=input_data);
 synthesizer = SingleTablePreset(metadata=metadata,name='FAST_ML');
 synthesizer.fit(data=input_data);
 synthetic_data = synthesizer.sample(num_rows=len(input_data))`

**Comment by npatki** [comment]
Hi @joshmwolff, nice to meet you. Is it possible that the SDV version is different on your local computer vs. streamlit? You can check with the following code:

```python
import sdv
print(sdv.__version__)
```

The latest version is **1.8.0**.

Please note that **auto-detecting metadata is not guaranteed to be accurate or complete**. After auto-detecting, I would encourage you to inspect the metadata and update any columns that are incorrectly specified. We also recommend **saving the metadata as a separate file** to prevent issues with auto-detection.

More information:
- [Metadata API](https://docs.sdv.dev/sdv/single-table-data/data-preparation/single-table-metadata-api)
- [Metadata Demo](https://colab.research.google.com/drive/1DlUlHNohxBhxN6GA5C_C4Fd9wx5AR11Y?usp=sharing)

**Comment by joshmwolff** [comment]
Well I feel silly. That was exactly the issue. Thanks for the super quick response and solution - I really appreciate it.

**Comment by npatki** [comment]
No silly Qs :) glad it was resolved!
