### ISSUE TITLE
Visualizations (get_column_plot() and get_visualization()) not showing — 404 Not Found

### ISSUE THREAD

**Issue by joanalza** [sdv-dev/SDV#1719]
SDV problem (bug)

Visualizations (get_column_plot() and get_visualization()) not showing — 404 Not Found

### Environment Details

* SDV version: 1.8.0
* Python version: 3.9
* Operating System: iOS Sonoma 14.1.2

### Error Description

I was using SDV version 1.5.0 to visualize the evaluation of the synthetic data generation models - Gaussian Copula in my case. Unfortunately, when upgraded to 1.8.0, apart from changing some property names ('Coverage' to 'Data Structure' in the Diagnostic report, for example), the visualization functions are not working, returning "404 Not Found" (image below). I can guarantee that the quality and diagnostic reports collect all the information properly, such as Column Shapes and Column Pair Trends.

### Steps to reproduce

```
quality_report.get_visualization('Column Pair Trends') # 'Column Shapes', 'Column Pair Trends'

diagnostic_report.get_visualization('Data Validity') # 'Data Validity', 'Data Structure'

get_column_plot(real_data=original_data,
                              synthetic_data=synthetic_data,
                              column_name="column",
                              metadata=metadata)
```
<img width="924" alt="Screenshot 2023-12-15 at 10 52 07" src="https://github.com/sdv-dev/SDV/assets/22146506/326cd954-cbfe-4612-b27b-729ac72d7e7c">

**Comment by npatki** [comment]
Hi @joanalza, I'm a bit confused. 404 error indicates to me that you are using a web service with a server that has hosted SDV. Has you or your team built one?

Could you explain how you are running SDV?

**Comment by joanalza** [comment]
Hi @npatki, thanks for the quick reply. 

I am using PyCharm 2023.3.1 and Jupyter Notebook to load the original data and generate synthetic data. As said in the first message, outputs were showing properly on SDV 1.5.0 version, but now showing any more for SDV 1.8.0

**Comment by npatki** [comment]
Is your Jupyter server printing out any info (error messages, etc.) when the 404 is appearing on your webpage? And is the 404 happening for _all_ of the commands you have listed (`get_visualization` for all the properties as well as `get_column_plot`)?

We use the `plotly` library for visualizations. In recent SDV versions, we updated the rendering settings for `plotly` so I'm wondering whether that's causing the issue. I'm curious what is printed out when you run the following:

```python
import plotly.io as pio
print(pio.renderers.default)
```

The default should be set to `'iframe'`

**Comment by arielfaur** [comment]
I'm experiencing the same issue in a Jupyer notebook with SDV 1.8 and Python 3.9.13 running in a conda environment

<img width="1160" alt="Screenshot 2023-12-28 at 18 54 39" src="https://github.com/sdv-dev/SDV/assets/3749268/518258b0-719b-4b4f-b84b-0d3c7f053512">

**Comment by npatki** [comment]
Hi @arielfaur, thanks for sharing. Were you able to run the above code to see what is printed out?

```python
import plotly.io as pio
print(pio.renderers.default)
```

### Possible Workaround
One other thing to try would be from [Plotly's docs](https://plotly.com/python/troubleshooting/#:~:text=The%20classic%20Jupyter%20Notebook%20(i.e.,%22)%20instead%20of%20just%20fig.). 

```python
fig = get_column_plot(...)
fig.show('notebook')
```

The docs seem to indicate that the following code could be used instead of including the `'notebook'` parameter inside each call:
```
import plotly.io as pio
pio.renderers.default='notebook'
```

Do let me know if that works, as I'm not quite able to replicate this one.

**Comment by arielfaur** [comment]
@npatki The output seems to be `vscode` by default. However, I confirm it works fine with the workaround (adding the `notebook` parameter).

![Screenshot 2024-01-03 at 22 13 50](https://github.com/sdv-dev/SDV/assets/3749268/8b20df60-0208-46a6-b786-87f56af111bb)

**Comment by joanalza** [comment]
@npatki In my case, the rendering output from Plotly,  `print(pio.renderers.default)`, returns the default `iframe` mentioned above. However, even setting the rendering to `'notebook'`, I do not obtain the expected visualisations for either `get_visualization()` or `get_column_plot()`.

<img width="859" alt="Screenshot 2024-01-09 at 12 35 54" src="https://github.com/sdv-dev/SDV/assets/22146506/42bc28da-163d-44fc-bfd2-08d5665ec82d">



Here are some screenshots:

> get_visualization()

<img width="859" alt="Screenshot 2024-01-09 at 12 26 47" src="https://github.com/sdv-dev/SDV/assets/22146506/8b294590-2d33-43bb-85e1-cd10ffe95cb7">
<img width="859" alt="Screenshot 2024-01-09 at 12 26 35" src="https://github.com/sdv-dev/SDV/assets/22146506/62815e6a-4919-42b3-8325-501f182f810a">


> get_column_plot()

<img width="859" alt="Screenshot 2024-01-09 at 12 33 14" src="https://github.com/sdv-dev/SDV/assets/22146506/5948e2d2-c5b6-46e2-b668-a0760bb54e35">
<img width="859" alt="Screenshot 2024-01-09 at 12 33 30" src="https://github.com/sdv-dev/SDV/assets/22146506/e4505c7b-68c3-4acd-a9cc-08a8e165158b">

**Comment by npatki** [comment]
Hi @joanalza, we do seem to have a separate issue in #1734 that may be related. Both are tricky for us to replicate so I'm going to leave the same reply here to see if it helps us debug.

### Is the issue with plotly?
Try creating a brand new Python environment and only pip installing plotly only (not SDV). Then you can try using the scatter plot function from directly within plotly to see if it works.

From [plotly's demo docs](https://plotly.com/python/line-and-scatter/)

```python
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species",
                 size='petal_length', hover_data=['petal_width'])
fig.show()
```

If this is breaking in your environment, then the issue is within the plotly library, so may be good to search through their GitHub / docs.

Do let me know what your findings are. We'll be sure to update if we find a way to replicate this or have any other learnings.

**Comment by npatki** [comment]
Hi @joanalza, are you still encountering this problem? Please do let us know if you are able to run the code above to help us pinpoint the issue, as it's been a tricky one.

We're very interested in discovering any root causes so that we may natively fix this in SDV for you and other users. Thanks.

**Comment by joanalza** [comment]
Hi @npatki, sorry for the late reply. 
After some tests with the solutions given above, I have realised that plotly is working fine until running the visualisations from SDV Evaluation (e.g. get_column_plot()). As stated previously, it must be a problem related to the rendering system used, although I might be wrong.

**Comment by makoffka** [comment]
Hi @npatki , I am running some SDV models on my Mac using VS code and jupyter nb and also get an empty screen, when trying to create plots. I have tried 

import plotly.io as pio
pio.renderers.default='notebook'

(and several other options, but was not able to make it create the plots within the notebook (It creates the plots and saves them to a separate folder.) the same code plots everything well in  Colab)

<img width="614" alt="Screenshot 2024-02-14 at 4 03 07 PM" src="https://github.com/sdv-dev/SDV/assets/120622715/d2d8f6c7-a3ce-4e0d-93f8-944185b8be1b">

**Comment by MykhailoYampolskyi** [comment]
This has worked for me:
 "force the notebook renderer to reload by calling fig.show("notebook") instead of just fig.show() ."
[Source](https://plotly.com/python/troubleshooting/)

**Comment by srinify** [comment]
Hey y'all, I wanted to close the loop on the discussion here with (hopefully) a satisfying solution.  

The issues being discussed here in this thread is linked to how Plotly is rendering charts. In most cases, explicitly asking Plotly to use a different renderer will solve your issue. You can read more about how Plotly thinks about renderers here: https://plotly.com/python/renderers/

As @MykhailoYampolskyi showcased, changing the renderer passed into `fig.show()` often will work. In this related issue, I showcase how `fig.show('vscode')` combined with the relevant VSCode extension (linked in the issue) will fix the rendering issues in VSCode: https://github.com/sdv-dev/SDV/issues/1734#issuecomment-2027740751
