### ISSUE TITLE
Unable to fit new data

### ISSUE THREAD

**Issue by kvrameshreddy** [sdv-dev/SDV#172]
* SDV version:v0.3.5 - 2020-07-09
* Python version:3.7
* Operating System:windows 8.1

### Description
After creating metadata from csv file unable to fit into model

### What I Did

![sdv issue](https://user-images.githubusercontent.com/49742709/88298864-50b5e680-cd1f-11ea-9097-b4080c4d71cb.JPG)

**Comment by kvrameshreddy** [comment]
how to solve this issue

![sdv_issuse](https://user-images.githubusercontent.com/49742709/88299092-97a3dc00-cd1f-11ea-9904-2d97cc7e0ea1.JPG)

**Comment by csala** [comment]
Hello @kvrameshreddy 

I think that the problem is that you are passing a custom `metadata` object but you are still passing also the `tables` variable that you obtained from the `load_demo` call.

Since your `metadata` already have all the information to load the CSV files, you can simply omit the `tables` variable when calling fit:

```
from sdv import Metadata, SDV

sdv = SDV()
sdv.fit(metadata)
```

**Comment by kvrameshreddy** [comment]
thank you for the solution. Now i am getting this error "ValueError: There are nan values in your data.". but my data has no 'nan' values
![nan_issue](https://user-images.githubusercontent.com/49742709/88368893-8d7bef00-cdac-11ea-910c-bbef5fb229f5.JPG)

**Comment by csala** [comment]
It's hard to tell without having a look at the data. Would it be possible for you to post here the two CSV files and the Metadata that you are using?

Note that if you built the Metadata on the fly from Python, you can save it as a JSON file using `metadata.to_json('metadata.json')`

**Comment by kvrameshreddy** [comment]
Hi @csala 
please have a look at the data and help in solving the issue.
[data.zip](https://github.com/sdv-dev/SDV/files/4987968/data.zip)

**Comment by kvrameshreddy** [comment]
Hi @csala, In the above issue nan's are appearing while calculating covariance internally. please check it once. Thank you.

**Comment by csala** [comment]
I was able to run HMA1 without issues on the attached data, so this can be closed for now.

Here's an esample notebook: https://colab.research.google.com/drive/1uESuO3FV1HwgYFxSzAaBH4z2Q-b_83tC#scrollTo=8DdQ6iIFrGcf
