### ISSUE TITLE
Mixed data type in synthetic   data 

### ISSUE THREAD

**Issue by Ng-ms** [sdv-dev/SDV#1787]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.19
* Python version: 3.8.10
* Operating System: Linux

I am getting a mixed data type in some of the columns even though I can see in the metadata the data type is correct; for example, I have numerical data, and when I generate the synths data, I am getting in the same column numerical and datetime at the same time, what could be the reason for that and how to fix it? 

this image from the original data, you can see that there are only numerical data 

![Screenshot from 2024-02-06 09-46-00](https://github.com/sdv-dev/SDV/assets/17408097/1f45cf77-c3e5-4fd3-bf31-c21ae3ee2722)
 here, form the synthetic data i there is dates in the columns that is supposed to be just numerical, and it is identity in the metadata as  numerical , this issue appears in multiple columns not just this one 
![image](https://github.com/sdv-dev/SDV/assets/17408097/6ff3640f-ff12-4e04-8836-e03eb403011b)

**Comment by Ng-ms** [comment]
i was not able to delete the issue , it was just a problem in saving the data without a sep

**Comment by npatki** [comment]
Great -- thanks for checking in. I will just mark the issue as closed then! Good to have a record of such issues in case other users run into the same problem.
