### ISSUE TITLE
Unable to load a saved model

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1789]
_I'm filing this issue on behalf of a Slack user._

### Error Description
I am using PARsynthizer to generete synth timeseries data, after traing the model sucefully i would like to use the pkl model to generte more data but it keep giving me this error eventhoug i am using the same code in the website

```python
synthesizer = PARSynthesizer.load('my_synthesizer.pkl')
```
```
    model = cloudpickle.load(f)
TypeError: __randomstate_ctor() takes from 0 to 1 positional arguments but 2 were given
```

This is the code
```python
from sdv.sequential import PARSynthesizer
synthesizer = PARSynthesizer.load('my_synthesizer.pkl')
synthesizer.fit(df)
synthetic_data = synthesizer.sample(num_rows=100)
print(synthetic_data)
```

**Comment by AryanSaeedi** [comment]
Hi, I think the issue is as a result of the recent upgrade. I have two virtual environments with two different versions of the SDV, and the one with the latest runs into this problem while the previous one doesn't.

**Comment by srinify** [comment]
Hey @AryanSaeedi I work with @npatki and was able to replicate this. It looks like PARSynthesizer model pkl's generated using sdv 1.8 and 1.9 don't work in sdv 1.10.

**Comment by srinify** [comment]
We're investigating potential solutions to this. For people running into this issue that are blocked you can either:

- Stick with SDV 1.8 or 1.9 and not upgrade to SDV 1.10
- Or you can upgrade to 1.10, re-run the PARSynthesizer and re-train the model, and then be fine moving forward

As it stands right now, there isn't a way to use PARSynthesizer pkl files created from SDV 1.8 or 1.9 in SDV 1.10.

**Comment by npatki** [comment]
Hi all,

Unfortunately it doesn't look like we'll be able to resolve this one for older synthesizers created and saved before SDV 1.10. The root cause is that we added functionality in SDV 1.10 that allows for improved modeling and data quality of the `sequence_index`. As the older synthesizers did not have this feature, they are crashing on SDV 1.10+ when it tries to use the feature.

For now, we'd recommend upgrading to 1.11 or higher and re-training your data. Going forward, we'll keep this backwards compatibility in mind. Apologies for the extra hassle!
