### ISSUE TITLE
CTGAN add custom constraints error [single table, multi columns]

### ISSUE THREAD

**Issue by WSpie** [sdv-dev/SDV#1797]
Hi, I'm using SDV ver 1.10.0 with Python 3.8.8, and I'm trying single table with CTGAN

In .py file for customized logic
```
from sdv.constraints import create_custom_constraint_class
import numpy as np
import pandas as pd

def is_valid_ieq(column_names, data):
    try:
        # Assuming column_names[0] = 'cumu_rain', column_names[1] = 'peak_int', column_names[2] = 'duration'
        # Check if peak_int >= cumu_rain / duration for each row
        validity = data[column_names[1]] >= (data[column_names[0]] / (data[column_names[2]] + 1e-6))
        return pd.Series(validity)
    except Exception as e:
        print(f"Error in is_valid_ieq: {e}")
        raise

def transform_fn_ieq(column_names, data):
    try:
        # Modify peak_int to ensure it's >= cumu_rain / duration
        transformed_data = data.copy()
        transformed_data['ieq'] = data[column_names[0]] / (data[column_names[-1]] + 1e-6)
        transformed_data[column_names[1]] = transformed_data[[column_names[1], 'ieq']].max(axis=1)
        data[column_names[1]] = transformed_data[column_names[1]]
        return data
    except Exception as e:
        print(f"Error in transform_fn_ieq: {e}")
        raise

def reverse_transform_ieq(column_names, transformed_data):
    return transformed_data.copy()

PeakIntConstraintClass = create_custom_constraint_class(
    is_valid_fn = is_valid_ieq,
    transform_fn = transform_fn_ieq,
    reverse_transform_fn = reverse_transform_ieq
)
```
Constraints
```
peak_int_constraints = {
    'constraint_class': 'PeakIntConstraintClass',
    'constraint_parameters': {
        'column_names': ['cumu_rain', 'peak_int', 'duration']
    }
}
```
Main program
```
ctgan_synthesizer.load_custom_constraint_classes(
    filepath = '../models/cCTGAN.py',
    class_names = ['PeakIntConstraintClass']
)
ctgan_synthesizer.add_constraints(
    [x_bounds_constraints, y_bounds_constraints, inequalty_constraints, positive_constraints]
+ [peak_int_constraints]
)
```
Here's my log
```
2024-02-19 21:58:06 - INFO - Start training...
2024-02-19 21:58:11 - INFO - Fitting table None metadata
2024-02-19 21:58:11 - INFO - Fitting formatters for table None
2024-02-19 21:58:11 - INFO - Fitting constraints for table None
2024-02-19 21:58:25 - INFO - Unable to transform CustomConstraint with columns ['cumu_rain', 'peak_int', 'duration'] due to an error in transform: 
'cumu_rain'
Using the reject sampling approach instead.
2024-02-19 21:58:25 - INFO - Setting the configuration for the ``HyperTransformer`` for table None
2024-02-19 21:58:39 - INFO - Unable to transform CustomConstraint with columns ['cumu_rain', 'peak_int', 'duration'] due to an error in transform: 
'cumu_rain'
Using the reject sampling approach instead.
2024-02-19 21:58:39 - INFO - Fitting HyperTransformer for table None
```
Can you check my transform_fn_ieq function, I'm trying to add make an inequality using three columns, thank you!

**Comment by WSpie** [comment]
Finally I figured the problem, my code was nothing wrong, just the order of the constraints mattered! The built-in constraints will modify the column names based on different types of constraints: 0.0#x#1.0: scalar range [0, 1], y#diff: positive constraint, y#z: inequality constraint to set y<z. If our customized constraints listed behind those built-in constrints,  `column_names` will never work properly. If we put it in the first order, it is fine. I really appreciate this package but lease add more intuitive guidance about constraints customization to this [doc](https://docs.sdv.dev/sdv/single-table-data/modeling/customizations/constraints) to help more developers and learners. Many thanks!!!

**Comment by WSpie** [comment]
Here my log using the same custom constraints code but changing the order.
```
2024-02-19 22:38:55 - INFO - Start training...
2024-02-19 22:39:00 - INFO - Fitting table None metadata
2024-02-19 22:39:00 - INFO - Fitting formatters for table None
2024-02-19 22:39:00 - INFO - Fitting constraints for table None
2024-02-19 22:39:14 - INFO - Setting the configuration for the ``HyperTransformer`` for table None
2024-02-19 22:39:28 - INFO - Fitting HyperTransformer for table None
```
BTW, please add some explanation for table `None` for single table data, I thought there is something wrong with my code and tried to debug for a week, however, nothing wrong for single table. Many thanks.

**Comment by npatki** [comment]
Hi @WSpie glad to see that you were able to find an acceptable solution to this.

Do note that `INFO` message are just meant for info -- it is not necessarily indicative of an error or anything going wrong. In the case of multiple overlapping constraints (overlapping on the same columns), it may be inevitable that SDV would need to switch strategies to get all constraints to work. Tinkering with the order may help in some cases but not all. So it is not a big concern if you see in the message. 

Does that make sense? Or was there actually a crash (Error) that you were observing before?

As a next steps, we can certainly file issues to:

1. Give you more clarity on how constraints work, and how multiple, overlapping constraints may affect SDV
2. Get rid of table `None` for single table INFO logs -- I think this is a remnant of multi-table, where each table has a name.
