### ISSUE TITLE
Allow the `detect_from_csv(s)` functions to accept additional read parameters

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1799]
_I'm filing this issue on behalf of a Slack user._

### Problem Description
My CSVs may require special parameters to read them into Python. For example, they may have a different character set encoding, delimiters, etc.

When this happens, I'm able to load my CSVs into Python using the `read_csv_parameters` option. Eg:

```python
my_dataset = load_csvs(
  folder_name='/data',
  read_csv_parameters={
    'encoding': 'latin-1'
  }
)
```

It would be nice if the detection methods also contained these options.

### Expected behavior
The functions `MultiTableMetadata.detect_from_csvs` and `SingleTableMetadata.detect_from_csv` should have a `read_csv_parameters` parameter that works the same way as it does for `load_csvs`.

### Workaround
Currently, if you require extra parameters, it is recommended you load them into Python first and then detect from DataFrames instead.

```python
my_dataset = load_csvs(
  folder_name='/data',
  read_csv_parameters={
    'encoding': 'latin-1'
  }
)

metadata.detect_from_dataframes(data=my_dataset)

```

**Comment by lajohn4747** [comment]
I believe this was fixed in SDV 1.6.0 in this task:
https://github.com/sdv-dev/SDV/pull/1649/files

`detect_from_csv` was given an extra argument to ingest read_csv_parameters.
