### ISSUE TITLE
Generating time series data 

### ISSUE THREAD

**Issue by andrewcztrack** [sdv-dev/SDV#181]
Hi @csala !! love the package!!!
so cool!
I was wondering when time series generation will be added many thanks and best,
Andrew

**Comment by andrewcztrack** [comment]
@ludovicc @Aylr @kveerama @k15z

**Comment by csala** [comment]
Hi @andrewcztrack time series data generation is being worked on and will be added to SDV sometime soon, but I'm afraid it would be very hard to set a reliable timeline.

Stay tuned for more news!
