### ISSUE TITLE
Show an error if I accidentally load an SDV synthesizer on an older version of SDV

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1837]
### Problem Description
Consider the following scenario:

1. I have been trying SDV for many months. I have multiple environments running with different SDV versions
2. I train and save a synthesizer on the latest SDV version (1.10.0)
3. Later, I accidentally re-load that synthesizer in an environment with an older version (eg. in my other environment with 1.9.0)
4. Some features don't work and error out. It is difficult to debug why this is happening.

Note that in this case, it is _expected_ that some features may error, as SDV does not offer forwards compatibility. That is to say, if you downgrade your SDV version (in step 3), there is no guarantee that anything will work.

### Expected behavior
Create a new `VersionError` type and show this if I try to load any synthesizer in this scenario.

```python
>>> synthesizer = HMASynthesizer.load('synthesizer.pkl')
VersionError: You are currently on SDV version 1.8.0 but this 
synthesizer was created on version 1.10.0. Downgrading your SDV version is not supported.
```

### Additional context
Apply this error to all synthesizers (available to public and enterprise)

Note that the trained version is available under `synthesizer.get_info()` (the enterprise version may not be -- perhaps we should add this)

**Comment by Ng-ms** [comment]
this error is happing again even without changing the version of the trained and loaded synthizers both are on sdv 1.9.0

**Comment by npatki** [comment]
Hi @Ng-ms that sounds like a bug. Could you file a new issue for it? Thanks.
