### ISSUE TITLE
Unmet patterns for HealthCare dataset

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1848]
_I'm filing this issue on behalf of @leeyuntien-milli. Original text is in issue #1755._

### Environment Details

* SDV version: 1.10.0

### Error Description
Fitting through the original datasets shows good results in terms of validity as well.

![image](https://github.com/sdv-dev/SDV/assets/3227804/36d8cd27-ef54-4746-b150-98ef042eb68b)

However we observe some issues which we hope can be resolved with some adjustments in package settings.
In `med` usually FromDate, ToDate, PayDate and ICD codes would vary for different claims with the same member or Member_ID, but seems not so in synthesized data.

![image](https://github.com/sdv-dev/SDV/assets/3227804/f4ae09cf-1d97-4286-abd5-01352e963af7)

In `pharm` usually FillDate and NDC codes would vary for different claims with the same member or Member_ID, but seems not so in synthesized data.

![image](https://github.com/sdv-dev/SDV/assets/3227804/499b1fea-4926-4b2a-9662-a610d9ca547e)

**Comment by npatki** [comment]
Hi @leeyuntien-milli, thanks for providing all the details. At this stage in the project, we'd need to think through the use case more specifically in order to adjust settings and add constraints.

### Features
Based on my (probably incomplete) understanding of your project, the following features may be helpful:
- **Constraints**: Add these if every single row of your data must adhere to some rule. For example, if FromDate < ToDate in all columns, then [Inequality Constraint](https://docs.sdv.dev/sdv/reference/constraint-logic/predefined-constraint-classes/inequality) can be used. For more info, [see constraint logic docs](https://docs.sdv.dev/sdv/reference/constraint-logic)
- **Adjusting parameters**: In theory, HMA _should_ be able to understand the fact that for each `mem` there are a variety of dates and ICD codes in `med`, as well as a variety of dates and NCD codes in `pharm`. Is it static for each member, or is it only for a few? Perhaps playing with the distributions may be helpful here. Alternatively, SDV Enterprise offers `HSASynthesizer` and `IndependentSynthesizer` that offers even greater control over this.

### Schema & Data Understanding
Other info about your schema structure may be helpful.

- It seems like `med` and `pharm` both reference claims (Claim ID) in some way. It seems to be as if claims are a 4th entity (in addition to mem, med, and pharm) that is missing from the schema. I wonder if adding it may help the model learn these nuances a bit better.
- When you mention that items like `ICD` and `NCD` codes must vary within a member ID, is this a hard requirement or a general trend? By that I mean: Should it _ever_ be possible that the codes/dates repeat (just not very likely)? Or is it a hard, business requirement that the values must be unique for 100% of members that exist? This has implications on whether ML alone would be able to understand it

**Comment by leeyuntien-milli** [comment]
Yes for each `mem` there would be a variety of dates and ICD codes in `med` because each member would have various medical records which can be thought of as visits to clinics. So to your questions,

- Codes or dates can repeat, but very unlikely, because one would seldom visit clinics within the same day and get exactly the same diagnoses. Normally visits would spread out to different dates with different diagnoses, but it can also be different visits having the same diagnoses.
- So in the `med` schema one row with different ICD codes means diagnoses for that visit, and several different rows with different ICD codes mean different ICD codes for different visits.
- How to add ClaimID to the metadata to help the models learn the sequences?

**Comment by npatki** [comment]
Hi @leeyuntien-milli, I appreciate the explanation. 

### Debugging Code
There seem to be a few columns in `med` and `pharm` tables that have repeating values for a given member/claim. To help debug this, I am providing a utility function below. For such columns, could you kindly run the function and return what it prints out?

**Utility Function**: This accepts as input the fitted HMA synthesizer, the table name (`'med'` or `'pharm'`), and the column name that is having issues.
```python
def print_params(synthesizer, table_name, column_name):
  if table_name not in ['pharm', 'med']:
    print('Error: Table name must be "pharm" or "med"')
    return

  prefix = '__' + table_name + '__Member ID__univariates__' + column_name + '__'
  table_synth = synthesizer._table_synthesizers['mem']._model


  for p in ['loc', 'scale', 'a', 'b']:
    try:
      i = table_synth.columns.index(prefix + p)
      d = table_synth.univariates[i]
      print(prefix + p, ':', d._params)
    except:
      print('Could not find', prefix+p)
``` 

Now you can use this function to inspect what the HMA model has learned. 
```python
>>> print_params(synthesizer, 'med', 'FromDate')
__med__Member ID__univariates__FromDate__loc : {'loc': 1.4818659430271567e+18, 'scale': 2.3913256972843012e+16, 'a': 1.2207969811417199, 'b': 0.7269658453684029}
...
```

_Please share this info with us._

### Follow Up Qs

>So in the med schema one row with different ICD codes means diagnoses for that visit, and several different rows with different ICD codes mean different ICD codes for different visits.

So it is possible to get a diagnosis for one visit (in one row) and then get the same diagnosis in a different visit (second row)? Or do they all have to be different?

> How to add ClaimID to the metadata to help the models learn the sequences?

Do you have a different table with Claim IDs? I imagine that the `med` and `pharm` table at least would reference a claims tables. Perhaps such a table should be added to the schema.

**Comment by npatki** [comment]
BTW the repeated values you are seeing (`med.FromDate`, and `med.ToDate`) -- are they always the min/max of the real data?

**Comment by leeyuntien-milli** [comment]
> ### Follow Up Qs
> > So in the med schema one row with different ICD codes means diagnoses for that visit, and several different rows with different ICD codes mean different ICD codes for different visits.
> 
> So it is possible to get a diagnosis for one visit (in one row) and then get the same diagnosis in a different visit (second row)? Or do they all have to be different?

They do not need to be different, but it is very rare the case to have exactly the same diagnoses for different visits.

> > How to add ClaimID to the metadata to help the models learn the sequences?
> 
> Do you have a different table with Claim IDs? I imagine that the `med` and `pharm` table at least would reference a claims tables. Perhaps such a table should be added to the schema.

No, there is no separate tables for Claim IDs. Should I split out a table for that?

**Comment by leeyuntien-milli** [comment]
`>>> print_params(synthesizer, 'pharm', 'FillDate')`
__pharm__Member_ID__univariates__FillDate__loc : {'loc': -5.366962929184692e+23, 'scale': 5.3669875154072357e+23, 'a': 14223.133368670891, 'b': 0.39772445673072}
__pharm__Member_ID__univariates__FillDate__scale : {'loc': 0.011052787501836324, 'scale': 7.923241896110015e+28, 'a': 0.08652122693739787, 'b': 8249.84738151103}
__pharm__Member_ID__univariates__FillDate__a : {'loc': 2.0901427541864465e-15, 'scale': 4101946834.2136154, 'a': 0.1227569362691876, 'b': 19715.937405065546}
__pharm__Member_ID__univariates__FillDate__b : {'loc': -5.184694576714565e-15, 'scale': 65538140346247.49, 'a': 0.07144550396781857, 'b': 49749.784542298425}
`>>> print_params(synthesizer, 'pharm', 'NDC')`
__pharm__Member_ID__univariates__NDC__loc : {'loc': -116590030.52118059, 'scale': 116590032.12945253, 'a': 8720.036479747334, 'b': 0.17811747337811107}
__pharm__Member_ID__univariates__NDC__scale : {'loc': -1.0635726042266599e-35, 'scale': 2478992779862.3447, 'a': 0.07708918035265691, 'b': 3836.6264084562827}
__pharm__Member_ID__univariates__NDC__a : {'loc': -4.5711910462983793e-10, 'scale': 226174026975.17682, 'a': 0.09038584812017172, 'b': 27704.707493669983}
__pharm__Member_ID__univariates__NDC__b : {'loc': -1.8733402038539413e-10, 'scale': 626294618266056.2, 'a': 0.0629470817192371, 'b': 41770.1485867201}

**Comment by leeyuntien-milli** [comment]
Just using these two representative features. Please advise if more are needed.
`>>> print_params(synthesizer, 'med', 'FromDate')`
__med__Member_ID__univariates__FromDate__loc : {'loc': -3.9901780765423695e+24, 'scale': 3.990180961433985e+24, 'a': 14055.08738203237, 'b': 0.2682624473122767}
__med__Member_ID__univariates__FromDate__scale : {'loc': 0.020816836623444687, 'scale': 3.6101263240664407e+28, 'a': 0.06343218036651307, 'b': 1239.5885204232468}
__med__Member_ID__univariates__FromDate__a : {'loc': 9.944822610765961e-17, 'scale': 2.457163730232998e+77, 'a': 0.007118614753080309, 'b': 2.9910318837210337}
__med__Member_ID__univariates__FromDate__b : {'loc': -5.787682456987545e-16, 'scale': 1.8175815819372616e+77, 'a': 0.0076712880334343534, 'b': 30081.20188854586}
`>>> print_params(synthesizer, 'med', 'ICDDiag01')`
__med__Member_ID__univariates__ICDDiag01__loc : {'loc': -120760733.0941288, 'scale': 120760734.51042971, 'a': 2356.3843977161996, 'b': 0.12749724444189975}
__med__Member_ID__univariates__ICDDiag01__scale : {'loc': 5.7575624759674796e-34, 'scale': 7301763479486.723, 'a': 0.06556912997389783, 'b': 13150.555808984232}
__med__Member_ID__univariates__ICDDiag01__a : {'loc': -3.69412507014686e-11, 'scale': 283456409990.78723, 'a': 0.07264818163004808, 'b': 13260.1150167064}
__med__Member_ID__univariates__ICDDiag01__b : {'loc': -1.2628615776934314e-13, 'scale': 614502154272871.0, 'a': 0.04766433347050786, 'b': 2762.5273156052363}

**Comment by npatki** [comment]
We've filed a new issue, #1895 to track this one, so I'm closing this off as a duplicate. Feel free to reply if you have any follow-ups and I can always re-open the issue to investigate.
