### ISSUE TITLE
Demo Meta Databases

### ISSUE THREAD

**Issue by zelmously** [sdv-dev/SDV#1851]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.8.0
* Python version: 3.9.18
* Operating System: Windows 11 Enterprise

### Problem description

I am trying to replicate the example at the link below.

https://colab.research.google.com/drive/1hGsL3N8_RGyvSIX9CreWzHeRRtLT7y81#scrollTo=6e70MXBbshfd

However, I cannot load the demo datasets. Namely, I get the error message when I run the Python lines below.

from sdv.demo import get_available_demos
demos = get_available_demos()
demos.shape

--------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[3], line 2
      1 from sdv.demo import get_available_demos
----> 2 demos = get_available_demos()
      3 demos.shape

This is the error message I received.

File ~\Anaconda3\envs\Research2024\lib\site-packages\sdv\demo.py:479, in get_available_demos()
    472 def get_available_demos():
    473     """Get available demos and information about them.
    474 
    475     Returns:
    476         pandas.DataFrame:
    477             Table with the available demos.
    478     """
--> 479     return pd.read_csv(DATASETS_URL)

File ~\Anaconda3\envs\Research2024\lib\site-packages\pandas\util\_decorators.py:211, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
    209     else:
    210         kwargs[new_arg_name] = new_arg_value
--> 211 return func(*args, **kwargs)

File ~\Anaconda3\envs\Research2024\lib\site-packages\pandas\util\_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~\Anaconda3\envs\Research2024\lib\site-packages\pandas\io\parsers\readers.py:950, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    935 kwds_defaults = _refine_defaults_read(
    936     dialect,
    937     delimiter,
   (...)
    946     defaults={"delimiter": ","},
    947 )
    948 kwds.update(kwds_defaults)
--> 950 return _read(filepath_or_buffer, kwds)

File ~\Anaconda3\envs\Research2024\lib\site-packages\pandas\io\parsers\readers.py:605, in _read(filepath_or_buffer, kwds)
    602 _validate_names(kwds.get("names", None))
    604 # Create the parser.
--> 605 parser = TextFileReader(filepath_or_buffer, **kwds)
    607 if chunksize or iterator:
    608     return parser

File ~\Anaconda3\envs\Research2024\lib\site-packages\pandas\io\parsers\readers.py:1442, in TextFileReader.__init__(self, f, engine, **kwds)
   1439     self.options["has_index_names"] = kwds["has_index_names"]
   1441 self.handles: IOHandles | None = None
-> 1442 self._engine = self._make_engine(f, self.engine)

File ~\Anaconda3\envs\Research2024\lib\site-packages\pandas\io\parsers\readers.py:1735, in TextFileReader._make_engine(self, f, engine)
   1733     if "b" not in mode:
   1734         mode += "b"
-> 1735 self.handles = get_handle(
   1736     f,
   1737     mode,
   1738     encoding=self.options.get("encoding", None),
   1739     compression=self.options.get("compression", None),
   1740     memory_map=self.options.get("memory_map", False),
   1741     is_text=is_text,
   1742     errors=self.options.get("encoding_errors", "strict"),
   1743     storage_options=self.options.get("storage_options", None),
   1744 )
   1745 assert self.handles is not None
   1746 f = self.handles.handle

File ~\Anaconda3\envs\Research2024\lib\site-packages\pandas\io\common.py:713, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    710     codecs.lookup_error(errors)
    712 # open URLs
--> 713 ioargs = _get_filepath_or_buffer(
    714     path_or_buf,
    715     encoding=encoding,
    716     compression=compression,
    717     mode=mode,
    718     storage_options=storage_options,
    719 )
    721 handle = ioargs.filepath_or_buffer
    722 handles: list[BaseBuffer]

File ~\Anaconda3\envs\Research2024\lib\site-packages\pandas\io\common.py:363, in _get_filepath_or_buffer(filepath_or_buffer, encoding, compression, mode, storage_options)
    361 # assuming storage_options is to be interpreted as headers
    362 req_info = urllib.request.Request(filepath_or_buffer, headers=storage_options)
--> 363 with urlopen(req_info) as req:
    364     content_encoding = req.headers.get("Content-Encoding", None)
    365     if content_encoding == "gzip":
    366         # Override compression based on Content-Encoding header

File ~\Anaconda3\envs\Research2024\lib\site-packages\pandas\io\common.py:265, in urlopen(*args, **kwargs)
    259 """
    260 Lazy-import wrapper for stdlib urlopen, as that imports a big chunk of
    261 the stdlib.
    262 """
    263 import urllib.request
--> 265 return urllib.request.urlopen(*args, **kwargs)

File ~\Anaconda3\envs\Research2024\lib\urllib\request.py:214, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    212 else:
    213     opener = _opener
--> 214 return opener.open(url, data, timeout)

File ~\Anaconda3\envs\Research2024\lib\urllib\request.py:523, in OpenerDirector.open(self, fullurl, data, timeout)
    521 for processor in self.process_response.get(protocol, []):
    522     meth = getattr(processor, meth_name)
--> 523     response = meth(req, response)
    525 return response

File ~\Anaconda3\envs\Research2024\lib\urllib\request.py:632, in HTTPErrorProcessor.http_response(self, request, response)
    629 # According to RFC 2616, "2xx" code indicates that the client's
    630 # request was successfully received, understood, and accepted.
    631 if not (200 <= code < 300):
--> 632     response = self.parent.error(
    633         'http', request, response, code, msg, hdrs)
    635 return response

File ~\Anaconda3\envs\Research2024\lib\urllib\request.py:561, in OpenerDirector.error(self, proto, *args)
    559 if http_err:
    560     args = (dict, 'default', 'http_error_default') + orig_args
--> 561     return self._call_chain(*args)

File ~\Anaconda3\envs\Research2024\lib\urllib\request.py:494, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    492 for handler in handlers:
    493     func = getattr(handler, meth_name)
--> 494     result = func(*args)
    495     if result is not None:
    496         return result

File ~\Anaconda3\envs\Research2024\lib\urllib\request.py:641, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    640 def http_error_default(self, req, fp, code, msg, hdrs):
--> 641     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 404: Not Found

**Comment by npatki** [comment]
Hi @zelmously nice to meet you. Thanks for providing the notebook.

From looking at your code, it appears that **SDV v0.18.0 is being installed** in your notebook (not 1.8.0).

<img width="1176" alt="image" src="https://github.com/sdv-dev/SDV/assets/3227804/f0f5f783-06a4-4b23-b3a2-f3a3e7274da1">

As this version is over a year old, it's not something we currently offer support for. We always recommend installing the most recent version of SDV (currently 1.10.0, soon to be 1.11.0) for the most up-to-date features and bug fixes. The API has also changed significantly.

I think what's messing it up is your initial command for matplotlib: (`pip install -U matplotlib==3.1.3`). Seems like this version of matplotlib is over 4 years old. Is there any reason you require this particular version? A more up-to-date version of `matplotlib` is already available in Colab so there's no need to re-install it (or downgrade it in this case).

I would recommend creating a fresh notebook and only using `pip install sdv`. (No need to touch matplotlib.)

**Comment by srinify** [comment]
Hi @zelmously did you have a chance to update and try this out? Let me know if I can help

**Comment by zelmously** [comment]
Many thanks, Neha. I currently have a working version of SDV.

Sincerely,

Ziad Elmously

**Comment by npatki** [comment]
Fantastic -- happy to help!

**Comment by zelmously** [comment]
Hi Neha,

This is another follow up question. According to the link below, the
HMASynthesizer
model maintains relationships across multiple tables. However,  it uses
Gaussian Copulas for every underlying individual table.

https://github.com/sdv-dev/SDV/issues/1549

This is ideal from my standpoint. In my view, Gaussian Copulas capture
inter relationships between variables (e.g., correlations) relative to
algorithms based on Generative AI.

Please confirm my understanding of HMASynthesizer.

Sincerely,

Ziad Elmously

**Comment by npatki** [comment]
Hi @zelmously, the HMASynthesizer performs some algorithmic aggregations before using Gaussian Copula on the individual tables.

For more info about the HMA, you can refer to [this original paper](https://dai.lids.mit.edu/wp-content/uploads/2018/03/SDV.pdf) published in 2016. Additional papers and technical descriptions are listed [on this webpage](https://sdv.dev/resources/).
