### ISSUE TITLE
load pickle model error 

### ISSUE THREAD

**Issue by Ng-ms** [sdv-dev/SDV#1861]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.9.0
* Python version: 3.8
* Operating System: Linux

I trained my PARsyntheizer on SDV 1.9.0 , and after saving the model I am trying to load the pkl model to generate more data but I am getting this error 
```
AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/ficheros/BSC/.local/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>

**Comment by srinify** [comment]
Hi @Ng-ms can you share the versions of pandas you had before (when you trained PARSynthesizer) and after / now (when you tried to load the model).

```
import pandas
print(pandas.__version__)
```

**Comment by srinify** [comment]
Hi @Ng-ms just following up :)

**Comment by srinify** [comment]
Closing this issue for now. Feel free to reply and re-open the issue though :)
