### ISSUE TITLE
Update documentation to remove support for composite sequence keys

### ISSUE THREAD

**Issue by gsheni** [sdv-dev/SDV#1866]
### Environment Details

* SDV version: 1.11.0
* Python version: 3.11.8
* Operating System: MacOS

### Error Description
- The SDV documentation states that composite sequence keys (`If you have multiple columns that form a sequence key together, first_name and last_name, you supply them using a tuple.`)
  - https://docs.sdv.dev/sdv/sequential-data/data-preparation/sequential-metadata-api
- However, I ran into an invalid metadata error when I tried this out. 

### Steps to reproduce

```python
import pandas as pd

data = pd.DataFrame({
    'time': [1, 2, 3],
    'first_name': ['Alice', 'Bob', 'Charlie'],
    'last_name': ['Smith', 'Jones', 'Brown'],
    'gender': ['F', 'M', 'M'],
    'measurement': [55, 60, 65]
})
metadata = SingleTableMetadata()
metadata.add_column('first_name', sdtype='id')
metadata.add_column('last_name', sdtype='id')
metadata.set_sequence_key(column_name=('first_name', 'last_name'))
metadata.set_sequence_index(column_name='time')

assert metadata.sequence_key == ('first_name', 'last_name')
instance = PARSynthesizer(
    metadata=metadata
)
instance.validate(data)
```

**Comment by npatki** [comment]
Docs have been updated with
- Removed example of composite keys and
- Added description stating that composite values are not yet supported for sequence keys
