### ISSUE TITLE
Add documentation on add_column function on Multi Table Metadata

### ISSUE THREAD

**Issue by gsheni** [sdv-dev/SDV#1879]
### Problem Description
- On this page (https://docs.sdv.dev/sdv/multi-table-data/data-preparation/multi-table-metadata-api), there is currently no documentation on the `add_column` function. As a user, I would like to see documentation on the function and it's proper usage. 

### Expected behavior
- An section for `add_column` with an example.

**Comment by srinify** [comment]
Just added documentation for `update_column()` in both Single and Multi Table:

- https://docs.sdv.dev/sdv/single-table-data/data-preparation/single-table-metadata-api#add_column
- https://docs.sdv.dev/sdv/multi-table-data/data-preparation/multi-table-metadata-api#add_column
