### ISSUE TITLE
issue in generating a logic in ecommerce transaction data.

### ISSUE THREAD

**Issue by zara009** [sdv-dev/SDV#1893]
I have been trying to generate transaction data with SDV. My real data has Customer Name, Order ID, Product ID, Order Date, City, Unit Price and quantity. We all know that , a product(Lipstick) cannot have different unit price on a same date( example: Jan 1 2024) in same city(Seattle). I cannot incorporate this logic into my SDV Models. I have been using Gaussian copula, CTGAN, copulagaussian and TVAE synthesizer. Iam getting different unit price for a product repeated in same order ID, same date and same city. Here we see other problem also. A order ID should not have same products repeated in it. each products in each order ID should be different. because we know if a customer buys a products  2 quantity, we wont mention that in two rows. We have quantity column. How do i prevent this? Also generating Order ID with SDV is also very challenging. we know that a order id should not be same for two different customers and different date. These conditions cannot be added to my model. for now iam generating order id manually. but other two problems remains. Please help. Is this one of the limitations of SDV or is it possible to achieve the condition i said?

note: i have 1000 rows of real data and i generated 100000 using this.

**Comment by npatki** [comment]
Hi @zara009 thanks for the feedback about SDV. Usually, when I see so many business rules being broken by SDV, it is indicative that data is has gone through some heavy alterations. In this case, you have 1 table that contains many concepts -- customers, orders, products etc. It would appear as if someone has selectively taken columns out of the original database, and merged into 1 denormalized table. 

The SDV works better when you allow each entity to be present in an original, normalized form. For example, 1 table that lists all the products, 1 table that lists all the orders, and perhaps a bridge table for items, connecting 1 product to 1 order, etc. (See [this wiki page](https://en.wikipedia.org/wiki/Associative_entity).)

When your data is present in a normalized format, you can use the multi-table SDV synthesizers such as HMA, which are designed to pay attention to the connections between all the different entities (tables).

Out of curiosity, what is the source of the dataset you're using? Is it publicly available or one of your own?

**Comment by zara009** [comment]
Hi, Thanks for your Suggestion!

The data I am using is similar to OnlineRetail.csv from kaggle. Link is given below:

https://www.kaggle.com/datasets/vijayuv/onlineretail

**Comment by npatki** [comment]
Thanks for providing the source. I think that Kaggle dataset has been altered in order to end up with exactly 1 table with all the info.

Are you using data from your company or are you using publicly available demo datasets (from Kaggle, SDV,etc.)? If you are using your own company's data, I would recommend trying to access the original (normalized) format of the database.

**Comment by npatki** [comment]
Hi @zara009, I'm closing this issue off since it has been inactive for a few weeks and I believe we answered the question. If there is more to discuss about this, please feel free to reply and we can re-open.

Otherwise, if you have a separate question or bug, please feel free to file a new issue. Thanks.
