### ISSUE TITLE
The get_cardinality_plot code block includes invalid child_foreign_key

### ISSUE THREAD

**Issue by gsheni** [sdv-dev/SDV#1900]
### Error Description
- The code block on [get_cardinality_plot](https://docs.sdv.dev/sdv/multi-table-data/evaluation/visualization#get_cardinality_plot) does not work. Specifically, it references user_id, which does not exist in the fake_hotels dataset. 
- The diagram should also not include user_id
```python
from sdv.evaluation.multi_table import get_cardinality_plot

fig = get_cardinality_plot(
    real_data=real_data,
    synthetic_data=synthetic_data,
    child_table_name='guests',
    parent_table_name='hotels',
    child_foreign_key='user_id',
    metadata=metadata)
    
fig.show()

```

**Comment by srinify** [comment]
Good catch! Just fixed

**Comment by npatki** [comment]
Hey @gsheni just a note that the examples provided in the docs are just meant to be that -- examples that show how you would hypothetically use a feature. They are for illustration/educational purposes only.

While it's create if that code actually works on a demo dataset, it is not a necessary condition.

@srinify With your fix, the code and the image don't match up anymore. I would recommend updating the code block with something other than `guests` and `hotels` (maybe `sessions` and `users`) and keeping the `user_id` as the foreign key.

**Comment by srinify** [comment]
Ahh fair enough, will update!

**Comment by srinify** [comment]
Updated!
