### ISSUE TITLE
Centralize root_tables function

### ISSUE THREAD

**Issue by gsheni** [sdv-dev/SDV#1934]
### Description
- There is currently 2 places we get the root parents:
- https://github.com/sdv-dev/SDV/blob/447d0d0f5b85b3fae3a0fc7a737915817e8742e0/sdv/_utils.py#L363-L366
- https://github.com/sdv-dev/SDV/blob/938bea04b00fff1becdcfb975d4ae8cf2eaac0d9/sdv/multi_table/base.py#L117-L122
- Ideally, this code lives in one place, most likely as a private method on the MultiMetadata class.

**Comment by fealho** [comment]
The `_get_root_parents` method has already been removed.
