### ISSUE TITLE
synthetic data  format is wrong based up on real data -Please help

### ISSUE THREAD

**Issue by Vasanthpravin** [sdv-dev/SDV#1943]
sdv versiom-1.12.0
databricks 13.3 LTS

dp_pandas = df.toPandas()

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(dp_pandas)

synthesizer = GaussianCopulaSynthesizer(metadata=metadata)
synthesizer.fit(data=df_pandas)

synthetic_data = synthesizer.sample(num_rows=50)

display(synthetic_data)
dp_pandas.info(verbose = True, null_counts = False)

Ouptut is coming

![image](https://github.com/sdv-dev/SDV/assets/167750615/8a31ae0c-d7ac-4067-8008-79b65badd2e4)
Person id                   PhoneId
sdv-pii-btwry        sdv-id-0

both columns are number but its generating sdv like that.Please help

**Comment by srinify** [comment]
Hi there @Vasanthpravin 

When you run `metadata.detect_from_dataframe(dp_pandas)`, SDV does a best-guess effort to automatically infer the metadata (and hence, the [sdtypes](https://docs.sdv.dev/sdv/reference/metadata-spec/sdtypes)) for all of your columns.

However, this process isn't perfect and we always recommend double checking the metadata to make sure it matches what you expect. You can display the `metadata` object to get a read-out of the auto-detected sdtypes:

```
print(metadata)
```

Then, you can update the sdtype of multiple columns at once using the [`update_columns_metadata`](https://docs.sdv.dev/sdv/single-table-data/data-preparation/single-table-metadata-api#update_columns_metadata) method from SingleTableMetadata:

```
metadata.update_columns_metadata(
  column_metadata = {
    'personid': { 'sdtype': 'numerical' },
    'phoneid': { 'sdtype': 'phone_number' }
  }
)
```

Then you can create your synthesizer object, fit the model, and sample:

```
synthesizer = GaussianCopulaSynthesizer(metadata=metadata)
synthesizer.fit(data=df_pandas)
synthetic_data = synthesizer.sample(num_rows=50)
```

**Comment by srinify** [comment]
Hi there @Vasanthpravin I'm closing out this issue for now, as it seems like there isn't a clear bug here. But let me know if you're still running into the issue or uncover a related bug and we can re-open the issue!
