### ISSUE TITLE
Update the evaluation verbosity examples in the docs

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1953]
### Problem Description
In [SDMetrics issue #538](https://github.com/sdv-dev/SDMetrics/issues/538), we improved how the quality and diagnostic report print out scores when verbosity is false. However, we have not updated the [SDV docs](https://docs.sdv.dev/sdv) to include this improvement.

The relevant docs would be the evaluation (diagnostic and quality) for both single and multi table.

**Comment by srinify** [comment]
Updated and closing this issue out!
