### ISSUE TITLE
Re-run the tutorial notebooks for the latest improvements

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1954]
### Problem Description
In the past few versions of the SDV, we've made many improvements including the verbosity as well as the order in which ID columns are generated. These improvements change the output synthetic data and results that a user sees when using SDV.

### Expected behavior
We should re-run all the [demo tutorials](https://docs.sdv.dev/sdv/demos) in our docs. 

### Additional context
The tutorials are authored by `company@datacebo.com` so we'd need to be logged in as that author in order to make the changes.

**Comment by srinify** [comment]
Re-ran and updated all tutorial notebooks. Closing this out! 🎉
