### ISSUE TITLE
Can't get attribute 'Provider.http_status_code' on <module 'faker.providers.internet'

### ISSUE THREAD

**Issue by iamamiramine** [sdv-dev/SDV#1959]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.12.1
* Python version: 3.10.9
* Operating System: Ubuntu 22.04 LTS

### Error Description

I was trying to load a synthesizer from a pickled file. I noticed that I have provided the wrong file name, however, I received a totally unrelated error.

> Can't get attribute 'Provider.http_status_code' on <module 'faker.providers.internet'

**Edit:**
The path was correct. I tried loading the _.pkl_ file using `pickle.load(file)`, but I got the same error

### Steps to reproduce

```
GaussianCopulaSynthesizer.load(filepath="path/that/does/not/exist")

Traceback (most recent call last):
File "/sdvault/src/application/synthesizer/models/ctgan.py", line 17, in init_synthesizer
    return CTGANSynthesizer.load(filepath=self.synthesizer_file)
  File "/miniconda3/envs/sdvault/lib/python3.10/site-packages/sdv/single_table/base.py", line 439, in load
    synthesizer = cloudpickle.load(f)
AttributeError: Can't get attribute 'Provider.http_status_code' on <module 'faker.providers.internet' from '/miniconda3/envs/sdvault/lib/python3.10/site-packages/faker/providers/internet/__init__.py'>
```

```
with open(path/to/pkl/file, "rb") as file:
    synthesizer = pickle.load(file)

Traceback (most recent call last):
  File "/home/amir/Desktop/Amir/Projects/synthetic-data/vault/sdvault/src/application/synthesizer/models/synthesizer_base.py", line 51, in __init__
    with open(self.synthesizer_file, "rb") as file:
```

**Comment by iamamiramine** [comment]
### Solved

Apparently I was training my synthesizers on one virtual environment with SDV version = 1.11.0, and I was trying to generate data using these synthesizers on another virtual environment with a different SDV version.

The issue was with the package "fakers". The attribute the code was trying to call is `http_status_code` from `Provider.http_status_code`. This attribute was introduced in fakers==22.5.0. On my first virtual environemnt, SDV seems to have installed fakers>=22.5.0, while on my second virtual environment, fakers==19.13.0 was installed.


### Solved

The solution was to upgrade fakers using the following command:

`pip3 install -U Faker` (not Fakers)

Also, make sure to run the same SDV version on different virtual environments

### Suggestions

It seems that when pickling the models, everything, including the classes, the imports and the weights, are being pickled. Is there a way in SDV to pickle only the weights and load the weights instead of loading the full model? If there is a way, any help on how to achieve that?

Thank you!

**Comment by srinify** [comment]
Hi there @iamamiramine glad you were able to solve this issue yourself! A few observations:

**Feature Request for a more minimal model pickle file**

This is a great suggestion and I've opened a new GitHub issue for this idea: https://github.com/sdv-dev/SDV/issues/1970

**Different package versions**

When you ran into this issue, did you install specific version of the Faker library in each environment? Or did you use `pip` to install specific versions of sdv and this _resulted_ in different Faker library versions being installed?
