### ISSUE TITLE
Unexpected NaN values in `sequence_index` when dataframe isn't reset

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1973]
### Environment Details
* SDV version: 1.12.1 (latest)

### Error Description
Like any SDV synthesizer, the PARSynthesizer is supposed to synthesize NaN values if (and only if) the real data also had NaN values for the column. However, we see that sometimes, PAR creates NaN values for the _sequence index_ column even though the real data does not have missing values.

This is replicable for the particular case where the index (aka row count) of the pandas dataframe hasn't been reset. This can happen, for instance, when you subset the rows. _Note that the pandas dataframe index is a separate concept than the PAR's sequence index! These are two separate columns._

### Steps to reproduce
As described [in this comment](https://github.com/sdv-dev/SDV/issues/1808#issuecomment-2081551310), we can replicate the issue by taking the demo dataset and dropping a few of the sequences.

```python
import numpy as np
import pandas as pd

from sdv.datasets.demo import download_demo
from sdv.sequential import PARSynthesizer

data, metadata = download_demo(modality='sequential', dataset_name='nasdaq100_2019',)

# modify the data by choosing a subset of it
data_subset = data.copy()
np.random.seed(1234)
symbols = data['Symbol'].unique()

# only select a subset of data in each sequence
for i, symbol in enumerate(symbols):
    symbol_mask = data_subset['Symbol'] == symbol
    data_subset = data_subset.drop(data_subset[symbol_mask].sample(frac = i / (2 * len(symbols))).index)

# now run PAR
# for performance's sake, we'll running with fewer epochs and create fewer samples
synthesizer = PARSynthesizer(metadata, epochs=5, verbose=True)
synthesizer.fit(data_subset)
synthetic_data = synthesizer.sample(num_sequences=5)

# observe that the synthetic data contains NaN values in sequence index column 'Date'
# even though the real data does not have NaN values for it
print('Real data has NaNs?:', pd.isnull(data_subset['Date']).any())
print('Synthetic data has NaNs?:', pd.isnull(synthetic_data['Date']).any())
```
```
Real data has NaNs?: False
Synthetic data has NaNs?: True
```

### Root Cause
This is happening because the _pandas DataFrame_ index is not a continuously increasing index (due to the subsetting). For example, observe how row 318 does not exist (because the subset didn't include it):

<img width="920" alt="image" src="https://github.com/sdv-dev/SDV/assets/3227804/e2994ec4-8a25-4ab2-b630-b1edf63f8989">

### Workaround
The workaround would be to reset the index of the subsetted data _before_ fitting it with PAR

```python
# reset the index column so it doesn't randomly skip rows
data_subset_reset = data_subset.reset_index().drop(columns='index')

# now fit PR on the reset data
synthesizer = PARSynthesizer(metadata, epochs=5, verbose=True)
synthesizer.fit(data_subset_reset)
synthetic_data2 = synthesizer.sample(num_sequences=5)
```

The problem then goes away.
```python
print('Real data has NaNs?:', pd.isnull(data_subset_reset['Date']).any())
print('Synthetic data has NaNs?:', pd.isnull(synthetic_data2['Date']).any())
```
```
Real data has NaNs?: False
Synthetic data has NaNs?: False
```

**Comment by MarcJohler** [comment]
Hi @npatki 

I also checked with my data set, which has strongly irregular dates as sequence indices and the workaround/fix also works perfectly well there. 

Thanks a lot for coming up with a solution so quickly, that's very convenient for my project!

**Comment by npatki** [comment]
Hi @Ng-ms as this is a slightly different problem, perhaps you should file a new issue for it? 

Off-the-cuff, I think the PARSynthesizer is designed to emulate patterns from your real data. Does your real data have any repeated sequence indicies? That may be something to check. If you file a new issue, we can provide code for that. Thanks.

**Comment by Ng-ms** [comment]
in real data, i do not see this behavior since my sequnece_index is the visit date so each date is unique
