### ISSUE TITLE
[HELP] CTGAN has Reproducibility?

### ISSUE THREAD

**Issue by limhasic** [sdv-dev/SDV#1991]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.12.1
* Python version: 3.9.5
* Operating System: ubunutu 20.04

### Problem description

CTGAN has no Reproducibility when i tried sample data

### What I already tried
```
import numpy as np
import torch

# 시드 설정
seed = 42

np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed) 

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
SEED_VALUE = 42

np.random.seed(SEED_VALUE)
torch.manual_seed(SEED_VALUE)
synthesizer.reset_sampling()
synthesizer._set_random_state(123)
d1 = synthesizer.sample(10, output_file_path=None)
d2 = synthesizer.sample(10, output_file_path=None)


from ctgan import CTGAN

ctgan = CTGAN(epochs=1, verbose = True)
ctgan.set_random_state(0)
ctgan.fit(data)
sample_1 = ctgan.sample(100)

ctgan = CTGAN(epochs=1, verbose = True)
ctgan.set_random_state(0)
ctgan.fit(data)
sample_2 = ctgan.sample(100)

sample_1.equals(sample_2)
```

all of false .... help

**Comment by npatki** [comment]
Hi @limhasic, I see that you closed this issue off. Does that mean you found a solution to your problem?

If so, could you share a little more about what your solution was? It would be a helpful reference to anyone else who's running into similar problems. Thanks.
