### ISSUE TITLE
where can I change the loss function of CTGAN

### ISSUE THREAD

**Issue by YujiaZhang** [sdv-dev/SDV#2000]
I want to change the generator and discriminator loss functions, could tell me which code file I should access?

**Comment by sdv-team** [comment]
Hi @YujiaZhang It’s great to see your interest in the SDV ecosystem. This comment is a reminder to consult your legal before adopting the SDV into your project, as SDV has [source-available license](https://github.com/sdv-dev/SDV/blob/master/LICENSE).

For more information, you can read through our [license FAQs](https://datacebo.com/license-faqs/) (not legal advice). For any other questions, you can [Contact Us](https://datacebo.com/contact/). You can also inquire about a commercial license to allow additional use.

**Comment by srinify** [comment]
Hi there @YujiaZhang 👋 

Do you mind sharing more about your use case here? Only asking because SDV has a lot of handles & levers for improving synthetic data quality and I want to make sure to align our advice towards your goals!

**Comment by srinify** [comment]
Hi there @YujiaZhang I haven't heard from you in a while so I'm closing this issue out for now. If you still need help, feel free to comment and tag me and I can re-open!

**Comment by YujiaZhang** [comment]
hi @srinify, I was wondering if I can change the sampling logic of the conditional generator? I want to do some enhancement for the logic
