### ISSUE TITLE
unable to run this code from sdv.demo import load_tabular_demo its showing error and stating No module named 'sdv.demo' 

### ISSUE THREAD

**Issue by mansiresh** [sdv-dev/SDV#2028]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:
* Python version:
* Operating System:

### Error Description

<Replace this text with a description of what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.>

### Steps to reproduce

<Replace this text with a description of the steps that anyone can follow to reproduce the error. If the error happens only on a specific dataset, please consider attaching some example data to the issue so that others can use it to reproduce the error.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by mansiresh** [comment]
No module named 'sdv.demo'
the above is the error
![Uploading Screenshot 2024-05-24 115915.png…]()

**Comment by npatki** [comment]
Hi @mansiresh, which website is telling you to do `from svd.demo import load_tabular_demo`?

Those instruction was for a very old version of SDV that is over 1 year old. For the most up-to-date instructions, please see our [documentation website](https://docs.sdv.dev/sdv). The new code is:

```python
from sdv.datasets.demo import download_demo

data, metadata = download_demo(
    modality='single_table',
    dataset_name='fake_hotel_guests'
)
```

**Resources:**
- [documentation website](https://docs.sdv.dev/sdv)
- [Tutorials](https://docs.sdv.dev/sdv/demos)

**Comment by npatki** [comment]
Hello, I'm going to close out this thread since we've answered the question. Please feel free to reply if you are still unable to load a demo and we can always continue to investigate.

Alternatively, if you run across any new problems, you can always file a new issue. Thanks.
