### ISSUE TITLE
Sampling should not create a file called ‘.sample.csv.temp’ by default

### ISSUE THREAD

**Issue by cynddl** [sdv-dev/SDV#2029]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.13.1
* Python version: 3.11.9
* Operating System: macOS (arm)

### Error Description

Calling _model.sample_ on any single table model (at least, I didn't check others) always writes to the disk an output file, even if output_file_path is set to None. The docstring mentions:

```
output_file_path (str or None):
                The file to periodically write sampled rows to. If None, does not
                write rows anywhere.
```
so I'd assume no file would be created.

Either the function definition for _sample()_  should be updated to set _output_file_path=DISABLE_TMP_FILE_ by default, either setting _None_ should defaults to _DISABLE_TMP_FILE_?

(In my case, the temporary file is problematic because I use sdv is with ray (which attempts to serialise data across multiple processes—and crashes when sdv creates this file called ".sample.csv.temp". I'd much prefer not writing to the disk, than tinkering with unique temporary files in order to not crash Python)

### Steps to reproduce

N/A

### See also

#1310

**Comment by npatki** [comment]
Hi @cynddl, thanks for the details. 

I've consolidate both this and the previous #1310 into a new feature request with an updated API definition. You can follow along any updates in #2042 as we track the fix. Thanks.
