### ISSUE TITLE
Why model fitting a long time for relation tables

### ISSUE THREAD

**Issue by Arrmlet** [sdv-dev/SDV#203]
* SDV newest:
* Python 3.8.2:
* Operating System: ubuntu 20

### Description

Hello there,

I need to generate a three related tables. But model fitting takes a lot of time

My metadata looks like:

```
Metadata
  root_path: .
  tables: ['courses_generated', 'activities_generated', 'activity_completion_generated']
  relationships:
    activities_generated.course_id -> courses_generated.id
    activity_completion_generated.activity_id -> activities_generated.id
```
I have limited an number of records for each table now tables contains data like this:
courses_generated: number of columns 10; number of records 11;
activities_generated: number of columns 8; number of records 100;
activity_completion_generated: number of columns 4; number of records 100;

But it still fitting a long period of time and consumes over 4 GB of RAM.

**Comment by csala** [comment]
Hello @Arrmlet 

It is hard to tell the details without looking at the data and the commands that you execute.

Would you be able to share it?

**Comment by csala** [comment]
Closing this because due to inactivity. Please re-open if new information is available.
