### ISSUE TITLE
SDV support for Ray?

### ISSUE THREAD

**Issue by raywang1021** [sdv-dev/SDV#2030]
Not sure how SDV can support generate large scale of data volume like TB level dataset?
Does SDV support effortlessly scale workloads like Ray?
https://www.ray.io/
Many thx

**Comment by srinify** [comment]
Hi there @raywang1021 hopefully this answer was helpful! I haven't heard from you in 2 weeks so I'm going to go ahead and close this issue out. Feel free to comment and tag me or open a new issue if you have more questions on this front!
