### ISSUE TITLE
PARSynthesizer errors during `fit` if sequence_index is numerical sdtype

### ISSUE THREAD

**Issue by frances-h** [sdv-dev/SDV#2079]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:
* Python version:
* Operating System:

### Error Description
After #2043, we fixed an issue where `enforce_min_max_values` was by default being set to `True` for the sequence_index transformer. However, if no transformer is assigned to the sequence_index (i.e. if the sequence is already a numerical sdtype), fit now errors.

To fix, we should check that (1) a transformer has been assigned (transformer is not `None`) and (2) that the transformer has the `enforce_min_max_values` attribute (instead of adding an additional check, we could use getattr with a `False` default value in place of directly accessing the attribute)

### Steps to reproduce
```python
from sdv.datasets.demo import download_demo
from sdv.sequential import PARSynthesizer

data, metadata = download_demo('sequential', 'CMAPPSJetEngine')
s1 = PARSynthesizer(metadata)
s1.fit(data)
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 s1.fit(data1)
      2 s1.sample(10)

File ~/Documents/SDV/sdv/single_table/base.py:471, in BaseSynthesizer.fit(self, data)
    469 self._data_processor.reset_sampling()
    470 self._random_state_set = False
--> 471 processed_data = self.preprocess(data)
    472 self.fit_processed_data(processed_data)

File ~/Documents/SDV/sdv/single_table/base.py:407, in BaseSynthesizer.preprocess(self, data)
    400     warnings.warn(
    401         'This model has already been fitted. To use the new preprocessed data, '
    402         "please refit the model using 'fit' or 'fit_processed_data'."
    403     )
    405 is_converted = self._store_and_convert_original_cols(data)
--> 407 preprocess_data = self._preprocess(data)
    409 if is_converted:
    410     data.columns = self._original_columns

File ~/Documents/SDV/sdv/sequential/par.py:286, in PARSynthesizer._preprocess(self, data)
    284 sequence_key_transformers = {sequence_key: None for sequence_key in self._sequence_key}
    285 if not self._data_processor._prepared_for_fitting:
--> 286     self.auto_assign_transformers(data)
    288 self.update_transformers(sequence_key_transformers)
    289 preprocessed = super()._preprocess(data)

File ~/Documents/SDV/sdv/sequential/par.py:267, in PARSynthesizer.auto_assign_transformers(self, data)
    265 if self._sequence_index:
    266     sequence_index_transformer = self.get_transformers()[self._sequence_index]
--> 267     if sequence_index_transformer.enforce_min_max_values:
    268         sequence_index_transformer.enforce_min_max_values = False

AttributeError: 'NoneType' object has no attribute 'enforce_min_max_values'
```

**Comment by ryantimjohn** [comment]
Is there any workaround end-users can do to get around this in the meantime till this release drops @lajohn4747 ?

**Comment by npatki** [comment]
Hi @ryantimjohn, sure thing. The bug only appears when `sequence_index` is a numerical sdtype, but it works just fine if the sdtype is datetime. So one workaround would be to convert your numerical column into datetimes. In the example below, I am converting a numerical column to datetimes by adding the # of days to Jan 1, 2000:

```python
import pandas as pd
from sdv.sequential import PARSynthesizer

index_name = 'COLUMN_NAME' # replace with the name of your numerical sequence index column

# convert the sequence index to datetime and update metadata to match
data[index_name] = pd.to_datetime('2000-01-01') + pd.to_timedelta(data[index_name], unit='d')
metadata.update_column(
    column_name=index_name,
    sdtype='datetime'
)

# now you can model and sample synthetic data using PAR
synthesizer = PARSynthesizer(metadata)
synthesizer.fit(data)
synthetic_data = synthesizer.sample(num_sequences=10)

# be sure to convert the datetimes back into numbers
synthetic_data[index_name] = synthetic_data[index_name] - pd.to_datetime('2000-01-01')
```

This is a bit hacky, but after the next release, you will not need to apply the workaround. Hope that helps!

**Comment by ryantimjohn** [comment]
Came up with the same solution, thank you!

**Comment by ryantimjohn** [comment]
@npatki Unfortunately, when I did this, though, I got another error, sorry to ask for help troubleshooting but wondered if you could help because I saw you dealt with a similar error here:
https://github.com/sdv-dev/SDV/issues/1214

After converting the sequence index column to a date and update the metadata, when I run the dataframe through the PAR Synthesizer, I get this error:
`AttributeError: 'NoneType' object has no attribute 'is_generator'`

Is there any reason why this might be that comes to mind?

Thanks very much for your help!

**Comment by npatki** [comment]
Hi @ryantimjohn no problem. I suspect this is unrelated to to the `fit` error and has something to do with the data/metadata itself. Would you mind filing a new bug with this info? It would be helpful to if you could also share the (updated) metadata and perhaps an example of the data itself that has the datetime index column. Thanks!
