### ISSUE TITLE
Custom Processing & Anonymization tutorial raises warning

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#2091]
### Problem Description

The [Custom Processing & Anonymization tutorial](https://colab.research.google.com/drive/1Z9Rff5G3eDI-LEc1LXiew9E3hF5Ob-on?usp=sharing) raises the following warning:
```
 Locales ['fr_CA'] do not support provider 'internet' and function 'email'.
In place of these locales, 'en_US' will be used instead. Please refer to the localized provider docs for more information https//faker.readthedocs.io/en/master/locales.html
  warnings.warn(
/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/rdt/transformers/pii/anonymizer.py102 UserWarning Locales ['fr_FR', 'fr_CA'] do not support provider 'credit_card' and function 'credit_card_number'.
In place of these locales, 'en_US' will be used instead. Please refer to the localized provider docs for more information https//faker.readthedocs.io/en/master/locales.html
  warnings.warn(
```
This is because the locales are updated to use ['fr_FR', 'fr_CA'], but Faker can't generate credit cards or emails for those regions.

### Expected behavior

- Change the example in the demo to use different locales that won't raise warnings. An example that has both would be ru_RU or uk_UA

**Comment by amontanez24** [comment]
This actually might not be an issue anymore. The demo should be rerun to make sure before making any changes

**Comment by srinify** [comment]
This is now updated & fixed, thanks for catching this!
