### ISSUE TITLE
Add user guides for demos

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#210]
A `Demo Datasets` subsection should be added within each data modality section in the user guides, explaining what datasets are available and how to use them.

**Comment by npatki** [comment]
With the addition of [**SVD 1.0 (Beta!)**](https://docs.sdv.dev/sdv/), this issue is now obsolete. 

We have now separated the ability to download a demo dataset by modality. See [demo data](https://docs.sdv.dev/sdv/single-table-data/data-preparation/loading-data#demo-data) for more details.
