### ISSUE TITLE
CTGAN: Document requirement to make batch_size divisible by pack_size

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#211]
Follow-up from this comment: https://github.com/sdv-dev/CTGAN/issues/60#issuecomment-667606519 by @k15z 

> The discriminator uses the PacGAN framework to prevent mode collapse with pack size 10. @csala The docstring can be updated to clarify this restriction, the batch size must be divisible by the pack_size.

**Comment by npatki** [comment]
Since this issue was first filed, `pack_size` has be renamed to `pac`. We're using issue #1269 to cover the docs updates so marking this one as a duplicate.
