### ISSUE TITLE
Scalability of theSDV tool and GPU support for Multi Table Data

### ISSUE THREAD

**Issue by manurajmr1** [sdv-dev/SDV#2110]
### Environment details

* SDV version:1.0 (latest by default)
* Python version:3.10
* Operating System:debian

### Problem description

Hi i wanted to use SDV for generating multi table data. For that i used [HMASynthesizer](https://docs.sdv.dev/sdv/multi-table-data/modeling/synthesizers/hmasynthesizer) which is free. SO i have few queries on this tool. Is the free synthesizer HMASynthesizer felt  slow while testing? how much scalability it can provide like example 1M data with constraints it took for me around 3 days. in the doc it says - The HMA Synthesizer uses hierarchical ML algorithm to learn from real data and generate synthetic data.  The algorithm uses classical statistics. which means it doesnt leverage GPU right? as its not neural network. 
Also i could find other synthesizers paid ones like HSASynthesizer, IndependentSynthesizer etcc, does that leverage GPU if i use  these ones which support a neural net synthesizer. And how much time will it take to generate a synthetic data around 1M with 2 tables 5 columns each in two tables and maintain a primary key foriegn key relation between tables, with a date constraint like hotel booking < hotel checkout date.
Is there a trail for paid version is available? to see it support GPU neural training, and to see it support also parallelism like distributing the load into multiple GPUS for faster performance (as pytorch by default support this).

### What I already tried

I tried the Multi table Data use case and saw the process is slow, but the quality of data generated is good.

**Comment by npatki** [comment]
Hi @manurajmr1, I'm closing off this issue since we've pointed you to the right venue for this type of Q.

If you need help troubleshooting any code when using SDV, please feel free to file a new issue here with any related code snippet(s).

**Comment by deepakbhavsar123** [comment]
Does SDV Enterprise solve the performance issue? SDV-free sdk takes too much time to generate data.

**Comment by npatki** [comment]
Hi @deepakbhavsar123, SDV Enterprise is designed to work on much larger datasets (hundreds of tables, with many levels of hierarchy). 

[This blog post](https://datacebo.com/blog/multi-table-synthesizers/) can give you some idea of the types of speedups possible with SDV Enterprise -- eg. the publicly-available HMA may be taking 1 hour to train on a particular dataset; the SDV Enterprise version (HSA) takes only 1 min for the same dataset.

If you haven't already, definitely feel free to [get in touch with us](https://datacebo.com/support/) about SDV Enterprise. Thanks.
