### ISSUE TITLE
Transformers for context columns are not allowed  to be updated

### ISSUE THREAD

**Issue by Pavamana15** [sdv-dev/SDV#2111]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:
* Python version:
* Operating System:

### Error Description

I used one of the available multi-sequence data sets online to generate a synthetic dataset. But I am getting the following errors.

### Steps to reproduce
<img width="1100" alt="DATACEBO" src="https://github.com/sdv-dev/SDV/assets/124121665/926e6ff0-71ab-4599-8503-e761475d872b">
<img width="1084" alt="DATACEBO_1" src="https://github.com/sdv-dev/SDV/assets/124121665/ab360407-b08e-4fba-bf7d-f4e5ac77b047">

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @Pavamana15 thanks for filing this issue and providing more details.

For multi-sequence data, it is not allowed for your context column to be the same as your sequence key. The sequence key is meant to identify each sequence so by definition, it will never vary within each sequence. However a context column is typically another column (not the sequence key) that does not vary within the sequence. I suggest removing the context column to continue with the modeling.

Resources:
- Duplicate issue found in #2097. We will provide better messaging for this.
- [This tutorial](https://colab.research.google.com/drive/1YLk2uwn8yrSRPy0soEeJwu8Hdk_tGTlE?usp=sharing) is a good resource for understanding multi-sequence data

**Comment by Pavamana15** [comment]
Thank you so much @npatki . The error is resolved now,but it is taking a lot of time to run

**Comment by Pavamana15** [comment]
@npatki  I could generate synthetic data using  PARSynthesizer with fewer epochs, i.e., 30 epochs. However, it does not generate synthetic data in sequential order. I mean, rows should be ordered in time. Original data had rows ordered in time. So why am I getting like this, or what mistake am I making?

**Comment by Pavamana15** [comment]
@npatki Can you also explain how to evaluate the quality of synthetic data?
