### ISSUE TITLE
Synthetic time series data generated from PARSynthesizer is not ordered in time

### ISSUE THREAD

**Issue by Pavamana15** [sdv-dev/SDV#2112]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:
* Python version:
* Operating System:

### Error Description

@npatki I could generate synthetic data using PARSynthesizer with fewer epochs, i.e., 30 epochs. However, it does not generate synthetic data in sequential order. Rows should be ordered in time. Original data had rows ordered in time. So why am I getting like this, or what mistake am I making?

### Steps to reproduce

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Pavamana15** [comment]
@npatki Can you answer above question here?

**Comment by npatki** [comment]
Hi @Pavamana15, that's unfortunate to hear. I am curious which value(s) you are using to determine whether the rows are ordered in time. Do you have a timestamp column that is being used for this purpose? And are you supplying it as a [sequence_index](https://docs.sdv.dev/sdv/sequential-data/data-preparation/sequential-metadata-api#set_sequence_index) in your metadata? If not, please add it as a `sequence_index` and retry.

For further troubleshooting, it will be easier for me to help if you are able to share:
- The code you are using to create the PARSynthesizer
- Your metadata and
- Perhaps a snippet or example of real data rows vs. synthetic data rows so I can see what you're talking about

Thanks.

**Comment by Pavamana15** [comment]
Thank You @npatki.I have already assigned the sequence index to the Date column. It is working now.

**Comment by npatki** [comment]
Great. I'll close off the issue since it's working now.
