### ISSUE TITLE
Primary keys may not be unique for variable length regexes

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#2116]
### Environment Details
* SDV version: 1.14.0

### Error Description
If a regex has variable length (eg. 3 or 4 characters long with a format such as `'[0-9]{3,4}'`), the primary keys that SDV generates may not always be unique. This is supported by the diagnostic report being less than 100%.

### Steps to reproduce
```python
import pandas as pd

from sdv.metadata import SingleTableMetadata
from sdv.single_table import GaussianCopulaSynthesizer
from rdt.transformers.text import RegexGenerator
from sdv.evaluation.single_table import run_diagnostic

data = pd.DataFrame(data={
    'id': [123, 456, 1234, , 5678],
    'col': [23.4, 12.3, 10.0, 90.4, 10.3]
})

metadata = SingleTableMetadata.load_from_dict({
    'columns': {
        'id': { 'sdtype': 'id', 'regex_format': '[0-9]{3,4}' },
        'col': { 'sdtype': 'numerical' }
    },
    'primary_key': 'id'
})

synth = GaussianCopulaSynthesizer(metadata)

# I am specifically assigning the RegexGenerator for illustration purposes
synth.auto_assign_transformers(data)
synth.update_transformers({
    'id': RegexGenerator(regex_format='[0-9]{3,4}', enforce_uniqueness=True, generation_order='alphanumeric')
})

synth.fit(data)
synthetic_data = synth.sample(num_rows=10_000)

diagnostic = run_diagnostic(data, synthetic_data, metadata)
diagnostic.get_details('Data Validity')
```
Output:
<img width="578" alt="image" src="https://github.com/sdv-dev/SDV/assets/3227804/099f1a06-5976-4b99-9043-7475a7c6d668">

### Expected Fix
This case can only happen when:

- The real data has a primary key (or alternate key) stored as an `int` AND
- The metadata for it includes a Regex AND
- The Regex allows for a `'0'` to be in the first position of the string

If _and only if_ all 3 conditions are met, the synthesizer should throw an error.

```python
synthesizer = HSASynthesizer(metadata)
synthesiser.fit(data)
```
```
SynthesizerInputError: Primary key for table 'users' is stored as an int but the Regex allows it to start with '0'. Please remove the Regex or update it to correspond to valid ints.
```

**Comment by amontanez24** [comment]
@npatki Do we only need to check primary keys, or should this error for other ids that have regexes?

**Comment by npatki** [comment]
@amontanez24 is there a reason why we should do this for other IDs?

The problem we are trying to solve is that duplicate values may be generated from a regex. This is only an issue if the column is a primary key (or alternate key) right?

**Comment by amontanez24** [comment]
I meant unique ids, so I guess alternate keys

**Comment by npatki** [comment]
Got it! I updated the original issue text to include alternate keys as well.

**Comment by amontanez24** [comment]
@npatki The issue includes the table name in the warning, but it would be kind of annoying to make that happen since at the point that the single table synthesizer gets fit, it doesn't know the table name. Is including the primary key name enough?

**Comment by npatki** [comment]
Discussed today with @amontanez24. Ideally we include the table name because the primary key name is not unique enough to identify a table. Eg. I've seen schemas where all of the primary keys are just called `ID`.
