### ISSUE TITLE
Enable multi table synthesizers to use new Metadata

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#2129]
### Problem Description

_As a user, I'd like to be able to use my metadata wherever it is applicable once created without having to do extra work._

### Expected behavior

Once #2104 is complete, we need to enable multi table synthesizers to work with the new Metadata
- Support the new class on initialization
- Deprecate MultiTableMetadata
    - Raise a future warning if users use this
- They should be backwards compatible (still support the old class)

### Additional context

Since the new class will be almost identical to the current MultiTableMetadata class, this should be a straightforward fix.

**Comment by gsheni** [comment]
Completed:
https://github.com/sdv-dev/SDV/pull/2146

**Comment by amontanez24** [comment]
This will be closed when #2186  is merged
