### ISSUE TITLE
Allow passing one or more instances of Tabular models to HMA1

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#215]
Current HMA1 input arguments include `model` and `model_kwargs`, where `model` must be a class and `model_kwargs` must be a dictionary with the arguments that will be used to create the `model` instance.

We could modify the `model` argument to also accept a pre-configured instance of the Tabular model, or even a dictionary indicating which model to use for each table, which would make set-up easier and provide more flexibility.

**Comment by npatki** [comment]
Closing off this issue as we have achieved this in SDV 1.0. We now allow you to pass in different configurations of the `GaussianCopulaSynthesizer` for each table, via the [`set_table_parameters` method](https://docs.sdv.dev/sdv/multi-table-data/modeling/hmasynthesizer#set_table_parameters). 

Note: The `HMA` only supports parametric models, so only the `GaussianCopula` is in scope. We have another issue open (#457) for the ability to support a non-parametric multi-table algorithm.
