### ISSUE TITLE
SDV documentation (TVAE)

### ISSUE THREAD

**Issue by Whitesheep18** [sdv-dev/SDV#2166]
As far as I understand the TVAESynthesizer is a VAE, so the loss should just be the ELBO, but the documentation states (under "epochs") that there should be a discriminator and a generator like in GAN..?

![image](https://github.com/user-attachments/assets/a4eaa371-73a5-4a3b-847e-3f444b31ec5b)

Similarly confusing is the customization section with the variable "pac":
![image](https://github.com/user-attachments/assets/31f2bd7b-6076-42f4-8d92-e44f51f82c7d)

Is TVAE a GAN where the generator is a VAE..? or is this a copy paste mistake in the documentation?

**Comment by srinify** [comment]
Hi there @Whitesheep18 you're absolutely right that TVAE Synthesizer is based on a VAE under the hood, not a GAN. This is **definitely a documentation mistake** on our part that I'll fix and update. Thank you so much for raising this!

**Comment by srinify** [comment]
@Whitesheep18 updates are now live, thanks again!

https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/tvaesynthesizer

_(Note: you might need to clear cache or hard refresh to see them)_
