### ISSUE TITLE
TypeError: cannot astype a datetimelike from [datetime64[ns]] to [int32]

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#218]
* SDV version: Any
* Python version: Any
* Operating System: Windows

### Description

The `TypeError` form the title seems to show up when running SDV on Windows, as reported on issues #205 and #217 

Unfortunately **we do not fully support windows environments yet**, so I'm opening this issue as a central collection point for the issues that may be raised around this problem, and to keep track of this topic once we add Windows support.

**Comment by csala** [comment]
It has been reported that [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) is a valid alternative to run SDV inside a Windows machine.

Also, a note has been added in the README to explicitly mention the supported OSs and the WSL alternative.

**Comment by pranavmyname** [comment]
I had the same issue and I used the workaround of using np datatype inside the astype function. 
For eg:
`df_comb['timestamp'] = (pd.to_datetime(df_comb['f0_'], format= '%Y-%m-%d', origin = 'unix' `).astype(int)/(10**9)).astype(int)`
was giving me the same error and which was fixed when I used np.int64 as the desired data type :
`df_comb['timestamp'] = (pd.to_datetime(df_comb['f0_'], format= '%Y-%m-%d', origin = 'unix' ).astype(np.int64)/(10**9)).astype(int)`
