### ISSUE TITLE
Is loss_factor not used? How to compute reconstruction loss?

### ISSUE THREAD

**Issue by turian** [sdv-dev/SDV#2196]
I am trying to compute reconstruction loss on held-out data, to do model selection.

However, I can't find anywhere in this repo or CTGan repo how to do this. In fact, I can't even find instances of `loss_factor` even being used.

I searched:
https://github.com/search?q=repo%3Asdv-dev%2FCTGAN%20loss_factor&type=code
https://github.com/search?q=repo%3Asdv-dev%2FSDV%20loss_factor&type=code

in the two repos and can't find it.

How do I compute reconstruction loss from a trained TVAE?

Related: #2166

**Comment by srinify** [comment]
Hi there @turian 👋 

**Loss Factor**

The `loss_factor` parameter value _is_ in fact used during model fitting: https://github.com/sdv-dev/CTGAN/blob/main/ctgan/synthesizers/tvae.py#L189

**Reconstruction Loss**

You can extract the loss values by calling the `loss_values` attribute, which returns a pandas DataFrame object with the loss values at the batch & epoch level.

- This is where the DataFrame is instantiated: https://github.com/sdv-dev/CTGAN/blob/main/ctgan/synthesizers/tvae.py#L128
- This is where the final loss values are added to the DataFrame: https://github.com/sdv-dev/CTGAN/blob/main/ctgan/synthesizers/tvae.py#L199

**SDV vs CTGAN**

In general, I'd recommend interacting with our models using the classes inside SDV - [CTGANSynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer) and [TVAESynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/tvaesynthesizer). These use the ctgan library under the hood but offer more affordances, a better user experience, and as a team we're more focused on SDV.

For example, we have functions to return the [DataFrame of loss values ](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer#get_loss_values) and another function [to generate a helpful plot of loss against the epochs](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer#get_loss_values_plot).

**Comment by srinify** [comment]
Hi @turian just following up :)

**Comment by srinify** [comment]
Hi @turian I haven't heard from you in over 2 weeks so I'll be closing this issue out. Feel free to open a new issue with new questions or blockers!
