### ISSUE TITLE
Fixed combinations is giving error

### ISSUE THREAD

**Issue by Pavan-Kalyan1432** [sdv-dev/SDV#2219]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:
* Python version:
* Operating System:

### Error Description

<Replace this text with a description of what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.>

### Steps to reproduce

<Replace this text with a description of the steps that anyone can follow to reproduce the error. If the error happens only on a specific dataset, please consider attaching some example data to the issue so that others can use it to reproduce the error.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

from sdv.lite import SingleTablePreset
from sdv.metadata import SingleTableMetadata
import pandas as pd
from sdv.constraints import FixedCombinations

real_data = pd.read_csv('CRM.csv')
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(real_data)
metadata.update_column(column_name="Middle Name", sdtype="categorical")
metadata.update_column(column_name="Full Name", sdtype="categorical")
metadata.update_column(column_name="Date of Birth", sdtype="datetime")
metadata.update_column(column_name="National ID", sdtype="categorical")
metadata.update_column(column_name="First Name", sdtype="categorical")
metadata.update_column(column_name="Last Name", sdtype="categorical")

metadata.visualize()

constraint = FixedCombinations(
    column_names = ['First Name', 'Middle Name', 'Last Name', 'Full Name']
)

synthesizer = SingleTablePreset(
    metadata,
    name='FAST_ML'
)

synthesizer.fit(data=real_data)

synthesizer.add_constraints(constraint)

synthesizer.sample(500)

Error
fixed combinations is not iterable

**Comment by srinify** [comment]
Hi @Pavan-Kalyan1432 which version of SDV are you running?

I noticed that you're missing the `constraint_class` in your constraint definition. I'd recommend comparing your code with the example code more closely: https://docs.sdv.dev/sdv/reference/constraint-logic/predefined-constraint-classes/fixedcombinations#example

```
my_constraint = {
    'constraint_class': 'FixedCombinations',
    'table_name': 'locations', # for multi table synthesizers
    'constraint_parameters': {
        'column_names': ['city', 'country']
    }
}

my_synthesizer.add_constraints(constraints=[
    my_constraint
])
```

Also I wanted to point out 2 more things:

- `FAST_ML` is deprecated, I'd recommend GaussianCopulaSynthesizer instead: https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/fast-ml-preset
- If the Full Name column is basically the First, Middle, and Last Name columns appended together, you probably don't want to include the Full Name column in your data, metadata, OR your constraint or you'll have SDV model it. You can always recreate this column in your synthetic data by appending the synthetic First, Middle, and Last name columns. Unless I'm mistaken about my assumption for the Full Name column :)

**Comment by srinify** [comment]
Hi @Pavan-Kalyan1432 closing this issue out since we haven't heard from you in 2 weeks and I saw that you posted some other follow up questions in Slack. Feel free to open a new issue if needed, thanks!
