### ISSUE TITLE
Pandas KeyError ("None of [Index([SELECTED_ENTITY_COLUMN], dtype='object')] are in the [columns]") when sampling from a PAR model

### ISSUE THREAD

**Issue by e-alizadeh** [sdv-dev/SDV#224]
* SDV version:  0.4.5
* Python version: 3.6
* Operating System: CentOS

### Description
I tried to run your notebook https://github.com/sdv-dev/SDV/blob/master/tutorials/timeseries_data/01_PAR_Model.ipynb 
But the step model.sample(1) will return a Pandas KeyError of 
"None of [Index(['Symbol'], dtype='object')] are in the [columns]"

### What I Did

The commands I ran were from the above notebook. When I ran model.sample(1), I got the following error. I first noticed this when I tested it on another dataset that I was working on and got the same message!

The Traceback error is
```
KeyError                                  Traceback (most recent call last)
<ipython-input-56-dce714f362b8> in <module>
----> 1 model.sample(1)

~/.conda/envs/apache_server_conda/lib/python3.6/site-packages/sdv/timeseries/base.py in sample(self, num_sequences, context, sequence_length)
    260                     context[column] = range(len(context))
    261 
--> 262         sampled = self._sample(context, sequence_length)
    263         return self._metadata.reverse_transform(sampled)
    264 

~/.conda/envs/apache_server_conda/lib/python3.6/site-packages/sdv/timeseries/deepecho.py in _sample(self, context, sequence_length)
    125                 columns=self._data_columns
    126             )
--> 127             group[self._entity_columns] = entity_values
    128             for column, value in zip(self._context_columns, context_values):
    129                 if column == self._sequence_index:

~/.conda/envs/apache_server_conda/lib/python3.6/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   3482             self._setitem_frame(key, value)
   3483         elif isinstance(key, (Series, np.ndarray, list, Index)):
-> 3484             self._setitem_array(key, value)
   3485         else:
   3486             # set column

~/.conda/envs/apache_server_conda/lib/python3.6/site-packages/pandas/core/frame.py in _setitem_array(self, key, value)
   3509                     self[k1] = value[k2]
   3510             else:
-> 3511                 indexer = self.loc._convert_to_indexer(key, axis=1)
   3512                 self._check_setitem_copy()
   3513                 self.loc._setitem_with_indexer((slice(None), indexer), value)

~/.conda/envs/apache_server_conda/lib/python3.6/site-packages/pandas/core/indexing.py in _convert_to_indexer(self, obj, axis, is_setter, raise_missing)
   1283                 # When setting, missing keys are not allowed, even with .loc:
   1284                 kwargs = {"raise_missing": True if is_setter else raise_missing}
-> 1285                 return self._get_listlike_indexer(obj, axis, **kwargs)[1]
   1286         else:
   1287             try:

~/.conda/envs/apache_server_conda/lib/python3.6/site-packages/pandas/core/indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1090 
   1091         self._validate_read_indexer(
-> 1092             keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
   1093         )
   1094         return keyarr, indexer

~/.conda/envs/apache_server_conda/lib/python3.6/site-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1175                 raise KeyError(
   1176                     "None of [{key}] are in the [{axis}]".format(
-> 1177                         key=key, axis=self.obj._get_axis_name(axis)
   1178                     )
   1179                 )

KeyError: "None of [Index(['Symbol'], dtype='object')] are in the [columns]"

```

**Comment by csala** [comment]
Hi @e-alizadeh thanks for reporting this!

This seems to be happening when using a `pandas` version lower than `1.1.0`, so we will update the dependency ranges accordingly and also improve the testing strategy to ensure that lower ends of the specified versions are actually supported.

Meanwhile, can you try upgrading `pandas` to a version higher than 1.1?

**Comment by e-alizadeh** [comment]
Hi @csala  thanks for the quick reply. 
I don't see any specific package requirements in README. So, I created a fresh conda environment with pandas 1.1.0 and sdv 0.4.5 (the environment file is attached). 
[environment.yaml.txt](https://github.com/sdv-dev/SDV/files/5461231/environment.yaml.txt)

Now, I have the following AttributeError when trying to load the timeseries data. 
![sdv](https://user-images.githubusercontent.com/30320825/97632020-4a16c980-1a08-11eb-8270-702b951d728d.png)

It will be good if you add a minimum package requirements file (or a sample environment file).

**Comment by csala** [comment]
> Hi @csala thanks for the quick reply.
> I don't see any specific package requirements in README. So, I created a fresh conda environment with pandas 1.1.0 and sdv 0.4.5 (the environment file is attached).
> [environment.yaml.txt](https://github.com/sdv-dev/SDV/files/5461231/environment.yaml.txt)
> 
> It will be good if you add a minimum package requirements file (or a sample environment file).

Thanks for your suggestion @e-alizadeh , but this is not necessary. The `sdv` package properly includes all the dependency specifications inside its `setup.py` file, which means that executing `pip install sdv` should be always enough without having to manually install anything else.

In this case, as I mentioned above, the problem is that the version range for the `pandas` dependency is too broad and includes versions that do not work, so the only thing needed here is to modify the range to ensure that we only cover supported versions.

> Now, I have the following AttributeError when trying to load the timeseries data.

Regarding the `AttributeError`, I opened the issue #227 to fix this.

If you look at the issue, you will see that you have an interim workaround there: Just import `urllib.request` before importing and executing the `load_timeseries_demo()` function.

```
$ python
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.request
>>> from sdv.demo import load_timeseries_demo
>>> data = load_timeseries_demo()
>>> 
```

**Comment by e-alizadeh** [comment]
@csala Thanks for the workaround. I can confirm that it works!
