### ISSUE TITLE
Metadata: Improve the error message load_tables is called without `path`

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#228]
When Metadata is created as a python object without passing `paths` and later on the `load_tables` method is called, it raises a `KeyError`. See #225 as an example.

This should be captured and enhanced with an easier to comprehend message that indicates how to solve the problem.

**Comment by npatki** [comment]
This issue is now obsolete, as with the new [**SDV 1.0 (Beta!)**](https://docs.sdv.dev/sdv) release, `paths` is no longer a valid parameter in the metadata.
