### ISSUE TITLE
Key column contains repeating values.

### ISSUE THREAD

**Issue by jalr4ever** [sdv-dev/SDV#2309]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:
* Python version:
* Operating System:

### Problem description
When I was using SDV for multi-table simulation today and specified a relationship, SDV reported an error saying the parent table's ID has duplicate values: "Error: Key column 'cust_no' contains repeating values." Does this mean SDV doesn't support duplicate values in the parent table's columns?

However, in real-world business tables, both the main table and the child table may have duplicate column values.

For example, in a multi-table simulation like the one below.

```python
import pandas as pd

# parent
data_main = {
    'id': [1, 2, 2, 3, 4],
    'value': ['A', 'B', 'C', 'D', 'E']
}
df_main = pd.DataFrame(data_main)

# child
data_b = {
    'id': [2, 2, 3, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
}
df_b = pd.DataFrame(data_b)
df_merged = df_main.merge(df_b, on='id', how='left')
```

### What I already tried

<Replace with a description of what you already tried and what is the behavior that you observe.
If possible, also add below the exact code that you are running.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by jalr4ever** [comment]
Or, in my current scenario, it's actually two tables where a regular column from the main table is joined with a regular column from the secondary table.It's not the ID column.

**Comment by srinify** [comment]
Hi there @jalr4ever 👋 

The SDV doesn't support repeating values for the _primary key_ column in a table. 

In SDV's metadata implementation:

-  An ID column can be the primary key for a table (e.g. `id` column for a `guests` table) or a non-primary key for a table (e.g. a foreign key column like `hotel_id` in a `guests` table)
- You can have multiple ID columns that are not the table's primary key but only one that _is_ the primary key, for a given table
- The ID column that is [set as the primary key](https://docs.sdv.dev/sdv/reference/metadata-spec/metadata-api#set_primary_key) for a table must contain a unique value for each row

If you have an ID column that's set as the primary key, you can [update the metadata ](https://docs.sdv.dev/sdv/reference/metadata-spec/metadata-api#remove_primary_key)for it to just act as a regular ID column. (But if you have a multi-table setup, keep in mind that you will need to set another column as the primary key in the parent table.)

Most databases require that primary keys be unique, so I'm wondering if your column that contains repeated values is better suited to be set to the non-primary key ID sdtype? Or is it possible that `cust_no` is actually a foreign key to another parent table?

> Or, in my current scenario, it's actually two tables where a regular column from the main table is joined with a regular column from the secondary table.It's not the ID column.

What are you hoping to achieve with this setup out of curiosity and can you tell me more about the properties of these 2 columns? Which of the 2 columns have only unique values, contain missing values, and do either of them have relationships with other columns in other tables besides these 2 tables?

We're actively researching more complex relationships between tables, so I'd love to learn more about your table patterns here!

**Comment by jalr4ever** [comment]
@srinify Hi, there!

> Most databases require that primary keys be unique, so I'm wondering if your column that contains repeated values is better suited to be set to the non-primary key ID sdtype? Or is it possible that `cust_no` is actually a foreign key to another parent table?

I can't set it to a non-primary key ID sdtype. As for now, I have a relationship using sdv code would be like:

```python
metadata.add_relationship(
    'table5',
    'table2',
    'cust_no',
    'cust_no'
)
```

which means  `cust_no` in `table_5` is the foreign key of `table_2`.

> 1. Do both of the columns contain repeating values, or just the one in the parent table? 
> 2. Which of the 2, if any, contain missing values
> 3. Can the column from the parent table also be joined with other table(s) in your data?
> 4. Do both columns represent the same concept in your domain?

1.  Both of the columns contain repeating values.
2.  Both of the table columns contain missing values.
3. Yes, it can.
4. Somehow we can say it's same concept but this column data are using in different domain system. For example, in a country, we as citizens have an ID number that is used and stored by different department systems within the country. Each department is a domain with its own business and data. But when collaborating between domains, it's necessary to use something like the ID numbers for cross-referencing and data analysis. 

Can SDV perform multi-table data synthesis for the ordinary columns and ordinary columns (many-to-many data column relationships) that I mentioned?

**Comment by jalr4ever** [comment]
> Can SDV perform multi-table data synthesis for the ordinary columns and ordinary columns (many-to-many data column relationships) that I mentioned?
@srinify Or does the commercial version of SDV LICENSE support this kind of multi-table data synthesis that I mentioned?

**Comment by npatki** [comment]
Hi @jalr4ever, I will let @srinify  answer your questions. 

Just piping in to say that SDV community version only supports one-to-many relationships. SDV Enterprise users can purchase a bundle that supports other types of relationships. We plan to support many-to-many in this bundle: https://docs.sdv.dev/sdv/reference/explore-sdv/cag-bundle

**Comment by srinify** [comment]
Hi @jalr4ever thanks for clarifying the schema pattern here -- many-to-many column relationship! As Neha mentioned, SDV Community doesn't support this out of the box.

**Workaround**

While this requires a bit more work on your end, one workaround would be to re-design the data architecture a bit to instead have a new parent table that just contains the primary key values (no missing or non-unique values) and then orient your 2 existing tables as child tables to this parent table.

This will work just fine because all requirements SDV expects are met:

- primary key columns are unique with no missing values
- foreign key columns don't have to be unique, can contain missing values, but must reference a valid value in the primary key column

**Comment by jalr4ever** [comment]
@npatki Hi, there. 

Does the SDV Business Edition support multi-table data synthesis to solve these issues?

> 1. Do both of the columns contain repeating values, or just the one in the parent table?
> 2. Which of the 2, if any, contain missing values
> 3. Can the column from the parent table also be joined with other table(s) in your data?
> 4. Do both columns represent the same concept in your domain?

1. Both of the columns contain repeating values.
2. Both of the table columns contain missing values.
3. Yes, it can.
4. Somehow we can say it's same concept but this column data are using in different domain system. For example, in a country, we as citizens have an ID number that is used and stored by different department systems within the country. Each department is a domain with its own business and data. But when collaborating between domains, it's necessary to use something like the ID numbers for cross-referencing and data analysis.

**Comment by jalr4ever** [comment]
@npatki I reviewed [CAG](https://docs.sdv.dev/sdv/reference/constraints/constraint-augmented-generation-cag), but I'm unsure how to address my issue. 

Here’s my ER diagram:
![image](https://github.com/user-attachments/assets/168a745b-fae3-4d33-9713-ad8a224fdf1c)

Can you help me determine if SDV Enterprise can synthesize my multi-table data?

**Comment by npatki** [comment]
Hi @jalr4ever, thanks for the schema diagram. 

Just to be clear, the CAG bundle does not _currently_ have the ability to address many-to-many relationships but it is something we plan add the future. So you would not see any patterns right now that would help you to address this. In the future, the CAG bundle **will be able to support many-to-many relationships** like in the schema that you are sharing.

If you'd like to continue on SDV Community in the meantime, you can use the workaround that @srinify specified in [his earlier comment](https://github.com/sdv-dev/SDV/issues/2309#issuecomment-2501801809). Thanks.

**Comment by jalr4ever** [comment]
@npatki Thanks for reply!
