### ISSUE TITLE
TypeError: cannot astype a datetimelike from [datetime64[ns]] to [int32] when using load_timeseries_demo()

### ISSUE THREAD

**Issue by e-alizadeh** [sdv-dev/SDV#232]
* SDV version: 0.4.5
* Python version: 3.8.5
* Operating System: Windows 10

### Description
Trying to run the timeseries (PAR Model) notebook tutorial. But get a TypeError from Pandas. 
I'm using pandas 1.1.3. 
 
A few days ago I raised a similar issue that @csala resolved.  
@csala This time, it's in a completely different system on a different computer. Not to mention that I had lots of problems installing SDV from even a fresh conda environment. After fixing that and trying to run the notebook, I'm getting another Pandas related error.  

### What I Did
Tried to run model.fit(data) where the data = load_timeseries_demo() function, I'm getting the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-b5876d4ef8a6> in <module>
----> 1 model.fit(data)

~\.conda\envs\my_env2\lib\site-packages\sdv\timeseries\base.py in fit(self, timeseries_data)
    191                      self._metadata.name, timeseries_data.shape)
    192         if not self._metadata_fitted:
--> 193             self._metadata.fit(timeseries_data)
    194 
    195         LOGGER.debug('Transforming table %s; shape: %s',

~\.conda\envs\my_env2\lib\site-packages\sdv\metadata\table.py in fit(self, data)
    485 
    486         LOGGER.info('Fitting HyperTransformer for table %s', self.name)
--> 487         self._fit_hyper_transformer(constrained, extra_columns)
    488         self.fitted = True
    489 

~\.conda\envs\my_env2\lib\site-packages\sdv\metadata\table.py in _fit_hyper_transformer(self, data, extra_columns)
    383         transformers_dict = self._get_transformers(dtypes)
    384         self._hyper_transformer = rdt.HyperTransformer(transformers=transformers_dict)
--> 385         self._hyper_transformer.fit(data[list(dtypes.keys())])
    386 
    387     @staticmethod

~\.conda\envs\my_env2\lib\site-packages\rdt\hyper_transformer.py in fit(self, data)
    135         for column_name, transformer in self._transformers.items():
    136             column = data[column_name]
--> 137             transformer.fit(column)
    138 
    139     def transform(self, data):

~\.conda\envs\my_env2\lib\site-packages\rdt\transformers\datetime.py in fit(self, data)
     77             data = pd.Series(data)
     78 
---> 79         transformed = self._transform(data)
     80         self.null_transformer = NullTransformer(self.nan, self.null_column, copy=True)
     81         self.null_transformer.fit(transformed)

~\.conda\envs\my_env2\lib\site-packages\rdt\transformers\datetime.py in _transform(self, datetimes)
     57         nulls = datetimes.isnull()
     58         integers = np.zeros(len(datetimes))
---> 59         integers[~nulls] = datetimes[~nulls].astype(int).astype(float).values
     60         integers[nulls] = np.nan
     61 

~\.conda\envs\my_env2\lib\site-packages\pandas\core\generic.py in astype(self, dtype, copy, errors)
   5544         else:
   5545             # else, only a single dtype is given
-> 5546             new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
   5547             return self._constructor(new_data).__finalize__(self, method="astype")
   5548 

~\.conda\envs\my_env2\lib\site-packages\pandas\core\internals\managers.py in astype(self, dtype, copy, errors)
    593         self, dtype, copy: bool = False, errors: str = "raise"
    594     ) -> "BlockManager":
--> 595         return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
    596 
    597     def convert(

~\.conda\envs\my_env2\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, align_keys, **kwargs)
    404                 applied = b.apply(f, **kwargs)
    405             else:
--> 406                 applied = getattr(b, f)(**kwargs)
    407             result_blocks = _extend_blocks(applied, result_blocks)
    408 

~\.conda\envs\my_env2\lib\site-packages\pandas\core\internals\blocks.py in astype(self, dtype, copy, errors)
   2098 
   2099         # delegate
-> 2100         return super().astype(dtype=dtype, copy=copy, errors=errors)
   2101 
   2102     def _can_hold_element(self, element: Any) -> bool:

~\.conda\envs\my_env2\lib\site-packages\pandas\core\internals\blocks.py in astype(self, dtype, copy, errors)
    593             vals1d = values.ravel()
    594             try:
--> 595                 values = astype_nansafe(vals1d, dtype, copy=True)
    596             except (ValueError, TypeError):
    597                 # e.g. astype_nansafe can fail on object-dtype of strings

~\.conda\envs\my_env2\lib\site-packages\pandas\core\dtypes\cast.py in astype_nansafe(arr, dtype, copy, skipna)
    937             return arr.astype(dtype)
    938 
--> 939         raise TypeError(f"cannot astype a datetimelike from [{arr.dtype}] to [{dtype}]")
    940 
    941     elif is_timedelta64_dtype(arr):

TypeError: cannot astype a datetimelike from [datetime64[ns]] to [int32]
```

**Comment by csala** [comment]
Hello @e-alizadeh 

I'm afraid this seems to be exactly the same issue that you reported on #217, which was also reported on #205 and #218.

Unfortunately, the response is exactly the same too: SDV is not fully supported on Windows systems, so at the moment the only solutions that exist are to switch to a GNU/Linux or macOS based system. Also note that [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) is a valid alternative too, and it should be fully compatible with your current Windows system.

**Comment by e-alizadeh** [comment]
@csala FYI, WSL hasn't worked either for me even when trying to install it from a fresh environment!  
Even tried outside conda. I just installed everything using pip in WSL. 
Although I like the idea of generating fake time series data using this package, it's just taking too much time trying to figure out what's going on. 

Providing clear dependency requirements would be great. For example, that pandas version of > 1.1.0 is clearly a requirement for using the PAR model. I think a similar issue exists for Numpy as well.

**Comment by csala** [comment]
I'm sorry to hear that it did not work for you, but I'm sure that might be because of the way you install it.

To make it work inside WSL, after installing `python3`, `python3-pip` and `python3-virtualenv` using `apt` inside your WSL, all you would need to do is:

1. Create a clean `virtualenv`
```bash
$ virtualenv sdv-venv
```

2. Activate the `virtualenv`
```bash
$ source sdv-venv/bin/activate
```

3. pip install sdv
```bash
$ pip install sdv
```

And you are ready to go!

So, if it is not working for you, it must be because you are doing additional steps or using a different environment setup that is interfering with the `sdv` dependencies and breaking your working environment.

Would you mind trying it this way?

Regarding the clear dependency requirements, as I mentioned [here](https://github.com/sdv-dev/SDV/issues/224#issuecomment-719450301), **you do not need to install anything other than `sdv`**, because the `sdv` dependencies are listed inside the [setup.py file](https://github.com/sdv-dev/SDV/blob/d0ae239f8819d6a15ed14f8742f34229edf7a0d6/setup.py#L14) and they are automatically installed for you when you execute the `pip install sdv` command.

I hope all this clarifies your doubts and helps you run SDV successfully!
