### ISSUE TITLE
Anonymizing PIIs with HMA1?

### ISSUE THREAD

**Issue by gennsev** [sdv-dev/SDV#238]
### Description

I wonder if we can use the `HMA1` model for relational databases alogside the [faker](https://faker.readthedocs.io/en/master/index.html) to anonymize PIIs like we can do with `GaussianCopula`.

Remembering how it's done with single table data:
```Python
pii_fields={'Name2': 'last_name', 'Name1':'first_name'}
model = GaussianCopula(primary_key='emp_no',anonymize_fields=pii_fields)
model.fit(employees)
synthetic_employees = model.sample()
```
Trying something like that:
```Python
model = HMA1(metadata, anonymize_fields=pii_fields)
```
Yields the following error
```Python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-6afda84499f9> in <module>
      3 pii_fields = {'dept_name':'last_name'}
      4 
----> 5 model = HMA1(metadata, anonymize_fields=pii_fields)
      6 tables = {
      7     'departments': departments,

TypeError: __init__() got an unexpected keyword argument 'anonymize_fields'
```

Which is actually expected given that there is no mention about it on the documentation.

**Comment by csala** [comment]
Hi @gennsev 

The faker-based anonymization can be used with HMA1, but at the moment the setup happens at the Metadata level.

To use it, when you create the tables in your metadata, you need to specify the following two properties in the fields that you want to anonymize:
- `pii: True`
- `pii_category: <the faker category>`

You can see what it looks like [here, in the Metadata JSON Schema page](https://sdv.dev/SDV/developer_guides/sdv/metadata.html#categorical-fields-data-anonymization).

For example, the JSON for an example like the one you indicated would look like this:

```python
{
    'tables': {
        'departments': {
            ...
        },
        'employees': {
            'fields': {
                'Name1': {
                    'type': 'categorical',
                    'pii': True,
                    'pii_category': 'first_name',
                },
                'Name2': {
                    'type': 'categorical',
                    'pii': True,
                    'pii_category': 'last_name',
                },
                ...
            }
        },
    }
}
```

Also, bear in mind that if you are creating the metadata directly from python using the `Metadata` class, you can [pass additional properties for the fields that you want to anonymize](https://sdv.dev/SDV/user_guides/relational/relational_metadata.html#add-a-table-specifying-field-properties), something like this:

```python
metadata.add_table(
    name='employees',
    ...
    fields_metadata={
        'Name1': {
            'type': 'categorical',
            'pii': True,
            'pii_category': 'first_name',
        },
        'Name2': {
            'type': 'categorical',
            'pii': True,
            'pii_category': 'last_name',
        },
    }
)
```

**Comment by gennsev** [comment]
Thanks @csala.
Indeed, I missed it on the documentation. 
Thanks.
