### ISSUE TITLE
ValueError: There are non-numerical values in your data.

### ISSUE THREAD

**Issue by gennsev** [sdv-dev/SDV#241]
SDV version: 0.4.5
Python version: 3.8.5
Operating System: Ubuntu 20.04.1 LTS

### Description

I'm having an error message with I try to fit my model using a single table that contains 16-digit credit card numbers in one of the columns.
I believe it might be related to the conversion of the 16-digit credit card number to a numerical value, from what I could investigate at the Copulas code documentation [here](https://sdv.dev/Copulas/_modules/copulas.html).

In the following sections I'm pasting the error message, the 5 first lines of the table that provokes the issue, and a look-alike table that does *not* induce that error (also with a 16-digit credit card value in the last column, but with a separator between each 4 digits).

### The Error:

```
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/service/async_routines.py", line 233, in synthetic_data_generator
    sample = synthetic_data.single_table_gen(list(tables.values())[0])
  File "/service/synthetic_data/generator.py", line 32, in single_table_gen
    model.fit(table)
  File "/usr/local/lib/python3.8/dist-packages/sdv/tabular/base.py", line 112, in fit
    self._fit(transformed)
  File "/usr/local/lib/python3.8/dist-packages/sdv/tabular/copulas.py", line 272, in _fit
    self._model.fit(table_data)
  File "/usr/local/lib/python3.8/dist-packages/copulas/__init__.py", line 211, in decorated
    raise ValueError('There are non-numerical values in your data.')
ValueError: There are non-numerical values in your data.
```
### The Table:
The table I'm using to fit looks like that:
```
emp_no,birth_date,first_name,last_name,gender,hire_date,card
201134,6/22/1952,Johann,Sommer,F,6/26/1991,5872452185244528
465888,3/14/1953,Joseph,Robertson,M,10/4/1990,5872452185244528
26376,5/10/1957,Yohann,Stweard,M,1/11/1986,5872452185244528
491124,9/12/1956,Mary,Stone,F,2/1/1990,5872452185244528
```

### A "Solution":
I've also found out that this error does *not* happen when I have a table like that:  
(also with a 16-digit credit card value in the last column, but with a separator between each 4 digits)
```
emp_no,birth_date,first_name,last_name,gender,hire_date,card
201134,6/22/1952,Johann,Sommer,F,6/26/1991,5872-4521-8524-4528
465888,3/14/1953,Joseph,Robertson,M,10/4/1990,5872-4521-8524-4528
26376,5/10/1957,Yohann,Stweard,M,1/11/1986,5872-4521-8524-4528
491124,9/12/1956,Mary,Stone,F,2/1/1990,5872-4521-8524-4528
```

So I do have the impression that it is related to the large numbers on the last column.

**Comment by csala** [comment]
Hi @gennsev!

You are right, the problem is that if there are on dashes the cc numbers get interpreted as integers, which end up being too large for Copulas to handle them properly.

The way to solve this without having to alter the values themselves adding dashes is to specify them as `categorical` using the `field_types` argument:

```python
form sdv.tabular import <a tabular model class>

field_types = {
    'card': {
        'type': 'categorical'
    }
}
model = <a tabular model class>(..., field_types=field_types)
model.fit(data)
```

Can you try this?

**Comment by gennsev** [comment]
Your solution works @csala, thanks!
However, that reaises a question: 
Will defining this column's field type this way affect the anonimizaiton of this field? I'm using the [faker](https://faker.readthedocs.io/en/master/index.html) to create synthetic credit card numbers.

**Comment by csala** [comment]
No, it should not affect, though there's actually one thing that you need to keep in mind: If you have a lot of unique values, setting it as a `categorical` may produce a lot of extra columns when the `one_hot_encoding` transformer is used, which is true by default.

If you want to avoid this, you should also change the field transformer to something else like `categorical` or `categorical_fuzzy`.

So, altogether, using GaussianCopula and including anonymizing the field as a visa card, would look something like this:

```python
from sdv.tabular import GaussianCopula

field_types = {
    'card': {
        'type': 'categorical'
    }
}
field_transformers = {
    'card': 'categorical'
}
anonymize = {
    'card': ('credit_card_number', 'visa')
}
model = GaussianCopula(
    field_types=field_types,
    field_transformers=field_transformers,
    anonymize_fields=anonymize
)
model.fit(df)
```

**Comment by csala** [comment]
The question has already been responded, so this can be closed.
