### ISSUE TITLE
Synthetizing a highly imbalanced dataset.

### ISSUE THREAD

**Issue by gentrexha** [sdv-dev/SDV#244]
* SDV version: 0.4.5
* Python version: 3.8.5
* Operating System: Windows 10 64bit

### Description

Hello everyone, I hope this is the right channel to ask. I'm having trouble synthetizing a highly imbalanced dataset, with 2 classes 280k 0s and 500~ 1s. Every time I try to synthetize with the GaussianCopula, I end up with a dataset with only 0 in the Class. What are some alternatives I can try? 

### What I Did

I've tried using different distributions but didn't had any success and couldn't figure out how to use the Constraints properly.

My dataset source: https://www.kaggle.com/mlg-ulb/creditcardfraud?select=creditcard.csv

```
def check_column_counts(data):
    counts = data["Class"].value_counts()
    try:
        if counts[1] > 260:
            return True
        else:
            return False
    except:
        return False

def generate_sdv(input_data):
    input_df = pd.read_csv("creditcard.csv")
    real_data = input_df.iloc[:, -1:]
    
    check_column_counts_constraint = ColumnFormula(
        column='Class',
        formula=check_column_counts,
        handling_strategy='reject_sampling'
    )
   
    constraints = [check_column_counts_constraint]
    model = GaussianCopula(constraints=constraints)
    model.fit(real_data)
    synthetic_data = model.sample()
    synthetic_data.to_csv("sample.csv")
```

**Comment by csala** [comment]
Hi @gentrexha 

Yes, that level of imbalance is hard to work with. However, setting the right distributions should be enough, in this case.

I tried downloading the data which you point at and by setting a `gamma` distribution on the `Class` column the `GaussianCopula` seems to be successful in learning to generate 1s alongside the 0s in a close enough proportion:

```python
import pandas as pd
from sdv.tabular import GaussianCopula

real_data = pd.read_csv("creditcard.csv")

model = GaussianCopula(distribution={'Class': 'gamma'})
model.fit(real_data)
synthetic = model.sample()
```

After this, the `synthetic` data gets a 1/0 ratio of around 0.2~0.3%.

If you wanted to push it further and use `Constraints` to get closer to the 0.17% of the real data, what I recommend is to use a `CustomConstraint` to discard the overpopulated class. In this case, since the sampled ratio is higher than the target, we could discard a few 1s to lower the ratio to the expected value.

The implementation could be something like this:

```python
import pandas
from sdv.constraints import CustomConstraint

target_ratio = real_data.Class.mean()
tolerance = 0.0001

def is_valid(data):
    ratio = data.Class.mean()
    size = len(data)
    valid = pd.Series([True] * size, index=data.index)
    diff = ratio - target_ratio
    if abs(diff) > tolerance:
        # discard 1s if positive diff, 0 otherwise
        class_to_discard = int(diff > 0)
        class_rows = data[data.Class == class_to_discard]
        
        # randomly select the rows that we will discard
        num_to_discard = int((ratio - target_ratio) * size)
        to_discard = class_rows.sample(num_to_discard)
        
        # Set as False the selected values
        valid.loc[to_discard.index] = False
    
    return valid.values

my_constraint = CustomConstraint(is_valid=is_valid)

model = GaussianCopula(
    distribution={'Class': 'gamma'},
    constraints=[my_constraint]
)
```

I hope this helps!

**Comment by gentrexha** [comment]
This helps a lot. Thank you!

**Comment by gentrexha** [comment]
> I tried downloading the data which you point at and by setting a `gamma` distribution on the `Class` column the `GaussianCopula` seems to be successful in learning to generate 1s alongside the 0s in a close enough proportion:
> 
> ```python
> import pandas as pd
> from sdv.tabular import GaussianCopula
> 
> real_data = pd.read_csv("creditcard.csv")
> 
> model = GaussianCopula(distribution={'Class': 'gamma'})
> model.fit(real_data)
> synthetic = model.sample()
> ```

This generates values 2,3,4 (`SDV {0: 283843, 1: 870, 2: 81, 3: 11, 4: 2}`) in the Class for me. Is there anyway to circumvent this without having to replace values manually?

**Comment by JulienGervai** [comment]
Hello, 

you can try to set some Constraints. For exemple : 
```
min_cols = {col : min(data[col]) for col in cols}

min_cols = {col : min(data[col]) for col in cols}

def is_valid(data):   
    valid = [True for i in range(len(data))]
    for col in cols:
        bool_col_min = (data[col] >= min_cols[col])
        bool_col_max = (data[col] <= max_cols[col])
        for j in range(len(data)):
            valid[j] = valid[j] and bool_col_min.tolist()[j] and bool_col_max.tolist()[j]

    return np.asarray(valid)

from sdv.constraints import CustomConstraint

valid_limits = CustomConstraint(
    is_valid = is_valid,

from sdv.tabular import CTGAN

model = CTGAN(epochs = 2000, verbose = True, constraints = [valid_limits])
model.fit(train)
```

With this Constaint the model.sample() will only return values in the interval between the min and the max of the original data ( [0,1] in your exemple)

**Comment by csala** [comment]
Hi @gentrexha were you able to fix the problem using @JulienGervai's solution?

To simplify a bit on his proposal, you could also just add an `is_valid` constraint that discards rows for which `Class` is not 0 or 1:

```python
import pandas as pd
from sdv.constraints import CustomConstraint
from sdv.tabular import GaussianCopula

real_data = pd.read_csv("creditcard.csv")

def zero_or_one(data):
    return data.Class.isin([0, 1])

model = GaussianCopula(
    distribution={'Class': 'gamma'},
    constraints=[CustomConstraint(is_valid=zero_or_one)]
)
model.fit(real_data)

synthetic = model.sample()
```
