### ISSUE TITLE
Integer values generated does not follow a specific structure.

### ISSUE THREAD

**Issue by abhisheknagar1983** [sdv-dev/SDV#247]
* SDV version: 0.4.5
* Python version: 3.6.9
* Operating System: Linux RHEL

### Description

In one of the scenario for synthetic data generation we have some integer columns which follows certain specific structure (e.g column should be 6/8 digit long).
But for SDV generated data does not follow any kind of structure for those integer columns. 

Do we have any configuration in SDV which can be used to force SDV to follow specify structure as per training data set? 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by csala** [comment]
Hi @abhisheknagar1983 

Just to make sure that I understand the question: Your target is to generate integer values with the requirement that they are between 6 and 8 digits long? So, in other words, they may stay between 100000 and 99999999?

**Comment by Wim65** [comment]
Hi,

Indeed. The format is context dependant. Some of these numbers are CustomerIDs having fixed length 8 , numeric. Or ContractIDs having fixed length 10 numeric.   So CustomerID would be like 00345839 , ContractID like 4394328013

**Comment by Wim65** [comment]
There us a second issue here that these being ID's they have to be  
generate unique. Perhaps that can be solved by putting a constraint on them ?
