### ISSUE TITLE
For categorical column highly imbalanced categories are being lost in the generated data.

### ISSUE THREAD

**Issue by abhisheknagar1983** [sdv-dev/SDV#248]
* SDV version: 0.4.5
* Python version: 3.6.9
* Operating System: Linux RHEL

### Description
In one of the scenario for synthetic data generation using SDV, we have a dataset in which a columns have some categories which is highly imbalanced (1% Approx).

In SDV generated dataset, those highly imbalanced  categories are being ignored completely. Hence the generated data looses its business purpose (due to lack of variations).

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @abhisheknagar1983, thanks for filing. The team is actively thinking about improvements to the modeling process. 

There are two possible ways you can fix this:

1. Try different categorical transformers for the model. Eg. the [GaussianCopula model](https://sdv.dev/SDV/api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.html#sdv.tabular.copulas.GaussianCopula) has 4 options for the `categorical_transformer`. It may be best to use `categorical_fuzzy`, as it creates continuous distributions that are more suited for copulas-based modeling.
2. Use [conditional sampling](https://sdv.dev/SDV/api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.sample_conditions.html) to get the exact proportions of the categories you need.

BTW, as hinted by 1, the quality of categorical data depends on the transformers. You'll likely see more improvements in this area after we integrate with the new [RDT library](https://docs.sdv.dev/rdt). I'll keep this issue open until then.

**Comment by npatki** [comment]
Hi everyone, I'm closing off this issue because we now have RDT transformers that are able to better handle imbalanced categories such as the [LabelEncoder](https://docs.sdv.dev/rdt/transformers-glossary/categorical/labelencoder).

We will also soon be including additional options for licensed SDV users.
