### ISSUE TITLE
Issues on running 01_PAR_Model tutorial code

### ISSUE THREAD

**Issue by CindyQi7788** [sdv-dev/SDV#253]
* SDV version: I downloaded it from the github repo and pip install sdv
* Python version: Python 3.6.10 :: Anaconda, Inc
* Operating System: I run it on AWS SageMaker 

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

I tried to run the 01_PAR_Model.ipynb inside the tutorial folder, 
But after running cell 7 as below, but got errors as below.

```
from sdv.timeseries import PAR

model = PAR(
    entity_columns=entity_columns,
    context_columns=context_columns,
    sequence_index=sequence_index,
)
model.fit(data)
```

**Error Message:**

```
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py:547: RuntimeWarning: invalid value encountered in sqrt
  sk = 2*(b-a)*np.sqrt(a + b + 1) / (a + b + 2) / np.sqrt(a*b)
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/scipy/optimize/minpack.py:162: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py:4798: RuntimeWarning: divide by zero encountered in true_divide
  return c**2 / (c**2 - n**2)
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:2407: RuntimeWarning: invalid value encountered in double_scalars
  Lhat = muhat - Shat*mu
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/scipy/optimize/minpack.py:162: RuntimeWarning: The number of calls to function has reached maxfev = 600.
  warnings.warn(msg, RuntimeWarning)
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
```

Then I tried to run cell 8:

```
new_data = model.sample(1)
```

**Error Message is**

```
KeyError: "None of [Index(['Symbol'], dtype='object')] are in the [columns]"
```

Please let me know what is wrong for it is just a demo code in the tutorial folder that I downloaded from the github and without changing anything yet. 

Looking forward to your reply. Thank you very much
Xin

**Comment by csala** [comment]
Hi @CindyQi7788 

Thanks for reporting this.

I suspect the error is the same one that was reported in issue #224 , which we found was caused by the pandas version being to small.

Would you mind trying any of these two options?

1. Install a newer version of pandas:
    ```bash
    pip install 'pandas>=1.1'
    ```
2. Install the latest SDV release candidate (which already has `pandas>=1.1` as a dependency):
    ```bash
    pip install sdv==0.4.6.dev2
    ```

**Comment by CindyQi7788** [comment]
The issue is resolved. Thank you so much for quick response!!
