### ISSUE TITLE
Error (list object does no attribute __Name__) while defining constraints

### ISSUE THREAD

**Issue by abhisheknagar1983** [sdv-dev/SDV#257]
* SDV version: 0.4.5
* Python version: 3.6.9
* Operating System: Linux (RHEL)

### Description

We wanted to define two constraints on our one of the table.
1) Unique column constrains (on one column)
2) Greater then constrains (using two date columns)

During the training we are getting the below error.

Attribute Error: 'list'  object has no object '__name__'

### What I Did

1) Define the constraints:

```
unique_cols = UniqueCombinations(
    columns=['col1'],
    handling_strategy='reject_sampling'
)
             
date_constraint = GreaterThan(
    low='col2',
    high='col3',
    handling_strategy='reject_sampling'
)
             
my_constraints = [
    unique_cols,
    date_constraint
    
]
```
model_kwargs = {
        'model': GaussianCopula,
        'model_kwargs': {
            'default_distribution': 'gaussian',
            'constraints':my_constraints,
        }
}
```
```
sdv = SDV(model_kwargs=model_kwargs)
```
Below is the error:

```
INFO:sdv.relational.hma:Modeling Table_1
INFO:sdv.relational.hma:Fitting GaussianCopula for table Table_1; shape: (2492, 5)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-c4d6b23fe97f> in <module>
      2 
      3 start_time = time.time()
----> 4 sdv.fit(metadata_dict, tables=tables)
      5 end_time = time.time()
      6 

/usr/local/second-app-dir/venvpy3/lib/python3.6/site-packages/sdv/sdv.py in fit(self, metadata, tables, root_path)
     58         """
     59         self._model_instance = self._model(metadata, root_path, **self._model_kwargs)
---> 60         self._model_instance.fit(tables)
     61 
     62     def sample(self, table_name=None, num_rows=None,

/usr/local/second-app-dir/venvpy3/lib/python3.6/site-packages/sdv/relational/base.py in fit(self, tables)
     61                 indicated in ``metadata``. Defaults to ``None``.
     62         """
---> 63         self._fit(tables)
     64         self.fitted = True
     65 

/usr/local/second-app-dir/venvpy3/lib/python3.6/site-packages/sdv/relational/hma.py in _fit(self, tables)
    185         for table_name in self.metadata.get_tables():
    186             if not self.metadata.get_parents(table_name):
--> 187                 self._model_table(table_name, tables)
    188 
    189         LOGGER.info('Modeling Complete')

/usr/local/second-app-dir/venvpy3/lib/python3.6/site-packages/sdv/relational/hma.py in _model_table(self, table_name, tables, foreign_key)
    160         LOGGER.info('Fitting %s for table %s; shape: %s', self._model.__name__,
    161                     table_name, table.shape)
--> 162         model = self._model(**self._model_kwargs, table_metadata=table_meta)
    163         model.fit(table)
    164         self._models[table_name] = model

/usr/local/second-app-dir/venvpy3/lib/python3.6/site-packages/sdv/tabular/copulas.py in __init__(self, field_names, field_types, field_transformers, anonymize_fields, primary_key, constraints, table_metadata, distribution, default_distribution, categorical_transformer)
    221             anonymize_fields=anonymize_fields,
    222             constraints=constraints,
--> 223             table_metadata=table_metadata
    224         )
    225 

/usr/local/second-app-dir/venvpy3/lib/python3.6/site-packages/sdv/tabular/base.py in __init__(self, field_names, field_types, field_transformers, anonymize_fields, primary_key, constraints, table_metadata)
     78                 if arg:
     79                     raise ValueError(
---> 80                         'If table_metadata is given {} must be None'.format(arg.__name__))
     81 
     82             if isinstance(table_metadata, dict):

AttributeError: 'list' object has no attribute '__name__'
```

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by JagdishKolhe** [comment]
Try  as follows


model_kwargs = {
'model': GaussianCopula(constraints=my_constraints),
'model_kwargs': {
'default_distribution': 'gaussian',
}
}

**Comment by npatki** [comment]
Hello, it seems as if this question has been answered and there hasn't been further discussion for a while. I'll close this issue off but feel free to re-open if there are further updates.
