### ISSUE TITLE
Questions about data leaks

### ISSUE THREAD

**Issue by JulienGervai** [sdv-dev/SDV#264]
Hello everybody,

I have done much tests with CTGAN and I noticed that to have a good synthetic data (distributions very close to the real data, correlation and good results to ML tests), we need to train the GAN a lot (50 000, 75 000, 100 000... epochs).
But I am worried that the GAN can be train too much and we start generating data very (too much) close to the real data. Does anyone has done some tests about this issue ?
Also, I am worried outliers can be a problem. Does the model have tendencies to generate outliers closer than "normal" points ?

Thank you, I would very appreciate if someone have some answers.

**Comment by fealho** [comment]
Hi @JulienGervai, I believe your concern has been addressed in our latest release, with the addition of Privacy Metrics. You can read more about it in our [user guide](https://sdv.dev/SDV/user_guides/evaluation/single_table_metrics.html) and the appropriate PR (https://github.com/sdv-dev/SDMetrics/pull/55).
