### ISSUE TITLE
Does GaussianCopula use GPU?

### ISSUE THREAD

**Issue by maskaravivek** [sdv-dev/SDV#268]
* SDV version: 0.5.0
* Python version: 3.x 
* Operating System: Linux (Google Colab)

### Description

I am trying to `fit` a dataset with 10000 rows using `GaussianCopula`. Google Colab gives me a warning that GPUs are not being utilized. 

### What I Did

I checked past issues/docs to see if there's anything that needs to be done to enable GPUs. Does SDV not support training using GPU?

**Comment by Baukebrenninkmeijer** [comment]
GaussianCopula does not support GPU currently. Only the deep learning based models (CTGAN, CopulaGAN) support GPUs.
