### ISSUE TITLE
Applying value constraints in PAR model

### ISSUE THREAD

**Issue by HarisNaveed17** [sdv-dev/SDV#280]
* SDV version: 0.5.0
* Python version: 3.6.9
* Operating System: Linux 18.04 (running model on Google Colab)

### Description
Hello,
I am trying to use the PAR model to generate time series data. 

It did generate data, but the new data featured a lot of negative values whereas all my columns are positive. While this can be fixed in the tabular case by manually choosing distributions in the CopulaGAN, I'm not sure how I can do that here, since I don't see support for that in the PAR model.

The final loss value after 300 epochs is also extremely high (about -737) so I guess the model isn't learning well to begin with. 
I'm using a single entity column with no context columns, and a datetime value sequence column. 

Thank you!

**Comment by npatki** [comment]
There isn't currently a way to set min/max bounds for the PARModel. Let's use #745 to discuss this feature request.
