### ISSUE TITLE
Unable to fit training data

### ISSUE THREAD

**Issue by Aditya-Agarwal-018** [sdv-dev/SDV#283]
* SDV version: 0.5.0
* Python version: 3.8.5
* Operating System:

### Description

Unable to fit the training data with CopulaGAN

### What I Did

-------------------------------CODE---------------------------------------------
import pandas as pd
from sdv.tabular import CopulaGAN
X_train = pd.read_csv(file, sep=';')
model = CopulaGAN()
model.fit(X_train)                            
-------------------------------CODE---------------------------------------------

**I get the following type error:**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-07760c73e0e8> in <module>
      4 
      5 model = CopulaGAN()
----> 6 model.fit(X_train)

~\.conda\envs\py3_jupyter\lib\site-packages\sdv\tabular\base.py in fit(self, data)
    113 
    114         LOGGER.debug('Fitting %s model to table %s', self.__class__.__name__, self._metadata.name)
--> 115         self._fit(transformed)
    116 
    117     def get_metadata(self):

~\.conda\envs\py3_jupyter\lib\site-packages\sdv\tabular\copulagan.py in _fit(self, table_data)
    194         table_data = self._ht.fit_transform(table_data)
    195 
--> 196         super()._fit(table_data)
    197 
    198     def _sample(self, num_rows):

~\.conda\envs\py3_jupyter\lib\site-packages\sdv\tabular\ctgan.py in _fit(self, table_data)
    119                 Data to be learned.
    120         """
--> 121         self._model = self._CTGAN_CLASS(
    122             embedding_dim=self._embedding_dim,
    123             gen_dim=self._gen_dim,

TypeError: __init__() got an unexpected keyword argument 'gen_dim'
-----------------------------------------------------------------------------------------------------------

Could someone help me out?

Thanks!

**Comment by Aditya-Agarwal-018** [comment]
Solved it

**Comment by Aditya-Agarwal-018** [comment]
Hi, 

Now I ran into another problem:
-------------------CODE-------------------------------------------------
import pandas as pd
from sdv.tabular import CopulaGAN
X_train     = pd.read_csv(file, sep=';')
model      = CopulaGAN()
model.fit(X_train)
-------------------CODE-------------------------------------------------


I get the following error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-180644a42f0e> in <module>
      2 
      3 model = CopulaGAN()
----> 4 model.fit(X_global)

c:\users\agd7fe\.conda\envs\sdv\lib\site-packages\sdv\tabular\base.py in fit(self, data)
    113 
    114         LOGGER.debug('Fitting %s model to table %s', self.__class__.__name__, self._metadata.name)
--> 115         self._fit(transformed)
    116 
    117     def get_metadata(self):

c:\users\agd7fe\.conda\envs\sdv\lib\site-packages\sdv\tabular\copulagan.py in _fit(self, table_data)
    198         table_data = self._ht.fit_transform(table_data)
    199 
--> 200         super()._fit(table_data)
    201 
    202     def _sample(self, num_rows):

c:\users\agd7fe\.conda\envs\sdv\lib\site-packages\sdv\tabular\ctgan.py in _fit(self, table_data)
     51         self._model.fit(
     52             table_data,
---> 53             discrete_columns=categoricals
     54         )
     55 

c:\users\agd7fe\.conda\envs\sdv\lib\site-packages\ctgan\synthesizers\ctgan.py in fit(self, train_data, discrete_columns, epochs)
    252             train_data,
    253             self._transformer.output_info_list,
--> 254             self._log_frequency)
    255 
    256         data_dim = self._transformer.output_dimensions

c:\users\agd7fe\.conda\envs\sdv\lib\site-packages\ctgan\data_sampler.py in __init__(self, data, output_info, log_frequency)
     41         # Prepare an interval matrix for efficiently sample conditional vector
     42         max_category = max(
---> 43             [column_info[0].dim for column_info in output_info
     44              if is_discrete_column(column_info)])
     45 

ValueError: max() arg is an empty sequence
--------------------------------------------------------------------------------------------------------

Can someone please give a hint?

Thanks!

**Comment by csala** [comment]
> Hi,
> 
> Now I ran into another problem:
> -------------------CODE-------------------------------------------------
> import pandas as pd
> from sdv.tabular import CopulaGAN
> X_train = pd.read_csv(file, sep=';')
> model = CopulaGAN()
> model.fit(X_train)
> -------------------CODE-------------------------------------------------
> ...
> c:\users\agd7fe.conda\envs\sdv\lib\site-packages\ctgan\data_sampler.py in **init**(self, data, output_info, log_frequency)
> 41 # Prepare an interval matrix for efficiently sample conditional vector
> 42 max_category = max(
> ---> 43 [column_info[0].dim for column_info in output_info
> 44 if is_discrete_column(column_info)])
> 45
> 
> ## ValueError: max() arg is an empty sequence

Hi @Aditya-Agarwal-018, it seems like you are reaching the same issue that you saw on CTGAN: https://github.com/sdv-dev/CTGAN/issues/115
@fealho has already [opened a PR to fix it](https://github.com/sdv-dev/CTGAN/pull/117) so we this should be fixed sometime soon.

Also, since this thread was originally open for a different problem, I just opened a new issue #284 to focus exclusively on this. Let's follow up there.
