### ISSUE TITLE
Constraints: handling_strategy='reject_sampling' causes "ZeroDivisionError: division by zero"

### ISSUE THREAD

**Issue by prithvidc** [sdv-dev/SDV#285]
* SDV version:sdv-0.6.0
* Python version:python3.6
* Operating System:Google Colab (linux1_x86_64)

### Description

Describe what you were trying to get done.
- I'm trying to generate synthetic data from a popular open-source Kaggle dataset - https://www.kaggle.com/gunjanpathak/melb-data

Tell us what happened, what went wrong, and what you expected to happen.
I get NaN values when using handling_strategy='transform' for a UniqueCombinations constraint for string columns. But if I change to handling_strategy='reject_sampling', the model.sample() fails with "ZeroDivisionError: division by zero" error.

### What I Did
- I removed all rows with NaN values in the source data

- Since the training time for a CTGAN synthetic data generation model takes a long time, I sampled only 200 rows from the source data.

- The source data contains 3 columns that should be a unique combination: ("Suburb", "CouncilArea", "Regionname"). This is similar to ("City", "Country")
- I setup the constraint as follows: 
unique_Regionname_CouncilArea_Suburb_constraint = UniqueCombinations(
    columns=['Regionname', 'CouncilArea', 'Suburb'],
    handling_strategy='reject_sampling'
    ) 

- I have 2 constraints:
constraints = [
               unique_Regionname_CouncilArea_Suburb_constraint, 
               rooms_constraint
               ]

- I setup the CTGAN model as below:
from sdv.tabular import CTGAN

model = CTGAN(
    anonymize_fields={'address': 'Address'},
    constraints=constraints
    )

- I trained the model as below:
model.fit(sample_real_data_frame_dataset)

- I generated the synthetic data generation as below:
sample_synthetic_data_frame_dataset = model.sample(10)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-77-137f20106533> in <module>()
----> 1 sample_synthetic_data_frame_dataset = model.sample(10)

/usr/local/lib/python3.6/dist-packages/sdv/tabular/base.py in sample(self, num_rows, max_retries)
    163             invalid = num_rows - num_valid
    164             remaining = num_rows - num_valid
--> 165             proportion = counter * num_rows / num_valid
    166             num_to_sample = int(remaining * proportion)
    167 

**ZeroDivisionError: division by zero**

```
Paste the command(s) you ran and the output.
- I generated the synthetic data generation as below:
sample_synthetic_data_frame_dataset = model.sample(10)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-77-137f20106533> in <module>()
----> 1 sample_synthetic_data_frame_dataset = model.sample(10)

/usr/local/lib/python3.6/dist-packages/sdv/tabular/base.py in sample(self, num_rows, max_retries)
    163             invalid = num_rows - num_valid
    164             remaining = num_rows - num_valid
--> 165             proportion = counter * num_rows / num_valid
    166             num_to_sample = int(remaining * proportion)
    167 

**ZeroDivisionError: division by zero**
If there was a crash, please include the traceback here.
```

**Comment by csala** [comment]
Thanks for reporting this @prithvidc, and also for putting so many details in the issue description. This helps a lot!

I believe that what happens is that the edge case in which the rows sampled initially by the model which contain no valid combinations is not properly handled.

The resampling loop should be reviewed to ensure this case is properly covered. Adding this as a bug fix for the next release.
