### ISSUE TITLE
PicklingError when calling model.save

### ISSUE THREAD

**Issue by RN35** [sdv-dev/SDV#293]
* SDV version: v0.6.0
* Python version: 3.8.2
* Operating System: Red Hat Enterprise Linux Server release 7.9

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

Tried to create a pickle file after model creation

```
from sdv.tabular import CopulaGAN
import pandas as pd
data = pd.read_csv('data/sale_opportunity.csv')
copula_model1 = CopulaGAN(constraints=constraints, verbose = True, log_frequency = True, cuda = True)
copula_model1.fit(data)
copula_model1.save('my_model.pkl')

---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-11-38881895bbf2> in <module>
----> 1 copula_model1.save('my_model.pkl')

/usr/local/lib/python3.8/dist-packages/sdv/tabular/base.py in save(self, path)
    226         """
    227         with open(path, 'wb') as output:
--> 228             pickle.dump(self, output)
    229 
    230     @classmethod

PicklingError: Can't pickle <class 'pandas.core.frame.Pandas'>: attribute lookup Pandas on pandas.core.frame failed
```

**Comment by csala** [comment]
Hello @RN35 

You seem to be hitting the issue #286, which was already resolved on [v0.6.1](https://github.com/sdv-dev/SDV/releases/tag/v0.6.1).

Would you mind trying to upgrade your SDV version to the latest one using `pip install -U sdv`?
