### ISSUE TITLE
Near-zero-variance/nearly constant values and outliers

### ISSUE THREAD

**Issue by Martin20494** [sdv-dev/SDV#294]
* CTGAN version 0.2.2: using CTGANSynthesizer
* Python version 3
* Operating System:

### Description

At first, thank you so much for all your hard work with this wonderful package. It helped me so much with my project at the moment. However, there are some questions regarding my problems that I have with my data as below that I really need your helps.

My dataset has big number of outliers and one variable has near-zero-variance problem (or this variable nearly constant and the values are around 0). I tried to create a synthetic data which will look alike the original data. However, it seems like the CTGANSynthesize() can produce the values with the outliers and near-zero-variance problem but not accurate enough to show the patterns. Could you please suggest any other ideas for this case?

**Comment by csala** [comment]
Hi @Martin20494

Have you tried using [CopulaGAN](https://sdv.dev/SDV/user_guides/single_table/copulagan.html)

If you know the distribution of that variable you should be able to specify it in the CopulaGAN arguments (or you could also try using `gaussian_kde`) and the variable will be transformed to a standard normal distribution that will be easier to learn by CTGAN.
