### ISSUE TITLE
OneHotEncoding Constraint

### ISSUE THREAD

**Issue by gunahn** [sdv-dev/SDV#303]
Problem Description

I am trying to generate this kind of data, using CTGAN.

as you can see from the above picture, categorical data saved as one-hot encoding.Sex_1, Sex_2 / race.ethnicity_1, race.ethnicity_2, race.ethnicity_3, race.ethnicity_4, race.ethnicity_5

0, 1 / 0, 0, 0, 0, 11,0 / 1, 0, 0, 0, 0There should be only one 1, and other variables should be 0. 

However, when I made data by using CTGAN some data shows 0,0, 1,1 0,-1 for Sex_1 and Sex_2. 

Expected behavior

I would like to use CustomConstraint  to solve this problem.1) I would like to set the output as binary. (data should be 0 or 1)2) also, I would like to set constraint likerace.ethnicity_1+race.ethnicity_2+race.ethnicity_3+race.ethnicity_4+race.ethnicity_5 = 1

married_1 + married_2 + married_3 + married_4 + married_5 + married_6 =1

Thank you so much for your help

**Comment by csala** [comment]
This is an interesting feature! Thanks for opening the issue @gunahn 

We can create a specific constraint for this, called `OneHotConstraint`, that takes a list of columns as argument and then just guarantees that only one of them is equal to 1. Additionally, an option could be added to revert the one-hot representation into a single column and let the model work on it using another type of representation transform, like the `CategoricalTransformer` or the `LabelEncoding`, so the models can learn to treat the columns as categorical values.

An initial implementation without the transformer option could be something like this:

```python
import numpy as np
from sdv.constraints import Constraint

class OneHotConstraint(Constraint):

    def __init__(self, columns):
        self._columns = columns

    def transform(self, table_data):
        table_data = table_data.copy()
        table_data[self._columns] = table_data[self._columns].astype(float)
        return table_data

    def reverse_transform(self, table_data):
        indexes = np.argmax(table_data[self._columns].values, axis=1)
        table_data[self._columns] = np.eye(len(self._columns))[indexes].astype(int)
        return table_data

sex_constraint = OneHotConstraint(['Sex_1', 'Sex_2'])
...
```

**Comment by csala** [comment]
I changed to title to better describe what this is about
