### ISSUE TITLE
sktime is missing

### ISSUE THREAD

**Issue by sdikby** [sdv-dev/SDV#311]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.7.0
* Python version: 3.8.5
* Operating System: windows 10 

### Error Description

While trying to use a demo example with `from sdv import load_demo` I get the following error message sysing that sktime is missing

### Steps to reproduce

1. Create a new conda env
2. install sdv
3. install Jupyter
4. Open a new notebook an run the below mentioned command in it

```
from sdv import load_demo

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-7b5369a3b9c5> in <module>
----> 1 from sdv import load_demo

~\Anaconda3\envs\synthetical_data_playground\lib\site-packages\sdv\__init__.py in <module>
      9 __version__ = '0.7.0'
     10 
---> 11 from sdv import constraints, evaluation, metadata, relational, tabular
     12 from sdv.demo import get_available_demos, load_demo
     13 from sdv.metadata import Metadata, Table

~\Anaconda3\envs\synthetical_data_playground\lib\site-packages\sdv\evaluation.py in <module>
      2 
      3 import pandas as pd
----> 4 import sdmetrics
      5 
      6 from sdv.metadata.dataset import Metadata

~\Anaconda3\envs\synthetical_data_playground\lib\site-packages\sdmetrics\__init__.py in <module>
      9 import pandas as pd
     10 
---> 11 from sdmetrics import (
     12     column_pairs, demos, goal, multi_table, single_column, single_table, timeseries)
     13 from sdmetrics.demos import load_demo

~\Anaconda3\envs\synthetical_data_playground\lib\site-packages\sdmetrics\timeseries\__init__.py in <module>
      1 """Metrics for timeseries datasets."""
      2 
----> 3 from sdmetrics.timeseries import base, detection, efficacy, ml_scorers
      4 from sdmetrics.timeseries.base import TimeSeriesMetric
      5 from sdmetrics.timeseries.detection import LSTMDetection, TimeSeriesDetectionMetric, TSFCDetection

~\Anaconda3\envs\synthetical_data_playground\lib\site-packages\sdmetrics\timeseries\detection.py in <module>
      7 
      8 from sdmetrics.goal import Goal
----> 9 from sdmetrics.timeseries import ml_scorers
     10 from sdmetrics.timeseries.base import TimeSeriesMetric
     11 

~\Anaconda3\envs\synthetical_data_playground\lib\site-packages\sdmetrics\timeseries\ml_scorers.py in <module>
      4 import torch
      5 from sklearn.pipeline import Pipeline
----> 6 from sktime.classification.compose import TimeSeriesForestClassifier
      7 from sktime.transformers.series_as_features.compose import ColumnConcatenator
      8 

ModuleNotFoundError: No module named 'sktime'
```

### Ability to contribute
yes I do...but I would need support

**Comment by csala** [comment]
Hello @sdikby Thanks for reporting this.

It seems like the conda recipe for SDMetrics, which is a dependency of SDV, is missing a couple of dependencies that are not available in conda and need to be installed manually using pip.

You should be able to work around this by running the following command inside your conda environment:

```bash
pip install 'sktime>=0.4,<0.5' 'tsfresh<1,>=0.15'
```

**Comment by ndemoor08** [comment]
Hello,
I have the same bug, and the command that you propose doesn't work, I have this issue :

(sdvtest) C:\Users\nd550840>pip install 'sktime>=0.4,<0.5' 'tsfresh<1,>=0.15'
The system cannot find the file specified.

**Comment by sdikby** [comment]
@ndemoor08 just install the newest version of `sktime` version <0.5 via `pip install` and the newest version of `tsfresh` version <1 either  via `pip install` or `conda install`
This way I successfully worked around this issue

**Comment by ndemoor08** [comment]
I will try, thank you!

**Comment by ndemoor08** [comment]
Doesn't work for me, so sad. I didn't have this bug with sdv 0.5.0

**Comment by ndemoor08** [comment]
Ok, I find the solution I will explain there, if someone has the same bug. 

Environment Details
Please indicate the following details about the environment in which you found the bug:

SDV version: 0.7.0
Python version: 3.8.6
Operating System: windows 10

I created my env in conda, after this I ran this line :

`(sdv) C:\Users\nd550840>conda install -c sdv-dev -c pytorch -c conda-forge sdv`

My problem was that I used the wrong pip to install the sktime and tsfresh into my conda env. To fix it, I ran this line :


```
(sdv) C:\Users\nd550840>where pip
C:\Anaconda3\envs\sdv\Scripts\pip.exe
C:\Anaconda3\Scripts\pip.exe
```

Now, I have the path of the correct pip that I needed to use ( C:\Anaconda3\envs\sdv\Scripts\pip.exe ). I used it to install sktime==0.4 and tsfresh==0.15, like this : 

`(sdv) C:\Users\nd550840>C:\Anaconda3\envs\sdv\Scripts\pip install  sktime ==0.4 tsfresh==0.15`

And now it works !

**Comment by fealho** [comment]
The latest patch in SDMetrics (v0.1.3) resolves this issue, so it can be closed.
