### ISSUE TITLE
Low dispersion of the synthesized data

### ISSUE THREAD

**Issue by Regi-na** [sdv-dev/SDV#312]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.7.0 
* Python version: Google Colaboratory
* Operating System: Windows 8.1

### Problem description

<I have spectral data. It consists almost 400 raws and 101 columns, only numerical (float) data. [This is the data example](https://docs.google.com/spreadsheets/d/1PWNSAmwfjQuMWFAJK6CGFz10bzjoLXhMJP7OTP7Pgf4/edit?usp=sharing) 

First of all trying to synthesize new data with CTGAN I got the error 'int' object is not iterable.
To synthesize I use CTGANSynthesizer and it works. However, PCA shows the separation of synthesized and real data or low dispersion of the synthesized data while the dispersion of real data much more. >

### What I already tried

```
from ctgan import CTGANSynthesizer
ctgan = CTGANSynthesizer(epochs=10)
ctgan.fit(real)
samples = ctgan.sample(100)
gen=samples
gen['target']=0
data1 = real
data1['target']=1
base = pd.concat([gen, data1], ignore_index=True)
print(__doc__)
# Authors: Kyle Kastner
# License: BSD 3 clause
from sklearn.preprocessing import StandardScaler
import numpy as np
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA, IncrementalPCA
scaler = StandardScaler()
X = base
X=scaler.fit_transform(X)
y = base.target

n_comps = 2


pca = PCA(n_components=n_comps)
X_pca = pca.fit_transform(X)

colors = ['navy', 'turquoise']

for X_transformed, title in [(X_pca, "PCA")]:
    plt.figure(figsize=(8, 8))
    for color, i, target_name in zip(colors, [0, 1],['gen','real']):
        plt.scatter(X_transformed[y == i, 0], X_transformed[y == i, 1],
                    color=color, lw=2, label=target_name)

    plt.title("dataset")
    plt.legend(loc="best", shadow=False, scatterpoints=1)
    plt.axis([-15, 15, -15, 15])


plt.show()
```

**Comment by fealho** [comment]
Hi @Regi-na, indeed CTGAN doesn't emulate the dispersion of the data very well, so your results are expected. Regarding the ` 'int' object is not iterable.` error, I was unable to reproduce it. If you want further assistance with it, would you mind opening a new issue?
