### ISSUE TITLE
CTGAN - Out of memory issues

### ISSUE THREAD

**Issue by sowmya-pol** [sdv-dev/SDV#315]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.7.0
* Python version: 3.6

### Problem description

Trying to generate synthetic data using CTGAN and running into memory issues. I'm not sure if there is any error in the way I defined field types and field transformers? Any guidance here?

### What I already tried

Sharing details about the test

* **Input** : patients.csv
* **Number of columns** : 25
* **Number of records** : 10K
* **Column names** : 
['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE']
* **Column Datatypes**:  BIRTHDATE,DEATHDATE are of type DATE, 
LAT,LON,HEALTHCARE_EXPENSES, HEALTHCARE_COVERAGE are of type DECIMAL,
ZIP is of type Integer and other columns are of type string.

Tried to run in Jupyter notebook in VM 
**Virtual machine size**
STANDARD_NC24 (24 Cores, 224 GB RAM, 1440 GB Disk)
Processing Unit GPU - 4 x NVIDIA Tesla K80

Error
```
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/nn/modules/module.py in convert(t) 603 if convert_to_format is not None and t.dim() == 4: 604 return t.to(device, dtype if t.is_floating_point() else None, non_blocking, memory_format=convert_to_format) --> 605 return t.to(device, dtype if t.is_floating_point() else None, non_blocking) 606 607 return self._apply(convert) 
RuntimeError: CUDA out of memory. Tried to allocate 11.80 GiB (GPU 0; 11.17 GiB total capacity; 221.54 MiB already allocated; 10.67 GiB free; 226.00 MiB reserved in total by PyTorch)
```

```
field_types = {
  "MARITAL": {
    "type": "categorical"
  },
  "RACE": {
    "type": "categorical"
  },
  "ETHNICITY": {
    "type": "categorical"
  },
  "GENDER": {
    "type": "categorical"
  },
  "PREFIX": {
    "type": "categorical"
  },
  "SUFFIX": {
    "type": "categorical"
  },
  "MAIDEN": {
    "type": "categorical"
  },
  "BIRTHPLACE": {
    "type": "categorical"
  },
  "CITY": {
    "type": "categorical"
  },
  "STATE": {
    "type": "categorical"
  },
  "COUNTY": {
    "type": "categorical"
  },
  "ZIP": {
    "type": "categorical"
  },
  "LAT": {
    "type": "categorical"
  },
  "LON": {
    "type": "categorical"
  },
  "HEALTHCARE_EXPENSES": {
    "type": "numerical",
    "subtype": "float"
  },
  "HEALTHCARE_COVERAGE": {
    "type": "numerical",
    "subtype": "float"
  },
  "BIRTHDATE": {
    "type": "datetime",
    "format": "%m/%d-%Y"
  },
  "DEATHDATE": {
    "type": "datetime",
    "format": "%m/%d-%Y"
  }
}
field_transformers = {
  "MARITAL": "categorical",
  "RACE": "categorical",
  "ETHNICITY": "categorical",
  "GENDER": "categorical",
  "PREFIX": "categorical",
  "SUFFIX": "categorical",
  "MAIDEN": "categorical",
  "BIRTHPLACE": "categorical",
  "CITY": "categorical",
  "STATE": "categorical",
  "COUNTY": "categorical",
  "ZIP": "categorical",
  "HEALTHCARE_EXPENSES": "float",
  "HEALTHCARE_COVERAGE": "float",
  "BIRTHDATE": "datetime",
  "DEATHDATE": "datetime"
}
anonymize = {
  "SSN": "ssn",
  "ADDRESS": "address",
  "LAT": "latitude",
  "LON": "longitude",
  "FIRST": "first_name",
  "LAST": "last_name",
  "Id": "uuid4"
}


model = CTGAN(field_types=field_types,field_transformers=field_transformers,anonymize_fields=anonymize,epochs=1) 

```

**Comment by fealho** [comment]
Hi @sowmya-pol, could you try temporarily deleting the `PASSPORT` column? If the issues still persists, could you try setting the `batch_size` in CTGAN to 100? So your last line should be:
```
model = CTGAN(batch_size=100, field_types=field_types, field_transformers=field_transformers, anonymize_fields=anonymize) 
```
Let me know if any of the suggestions work.
