### ISSUE TITLE
Pip install sdv error on Windows (Python 3.9)

### ISSUE THREAD

**Issue by dmtrinh** [sdv-dev/SDV#318]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:  Latest
* Python version:  3.9.1
* Operating System:  Windows 10 Version 20H2 (OS Build 19042.746)

### Error Description

'pip install sdv' throws error on a fresh python environment.  Full trace is below:

### Steps to reproduce

PS C:\Dev\SyntheticData-env> python --version
Python 3.9.1
PS C:\Dev\SyntheticData-env> pip --version
pip 21.0.1 from c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages\pip (python 3.9)
PS C:\Dev\SyntheticData-env> pip install sdv
Collecting sdv
  Using cached sdv-0.3.2-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: graphviz>=0.13.2 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from sdv) (0.16)
Requirement already satisfied: numpy<1.17,>=1.15.4 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from sdv) (1.16.6)
Requirement already satisfied: exrex<0.11,>=0.9.4 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from sdv) (0.10.5)
Collecting pandas<0.25,>=0.23.4
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
Collecting copulas<0.3,>=0.2.5
  Using cached copulas-0.2.5-py2.py3-none-any.whl (44 kB)
Collecting rdt<0.3,>=0.2.1
  Using cached rdt-0.2.1-py2.py3-none-any.whl (16 kB)
Collecting matplotlib<4,>=2.2.2
  Using cached matplotlib-3.3.4-cp39-cp39-win_amd64.whl (8.5 MB)
Collecting scipy<1.3,>=0.19.1
  Using cached scipy-1.2.3.tar.gz (23.3 MB)
Collecting boto3<1.10,>=1.7.47
  Using cached boto3-1.9.253-py2.py3-none-any.whl (128 kB)
Requirement already satisfied: docutils<0.15,>=0.10 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from copulas<0.3,>=0.2.5->sdv) (0.14)
Requirement already satisfied: botocore<1.13.0,>=1.12.253 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from boto3<1.10,>=1.7.47->copulas<0.3,>=0.2.5->sdv) (1.12.253)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from boto3<1.10,>=1.7.47->copulas<0.3,>=0.2.5->sdv) (0.2.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from boto3<1.10,>=1.7.47->copulas<0.3,>=0.2.5->sdv) (0.10.0)
Requirement already satisfied: urllib3<1.26,>=1.20 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from botocore<1.13.0,>=1.12.253->boto3<1.10,>=1.7.47->copulas<0.3,>=0.2.5->sdv) (1.25.11)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\dmtrinh\appdata\roaming\python\python39\site-packages (from botocore<1.13.0,>=1.12.253->boto3<1.10,>=1.7.47->copulas<0.3,>=0.2.5->sdv) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<4,>=2.2.2->copulas<0.3,>=0.2.5->sdv) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<4,>=2.2.2->copulas<0.3,>=0.2.5->sdv) (8.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<4,>=2.2.2->copulas<0.3,>=0.2.5->sdv) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<4,>=2.2.2->copulas<0.3,>=0.2.5->sdv) (1.3.1)
Requirement already satisfied: six in c:\users\dmtrinh\appdata\roaming\python\python39\site-packages (from cycler>=0.10->matplotlib<4,>=2.2.2->copulas<0.3,>=0.2.5->sdv) (1.15.0)
Requirement already satisfied: pytz>=2011k in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from pandas<0.25,>=0.23.4->sdv) (2021.1)
Collecting Faker>=1.0.1
  Using cached Faker-6.1.1-py3-none-any.whl (1.1 MB)
Requirement already satisfied: text-unidecode==1.3 in c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages (from Faker>=1.0.1->rdt<0.3,>=0.2.1->sdv) (1.3)
Using legacy 'setup.py install' for pandas, since package 'wheel' is not installed.
Using legacy 'setup.py install' for scipy, since package 'wheel' is not installed.
Installing collected packages: scipy, pandas, matplotlib, Faker, boto3, rdt, copulas, sdv
    Running setup.py install for scipy ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\dmtrinh\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dmtrinh\\AppData\\Local\\Temp\\pip-install-pun6o58p\\scipy_c24121754a164ed0affd32c28ace2ffa\\setup.py'"'"'; __file__='"'"'C:\\Users\\dmtrinh\\AppData\\Local\\Temp\\pip-install-pun6o58p\\scipy_c24121754a164ed0affd32c28ace2ffa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dmtrinh\AppData\Local\Temp\pip-record-7879qfjy\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dmtrinh\appdata\local\programs\python\python39\Include\scipy'
         cwd: C:\Users\dmtrinh\AppData\Local\Temp\pip-install-pun6o58p\scipy_c24121754a164ed0affd32c28ace2ffa\
    Complete output (191 lines):

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)

    Running from scipy source directory.
    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['c:\\users\\dmtrinh\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\dmtrinh\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas not found in ['c:\\users\\dmtrinh\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\dmtrinh\\appdata\\local\\programs\\python\\python39\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    openblas_clapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas,lapack not found in ['c:\\users\\dmtrinh\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\dmtrinh\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\users\dmtrinh\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\system_info.py:639: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack not found in ['c:\\users\\dmtrinh\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\dmtrinh\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dmtrinh\AppData\Local\Temp\pip-install-pun6o58p\scipy_c24121754a164ed0affd32c28ace2ffa\setup.py", line 492, in <module>
        setup_package()
      File "C:\Users\dmtrinh\AppData\Local\Temp\pip-install-pun6o58p\scipy_c24121754a164ed0affd32c28ace2ffa\setup.py", line 488, in setup_package
        setup(**metadata)
      File "c:\users\dmtrinh\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\core.py", line 137, in setup
        config = configuration()
      File "C:\Users\dmtrinh\AppData\Local\Temp\pip-install-pun6o58p\scipy_c24121754a164ed0affd32c28ace2ffa\setup.py", line 395, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\dmtrinh\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dmtrinh\\AppData\\Local\\Temp\\pip-install-pun6o58p\\scipy_c24121754a164ed0affd32c28ace2ffa\\setup.py'"'"'; __file__='"'"'C:\\Users\\dmtrinh\\AppData\\Local\\Temp\\pip-install-pun6o58p\\scipy_c24121754a164ed0affd32c28ace2ffa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dmtrinh\AppData\Local\Temp\pip-record-7879qfjy\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dmtrinh\appdata\local\programs\python\python39\Include\scipy' Check the logs for full command output.
PS C:\Dev\SyntheticData-env>

**Comment by csala** [comment]
Hello @dmtrinh,

At the moment [SDV is only supported on Python 3.6, 3.7 and 3.8](https://sdv.dev/SDV/getting_started/install.html#requirements).

Would you mind trying to install again on any of these?

**Comment by dmtrinh** [comment]
Thanks @csala - downgrading to Python 3.8.7 works!  I had related issues with Numpy as noted [here](https://github.com/numpy/numpy/issues/17569).

**Comment by csala** [comment]
I'm glad to hear it worked, thanks for sharing @dmtrinh !
