### ISSUE TITLE
Conditional sampling on non-existing category

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#338]
### Problem Description

When using conditional sampling and passing non-existing categories as condition, no error is thrown. Instead, it simply ignores that condition and moves on to the next.

### Expected behavior

It should raise the appropriate error.

### Additional context

For example, if we run the following code:

```python3
data = pd.DataFrame({
    "column1": 1.0, 0.5, 2.5  10,
    "column2": "a", "b", "c"  10
})

model = CTGAN(epochs=1)
model.fit(data)
conditions = pd.DataFrame({
    "column2": 'a','d','a'
})
sampled = model.sample(conditions=conditions)
print(sampled)
```

it will return:

```
column1 column2

0  2.546468       a
2  2.683195       a
```

instead of failing, since the 'd' category doesn't exist in the data.

**Comment by npatki** [comment]
In the new API, we've exposed a `sample_conditions` method that appropriately throws an Error when the category doesn't exist.

```
ValueError: Unable to sample any rows for the given conditions. This may be because the provided values are out-of-bounds in the current model. 
Please try again with a different set of values.
```

Closing the issue.
