### ISSUE TITLE
Unreadable error when conditional sampling without specifying number of samples

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#339]
### Problem Description

When using conditional sampling without passing the number of samples (when conditions is a dictionary) it fails with the unreadable error `TypeError: can't multiply sequence by non-int of type 'NoneType'`.

### Expected behavior

It should tell the user they forgot to pass the number of samples, especially because it is not required when conditions is a dataframe, which makes this mistake quite plausible.

### Additional context

The code below shows an example of this happening:

```python3
data = pd.DataFrame({
    "column1": 1.0, 0.5, 2.5  10,
    "column2": "a", "b", "c"  10
})

model = CTGAN(epochs=1)
model.fit(data)
conditions = {
    'column2': 'a'
}
sampled = model.sample(conditions=conditions)
```

**Comment by npatki** [comment]
This issue is obsolete, since we've moved to a new API that exposes a `sample_conditions`. The number of rows is a required parameter to create the conditions.
