### ISSUE TITLE
Add integration tests for Metadata Validation

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#358]
Issue #348 was resolved including unit tests that certify that individual errors are added to a list.

Integration should be added/extended to test metadata validation with multiple errors, asserting that the error message includes all of them.

**Comment by npatki** [comment]
I believe this issue is now stale, as SDV 1.0 now has a new **Metadata** object that we've written new integration tests for. 

@amontanez24 to correct if I'm wrong and re-open the issue as needed.
