### ISSUE TITLE
Saving and Loading Serialized Model Bug

### ISSUE THREAD

**Issue by yurix** [sdv-dev/SDV#363]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

SDV version: 0.8.0
Python version: 3.8
Operating System: Debian

### Error Description

I trained default tabular demo (https://sdv.dev/SDV/user_guides/single_table/ctgan.html) to save and load model. When i try to generate new samples for loaded model the error throws.  

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-5bf346c11434> in <module>
----> 1 out2 = mode2.sample(200)
      2 print (out2)

~/anaconda3/envs/sdv/lib/python3.8/site-packages/sdv/tabular/base.py in sample(self, num_rows, max_retries, max_rows_multiplier, conditions, float_rtol)
    365         if conditions is None:
    366             num_rows = num_rows or self._num_rows
--> 367             return self._sample_batch(num_rows, max_retries, max_rows_multiplier)
    368 
    369         # convert conditions to dataframe

~/anaconda3/envs/sdv/lib/python3.8/site-packages/sdv/tabular/base.py in _sample_batch(self, num_rows, max_retries, max_rows_multiplier, conditions, transformed_conditions, float_rtol)
    272                 Sampled data.
    273         """
--> 274         sampled, num_valid = self._sample_rows(
    275             num_rows, conditions, transformed_conditions, float_rtol)
    276 

~/anaconda3/envs/sdv/lib/python3.8/site-packages/sdv/tabular/base.py in _sample_rows(self, num_rows, conditions, transformed_conditions, float_rtol, previous_rows)
    201                     Number of rows that are considered valid.
    202         """
--> 203         if self._metadata.get_dtypes(ids=False):
    204             if conditions is None:
    205                 sampled = self._sample(num_rows)

~/anaconda3/envs/sdv/lib/python3.8/site-packages/sdv/metadata/table.py in get_dtypes(self, ids)
    250         """
    251         dtypes = dict()
--> 252         for name, field_meta in self._fields_metadata.items():
    253             field_type = field_meta['type']
    254 

AttributeError: 'NoneType' object has no attribute 'items'

### Steps to reproduce

from sdv import Metadata
from sdv.tabular import CTGAN
import pandas as pd
from sdv.demo import load_tabular_demo

mode = CTGAN(cuda=False)
dataset = load_tabular_demo('student_placements')
mode.fit ( dataset )
out = mode.sample(200)
mode.save ("trained_sdg.pkl")
mode2 = CTGAN(cuda=False)
mode2.load("trained_sdg.pkl")
out2 = mode2.sample(200)

**Comment by pvk-developer** [comment]
Hi @yurix , I believe that this is not a bug, the `load` method should be only used as classmethod, which means that you have to use `CTGAN.load` .

If you change your code to:

```python
from sdv import Metadata
from sdv.tabular import CTGAN
import pandas as pd
from sdv.demo import load_tabular_demo

mode = CTGAN(cuda=False)
dataset = load_tabular_demo('student_placements')
mode.fit ( dataset )
out = mode.sample(200)
mode.save ("trained_sdg.pkl")

# load the previously saved model using the class CTGAN
mode2 = CTGAN.load("trained_sdg.pkl")
out2 = mode2.sample(200)
```  
Should work fine.

I would like to recommend you to check out our user guide on [how to load a pretrained model](https://sdv.dev/SDV/user_guides/single_table/ctgan.html#load-the-model-and-generate-new-data) for more details.

**Comment by yurix** [comment]
> Hi @yurix , I believe that this is not a bug, the `load` method should be only used as classmethod, which means that you have to use `CTGAN.load` .
> 
> If you change your code to:
> 
> ```python
> from sdv import Metadata
> from sdv.tabular import CTGAN
> import pandas as pd
> from sdv.demo import load_tabular_demo
> 
> mode = CTGAN(cuda=False)
> dataset = load_tabular_demo('student_placements')
> mode.fit ( dataset )
> out = mode.sample(200)
> mode.save ("trained_sdg.pkl")
> 
> # load the previously saved model using the class CTGAN
> mode2 = CTGAN.load("trained_sdg.pkl")
> out2 = mode2.sample(200)
> ```
> 
> Should work fine.
> 
> I would like to recommend you to check out our user guide on [how to load a pretrained model](https://sdv.dev/SDV/user_guides/single_table/ctgan.html#load-the-model-and-generate-new-data) for more details.

Thank you!
