### ISSUE TITLE
Is it possible to limit a column to possitive values?

### ISSUE THREAD

**Issue by jordialcaraz** [sdv-dev/SDV#365]
I want to limit the values of some columns to possible values, is it possible to do with constraint or any other method?

I saw that constraints are between different columns, but did not  find the case above.

Thank you.

**Comment by pvk-developer** [comment]
Hi @jordialcaraz  this issue has been already answered here: https://github.com/sdv-dev/SDV/issues/200

If you follow [this example](https://github.com/sdv-dev/SDV/issues/200#issuecomment-707539800) you will see that you can use a different `field_distribution` for a column. If you use the `gamma` distribution for the column that  you want to be only positive you will be able to produce only positive numbers.
