### ISSUE TITLE
Is there any method that SDV by defaults automatically selects the best field distribution method so then we could not specify the method for each column ? 

### ISSUE THREAD

**Issue by hamzanaeem1999** [sdv-dev/SDV#375]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:
* Python version:
* Operating System:

### Problem description

<Replace this with a description of the problem that you are trying to solve using SDV. If
possible, describe the data that you are using, or consider attaching some example data
that others can use to propose a working solution for your problem.>

### What I already tried

<Replace with a description of what you already tried and what is the behavior that you observe.
If possible, also add below the exact code that you are running.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by HarisNaveed17** [comment]
If you don't specify the field distributions, SDV automatically selects the distributions it believes are best. You can check what it chose by:
`model.get_distributions()`
