### ISSUE TITLE
Learn module base table/s directly?

### ISSUE THREAD

**Issue by avico78** [sdv-dev/SDV#376]
I have set of 4 tables in Postgres with some relation between them,
far as i search on the documentation couldn't find an example 
how to fetch the data from the DB and assign it/sample of it to the learning module.,
I think the documentation is good when it come for demo part but less in real world cases,
obviously the data actually lives in a DB and less as in a demo module
- so I think it make sense to documentation should cover this subject and should focus more on this assumption(data lives in DB:)),
beside the technical side of "how to " which I think it doesn't cover well ,

would really appreciate if some1 explain what is the best practice to learn the module from data coming from relational DB?
second ,what would be best suited model for such operation(multiple tables in relational db  )?SDV?HMA1?

**Comment by pvk-developer** [comment]
Hi @avico78 , thank you for your suggestions, we will have those in consideration.

Regarding your question, `SDV` works with `pandas.DataFrame`, which is very common tool for the data scientists. What I can recommend you in your case it's to export the data from `postgress` in a `csv` format and load it with [`pandas.DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) and then create your `MetaData` object with the relations as shown in our [documentation](https://sdv.dev/SDV/user_guides/relational/relational_metadata.html).

The model that you should be using it's the `HMA1`, which is the only one that we have at the moment for relational datasets. The `SDV` class at this moment uses that one as default.

**Comment by avico78** [comment]
Thanks @pvk-developer
