### ISSUE TITLE
metadata.add_table - error

### ISSUE THREAD

**Issue by avico78** [sdv-dev/SDV#377]
### Environment details

* SDV version:       0.9.0
* Python version:3.8.1 32bit
* Operating System: Docker

### Problem description

follow documentation for preparing Metadata class :  
https://sdv.dev/SDV/user_guides/relational/relational_metadata.html#relational-metadata

```
    from sdv import Metadata
    metadata = Metadata()
    metadata.add_table(
            name='customer',
            data=tables['customer'],
            primary_key='customer_id'
     )
    
```
Getting error:
```
ws | await self.app(scope, receive, send)

ws | File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app

ws | response = await func(request)

ws | File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app

ws | raw_response = await run_endpoint_function(

ws | File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function

ws | return await dependant.call(**values)

ws | File "./syntdata/routes.py", line 198, in dvd

ws | return demo()

ws | File "./syntdata/routes.py", line 67, in demo

ws | data=tables['customer'],

ws | NameError: name 'tables' is not defined
```

**Comment by pvk-developer** [comment]
Hi @avico78 , you are missing the demo `tables`:
```python
from sdv import load_demo

tables = load_demo()
```
https://sdv.dev/SDV/user_guides/relational/relational_metadata.html#load-the-demo-data

**Comment by avico78** [comment]
> ```python
> tables = load_demo()
> ```

Thanks @pvk-developer ,
if my table reside on DB how can assign it to learning module?

**Comment by avico78** [comment]
> Hi @avico78 , you are missing the demo `tables`:
> 
> ```python
> from sdv import load_demo
> 
> tables = load_demo()
> ```
> 
> https://sdv.dev/SDV/user_guides/relational/relational_metadata.html#load-the-demo-data

Thanks @pvk-developer ,
I'd like to learn the module by 2 tables coming from DB (postgres),
can u please example how i can do that ?
