### ISSUE TITLE
Foundational Paper for CopulaGAN?

### ISSUE THREAD

**Issue by FlorianRempel** [sdv-dev/SDV#407]
Hello,

the CopulaGAN model as a variant built on top of the CTGAN Frameworks is a very interesting Framework that I would like to feature in an academic thesis of mine. However, I am unable to identify any paper that introduces said model neither under the official https://sdv.dev/SDV/user_guides/single_table/copulagan.html, nor by searching through other sources such as journals, etc. 
While a few papers use the SDGYM benchmark results or it's performance on their own metrics, none explain it's functionality in an academic setting. 

Are you currently in the process of writing/publishing such a paper?

Many Thanks

**Comment by kveerama** [comment]
Hi @FlorianRempel I agree. I think it is an interesting combination combing the best of the both. 

We designed `SDV` system such that we can mix and match different modules and enable different models. As such last fall, we decided to mix `Copula` based transformation and give data that is transformed and each variable given to `CTGAN` follows `standard normal` marginally. Our results on a suite of datasets showed a lot of promise. 

As we expand the number of models by mixing and matching, we may not be able to keep up and write papers for each. 

However, look for our `benchmarking` results on these different models and several datasets. 

If you'd like to `cite` in your thesis, you are welcome to cite the original `SDV` paper and `CTGAN` paper and mention that we formed a combination. Hope this helpful.
