### ISSUE TITLE
PII columns need consistent mapping

### ISSUE THREAD

**Issue by bweinert89** [sdv-dev/SDV#415]
Is there a way to mark a column as PII and map it using Faker, but keep the mapping consistent when sampling?  For instance, mapping a NAME column with fake names, but keep the same distribution of names. So "Joe Smith" will always map to "John Doe," for example.

It looks like when a pii column is fit it is mapped with a unique fake value so the model learns the distribution of the PII column but then in the reverse_transform method (https://github.com/sdv-dev/SDV/blob/63a2423bd4c57f9e46efeb1e856df5526bac8ee1/sdv/metadata/table.py#L561) the generated values are replaced with new fake values, removing the mapping.  

Can there be a flag to keep the mapping and skip the reverse_transform for pii columns?  If there is an issue with the stored anonymization maps keeping the original data (GaussianCopula._metadata._ANONYMIZATION_MAPPINGS), then hashing PII columns such that the key is the hash of the unique values is a possible solution.

Also, if the mapping is overwritten, would it speed things up to remove the column when fitting the model, then generate Faker values afterwards and append it to the dataframe?

**Comment by npatki** [comment]
There isn't currently a way to perform a mapping like this so I'm marking it as a feature request. To help craft a solution & prioritize it, I'd love to hear more about your use case. To the extent you're able to share, what does your dataset represent, and what are you hoping to accomplish with the synthesized data?

Some details that would be useful:

- Are you trying so synthesize a single table or multiple related tables? I assume if you're using `GaussianCopula` it might be a single table.
- For a single table, the PII mappings will only be useful if the same values appear multiple times in your table. Just to confirm: Does the same user (`John Doe`) appear in multiple rows of your table? 
- What is the significance of the same user (`John Doe`) appearing in multiple rows? One guess I have is that the rows corresponding to `John Doe` are related to each other in some way -- for eg. a series of credit card transactions that `John Doe` has made?

**Comment by bweinert89** [comment]
This would be for both Multi and Single Table.  The GaussianCopula was from tracking HMA1->GaussianCopula.  For the Multi table we add in the anonymize_fields by building it into the fields_metadata for the add_table() method in the MetaData object.

For single table a user can appear in multiple rows.  Like you mentioned repeat customers in transaction data is a use case.  One idea would be using the synthetic data to group by same customer so you can determine types of customers or cluster them.  Or possibly using the synthetic data to train recommendations.

For multi table, I can imagine a case where you have the same person (or field) showing up in multiple tables.  Employee Manager being an example.  Being able to create a mapping across tables or use the synthetic data to build graph relations could be interesting.

It seemed like the data was being transformed consistently from the _make_anonymization_mappings() method and then fit which would learn these relationships but then it was removed in the reverse_transform.

**Comment by npatki** [comment]
Thanks for the detail. I think there are a few issues coming up, so I've spun up some more.

1. [This issue] Add PII mapping for a single table: We'll need to discuss the best approach for this. In theory, any table where the rows are related to each other is more suited to using the PAR model (in our `DeepEcho` library) bc this technically becomes a sequential/time series data. However, the PAR model doesn't have the mapping right now either.
2. [New issue #439] If we aren't doing any sort of mapping, then we don't need to learn the relationships at all. This would be a performance improvement 
3. [TBD] Mapping for multi-table: If the primary key/foreign keys are the anonymized fields, I believe that a mapping between the parent/child tables should already work. But we should spin up a bug if that's not the case.

**Comment by bweinert89** [comment]
PAR makes sense but I have seen cases where multiple entries in the same table aren't a time series.  There have been tables where multiple items in a users cart get split into multiple rows (user, order, item) for each item.  This case would still need consistent mapping without the time series.

I'm not sure how primary/foreign keys work.  It looks like in the Table.py file when it checks for the PII, it makes sure type is not "ID" so it would skip these fields when anonymizing the data.  If this is the case, then the mapping among parent/child tables should be consistent.  For non key columns that appear in both I don't think consistent mapping is conserved.  It looks like for each table it randomly assigns a faker value to each real entry, but it doesn't guarantee the same faker value in each table.

Does the Dataset.py handle PII differently than Table.py?  I see how Table.py handles PII but Im not sure how Dataset.py does.

**Comment by npatki** [comment]
> There have been tables where multiple items in a users cart get split into multiple rows (user, order, item) for each item.

Got it! We'll keep this in mind when fixing this. Seems to me like a valid reason to include this feature for single table models, and not just PAR.

> For non key columns that appear in both I don't think consistent mapping is conserved.

What are some examples of non-key columns that appear in multiple tables? I was assuming the only information that is linked in a multi-table would be `primary key` and `foreign key` relationships. But this assumption may well be wrong.

**Comment by bweinert89** [comment]
One example I can think of seeing where a non-key column appears in multiple tables is a transportation dataset.  There was a shippers and a receivers table in the database.  The same facility ("Daves Warehouse") could be in both tables with columns like phone number, address, etc.  Maybe also something where a business has an employee contact table and a customer table where the same person can show up in both.

**Comment by poornima-sivanand** [comment]
I am also facing this same issue. For eg: in health data, Synthea-Covid 19 dataset. I tried using HMA1 for multi table, but I couldn't get it to generate the Primary key in the same format, the id is "000e7adf-cbaa-4fad-ab2f-658c32f7d4d3", but hma1 generates this as 'a'. So I had to combine the tables and I have multiple rows for the same patient. However, while the real data has 939 unique patients, the synthetic data only has 103.

**Comment by npatki** [comment]
Great news everyone! The new, [**SDV 1.0 (Beta!)**](https://docs.sdv.dev/sdv/) version now supports pseudo-anonymization, which creates a consistent mapping between real and synthetic PII values. You can also retrieve the mapping if you want to backtrack what the original values are.

For more information see:
-  [Anonymizing Sensitive Data docs](https://docs.sdv.dev/sdv/single-table-data/modeling/advanced-features/transform-and-anonymize#anonymizing-sensitive-data)
- [Pseudo-Anonymization Tutorial](https://colab.research.google.com/drive/1b0W9jpgOHFrkz-i1QynVuaMZXs7BSPb_?usp=sharing#scrollTo=aTzDaN89FkXt)

I'll close this issue off since the titular request (PII columns need consistent mapping) has been resolved. If there are any related issues or follow-ups to this, please feel free to raise a new issue!
