### ISSUE TITLE
An error while import sdv in Google Colab: numpy.ndarray size changed

### ISSUE THREAD

**Issue by vpozdnyakov** [sdv-dev/SDV#417]
### Environment Details

* SDV version: 0.9.0
* Python version: 3.7.10
* Operating System: Google Colab web platform

### Error Description

I cannot import SDV in Google Colab. An error occurs:

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

### Steps to reproduce

1. Open Google Colab (https://colab.research.google.com/)
2. Click on the "New notebook" button
3. Run the following code
```
!pip install sdv
import sdv
```
4. Look at "You must restart the runtime in order to use newly installed versions" warning and click on the "Restart runtime" button
5. Run the code again

**Comment by vpozdnyakov** [comment]
It works if update numpy:

```
!pip install numpy==1.20
!pip install sdv
import sdv
```

**Comment by Timbimjim** [comment]
Hey, i have the same problem. Tried your fix, didnt help. Also tried uninstalling numpy.

Same error as above mentioned trying to run it in jupyter.

**Comment by vpozdnyakov** [comment]
@Timbimjim It works for me after restarting runtime.
1. Open Colab, insert this code into the cell
```
!pip install numpy==1.20
!pip install sdv
import sdv
```
2. Run the cell
3. Click on "Runtime" - "Restart runtime"
4. Run the cell again

**Comment by Timbimjim** [comment]
Yes it actually does work now. Dont really know what the problem was. Downgrading numpy helped. Thx!

**Comment by Sukriti-Mehrotra** [comment]
Check the version of numpy installed
```
!import numpy as np
!np.__version__
```
If the version displayed is anything less than 1.20 then uninstall numpy and install latest version again

```
!pip uninstall numpy
!pip install numpy==1.20.3
```

It installed numpy-1.20.3 for me and the error does not show up.

**Comment by alireza0r** [comment]
> @Timbimjim It works for me after restarting runtime.
> 
> 1. Open Colab, insert this code into the cell
> 
> ```
> !pip install numpy==1.20
> !pip install sdv
> import sdv
> ```
> 
> 2. Run the cell
> 3. Click on "Runtime" - "Restart runtime"
> 4. Run the cell again

Thank you
it works

**Comment by npatki** [comment]
Hi everyone, I'm closing off this issue, as it has been inactive for a while and seems like everyone found a workaround.

BTW the underlying issue should be fixed. If you try running this again, it should work without needing any special handling of `numpy`. To be more explicit, you can try pinning the SDV version to the latest:

```python
!pip install sdv==0.15.0
import sdv
```

Please feel free to reply or file a new issue if there are any persisting bugs in installation.
