### ISSUE TITLE
Fix UniqueCombinations documentation

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#437]
`UniqueCombinations` can only be applied to categorical columns, so the documentation should specify that.

Both the [API docs](https://sdv.dev/SDV/api_reference/constraints/api/sdv.constraints.UniqueCombinations.html) and the [user guide](https://sdv.dev/SDV/user_guides/single_table/constraints.html?) need to be updated.

**Comment by tjhallum** [comment]
As per https://github.com/sdv-dev/SDV/pull/481, I think UniqueCombinations has been expanded to handle non-strings. So, this issue could probably be closed.

**Comment by npatki** [comment]
Closing the issue per Ted's previous comment. We have since iterated on this constraint and added new documentation.
