### ISSUE TITLE
Adding constraints for relational data

### ISSUE THREAD

**Issue by Abhishek-Baseshankar** [sdv-dev/SDV#441]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:3.1.0
* Python version:3.6.8
* Operating System:Ubuntu

###Problem arises while applying constraints on relational Table data

<While generating the synthetic data for  relational data model generate some wrong data,from that I am trying to apply constraints,but after applying constraints it will throw value Error from BaseTabularModel class>

### What I already tried

<I want to apply constraints for relational data>

```

```

**Comment by fealho** [comment]
Hi @Abhishek-Baseshankar, I will need more information to be able to help you. Could you paste your stack trace here, as well as the code you are trying to run?

**Comment by npatki** [comment]
Hi everyone, I'm closing this issue out since it's been inactive for a while. Please feel free to reopen if you have any further clarifications or feedback!
