### ISSUE TITLE
Best practice/ general approach for learning data based Json

### ISSUE THREAD

**Issue by avico78** [sdv-dev/SDV#442]
I'd like to advise for what is the approach recommended for learning Json .
For simple /flat Json - I guess it can be learnt as regular table ,
But how should handle nested json ?
flatten the json in separated  DF and apply learning as single table?
But then, it might loose the context of the whole json document.
would appreciate for any guidance or example.

**Comment by fealho** [comment]
Hi @avico78. As you mentioned, currently our libraries don't accept JSON objects as input, so the issue is how to transform a nested JSON into a table. This task seems to depend on your specific dataset, so I could try to come up with something if you are willing to share some sample of your data.

**Comment by avico78** [comment]
@fealho  - thanks ,appreciated your help.

In general , I have a json representing customer and his subscribers ,
Where first level of json - customer personal info
Each customer can have multiple subscribers
Each subscriber can have multiple usage


i.e:
```json
{"first_name":"Jimmi","last_name":"Hendrix","email":"Jimi@heaven.com","customer_no":1000,"address":[{"address":"7342 Tiffany Trace\nGambletown, WI 69532","zip_code":"87803"}],"subscriber":[{"subscriber_no":307724738,"is_active":true,"subscriber_usage":[{"usage_id":426775286,"usage_type":"Call","event_duration":15.023950609686787},{"usage_id":426775286,"usage_type":"SMS","event_duration":125}]},{"subscriber_no":307724739,"is_active":false,"subscriber_usage":[{"usage_id":426775286,"usage_type":"GPRS","event_duration":123123}]}]}
```

**Comment by npatki** [comment]
Circling back to this issue -- For this particular use case, the best approach for the SDV would be to represent this data as a multi-table dataset with tables for: customer personal info, subscribers and usage. You can generate one-to-many mappings between these tables. Eg. if each customer has multiple subscribers, then customers is the parent table and subscribes is the child.

The SDV does not currently have any methods to read JSON or represent it in this way, so this is something you'd have to do manually for now. If you'd like to request support for this, it would be great to file a separate feature request.

**Comment by npatki** [comment]
Hi everyone, this issue has been inactive for over a week and originally filed over a year ago. I'll close it off since we've answered the original question. Feel feel to reply if there is more to discuss and I'll re-open the issue.
