### ISSUE TITLE
Discrete columns in copulaGAN

### ISSUE THREAD

**Issue by Zepp3** [sdv-dev/SDV#445]
Hi!

You can not name the discrete columns using copulaGAN. How does the networks know the discrete values then?

**Comment by fealho** [comment]
Hi @Zepp3, the categorical columns can be either (1) extracted from the metadata when available or (2) detected based on the data type. You can check out the logic [here](https://github.com/sdv-dev/SDV/blob/master/sdv/tabular/ctgan.py#L36).

**Comment by Zepp3** [comment]
Thanks you!

**Comment by Zepp3** [comment]
I recognized that the recognition of discrete values doesn't always function properly and doesn't recognize al categorical values of the dataset. Therefore I think it would be good to add the possibility to name the discrete columns by the user.

**Comment by npatki** [comment]
Could you provide some more detail about what isn't functioning properly? An example of your use case & output will be very helpful in diagnosing this!

**Comment by Zepp3** [comment]
As far as I can see, the algo does recognize columns containing strings as discrete but columns with the int data type (for example in my dataset a column with der quarter of the year 1,2,3,4) weren't recognized as a discrete column.
I quitted my work on the project with copulaGAN but if it helps you I can rewind the project and can post additional outputs and code.

**Comment by npatki** [comment]
Gotcha! Currently the SDV only recognizes strings as discrete columns by default, not ints or floats. However, you can override the default settings using the `field_types` kwarg when you instantiate the model.

In the example below, assume there's a column called `quarter` with integer values `1, 2, 3, 4` that should be treated as discrete (categorical), not continuous.

```python
types = {
    'quarters': {
        'type': 'categorical'}}

model = CopulaGAN(field_types=types)
```

**Comment by Zepp3** [comment]
Great, thanks! So, in principle that works exactly the same as naming the discrete columns a priori, cool :)
