### ISSUE TITLE
Error in HMA Model with relational data when sampling from child table 

### ISSUE THREAD

**Issue by rahulragunathan** [sdv-dev/SDV#451]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.9.0
* Python version: 3.8.8
* Operating System: Ubuntu 18.04 LTS

### Error Description

We are testing generation for relational data using the AdventureWorks data warehouse schema (using the Docker image here: https://github.com/sripathikrishnan/adventureworks). This schema consists of a star schema with multiple fact and dimension tables.

One of these dimension tables, "dimcustomer" has a parent-child relationship with the related fact table "factsurveyresponse", with each customer potentially linked to multiple survey responses. However, for the majority of the customers (~91%) in the table, there are no linked survey responses in the child table. 

When we try to run the HMA model, the model is able to be fit correctly, and learns that the average num_rows for the child given each parent customer ~0 (which is correct). Therefore, when we try to sample from the parent table with sample_children=True, for each customer record that is generated, the child model sets num_rows=0 for the GaussianCopula model, based on the provided sampled value for the associated num_rows in the parent.  So, the method _sample_child_rows in hma.py 

https://github.com/sdv-dev/SDV/blob/9514264e0f1eac1b92edb226a592d79dedd7c093/sdv/relational/hma.py#L352

does not update the sampled_data dictionary with any records for the child factsurveyresponse table.

This then causes an error to be raised in the _sample_children method

https://github.com/sdv-dev/SDV/blob/9514264e0f1eac1b92edb226a592d79dedd7c093/sdv/relational/hma.py#L354:

Because no rows were generated for the child for any of the parent rows, there is no related dataframe for the child table present in the sampled_data dictionary, and we get the following error: 

```
Exception has occurred: KeyError       
'factsurveyresponse'
  File "/home/rahulragunathan/anaconda3/envs/MultiTable/lib/python3.8/site-packages/sdv/relational/hma.py", line 354, in _sample_children
    child_rows = sampled_data[child_name]
  File "/home/rahulragunathan/anaconda3/envs/MultiTable/lib/python3.8/site-packages/sdv/relational/hma.py", line 430, in _sample_table
    self._sample_children(table_name, sampled_data, table_rows)
  File "/home/rahulragunathan/anaconda3/envs/MultiTable/lib/python3.8/site-packages/sdv/relational/hma.py", line 471, in _sample
    self._sample_table(table, num_rows, sampled_data=sampled_data)
  File "/home/rahulragunathan/anaconda3/envs/MultiTable/lib/python3.8/site-packages/sdv/relational/base.py", line 184, in sample
    return self._sample(table_name, num_rows, sample_children)
  File "/c/Users/rrr0901/Documents/Workspace/synthetic-data/multi_table/mtgen.py", line 61, in sample
    return self.model.sample(num_rows=num_rows, table_name=table_name, sample_children=sample_children)
```

### Steps to reproduce

This can also be reproduced with any other test schema, where we we try to sample from a parent table and its children where only a small fraction of the parent table have linked records in the child.  In this scenario, we believe that the code should simply stop and return without generating the child records, instead of raising an error.

We also verified that manually removing the records in the parent table that did not have any linked records in the child (so that the average num_rows for each record in the parent was != 0) did resolve the issue, and generate records for the children. 

The code that was run:

```
kwargs = {}
kwargs['default_distribution'] = 'parametric'
kwargs['categorical_transformer'] = 'categorical_fuzzy'

model = HMA1(self.metadata,model_kwargs={k: v for k,v in kwargs.items() if v is not None})
model.fit(self.table_dict)

model.sample(num_rows=2, sample_children=True)
```

### Ability to contribute

https://github.com/sdv-dev/SDV/blob/9514264e0f1eac1b92edb226a592d79dedd7c093/sdv/relational/hma.py#L354

Yes, can contribute. We would want to just add a check before the line above to make sure that the child_name is in the sampled_data dictionary.

**Comment by npatki** [comment]
Hello, seems this issue has been stale for some time and seems like the newer versions of the SDV may have resolved it. 

I'll close it off as obsolete since I can no longer replicate it. Please feel free to reply if this bug still persists and I can reopen the issue.

**Comment by rahulragunathan** [comment]
Hi Neha,

Thank you for the response. I have not had a chance with the more recent versions of SDV. I will respond here or potentially raise a new ticket if I still do see this issue.
