### ISSUE TITLE
Jinja2>=3.0.0 makes the docs build fail

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#452]
### Environment Details

* SDV version: 0.10.0

### Error Description

The docs build for v0.10.0 failed because of [this error](https://github.com/pydata/pydata-sphinx-theme/issues/394):

```
generating indices...  genindexfailed

Theme error:
An error happened in rendering the page genindex.
Reason: UndefinedError("'meta' is undefined")
make[1]: *** [Makefile:20: html] Error 2
```

The error seems to happen with `Jinja2>=3.0.0`, which was released on May 11th, 2021.

We should cap the Jinja2 version to `<3` to fix the problem, and this should be done directly on the `stable` branch as a hotfix to fix the current docs build.

**Comment by csala** [comment]
Closed via #453

**Comment by jonas-eschle** [comment]
Do you know what is actually happening? I experience the same issue, and capping to <3 helps, but that is more of an ad-hoc way, not a  real solution (I think we want to upgrade to 3 at some point?)

**Comment by csala** [comment]
Not really @jonas-eschle but it seems like the [pydata-sphinx-theme was already adapted to the Jinja change](https://github.com/pydata/pydata-sphinx-theme/pull/395), so upgrading `pydata-sphinx-theme` should make the problem go away.
In our case we did not upgrade yet because we further modified the theme on our side, so we have not had the chance to try it.

**Comment by jonas-eschle** [comment]
Ah I see, makes sense. Thanks for pointing to the thread, I must have overlooked that
