### ISSUE TITLE
Using predefine sequences ranges for specific fields

### ISSUE THREAD

**Issue by avico78** [sdv-dev/SDV#456]
for a single table data (TVAE,CTGAN),
need to generate synthetic data specific starting sequences,
Source data:

```
  record_type source_system     sys_update_date  sequence_1    sequence_1
0        0010           VKD 2021-04-27 09:04:14       1                 30030 
1        0010           VKD 2021-04-27 09:04:14       2                 30031 
2        0010           VKD 2021-04-27 09:04:13       3                 30032
3        0010           VKD 2021-04-27 09:04:13       4                 30033
```
But synthetic data to start with different sequences:

```
  record_type source_system     sys_update_date  sequence_1    sequence_1
0        0010           VKD 2021-04-27 09:04:14       10000         20030 
1        0010           VKD 2021-04-27 09:04:14       10001         20031 
2        0010           VKD 2021-04-27 09:04:13       10002         20032
3        0010           VKD 2021-04-27 09:04:13       10003         20033
3        0010           VKD 2021-04-27 09:04:13       10004         20034
3        0010           VKD 2021-04-27 09:04:13       10005         20035
```

1.Is there an option to define specific column to use predefine list? or any other way?
i.e:
```
N=20035
sequence_1    = pd.DataFrame({ 'sequence_1' : range(20030, N + 1 ,1),})
N=10005
sequence_2    = pd.DataFrame({ 'sequence_2 ' : range(10000 , N + 1 ,1),})
```

2.I couldn't find an explanation or comparison between the models  for a single table.
How do i know which one to choose TVEW/CTGAN/CopulaGAN/GaussianCopula ?
I think it would make things clearer if u add some explanation for differences between them
and which one will work best for a specific use case

**Comment by fealho** [comment]
Hi @avico78, I'm a little confused about your question. You seem to want to generate synthetic data where the columns `sequence_1` and `sequence_2` are predefined values, correct? If that is the case, what you are looking for is conditional sampling. You can read more about how to use it [here](https://sdv.dev/SDV/user_guides/single_table/ctgan.html#conditional-sampling).

Do note that you should set the `sequence` columns to values originally present in your dataset. So if your original dataset only has `sequence_1` going from 1 to 1000, you should only sample conditionally for values in that range.

Regarding your second question, I'm not aware of any simple rule to decide which model to use. I recommend simply trying multiple models to figure out which one is the best for your specific use case.

**Comment by fealho** [comment]
I'll be closing the issue since it seems like it was answered. Feel free to reopen it if you need further clarification.
