### ISSUE TITLE
Model multi-table datasets using non-parametric models (CTGAN, CopulaGAN, etc.)

### ISSUE THREAD

**Issue by abedshantti** [sdv-dev/SDV#457]
### Problem Description

This is more of a question rather than feature request (but it doesn't fit the question issues either). I have noticed that Gaussian Coupla is the default generative model for the relational database HMA1 model. Is there a specific reason why the Gaussian model was used? Would the other synthesizers, such as CTGAN work well for relational data?

### Expected behavior

Using CTGAN might generate even more realistic synthetic children datasets than the Gaussian Coupla model. I am not sure if this something that was implemented earlier with relational databases or not. 

### Ability to contribute

I am available to contribute if the developers want to add the CTGAN as an option when implementing HMA1. Otherwise, I am happy to implement my own solution and submit a pull request if everything works as expected.

**Comment by MLjungg** [comment]
Hi SDV,

I'm curious about the problem description as well – any comment @csala, @npatki?

**Comment by npatki** [comment]
Right now, the HMA1 algorithm is only compatible with single table models that are parametric. `GaussianCopula` is currently our only parametric single table model. You can read more about HMA1 in the original [SDV paper](https://dai.lids.mit.edu/wp-content/uploads/2018/03/SDV.pdf).

We can keep this issue open as a feature request for multi-table algorithms that can use non-parametric models (like CTGAN, CopulaGAN, etc.)

**Comment by npatki** [comment]
I'm closing this issue as resolved, as we now have an [HSASynthesizer](https://docs.sdv.dev/sdv/multi-table-data/modeling/synthesizers/hsasynthesizer) that is capable of using non-parametric models on individual tables.

This is currently available in our private library to licensed users. If you'd like to explore this option, feel free to [contact us](https://datacebo.com/contact/).
