### ISSUE TITLE
Downsampling?

### ISSUE THREAD

**Issue by qwert666** [sdv-dev/SDV#461]
Hi

I have a big tabular dataset that I'm working on and would like to downsample ( or upsample ) it in a way that all the statistical properties are preserved, would using SDV/Copulas be a reasonable approach or just an overkill?

**Comment by npatki** [comment]
Hi Michał,

We've seen members successfully use the SDV to upsample their data sets for a variety of reasons -- if they don't have enough data to begin with, if they want to balance out certain categories to unbias their dataset, etc.

Although I haven't personally seen a case with downsampling, this seems like a reasonable use case as well. I would keep in mind that synthetic data is generated randomly so the [Law of Large Numbers](https://en.wikipedia.org/wiki/Law_of_large_numbers) will apply. That is to say, you might need to hit a certain threshold. Eg. if you have 500k rows and you want to downsample to 5K, that might be reasonable. But if you want to downsample to only 50, you will be subject to more randomness.

Hope this helps. If you're able to use the SDV to successfully downsample (or upsample) the dataset, we'd love to hear back about your experience!

**Comment by qwert666** [comment]
Sure, thanks for your feedback.
