### ISSUE TITLE
SDV PAR Model doesn't capture latitude/longitude properly

### ISSUE THREAD

**Issue by 9harshit** [sdv-dev/SDV#472]
```
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: sdv 0.10.1
* Python version: 3.8
* Operating System: Mac OS

### Problem description

I am trying to generate user location (lat/long) from real data using par model. But the distribution is extremely bad. Generated values are all in the center of the city. Even after 10000 epochs and 500 sample value. I have even tried bigger sample doesnt work with it either.

My real dataset : 

user_id | ts | latitude | longitude
9014490395669211220 | 2021-02-01 00:00 | 13.034033 | 77.557050
4167942243769043381 | 2021-02-01 00:00 | 13.109547 | 77.603560
6325304668018530216 | 2021-02-01 00:00 | 12.907233 | 77.631423



### What I already tried

My code : 
entity_columns = ['user_id']
context_columns= [] 
sequence_index = 'ts'
 
from sdv.timeseries import PAR

model = PAR(context_model = "gaussian_copula",epochs = 10000, entity_columns=entity_columns,  sequence_index=sequence_index,  cuda=True, verbose=True)

model.fit(test_data)

 Standard Deviation (lat | long) : 0.058267 | 0.060721 

Synthetic Data 

  Standard Deviation (lat | long) :  0.005298 | 0.002827


```
Red is synthetic data blue is real.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/43147421/122634725-7d27dd80-d0fd-11eb-8da1-d11f3c955f23.png">

Test data is real data 500 sample description
New data is synthetic data

<img width="671" alt="Screen Shot 2021-06-19 at 12 58 33 PM" src="https://user-images.githubusercontent.com/43147421/122634793-10f9a980-d0fe-11eb-84d8-28ac30d70b6d.png">

**Comment by fealho** [comment]
Thanks for the detailed issue, we'll have a look as soon as possible.

**Comment by 9harshit** [comment]
Hi @fealho thankyou for looking into the issue.

**Comment by npatki** [comment]
Hi @9harshit, seems like there are 2 possibilities:

1. Using RDT and Contextual Anonymization to understand the specific regions -- we had a discussion about this in #469 
2. Setting min/max bounds on the numerical latitude and longitude values. This will achieve the effect of keeping the synthesized values close to the real ones. While this is not yet possible with the `PARModel`, we are tracking this feature request in #745. You can follow along for updates.

I'll close this issue out in favor of the above 2. Please feel free to re-open if there's more to discuss!
