### ISSUE TITLE
How to train PAR model on dataset of 1gb or more?

### ISSUE THREAD

**Issue by 9harshit** [sdv-dev/SDV#486]
### Problem description

I am trying to train PAR model but my dataset is too large (35 million rows in it), and it won't fit in RAM, any suggestions on how to train in because there is no batch size hyperparameter in PAR documentation

**Comment by fealho** [comment]
Hi @9harshit, thanks for reporting this. Adding a batch size hyperparameter is actually something we are considering for the future. We'll let you know if/when we decide to implement it (or some alternative solution).

**Comment by 9harshit** [comment]
Hi @fealho looking forward for the update

**Comment by npatki** [comment]
Hi @9harshit, right now our models are not set up for incremental training. Once we do this, it would be easy to load the data in batches for updates.

We have an ongoing discussion about this, so I'll resolve this issue in favor of #805. Feel free to follow along and add any feedback/ideas to it.
