### ISSUE TITLE
UniqueCombinations constraint for more than 2 columns

### ISSUE THREAD

**Issue by onacrame** [sdv-dev/SDV#494]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.10
* Python version: 3.9
* Operating System: Windows

### Error Description

I was under the impression that adding a list of columns (more than 2) would constrain the model in respect of the combinations of categories represented by those columns but it does not seem to work. I see nulls generated where there should be none

### Steps to reproduce

I can’t share my example due to privacy etc. but imagine that a toy example where a list of three categories passed to uniquecombinations would probably generate the same result.

**Comment by tjhallum** [comment]
This issue of nan values being generated is **_NOT_** just limited to cases in which a UniqueCombinations constraint is applied to more than two columns. The generation of nan values likewise occurs when the UniqueCombinations constraint is applied to only two columns. A full reproducible example is provided in the form of a Jupyter Notebook attached to this issue: https://github.com/sdv-dev/SDV/issues/521.

**Comment by csala** [comment]
A full explanation of what caused this issue has been added in the PR that closed it.
