### ISSUE TITLE
Improve usage for writing & supplying a custom constraint

### ISSUE THREAD

**Issue by onacrame** [sdv-dev/SDV#495]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.10
* Python version: 3.9
* Operating System: Windows

### Error Description

I trained a CopulaGan model with a custom is_valid type constraint and saved it to disk.  Upon load though the model load fails with an AttributeError because it cannot find the requisite is_valid constraint as per below.  My custom constraint applies certain checks to ensure a row is validAre there any workarounds?

---------------------------------------------------------------------------
```
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f4b86dbcd5a8> in <module>
----> 1 model = CopulaGAN.load('E:/synthetic_model')

e:\Continuum\Miniconda3\envs\synthetic2\lib\site-packages\sdv\tabular\base.py in load(cls, path)
    523         """
    524         with open(path, 'rb') as f:
--> 525             return pickle.load(f)

AttributeError: Can't get attribute 'is_valid' on <module '__main__'>
```

### Steps to reproduce

Unfortunately can't share any code.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by onacrame** [comment]
I was able to load the model after including an if __name__ == '__main__' block and defining the constraint within that block before loading the pickled model.  Maybe documentation should be more clear here in the absence of a direct fix.

**Comment by npatki** [comment]
@onacrame thanks for filing and explaining. Let's keep this bug open. The team is actively thinking about improving the constraints usage, including how to write and use custom constraints.

I'll update the title to reflect that.

**Comment by npatki** [comment]
Hi @onacrame, the newest SDV release, v0.16.0, now includes an updated API for defining and using custom constraints.

Check out the [Custom Constraints User Guide](https://sdv.dev/SDV/user_guides/single_table/custom_constraints.html) for more info.
