### ISSUE TITLE
Relational data generation talking long time

### ISSUE THREAD

**Issue by kvrameshreddy** [sdv-dev/SDV#498]
* SDV version: 0.10.0
* Python version: 3.8.10
* Operating System: Windows 10

### Problem description
The relational data of three tables is taking hours to generate 10000 records.

### What I already tried
```python
from sdv.relational import HMA1
from sdv import Metadata
import pandas as pd

Emp=pd.read_csv("Emp.csv")
Dept=pd.read_csv("Dept.csv")
Emp_dept_hist=pd.read_csv("Emp_dept_hist.csv")

table={'Emp':Emp,'Dept':Dept,'Emp_dept_hist':Emp_dept_hist}

metadata1 = Metadata()
metadata1.add_table(name='Emp', data=table['Emp'],primary_key='BusinessEntityID')
metadata1.add_table(name='Dept', data=table['Dept'],primary_key='DepartmentID')
metadata1.add_table(name='Emp_dept_hist',data=table['Emp_dept_hist'])
metadata1.add_relationship(parent='Emp', child='Emp_dept_hist')
metadata1.add_relationship(parent='Dept', child='Emp_dept_hist')

model=HMA1(metadata1)
model.fit(table)
df_synth1 = model.sample(num_rows=10000)
```
[SDV_data.zip](https://github.com/sdv-dev/SDV/files/6753896/SDV_data.zip)

Can you please take a look into this and please let me know why generation is taking more time.

Thanks

**Comment by tim5go** [comment]
@kvrameshreddy 
Encountering the same problem

**Comment by kvrameshreddy** [comment]
Hi @tim5go, 
Did you got any chance to find the exact reason why it is taking that long to generate data.

**Comment by tim5go** [comment]
@kvrameshreddy 
Not close, but I am suspecting it may be related #310.
From my understanding, the **HMA1** model, by default, will apply GaussianCopula to categorical data, which is a problem.

**Comment by Ganstrich** [comment]
Hello, 
After looking in the code, I think the generation is taking so long using HMA1 because of a for loop in here : 
https://github.com/sdv-dev/SDV/blob/ccfccdcc412864904fceea451b40390f7c0ef7ca/sdv/relational/hma.py#L347-L355

This function iterates over all the parent table rows to generate child rows. Maybe something more efficient can be done ? 
Happy to discuss, 
Thanks to the SDV Team for a wonderful work !
