### ISSUE TITLE
Improve error message for `ColumnFormula` constraint when constraint column used in formula

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#508]
Using the `ColumnFormula` constraint where the constraint column is used in the constraint formula crashes with a `KeyError`. While this is expected, the error message could be improved to provide a more meaningful explanation of what's causing the issue. 

Below is some code to produce this error:
```python3
import pandas as pd
from sdv.constraints import *
from sdv.tabular import *

ones = [1 for i in range(10)]
data = pd.DataFrame({
    'a': ones,
    'b': ones,
    'c': ones
})

def formula(data):
    return data['a']

constraint = ColumnFormula(
    column='a',
    formula=formula
)

model = GaussianCopula(constraints=[constraint])
model.fit(data)
samples = model.sample(10)
```

**Comment by katxiao** [comment]
Instead of updating the comment, we will add an argument to optionally keep the original column instead of always dropping it.
