### ISSUE TITLE
`UniqueCombinations` constraint outputting wrong data type

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#510]
The `UniqueCombinations` constraint can sometimes produce the wrong output data type. For example, if the passed input only contains integers, the output is expected to be made of only integers as well. Instead, sometimes it can produce floats. Below is some code that runs this example.

```python3
import pandas as pd
from sdv.constraints import *
from sdv.tabular import *

zero_to_nine = [i for i in range(10)]
data = pd.DataFrame({
    'a': zero_to_nine,
    'b': zero_to_nine,
    'c': zero_to_nine
})

constraint = UniqueCombinations(
    columns=['a', 'b'],
)

model = CTGAN(constraints=[constraint])
model.fit(data)
samples = model.sample(10, conditions={'a': 1})
samples
```

The code above returns the following: 
```
	a	b	c
0	1	1.0	5
1	1	1.0	6
2	1	1.0	5
3	1	1.0	2
4	1	1.0	3
5	1	1.0	3
6	1	1.0	6
7	1	1.0	4
8	1	1.0	2
9	1	1.0	4
```

**Comment by onacrame** [comment]
I also get nulls produced by unique combinations

**Comment by onacrame** [comment]
I'll see if I can produce a simple example.  I should note that the proportion of joint nulls across the specific columns was small relative to the valid data

**Comment by tjhallum** [comment]
I just saw this comment above by @onacrame:

> I also get nulls produced by unique combinations

I have an open issue about this same problem: https://github.com/sdv-dev/SDV/issues/521

**Comment by csala** [comment]
A full explanation of what caused this issue has been added in the PR that closed it.
