### ISSUE TITLE
What are the Default Transformers for each Field Type/Subtype?

### ISSUE THREAD

**Issue by tjhallum** [sdv-dev/SDV#519]
SDV version: 0.11.0
Python version: 3.6.8
Operating System: Windows 10

Are the default transformers for each field type/subtype documented yet?

I'd like to start iteratively experimenting with different types of transformers for each field type/subtype...but since I don't know which transforms are being applied by default...I'm not really sure which ones I've already tried as a matter of course and which ones I still need to experiment with.

**Comment by npatki** [comment]
Hi @tjhallum, the default transformers are not documented anywhere. We can turn this into a request for documentation.

Note that different models are optimized for different sets of transformers. Until we add the documentation, you'll only be able to answer this by looking at the code.

For example, [here](https://github.com/sdv-dev/SDV/blob/master/sdv/metadata/table.py#L109) you can find a base set of starting transformers. However, each model will override certain ones -- eg [GaussianCopula](https://github.com/sdv-dev/SDV/blob/master/sdv/tabular/copulas.py#L125) works best with categorical fuzzy.

If there is a particular model you are interested in, let me know and I can summarize them here.

**Comment by npatki** [comment]
HI @tjhallum -- this issue has now been resolved by our new SDV 1.0 (Beta) release.

For any synthesizer you create, you can get the RDT objects using `get_transformers()`. For more details, see the [transformers API](https://docs.sdv.dev/sdv/single-table-data/modeling/advanced-features/transform-and-anonymize#viewing-the-transformations).
