### ISSUE TITLE
Synchronize CopulaGAN and CTGAN hyperparameters

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#520]
PRs #334 and #277 introduced new CTGAN hyperparameters that are not properly exposed in the `CopulaGAN` class, either because they are just not there, like `pac`, or because they are not listed in the `docstring`, like `discriminator_lr`.

`CopulaGAN` should be updated to ensure that all the available `CTGAN` hyperparameters are both exposed and described in the docstring.

**Comment by npatki** [comment]
This issue has now been resolved in our SDV 1.0 (Beta) release.

The [CopulaGANSynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/copulagansynthesizer#parameter-reference) contains the same GAN-based parameters available in the [CTGANSynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer#parameter-reference).
