### ISSUE TITLE
UniqueCombinations constraint with handling_strategy = 'transform' yields synthetic data with nan values

### ISSUE THREAD

**Issue by tjhallum** [sdv-dev/SDV#521]
### Environment Details

SDV version: 0.11.0
Python version: 3.6.8
Operating System: Windows 10

### Error Description

When applying a `UniqueCombinations` constraint with `handling_strategy = 'transform'`, the CTGAN model produces some synthetic observations that exhibit `nan` values for those columns specified within the constraint (_despite training the `CTGAN` model on **nan-free data**_).

This screen capture illustrates the bug:

![image](https://user-images.githubusercontent.com/53157308/126512114-7ea510a3-cc87-4330-ba82-45f625b39d40.png)

### Steps to reproduce

The full Jupyter Notebook that reproduces this bug is attached (the notebook pulls it's own data from the web): 
[generate_adversarial_data-ctgan.zip](https://github.com/sdv-dev/SDV/files/6856991/generate_adversarial_data-ctgan.zip)

**Comment by csala** [comment]
A full explanation of what caused this issue has been added in the PR that closed it.
