### ISSUE TITLE
Contrary to documentation, the transform strategy with UniqueCombinations does slow down model fitting

### ISSUE THREAD

**Issue by tjhallum** [sdv-dev/SDV#522]
### Environment Details

SDV version: 0.11.0
Python version: 3.6.8
Operating System: Windows 10

### Error Description

When applying a `UniqueCombinations` constraint with `handling_strategy = 'transform'` to TVAE/CTGAN models being trained on > 2,000 observations, the time required for model fitting increases considerably (even worse, the increased time requirement does not appear linearly correlated to the size of the training set).

As an example, my computer can fit non-constrained TVAE/CTGAN models on 10,000 observations of airline data within just a few minutes. By contrast, I added a `UniqueCombinations` constraint with `handling_strategy = 'transform'` and had to stop the model fitting process at 1 hour...because I wasn't sure exactly how long the model fitting was going to take.

This behavior is in direct conflict with the Handling Constraints User Guide, which states that the transform strategy for constraints "[is very efficient and does not affect the speed of the modeling and sampling process, but in some cases might affect the quality of the learning process or simply not be possible.](https://sdv.dev/SDV/user_guides/single_table/constraints.html#:~:text=The%20Transform%20strategy%20is%20very%20efficient%20and%20does%20not%20affect%20the%20speed%20of%20the%20modeling%20and%20sampling%20process%2C%20but%20in%20some%20cases%20might%20affect%20the%20quality%20of%20the%20learning%20process%20or%20simply%20not%20be%20possible.)" 

### Steps to reproduce

The full Jupyter Notebook that reproduces this behavior is attached (the notebook pulls it's own data from the web): [generate_adversarial_data-tvae.zip](https://github.com/sdv-dev/SDV/files/6863552/generate_adversarial_data-tvae.zip)

**Comment by katxiao** [comment]
Thanks for the issue @tjhallum! 

We believe that this is because the current default behavior of UniqueCombinations sets `fit_column_model=True`, which fits a GaussianCopula model to the constraint columns. We are working on updating it to `fit_column_model=False` by default. In the meantime, you could try manually setting the parameter to `False` and seeing if that solves the performance issue.
