### ISSUE TITLE
Document that HMA1 can only work with parametric models

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#537]
The HMA1 class can only work in combination with parametric tabular models, and sometimes this generates confusion, as seen in issues #340 and #526.

The error message shown when a non-parametric model is used will be improved in the issue #362 , but the limitation should also be added in the [HMA1 User Guide](https://sdv.dev/SDV/user_guides/relational/hma1.html) and [API Reference](https://sdv.dev/SDV/api_reference/relational/api/sdv.relational.hma.HMA1.html#sdv.relational.hma.HMA1) sections of the documentation.

**Comment by npatki** [comment]
This issues has been resolved by the SDV 1.0 (Beta). We no longer allow users to set a single table model but they can supply any parameters that GaussianCopula contains. The technical details also mention that HMA uses GaussianCopula.

[See HMASynthesizer docs](https://docs.sdv.dev/sdv/multi-table-data/modeling/hmasynthesizer) for more details.
