### ISSUE TITLE
Implement proper unit tests for BaseTabularModel

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#543]
The tests found in https://github.com/sdv-dev/SDV/blob/master/tests/unit/tabular/test_base.py are not properly implemented and should be re-written.

The changes required are:
- All the tests should be created inside a class called `TestBaseTabularModel`.
- Each test should cover only one method of the class, mocking everything else if necessary.
- Subclasses of the `BaseTabularModel` should not be used. These should to be tested on their own test modules.

**Comment by npatki** [comment]
Since we've released SDV 1.0, I believe most unit/integration tests have be re-written and this issue is stale.

@amontanez24 to correct if I'm wrong (feel free to reopen the issue if so).
