### ISSUE TITLE
Upgrade dependency ranges

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#556]
The latest versions of some libraries are not currently supported:

| Library | Upper bound (unsupported) | Latest release |
|-|-|-|
|'Faker'|4.15|8.11|
| `pandas` | 1.1.5 | 1.3.1 |
| `pomegranate` | 0.14.2 | 0.14.5 |
| `sktime` | 0.6 | 0.7.0 |

We should investigate why and update the code if necessary to support them.

**Comment by npatki** [comment]
This issue is now stale, as we've made several dependency updates since.

See [setup.py](https://github.com/sdv-dev/SDV/blob/master/setup.py) for more info.

-  `faker` is capped at `15`
- `pandas` is uncapped
- `pomegranate` is capped at `0.15.0`
- `sktime` is no longer a dependency
