### ISSUE TITLE
Updating the supported versions of `pandas`

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#558]
The libraries currently support versions 1.1 through 1.1.5. Versions before 1.1 don't work for all the libraries, and versions after 1.1.5 crash for Copulas. We could try to look into why that happens and see if we can update the code to support the latest versions of pandas.

**Comment by csala** [comment]
I just opened issue [#266](https://github.com/sdv-dev/Copulas/issues/266) on Copulas to cover the upgrade there.
