### ISSUE TITLE
HMAI not accepting constraints

### ISSUE THREAD

**Issue by nviets** [sdv-dev/SDV#566]
### Environment Details

* SDV version: 0.11.0
* Python version: 3.7

### Error Description

HMA1 does not accept constraints. If my syntax is incorrect, could someone please clarify what's required?

```
constraints = [
   balance_limit_constraint,
   pos_dollars_constraint
]

KWARGS = {
   'default_distribution': 'gaussian',
   'categorical_transformer': 'categorical_fuzzy',
   'constraints': 'constraints'
}

model = HMA1(metadata, model_kwargs=KWARGS)
```

```
...
site-packages/sdv/tabular/base.py", line 106, in __init__
    'If table_metadata is given {} must be None'.format(arg.__name__))
AttributeError: 'str' object has no attribute '__name__'
```

**Comment by npatki** [comment]
Hello,

The `HMA1` model doesn't natively support constraints right now. You might be interested in following #296, and [this workaround](https://github.com/sdv-dev/SDV/issues/296#issuecomment-879752976) in the meantime.
