### ISSUE TITLE
There is lot of warning messages!

### ISSUE THREAD

**Issue by dariush-bahrami** [sdv-dev/SDV#568]
After creating an instance of `CTGAN` and running its `fit` method following warnings showed a lot:
* dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
* dist-packages/sklearn/mixture/_base.py:269: ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)
* dist-packages/sklearn/mixture/_base.py:269: ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)

**Comment by csala** [comment]
Hi @dariush-bahrami Thanks for pointing this out.

I already took note of the `FutureWarning` in issue #569. The rest are expected and are usually seen even if the fitting process was successful, so you can safely ignore them.

If you want to [silence them](https://docs.python.org/3/library/warnings.html#overriding-the-default-filter), you can to add these two lines in your code (or notebook) before running the model:

```python3
import warnings

warnings.filterwarnings('ignore')
```
