### ISSUE TITLE
Adapt to sklearn 1.0 kwargs

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#569]
scikit-learn is issuing a `FutureWarning` about a keyword argument that will be deprecated soon (see #568 )

```
dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
"will result in an error", FutureWarning)
```

We should find where this keyword argument is being used and adapt it to the new style before the new sklearn is released.

**Comment by srinify** [comment]
AFAIK this isn't relevant anymore
