### ISSUE TITLE
Labels for CTGAN

### ISSUE THREAD

**Issue by khanwa** [sdv-dev/SDV#575]
How CTGAN learns the distribution for multi-class data? How does it consider the Label?

If we give a multi-class labelled data "ctgan.fit(data, discrete_columns)" to CTGAN then how it treats the class information?  I tried to look for the class information but couldn't found. (In Conditional GAN we specify "y_train"). 

Thanks you

**Comment by npatki** [comment]
Hi @khanwa, the discrete labels are one hot encoded. CTGAN is specifically designed to evenly explore all discrete values by considering the encoded labels as conditional inputs.

For more information, I'd recommend reading the [CTGAN paper](https://arxiv.org/pdf/1907.00503.pdf) which provides more insight into the algorithm.

**Comment by npatki** [comment]
Hello, this issue has been stale for some time now. Since we've answered your initial question, I'll close it off. 

Feel free to reply if there is more to discuss and I'll reopen the issue.
