### ISSUE TITLE
Model configuration guidelines

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/SDV#582]
### Problem Description

It can be unclear how to optimize a model's performance, either by selecting the appropriate model or by tuning the available hyperparameters.

### Expected behavior

We should create a model configuration cheat sheet that includes
1. Model selection - how to select the appropriate model
2. Hyperparameter guidelines for each model (Possibly create a function that returns the recommended configuration?)
3. Guidelines to how to optimize hyperparameters and how to debug models given any observed discrepancies. (Example: Majority categories being oversampled may mean the number of epochs was too low)

**Comment by npatki** [comment]
I think the crux of this issue has been resolved by creating Presets: our new approach for "recommending" model and hyperparameters through directly configuring these as new presets (see #715 and #716).

As for debugging/FAQs, this is something we should consider when updating the SDV documentation. It might be best to file separate issues for each parameter as we update the SDV models & abstractions.

Shall we close this issue as resolved? Feel free to re-open if I've missed something or you think it's still worth tracking for the documentation changes.
