### ISSUE TITLE
Improve categorical column quality: Use label encoding (+noise)

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/SDV#583]
### Problem Description

When modeling a categorical column with two categories, sometimes the less frequent value is not sampled.  

### Expected behavior

Modeling the binary categorical column as a boolean column seems to fix this issue, so that both values are sampled.

**Comment by npatki** [comment]
This issue has now been resolved, as SDV 1.0 now assigns Label Encoding (with noise) by default to all categoricl and boolean columns.
