### ISSUE TITLE
Improve CTGAN performance by customizing categorical column transformations

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/SDV#584]
### Problem Description

CTGAN fails to finish in reasonable times on datasets like Airbnb and Housing Market.

### Expected behavior

We should review CTGAN speed on big datasets by figuring out what the current limitation is (number of columns/rows/categorical variables). We can then create a plan of action for improving the performance.

**Comment by fealho** [comment]
One of the main limiting factors of CTGAN is the number of categorical values. Anything in the hundred's will slowdown the model manifold. In such cases, it may be better to have a hyperparameter that allows you to treat categorical values as numerical which defaults to 200 (so if there are more than 200 categories, it will be treated as a numerical).

**Comment by npatki** [comment]
As mentioned in the previous issue I'm closing this out, as it is now possible to assign transformers to CTGAN's data. 

However, there is still an issue that CTGAN is treating the column as discrete instead of continuous, which is being tracked in #1450
