### ISSUE TITLE
Improve modeling of internally created columns 

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/SDV#585]
### Problem Description
Improve modeling of internally created columns 

### Expected behavior

We should skip the distribution selection for internally created columns and rather pin the right distribution (especially if the columns are boolean).

**Comment by npatki** [comment]
> especially if the columns are boolean

When the original data has missing columns, the SDV models this by internally creating a new boolean column (`is_missing`) -- #551 might be a related issue

**Comment by npatki** [comment]
This overall issue has been resolved, as we no longer perform a univariate search for each column. For Gaussian Copula, any new columns that we create will now use the `default_distribution`.

```python
from sdv.datasets.demo import download_demo
from sdv.single_table import GaussianCopulaSynthesizer
from rdt.transformers.datetime import UnixTimestampEncoder

data, metadata = download_demo(
    modality='single_table',
    dataset_name='fake_hotel_guests'
)

synth = GaussianCopulaSynthesizer(metadata,
                                  default_distribution='beta')
synth.auto_assign_transformers(data)
synth.update_transformers({
    'checkout_date': UnixTimestampEncoder(model_missing_values=True)
})

synth.fit(data)
synth.get_learned_distributions()['checkout_date.is_null']
```
```
{
 'distribution': 'beta',
 'learned_parameters': {
   'loc': 0.005942405330242786,
   'scale': 0.9940575946697573,
   'a': 0.11207783853374471,
   'b': 0.11396787614933043
 }
}
```

Note that you cannot specify an explicit distribution for these columns. But we could treat that as a different feature request, if this is needed by our users.
