### ISSUE TITLE
getting error "decoding to str: need a bytes-like object, int found" while running command "new_data = model.sample()"

### ISSUE THREAD

**Issue by sharmin-sultana-sheuly** [sdv-dev/SDV#594]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:0.12.0 (not sure, installed it yesterday with command "pip install sdv")
* Python version:Python 3.7.11
* Operating System: windows 10

### Problem description

I fitted the svd model and saved it .However, when I run the command "new_data = model.sample()" it gives error :
**/usr/lib/python3.7/re.py in escape(pattern)
    259         return pattern.translate(_special_chars_map)
    260     else:
--> 261         pattern = str(pattern, 'latin1')
    262         return pattern.translate(_special_chars_map).encode('latin1')
    263 
TypeError: decoding to str: need a bytes-like object, int found**

The data that I used is like this
![image](https://user-images.githubusercontent.com/83068238/133764399-698e5987-5049-41bd-87d4-954bb7c7e5a5.png)

<Replace with a description of what you already tried and what is the behavior that you observe.
If possible, also add below the exact code that you are running.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @sharmin-sultana-sheuly I'm closing this issue off since it's been inactive for some time. Please feel free to re-open if you have any further questions or feedback!
