### ISSUE TITLE
Fix NaN problem that happens when modelling

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#6]
* SDV version:
* Python version:
* Operating System:

### Description

Covariance matrices are being filled with NaNs. This is likely because column of foreign key is being modeled (all values are the same which causes that column to become all NaNs when creating a copula from it).

### What I Did

Running RCPA causes many of the copula models to get covariance matrices filled with NaNs

**Comment by kvrameshreddy** [comment]
Thank you @amontanez24 . Can you please check this issue #172. I am unable to solve it.
