### ISSUE TITLE
Sample() can only return up to the number of rows used for the fitting if a unique constraint is used

### ISSUE THREAD

**Issue by xamm** [sdv-dev/SDV#612]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.12.1
* Python version: 3.8.10
* Operating System: Linux

### Error Description

When sampling from a model created with a `Unique` constraint, the `num_rows` parameter is partially ignored.
The number of rows sampled cannot exceed the number of rows passed to the model during fitting.

### Steps to reproduce

- Create a DataFrame to fit the model
- Create a model, specify a unique constraint
- Fit the model passing the created DataFrame
- Sample more rows than included in the DataFrame for fitting

```
def test_sample_more_rows_with_unique_constraint_than_original_data():
    """Test that the ``sample`` method returns the amount of rows specified.
    Even when this exceeds the number of rows in the real data
    and also when constraints are specified.

    The ``sample`` method is expected to sample the amount of rows specified.

    Setup:
    - The model is created with a unique constraint specified.
    - The model is fit on the whole DataFrame.

    Input:
    - DataFrame utilizing unique constraint.
    """
    # Setup
    test_df = pd.DataFrame({
        "key": [
            1,
            2,
            3,
            4,
            5,
        ],
        "error_column": [
            "A",
            "B",
            "C",
            "D",
            "E",
        ]
    })
    unique = Unique(
        columns=["error_column"]
    )
    model = GaussianCopula(constraints=[unique])

    # Run
    model.fit(test_df)

    # Assert
    assert len(model.sample(10)) == 10
```

**Comment by vspr14** [comment]
I have the same problem but with a datetime column. Adding a unique constraint to a datetime column and specifying the number of rows to be greater than the size of the original dataset leads to diminished number of rows being returned as a result.

SDV version: 1.14.0
Python version: 3.12.2
Operating System: MacOS
