### ISSUE TITLE
SDV CTGAN and TVAE both use CPU instead of the GPU

### ISSUE THREAD

**Issue by astrogilda** [sdv-dev/SDV#628]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.12.1
* Python version: 3.7
* Operating System: Ubuntu 20 LTS

### Error Description

My sdv CTGAN generator (from sdv.tabular import CTGAN) automatically uses the CPU for training, in spite of cuda=True when defining the CTGAN object. How do I fix this?

### Steps to reproduce
from sdv.tabular import CTGAN, TVAE
generator_ctgan = CTGAN(batch_size=1000, epochs=100, generator_lr=5e-4, discriminator_lr=5e-4, verbose=True)
_ = generator_ctgan.fit(X_val)

When I do nividia-smi, the GPU usage is at 3%, whereas with `top`, the CPU usage is at 2400%, meaning it's using all 12 cores of my CPU.

**Comment by katxiao** [comment]
Hi @astrogilda, thanks for your question.

`CTGAN` uses CPU initially to fit the data transformer and train gaussian mixtures. It can sometimes take a while (up to half of the total fitting time) to complete this initial step.

When you ran with `verbose=True`, did you reach the point of seeing logs that display the epochs and losses? At that point, we should be utilizing the GPU.

**Comment by npatki** [comment]
Hi everyone, I'm closing this issue out since we've discussed the question and it's been inactive for a while. Please feel free to re-open if you have any further questions or feedback!
