### ISSUE TITLE
Is it possible to use conditions and constraints in multi table?

### ISSUE THREAD

**Issue by Puspak64** [sdv-dev/SDV#637]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.12.0
* Python version: 3.8
* Operating System: Windows

### Problem description
I want to put some conditions or constraints in one of the table in multi-table evaluation. I have pasted the json format where i have put condition in bold in user table json. Is there any way to achieve the same since we are doing it for the single table?

{
    "tables": {
        "users": {
            "fields": {
                "user_id": {
                    "type": "id",
                    "subtype": "integer"
                },
                "country": {
                    "type": "categorical"
                },
                "gender": {
                    "type": "categorical"
                },
                "age": {
                    "type": "numerical",
                    "subtype": "integer"
                }
            },
            "primary_key": "user_id",
            **"conditions":{"age" : 20}**
        },
        "sessions": {
            "fields": {
                "session_id": {
                    "type": "id",
                    "subtype": "integer"
                },
                "user_id": {
                    "type": "id",
                    "subtype": "integer",
                    "ref": {
                        "table": "users",
                        "field": "user_id"
                    }
                },
                "device": {
                    "type": "categorical"
                },
                "os": {
                    "type": "categorical"
                },
                "minutes": {
                    "type": "numerical",
                    "subtype": "integer"
                }
            },
            "primary_key": "session_id"
        },
    }
}

**Comment by katxiao** [comment]
Hi @Puspak64, thanks for your question. We are tracking the issue of passing tabular constraints to HMA1 [here](https://github.com/sdv-dev/SDV/issues/296). You can also find a workaround in the linked issue.

We don't currently support using conditions with multi-table, but are planning on adding that through conditional sampling, similar to what is currently supported in our single table models. We will track this feature request [here](https://github.com/sdv-dev/SDV/issues/661).

**Comment by katxiao** [comment]
I'm going to close out this issue in favor of the other two issues that are linked in my above comment. Please feel free to track the multi-table conditional sampling and constraint functionality there!
