### ISSUE TITLE
Metric evaluation error handling

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/SDV#638]
### Problem Description

When a metric returns `nan`, [evaluate](https://github.com/sdv-dev/SDV/blob/master/sdv/evaluation.py#L136) will drop the metric completely. As a result, when a metric errors out, it is omitted from the results. We should print a warning or display it as an error, so that end users know the metric was supposed to run but was not computed successfully.

**Comment by npatki** [comment]
When you call `evaluate` with `aggregate=False`, it would be nice to print out all the metrics that were attempted. That way, it's easy to see:
- Which metrics are considered. This should be the same for different synthesizers, and it's unexpected when that's not the case.
- How many metrics errored, potentially for what reasons

**Comment by cafornaca** [comment]
Evaluation on official documentation is showing errors: https://sdv.dev/SDV/user_guides/evaluation/evaluation_framework.html

![image](https://user-images.githubusercontent.com/10930318/152427326-0065bbd8-4a08-4e1b-94e3-59599126a6a1.png)

**Comment by katxiao** [comment]
@cafornaca These errors are expected -- Those metrics are Machine Learning Efficacy metrics, and the user needs to specify which column is the target column that is going to be predicted. Since we now expect to see all attempted metrics and the corresponding errors, these errors are now shown in this table.

We may want to add more actionable errors, or an option to ignore errors (cc @npatki)
