### ISSUE TITLE
Use transformed data for multiple models or subsequent fitting runs (pipelining SDV).

### ISSUE THREAD

**Issue by xamm** [sdv-dev/SDV#643]
### Problem Description

When fitting a model, the input data is first transformed, and then the model is trained using the transformed data.
The transformation of the data accounts for a large portion of the actual fitting time for the model. Moreover, this transformation is performed on the CPU.

The transformed inputs are not stored, and for each model fitting, the inputs must be transformed again.
When evaluating multiple models, hyperparameters, or input sizes, this transformation causes a high overhead.

### Expected behavior / Feature request

It would be nice if the processes of data conversion and training of the actual SDV model were split into two parts.
This would allow the data to be transformed first and then the transformed data to be reused and also shared.

### Advantages

- Transformed inputs can be reused / shared
- Larger inputs can be transformed and then sampled for fitting
  - Instead of subsetting inputs, transforming them and then fitting them
- Transforming inputs on the CPU, then training on the GPU
  - could make the fitting process more efficient
  - reduces the cost

### Example Pipeline
![general_pipeline gv](https://user-images.githubusercontent.com/39380924/142760952-e7f99eb5-a11e-4a5b-b430-433f278dc745.gif)

**Comment by npatki** [comment]
Hello @xamm, seems like with the introduction of SDV 1.0 this workflow is now possible.

### Recommended Usage
We recommend using the [RDT library](https://docs.sdv.dev/rdt) library directly to transform your original data into numerical data (and back!). You'll need to choose which transformers to use based on what your data represents.

```python
from rdt import HyperTransformer
from rdt.transformers.categorical import LabelEncoder

# preprocess the data ourselves using the RDT library
ht = HyperTransformer()
ht.detect_initial_config(original_data)
ht.update_transformers(column_name_to_transformer={
    'column_name': LabelEncoder(add_noise=True)
})
numerical_data = ht.fit_transform(df) 
```

Now, you can use the numerical data to fit any of the synthesizers.
```python
from sdv.metadata import SingleTableMetadata
from sdv.single_table import GaussianCopulaSynthesizer

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(numerical_data) # this will detect everything as numerical
synth = GaussianCopulaSynthesizer(metadata)
synth.fit(data)
```
Finally, after sampling synthetic data, remember to reverse transform it back to get the original formatting.
```python
raw_synthetic_data = synth.sample(num_rows=1000)
synthetic_data = ht.reverse_transform(raw_synthetic_data)
```

### Feedback
Should this process be easier? We can discuss additional features for the [RDT library](https://github.com/sdv-dev/RDT/issues) that may save time.
