### ISSUE TITLE
Multi-Table model | HMA1 | ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by jinhub** [sdv-dev/SDV#650]
### Error Description

I am facing an issue while using relational multi table model (HMA1) on a relational dataset. I am able to fit the data tables on the model but while generating the sample rows from it. I am getting an exception saying "ValueError: array must not contain infs or NaNs". Does anyone know what might be going wrong here?

Below is a full stack trace:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_38459/4104246050.py in <module>
----> 1 generated_data = model.sample(num_rows=10)

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/relational/base.py in sample(self, table_name, num_rows, sample_children, reset_primary_keys)
    182             self._reset_primary_keys_generators()
    183 
--> 184         return self._sample(table_name, num_rows, sample_children)
    185 
    186     def save(self, path):

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/relational/hma.py in _sample(self, table_name, num_rows, sample_children)
    469         for table in self.metadata.get_tables():
    470             if not self.metadata.get_parents(table):
--> 471                 self._sample_table(table, num_rows, sampled_data=sampled_data)
    472 
    473         return self._finalize(sampled_data)

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/relational/hma.py in _sample_table(self, table_name, num_rows, sample_children, sampled_data)
    428 
    429         if sample_children:
--> 430             self._sample_children(table_name, sampled_data, table_rows)
    431 
    432         return sampled_data

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/relational/hma.py in _sample_children(self, table_name, sampled_data, table_rows)
    350                 LOGGER.info('Sampling rows from child table %s', child_name)
    351                 for _, row in table_rows.iterrows():
--> 352                     self._sample_child_rows(child_name, table_name, row, sampled_data)
    353 
    354                 child_rows = sampled_data[child_name]

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/relational/hma.py in _sample_child_rows(self, table_name, parent_name, parent_row, sampled_data)
    331         table_meta = self._models[table_name].get_metadata()
    332         model = self._model(table_metadata=table_meta)
--> 333         model.set_parameters(parameters)
    334 
    335         table_rows = self._sample_rows(model, table_name)

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/tabular/base.py in set_parameters(self, parameters)
    568 
    569         if self._metadata.get_dtypes(ids=False):
--> 570             self._set_parameters(parameters)
    571 
    572     def save(self, path):

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/tabular/copulas.py in _set_parameters(self, parameters)
    480         """
    481         parameters = unflatten_dict(parameters)
--> 482         parameters = self._rebuild_gaussian_copula(parameters)
    483 
    484         self._model = copulas.multivariate.GaussianMultivariate.from_dict(parameters)

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/tabular/copulas.py in _rebuild_gaussian_copula(self, model_parameters)
    466         covariance = model_parameters.get('covariance')
    467         if covariance:
--> 468             model_parameters['covariance'] = self._rebuild_correlation_matrix(covariance)
    469         else:
    470             model_parameters['covariance'] = [[1.0]]

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/tabular/copulas.py in _rebuild_correlation_matrix(cls, triangular_covariance)
    438         correlation += np.identity(size)
    439 
--> 440         return cls._get_nearest_correlation_matrix(correlation).tolist()
    441 
    442     def _rebuild_gaussian_copula(self, model_parameters):

/codemill/khabiya/venv/lib64/python3.7/site-packages/sdv/tabular/copulas.py in _get_nearest_correlation_matrix(matrix)
    376         Insipired by: https://stackoverflow.com/a/63131250
    377         """
--> 378         eigenvalues, eigenvectors = scipy.linalg.eigh(matrix)
    379         negative = eigenvalues < 0
    380         identity = np.identity(len(matrix))

/codemill/khabiya/venv/lib64/python3.7/site-packages/scipy/linalg/decomp.py in eigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals, type, check_finite, subset_by_index, subset_by_value, driver)
    443                          ''.format(driver, '", "'.join(drv_str[1:])))
    444 
--> 445     a1 = _asarray_validated(a, check_finite=check_finite)
    446     if len(a1.shape) != 2 or a1.shape[0] != a1.shape[1]:
    447         raise ValueError('expected square "a" matrix')

/codemill/khabiya/venv/lib64/python3.7/site-packages/scipy/_lib/_util.py in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    291             raise ValueError('masked arrays are not supported')
    292     toarray = np.asarray_chkfinite if check_finite else np.asarray
--> 293     a = toarray(a)
    294     if not objects_ok:
    295         if a.dtype is np.dtype('O'):

/codemill/khabiya/venv/lib64/python3.7/site-packages/numpy/lib/function_base.py in asarray_chkfinite(a, dtype, order)
    487     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
    488         raise ValueError(
--> 489             "array must not contain infs or NaNs")
    490     return a
    491 

ValueError: array must not contain infs or NaNs

**Comment by vishal-singh-sumup** [comment]
Facing the same above issues while generating the data. 
Is anyone is looking into this issues.

**Comment by npatki** [comment]
Hi @vishal-singh-sumup, are you able to share the metadata that describes your dataset? This will help us replicate the issue.

**Comment by vishal-singh-sumup** [comment]
@npatki, Yeah happy to share!
The model didn't support NaN values as in the dataset, one attribute has the NaN Values.
And the another issues is regarding the Primary and Secondary Keys.
The model expect somewhere around 30 to 40 % (its not mentioned in the docs as far as i know, it's my observation after doing many failed trails) of foreign key to be present in the child table when feeding the data to the model.
The error was showing "Key Error" which was very abstract to track down the root cause. As it was not very clear.
The other challenges was using constraints but we figured out the way to handle after altering the data.

**Comment by npatki** [comment]
Thanks for sharing @vishal-singh-sumup.

Right, the HMA1 model is not able to support `NaN` values key or ID columns. I don't think many databases support such a construct, but do let me know if you see a use case for it.

However, if you are seeing issues when `NaN` is in any other column (not a key or id column), then this might be a bug. Feel free to file a bug with any other details you are able to provide that would help us replicate.

**Comment by npatki** [comment]
Hello, just checking in again. I'll consider this issue closed, as it seems to be caused by key/ID columns having `NaN` values. If you'd like to see support for this, I encourage you to [file a feature request](https://github.com/sdv-dev/SDV/issues/new/choose).
