### ISSUE TITLE
evalute() from sdv.evaluation not working

### ISSUE THREAD

**Issue by cafornaca** [sdv-dev/SDV#651]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.12.1 (sdmetrics 0.3.2)
* Python version: Python 3
* Operating System: Windows 10

### Error Description

Original inquery on Slack can be found [here](https://sdv-space.slack.com/archives/C01H85E9Q8H/p1638134343048300).

Error with ```evaluate(synthetic_data, original_data)``` and ```evaluate(synthetic_data, original_data, aggregate=False)```. Blank table is generated when aggregate is set to false. NaN is received without setting aggregate to false. 

All dataframes fed to ```evaluate()``` were confirmed to be Pandas dataframes that were successfully and correctly read in.

### Steps to reproduce

Used  ```evaluate(synthetic_data, original_data)``` and ```evaluate(synthetic_data, original_data, aggregate=False)``` with the original dataset (Pandas dataframe) and four different synthetic dataframes generated by ```SDV``` (TVAE, GaussianCopula, CopulaGAN, and CTGAN) in four different instances.

When running ```evaluate()``` on two _generated_ datasets, with either aggregate settings, it seemed to run fine. I'm not sure why it isn't working with the original dataset. I thought maybe it was an issue with the difference in size of the datasets, but when I sampled one of the generated datasets to be the same size as the original (the generated datasets are larger than the original data), ```evaluate()``` did not work. 

![image](https://user-images.githubusercontent.com/10930318/143955811-74570cf9-037e-496d-84ed-46f3bc1c26a2.png)

![image](https://user-images.githubusercontent.com/10930318/143955899-f6658f14-9329-41d0-9e4e-0c149017c4f9.png)

```
# If running stand-alone, import Pandas & ignore warnings
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Metrics library
from sdv.evaluation import evaluate

# Read the original data in
original_data = pd.read_csv('clean_prfdata2.csv')
n_sample = len(original_data.index)

# Read the four datasets we generated in
GaussianCopula_data = pd.read_csv("prf_GaussianCopula.csv").sample(n=n_sample)
CTGAN_data = pd.read_csv("prf_CTGAN.csv").sample(n=n_sample)
CopulaGAN_data = pd.read_csv("prf_CopulaGAN.csv").sample(n=n_sample)
TVAE_data = pd.read_csv("prf_TVAE.csv").sample(n=n_sample)

# Compare the GaussianCopula data
evaluate(GaussianCopula_data, original_data, aggregate=False)

# Compare the CTGAN data
evaluate(CTGAN_data, original_data)#, aggregate=False)

```

**Comment by xamm** [comment]
If I understand it correctly, comparing two synthetic data sets gives the expected result.
When I compare a synthetic data set with the original data set, the evaluation result is NaN.

Does this problem occur with any synthetic data set or only with the GaussianCopula data?

If this problem only occurs when comparing to the original data, I would guess that there is a difference in the DataFrame.

Could you provide more information about the original dataset and the synthetic dataset?
Do both datasets have the same columns, dtypes, etc.?

**Comment by cafornaca** [comment]
> Does this problem occur with any synthetic data set or only with the GaussianCopula data?

This problem occurs with any of the four synthetic datasets (generated with the respective model of its namesake).

> If this problem only occurs when comparing to the original data, I would guess that there is a difference in the DataFrame.

This is originally what I thought too which is why I sampled from the synthetic datasets. The original dataset has fewer rows than the generated datasets. This is illustrated in the code snippet (not the screenshot). When I matched the number of rows in each dataframe (original and generated), I would get the same NaN/blank table issue.

> Could you provide more information about the original dataset and the synthetic dataset?
> Do both datasets have the same columns, dtypes, etc.?

Well, well, well... It looks like the generated datasets are adding a column that is not in the orignal dataset. I'm not sure why THAT is happening, but when I drop the mysterious column, ```evaluate()``` finally works.

**Comment by katxiao** [comment]
Thanks for the update @cafornaca. Could you share the name of the added column?

**Comment by cafornaca** [comment]
> Thanks for the update @cafornaca. Could you share the name of the added column?

"Unnamed: 0.1"

**Comment by cafornaca** [comment]
ALSO: Now that I have it working, it does appear that the number of rows doesn't matter afterall. I can successfully compare the smaller original dataset and the larger generated ones.

**Comment by cafornaca** [comment]
> Thanks for the update @cafornaca. Could you share the name of the added column?

I'm using ```evaluate()``` on another one of my use cases now and am noticing that it also generated a new mystery column. It seems like it tried generating a column named "Unamed: 0" to replace an original column labeled "id".

**Comment by cafornaca** [comment]
I'll open a new issue with the mystery columns being added.

**Comment by katxiao** [comment]
@cafornaca Opening another issue about the additional columns would be great. In it, could you clarify if the additional column is coming from the sampling process or from `evaluate`?

**Comment by sakara11** [comment]
I have the same problem (evaluate function return "nan") after I installed CUDA before I was using it on the CPU and it work fine (I try to use cuda=false but it still returns to me "nan").
I don't have any new column created like @cafornaca

**Comment by Aybikee09** [comment]
I have the same problem (evaluate function return "nan") 
I don't have any new column created like @cafornaca. I can't evaluate my real and synthetic data?

**Comment by katxiao** [comment]
Hi @sakara11 and @Aybikee09, please try running `evaluate` with SDV `v0.13.1`. I'm not sure which version of SDV you are currently using but there is an incompatibility with older versions of SDV and the newest SDMetrics release.

If you are still experiencing issues with `evaluate`, please open a separate issue with more details.
