### ISSUE TITLE
Constrain by aggregate statistics

### ISSUE THREAD

**Issue by eperrier** [sdv-dev/SDV#654]
### Problem Description

I am seeking to implement a constraint based on the mean, median, variance and other functions of column values. Using workarounds from the custom constraint options has proven unsuccessful thus far.

### Expected behavior

A new constraint class should be added to tabular.py that enables easy implementation of constraints based on functions of the entire column, such as the median, mode, mean, variance etc. The constraint would mean the models seek to generate data for those columns such that the aggregate statistical constraints are met.

**Comment by npatki** [comment]
Circling back to this, I'll plan to close the issue since it's been stale for a bit and there are some existing solutions to this already (see point 2 above). Please feel free to respond and re-open if there is more to discuss.
