### ISSUE TITLE
synthesize rows given some restrictions

### ISSUE THREAD

**Issue by echo66** [sdv-dev/SDV#67]
* SDV version: 0.1.0
* Python version: 3.6
* Operating System: Fedora release 28 (Twenty Eight)

### Description

In the master thesis and old documentation, it is stated that users are able to sample from tables according to arbitrary conditions on [certain features](http://hdi-project.github.io/SyntheticDataVault/table.html?highlight=synth_row#table.Table.synth_row). In the current version, I can't find anything like this in the documentation.

### What I Did

I looked into the documentation and the source code.

### Notes

I might be wrong but, probably, SDV team is waiting for a PR on this: https://github.com/DAI-Lab/Copulas/issues/47

**Comment by ManuelAlvarezC** [comment]
Thanks for reporting this issue @echo66.

Indeed, the issue in copulas must be solved before we proceed with the changes on SDV. We will get on it after those changes are done.

**Comment by csala** [comment]
Closing this to keep track of this feature in the issue #156
