### ISSUE TITLE
Does anonymization mapping work correctly?

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#670]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.13.0
* Python version: Any
* Operating System: Any

### Problem description

In the `fit` method of the `metadata.Table` class, an anonymization mapping is created by mapping each unique value for pii fields, to a faker generated value. https://github.com/sdv-dev/SDV/blob/f87f503cb66cd49d2bb5ddec2ba09c9ccad3ed47/sdv/metadata/table.py#L541-L550

This is used to privatize the data before modeling.
https://github.com/sdv-dev/SDV/blob/f87f503cb66cd49d2bb5ddec2ba09c9ccad3ed47/sdv/metadata/table.py#L656

However, when reverse transforming, we don't use the values sampled from the model, whcih would theoretically be private. Instead, they are faked again: 
https://github.com/sdv-dev/SDV/blob/f87f503cb66cd49d2bb5ddec2ba09c9ccad3ed47/sdv/metadata/table.py#L712

I believe this means that if someone were to try and use the anonymization map to get back original values, it wouldn't work because a lot of the values generated by faker in the `reverse_transform` would not be in the `self._ANONYMIZATION_MAPPINGS`

**Comment by npatki** [comment]
While anonymized mapping may not be working correctly at the moment, our long term plan is to address this using RDTs.

In particular, we could apply the [PseudoAnonymizedFaker](https://github.com/sdv-dev/RDT/issues/517) to such columns. This transformer will take care of transforming the values to numerical values and also keep track of the mapping.

Should we close this issue in favor of the RDT issue? Then whenever we do the integration with RDT 1.0, we can get this functionality for free.

**Comment by amontanez24** [comment]
We still need to remove all the unnecessary code once we integrate RDT >=1.0
