### ISSUE TITLE
Ensure unique sequence index for each row (ideally business days)

### ISSUE THREAD

**Issue by sokol11** [sdv-dev/SDV#678]
Hi. Thanks so much for writing such a great library! I just started using it today, trying to generate some timeseries data with `from sdv.timeseries import PAR`. I noticed that when I call `model.sample(1)`, it generates timeseries with duplicate dates. Is that intended behavior? Is there some way to get around it and force the dates to be unique (ideally, business days from the original sequence index without any "skips")? Thank you!

**Comment by npatki** [comment]
Thanks for filing @sokol11. 

I suspect that the synthesized sequence index values might all be slightly different, but they are being rounded to the same value. For example, the values might be hours apart but they map to the same day (date).

I'll turn this into a feature request and we can keep it open for tracking. To help us prioritize, it would be great if you're able to share more about your use case. Are you working on a specific project that has this property? How are you planning to use the synthetic data?

**Comment by npatki** [comment]
Update -- this seems to be a duplicate feature request with #1723. As we've had more discussions in #1723, let's use that one for communication.

I'm closing this one off in favor of the other issue. Please feel free to reply to the other issue for continued updates and conversation.
