### ISSUE TITLE
Generate synthetic data only for subset of the tables 

### ISSUE THREAD

**Issue by nandakishorkoka** [sdv-dev/SDV#681]
This is a question on generating synthetic data using the relational model (HMA1). I have a relational tables like the below: 

**Metadata
  root_path: .
  tables: ['orders', 'items', 'order_items']
  relationships:
    order_items.items_id -> items.items_id
    order_items.order_id -> orders.order_id**

The Items tables does not have any PII and I would like to use the same items in my original data. i.e. I want to generate only orders and order_items. Is this possible ?

**Comment by npatki** [comment]
Hi @nandakishorkoka, referencing the HMA1 [Sample API](https://sdv.dev/SDV/api_reference/relational/api/sdv.relational.hma.HMA1.sample.html): There is a parameter called `table_name` that you can use:

```python
# samples only the orders table and its child (order_items)
model.sample(table_name='orders', sample_children=True)
```

There is a known issue about the way we assign parent IDs that you can follow at #563. 

Let me know if that helps!

**Comment by npatki** [comment]
Hi, I'm closing off the issue since I've answered your question. Please feel free to re-open if you have any follow ups!
