### ISSUE TITLE
Is it possible to use the models that are sorted under "single table data" on a multi table dataset with relational data?

### ISSUE THREAD

**Issue by joostka1998** [sdv-dev/SDV#683]
### Problem description

I would like to generate data for a relational model, is it possible to use any of these models that are sorted under the single table models:

- GaussianCopula Model
- CTGANvModel
- CopulaGAN Model
- TVAE Model

If i understand the documentation properly, i expect only to have the HMA1 model working while using relational data while using the metadata class.

Is it possible to use the models that are sorted under "single table data" on a multi table dataset with relational data?

**Comment by npatki** [comment]
Hi @joostka1998, you are correct in that only the `HMA1` model is designed for relational data right now. Under-the-hood, the `HMA1` algorithm currently uses the `GaussianCopula` model. 

Is there a specific model you need for your use case? It will help us prioritize if you're able to add any details about your use case in a new feature request.

**Comment by AbderrahimAl** [comment]
Hello @joostka1998, 
`HMA1` works only with parametric models like `GaussianCopula`. Other tabular models `CTGAN`, `CopulaGAN` and `TVAE` cannot be used.

**Comment by npatki** [comment]
Hi, I'm closing off the issue since your question has some answers. Please feel free to re-open the issue if you have any follow-ups or raise a feature request for supporting a particular model.
