### ISSUE TITLE
Is it possible to generate data with new set of primary keys? 

### ISSUE THREAD

**Issue by abimarticio** [sdv-dev/SDV#686]
I want to generate a synthetic data that I can append to my original data. Is there a way to exclude the primary keys that is already in the original data when generating synthetic data?

I want to generate a large number of data, but I have limited resources so I am planning to generate small sets of data and just append it to my original data.

**Comment by npatki** [comment]
Hi @abimarticio,

> Is there a way to exclude the primary keys that is already in the original data when generating synthetic data?

We have found that the default work for most cases: If your primary key is a string, the SDV will generate 'a', 'b', 'c', etc. by default. (If it's numerical, it'll generate 0, 1, 2,...). Is this causing conflicts for you?

Other options:
- Write metadata and specify a different `regex` for the primary key (see [guide](https://sdv.dev/SDV/developer_guides/sdv/metadata.html#primary-key-fields))
- Manually overwrite the column after sampling with whatever you want

> I want to generate a large number of data, but I have limited resources so I am planning to generate small sets of data and just append it to my original data.

I have filed #693 for handling batch sampling internally -- so you would not have to do this manually. You can follow that issue for updates.

Let me know if that helps or if you have any follow ups!

**Comment by abimarticio** [comment]
Hi @npatki! Thank you very much for the reply. This is really helpful. 

For the meantime what I did was overwrite the column after sampling and create mapping for the foreign keys. But I will also try the first option you suggested. And will also wait and follow the issue you filed.

Thank you very much!

**Comment by npatki** [comment]
Glad it helped! I'll close this issue in favor of the new feature request. Feel free to re-open if you have any follow ups.
