### ISSUE TITLE
Anonymizing Geographic Fields

### ISSUE THREAD

**Issue by TheFrator** [sdv-dev/SDV#688]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.13.1
* Python version: 3.8.5
* Operating System: Windows 10

### Error Description

I have a pandas dataframe with a column of geographic lat/long tuples that I wish to anonymize. However, every attempt and combination I have tried has resulted in unchanged data when I sampled the model. E.g. New York city has the same lat/long in the original dataset and in the samples. SDV documentation [(link to PII section)](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html#anonymizing-personally-identifiable-information-pii) indicates that geographic anonymity is possible because this feature is built using [Faker providers](https://faker.readthedocs.io/en/master/providers.html). 

### Steps to reproduce

`coord` is the name of the column in `geo_df` which contains lat/long tuples
```
anon_field = {"geo" :'coord'}
model = GaussianCopula(anonymize_fields= anon_field)
model.fit(geo_df)
synth =model.sample(200)
synth .coord.isin(geo_df.coord).sum()```

### Output
Output: 200

**Comment by npatki** [comment]
Hi @TheFrator, [this GitHub Discussion](https://github.com/sdv-dev/SDV/discussions/667) might provide some useful insight on using PII fields.

From your code, I see 2 things that could be going wrong:

1. The anonymize fields expects `{pii_column_name: provider_name}`. I think you have it backwards.
2. I believe the provider name is not the name of the class but the name of a method. So `"geo"` is not valid -- but `"coordinate"` would be. Or, if you require a pair of coordinates, then you'd probably want `"latlng"`. 

Try using: 
```python
anon_field = {'coord': 'latlng'}
```

And let me know if that helps!

**Comment by TheFrator** [comment]
@npatki Thank you for your quick reply and link to the GitHub discussion page. This resolved my initial issue of generating tuples of lat / long coordinates. But opened another question- for country specific coordinates how do I return only the tuple of lat / long? I am using the following Provider [Provider documentation](https://faker.readthedocs.io/en/master/locales/en_US.html#faker.providers.geo.en_US.Provider.local_latlng). There is the parameter `coords_only` that I want to set to `True`.

Code snippet:

```
anon_field = {"coord": 'local_latlng'}
model = GaussianCopula(anonymize_fields= anon_field)
model.fit(geo_df)
metadata = model.get_metadata().to_dict()
metadata['fields']['coord']['pii_locales'] = ['en_US']
model_locale = GaussianCopula(table_metadata=metadata)
model_locale.fit(geo_df)
print(model_locale.sample(200)["coord"].head())
```

Output:
```
0    (29.65163, -82.32483, Gainesville, US, America...
1    (40.58654, -122.39168, Redding, US, America/Lo...
2    (35.05266, -78.87836, Fayetteville, US, Americ...
3    (40.63316, -74.13653, Port Richmond, US, Ameri...
4    (41.48199, -81.79819, Lakewood, US, America/Ne...
```

Thank you for you help

**Comment by TheFrator** [comment]
In case anyone needs this, to specify Faker parameters please read [this section of SDV documentation](https://sdv.dev/SDV/developer_guides/sdv/metadata.html#metadata-schema). Specifically the note: "Sometime Faker categories admit a type, which can be passed as an additional argument. If that is the case, you set a list containing both the category and the type instead of only the string: 'pii_category': ['credict_card_number', 'visa']"

So for generating US only lat/long tuples your code should look like this. The difference being in the first line. The value of the `anon_field` dictionary is now a list with the the parameters of the Faker provider in the order Faker documentation specifies. 

```
anon_field = {"coord": ['local_latlng',"US","True"]}
model = GaussianCopula(anonymize_fields= anon_field)
model.fit(geo_df)
print(model.sample(200)["coord"].head())
```

Output:
```
0     (41.84364, -87.71255)
1     (33.45122, -86.99666)
2     (26.18924, -98.15529)
3    (33.03699, -117.29198)
4     (39.78504, -85.76942)
Name: coord, dtype: object
```
