### ISSUE TITLE
Rounding constraint is not working

### ISSUE THREAD

**Issue by abimarticio** [sdv-dev/SDV#699]
### Environment Details

* SDV version: 0.13.1
* Python version: 3.9.6
* Operating System: Windows

### Error Description

I was trying to add Rounding Constraint with 3 digits on "salary" column. But after sampling using the GaussianCopula model the "salary" column is still 2 decimal places same as the original data. I was expecting that it should convert the "salary" column into 3 decimal places.

### Steps to reproduce

```
from sdv.demo import load_tabular_demo
from sdv.tabular import GaussianCopula
from sdv.constraints import Rounding

employees = load_tabular_demo()

rounding_constraint = Rounding(
    columns="salary",
    digits=3,
    handling_strategy="transform"
)
model = GaussianCopula(
    constraints=[rounding_constraint],
)
model.fit(employees)
model.sample()

```
output:
![synthetic_data](https://user-images.githubusercontent.com/68144906/151505495-e335ec9b-d9bb-41ab-8759-4befe8bda96a.PNG)

**Comment by npatki** [comment]
Right now, the default of `GaussianCopula` is to round all columns by default to match the input data. The `Rounding` constraint is meant for overriding this default.

The below code should work -- `salary` will have 4 digits but none of the others will be rounded.

```python
model = GaussianCopula(
    rounding=None, # do not automatically round all columns
    constraints=[rounding_constraint] # but use the Rounding constraint on the salary column
)
```

We can simplify this behavior in the future. To help prioritize, could you explain your use case? Do you have a need for rounding to a different # of digits as your input data? (eg. original `salary` column has 2 digits, but for some reason you want the synthetic data to have 3?) I'd love to hear about any scenarios where this is needed.

**Comment by npatki** [comment]
Hello! I'm closing off this issue since I've answered your question. Please feel free to re-open if you have any follow-ups.
