### ISSUE TITLE
Enforce data constraints

### ISSUE THREAD

**Issue by ManuelAlvarezC** [sdv-dev/SDV#70]
After this [issue](https://github.com/HDI-Project/MetaData.json/issues/5) is solved, we should be ready to enforce data constraints on sampled data.

In order to implement them, they should be checked after data is sampled and reverse_transformed but before is returned. It should be on `sdv.Sampler.sample_rows` as it's the common access to the process of sampling for the three public methods. The roadmap should be as follows:

1-. Create a method `sdv.Sampler.check_constraints` that gets a dataframe sampled and reverse transformed and return an array of indices corresponding to rows that fulfill constraints.

2-. Modify the method  `sdv.Sampler.sample_rows` that handles the process of sampling, but before returning the result, checks the data fullfill the constraints, discard the rows that fail and samples again until it gets to the desired number of rows.

**Comment by csala** [comment]
A functionality equivalent to this issue was added in #173 , so this can be closed now.
