### ISSUE TITLE
The same values of float field (column) are sampled. 

### ISSUE THREAD

**Issue by jke513** [sdv-dev/SDV#703]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.13.1
* Python version: 3.7
* Operating System: linux 

### Error Description

I modeled with GaussianCopula with 'float' field_transformers as well as 'integer' and 'categorical'. 
After fitting the model, generated samples contain the same values for the 'float' column. 
Is it bug? Otherwise, how this can happen? 

### Steps to reproduce

```
model = GaussianCopula(
            field_names = ['input','p0','p1','p2','p3','p4','p5','p6','p7','speedup'],    
            field_transformers = {'input': 'integer',
                                  'p0': 'categorical',
                                  'p1': 'categorical',
                                  'p2': 'categorical',
                                  'p3': 'categorical',
                                  'p4': 'categorical',
                                  'p5': 'categorical',
                                  'p6': 'categorical', 
                                  'p7': 'categorical',
                                  'speedup': 'float'},
            constraints=[constraint_input]
    )
model.fit(real_data)
ss1 = model.sample()

In [7]: ss1['speedup']
Out[7]: 
0     7.400928
1     7.299876
2     7.297507
3     7.608149
4     7.681686
        ...   
82    7.645509
83    7.578899
84    7.524214
85    7.681686
86    7.681686
Name: speedup, Length: 87, dtype: float64

In [6]: len(ss1['speedup'].unique())
Out[6]: 56
```

Any help will be much appreciated.

**Comment by npatki** [comment]
Hi @jke513 -- It would be helpful if you could describe your use case & dataset a little more. What is `'speedup'` and how does it look like in the original, input data?

The SDV will model the distribution as continuous -- so chances of getting the same value are low. However, it will also automatically round the values to the same decimal digits as the original. I see that `'speedup'` has 6 decimal digits, which might be causing duplicate values after the rounding.

To fix this you could:
1. Add `rounding=None` as a param when creating your `GaussianCopula` OR
2. Use a `Unique` constraint on the `speedup` column to ensure there are no duplicates (see [User Guide](https://sdv.dev/SDV/user_guides/single_table/handling_constraints.html#unique-constraint))

Let me know if that helps! I'll mark this as a Question for now, but if you think there's still a bug we can reclassify.

**Comment by npatki** [comment]
Hi @jke513, I'm closing off this issue since I've answered your Q. Please feel free to reopen if you have more comments or the fixes are not working.
