### ISSUE TITLE
Missing examples and documentation on loading custom CSV data

### ISSUE THREAD

**Issue by FrancisJMR** [sdv-dev/SDV#710]
### Problem Description

All examples and tutorials assume usage of demo data packaged with SDV but no examples using raw/custom CSV file data.

### Expected behavior

There should be multiple examples showing how to load data from raw CSV files and how to create the metadata files. Documentation is also missing at https://sdv.dev/SDV/user_guides/single_table/table_metadata.html

**Comment by npatki** [comment]
Hi @FrancisJMR thank you for the feedback! We're actively working to update our documentation and I'm noting this down to make sure we address it. I will continue to update the bug as we make changes.

BTW -- I'm curious what kind of troubles you have had with using raw/custom CSV file data? If there are any known complexities, we can address them as well.

**Comment by FrancisJMR** [comment]
Thank you @npatki  for the quick reply!

Some unexpected behaviour for example with a simple CSV say 3 columns: 'gender', 'age', 'height'. Metadata in a 'tables' object might look like (based on google search example since no documentation):
```
{
  "tables": {
    "patients": {
      "fields": {
        "gender": {
          "type": "categorical"
        },
        "age": {
          "type": "numerical",
          "subtype": "integer"
        },
        "height": {
          "type": "numerical",
          "subtype": "float"
        }
      }
    }
  }
}
```
But such a table can't be loaded into a single table model like GaussianCopula, then fitted.
```
model = GaussianCopula(metadata)
table_df = pd.read_csv(path)
model.fit(table_df)
```
This results in a KeyError: Metadata

I would argue all metadata files should follow a 'tables' structure with one or more tables that are or aren't relational. This would simplify model use. Ideally a metadata generator from CSV as a helper would also be great (I can help with this if interested).

I'm currently looking for the current accepted way to define the metadata for a single table. Do you have any links?

Cheers!

**Comment by FrancisJMR** [comment]
Thank you Neha @npatki  very helpful!
