### ISSUE TITLE
Different evaluation values every time

### ISSUE THREAD

**Issue by haris-buaa** [sdv-dev/SDV#714]
I am generating synthetic data using TVAE but every time I generate data it gives me different values for the overall score using evaluate command. 
Its possible that the synthetic data is different every time I generate it but if I want to optimize the hyperparameters of the network through other algorithms, the value of the evaluation metrics should be similar for each set of hyperparameters.

**Comment by npatki** [comment]
Hi @haris-buaa there are 2 sources of randomness within your setup:

1. The sampling algorithm in `TVAE` returns different synthetic data every time it is called. We are planning to add a way to reliably sample the same data. You can follow issue #690 for more info.
2. Certain metrics in `evaluate` also have randomness. For example, when I run the `LSTMDetection` from the [Time Series metrics](https://sdv.dev/SDV/user_guides/evaluation/timeseries_metrics.html#detection-metrics), I get different results ranging from 0.44 to 0.54.

Some suggestions:
- For now, you can manually fix a random seed using the workaround described in #515 
- If there is a particular metric you are interested in optimizing, I suggest applying it multiple times and using the average result

Let me know if that helps!

BTW What range of values are you getting? I expect the values to differ between each successive run, but not substantially.

**Comment by haris-buaa** [comment]
Hi Neha,
Thanks for your prompt. Eventually I found out a way to remove randomness exactly by the way as described in issue #515. 
I was getting the values between 0.68-0.71 and it was creating errors in optimization of the hyperparameters. 
Thanks.
