### ISSUE TITLE
Field distribution return value

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/SDV#744]
The field distribution mapping in GaussianCopula contains internally transformed columns (e.g. `col.value` and `col.is_null`). Should the user-facing API contain those columns? Is there a way to make it more user friendly?

**Comment by npatki** [comment]
In the new, [**SDV 1.0 (Beta!)**](https://docs.sdv.dev/sdv) release, we are exposing any distribution that we learn, including the ones created for new columns. This is done through the [get_learned_distributions](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer#accessing-learned-distributions) method.

- If I am modeling missing values, then `column_name.is_null` will appear in as a learned distribution along with its parameters.
- We dropped the `.value` suffix for other transformers, meaning that they will be referenced by their original names.

This should make the API easy for users to parse.
