### ISSUE TITLE
Set the bounds on the PAR model 

### ISSUE THREAD

**Issue by phervin** [sdv-dev/SDV#745]
### Problem Description

I'm running the PAR model example from the User Guide (see code snippet attached) and in the resulting synthetic data I'm getting negative values in the column Volume, while in the original dataset all values in this column are positive.

### Expected behavior

Getting only positive values in the synthetic dataset when the real dataset is all positive

### Additional context

![warnings](https://user-images.githubusercontent.com/31543852/160367830-c149f211-eea0-4bcf-8ee6-fc8c4ef41470.png)
![code_snippet](https://user-images.githubusercontent.com/31543852/160367835-0d2e3b48-38c7-4706-88de-72abbb1ea9f5.png)

**Comment by npatki** [comment]
Thanks for filing @phervin. 

We currently don't model min/max values or perform any boundary checks on the synthetic data. We'll update this issue as we make progress on it. BTW this is somewhat also related to #655, as constraints could be another way to specify min/max boundaries.

To help us prioritize, it would be great to hear more about your use case and how you plan to use the synthetic data.

**Comment by npatki** [comment]
Hi @phervin and @schweima great news -- the new [**SDV 1.0 (Beta!)**](https://docs.sdv.dev/sdv) release now includes a parameter `enforce_min_max_values`.

When set to `True` (default), PAR will produce synthetic data that is inside the ranges found in the real data. In this way, you are setting the bounds to what is true of the real data.

For more information see the new documentation for the [PARSynthesizer](https://docs.sdv.dev/sdv/sequential-data/modeling/parsynthesizer).
