### ISSUE TITLE
Synthetic Data Generation issue of Relational dataset having more than one relational column

### ISSUE THREAD

**Issue by himanshu034** [sdv-dev/SDV#758]
I have relational data having below structure.
Company Table having columns: <b>company_id</b>, company_name
Product Table having columns: <b>product_id</b>, product_name,<b>company_id</b>
Order Table having columns: order_id, <b>product_id, company_id,</b> quantity
How can I create metadata from above structure so that Order Table data generates data with combined relation of customer and product which is already there in Product Table.

**Comment by npatki** [comment]
Hi @himanshu034 the SDV should be able to support your schema. Have you already tried to write the metadata and create a model from it? If you are running into issues with your model, it would be helpful if you can share your code.

If you have not yet created the metadata, you can reference [this Metadata guide](https://sdv.dev/SDV/developer_guides/sdv/metadata.html).

**Comment by himanshu034** [comment]
Hi @npatki I have created metadata from the structure I mentioned above.
<pre>{
    "tables": {
        "Company": {
            "fields": {
                "company_id": {
                    "type": "id",
                    "subtype": "integer"
                },
                "company_name": {
                    "type": "categorical"
                }
            },
            "primary_key": "company_id"
        },
        "Product": {
            "fields": {
                "product_id": {
                    "type": "id",
                    "subtype": "integer"
                },
                "product_name": {
                    "type": "categorical"
                },
                "company_id": {
                    "type": "id",
                    "subtype": "integer",
                    "ref": {
                        "table": "Company",
                        "field": "company_id"
                    }
                }
            },
            "primary_key": "product_id"
        },
        "Order": {
            "fields": {
                "order_id": {
                    "type": "id",
                    "subtype": "integer"
                },
                "customer_id": {
                    "type": "id",
                    "subtype": "integer",
                    "ref": {
                        "table": "Product",
                        "field": "company_id"
                    }
                },
                "product_id": {
                    "type": "id",
                    "subtype": "integer",
                    "ref": {
                        "table": "Product",
                        "field": "product_id"
                    }
                },
                "quantity": {
                    "type": "numerical",
                    "subtype": "integer"
                }
            },
            "primary_key": "order_id"
        }
    }
}
</pre>
[sample_records.xlsx](https://github.com/sdv-dev/SDV/files/8464377/sample_records.xlsx)

I have trained model with above metadata. After generating the data using trained model I found that in <b>Order</b> table the relation is not same as declared in <b>Product</b> table between product_id and company_id.

Please let me know if I am doing any mistake in the creation of metadata. For reference I am sending some records in attachment.

**Comment by npatki** [comment]
Hi @himanshu034 thanks for the details. Your metadata definition seems correct. I think I understand your issue now. Essentially:
- The order refers to a company, and
- The order refers to a product (which in turn refers to a company too)

And you want to make sure that for all orders, both of those company values are the same?

Unfortunately, the SDV will not guarantee this -- though you are welcome to [file a feature request](https://github.com/sdv-dev/SDV/issues/new/choose) with this use case in mind. I suspect it might actually have to be a new constraint.

In the meantime, I'm wondering what will happen if you drop the company ID column from the Orders table? That way, you only have 1 single line of connections: Company --> Product --> Order and there will be no issues with multiple companies.

**Comment by himanshu034** [comment]
Thanks for your response @npatki. Single line relation between tables working fine. I can manage with this.

I'm facing one more issue while generating data with the trained model. I am trying to generate 10k records and it is taking too long time approx. 5+ hours and still running(didn't get result). Is there any solution to resolve this issue. I am trying to generate records with below code:

req_rows = 10000
sdv_model = HMA1.load(model_path)
sample_df = loaded.sample(num_rows=req_rows)

Please suggest if there is any solution for this.

Fyi.. I have successfully generated 5000 records and it took 2.5 hours. In the generated data I found below record count for each table which is fine as per my use case and relation between the entities are also fine.
Company - 5000
Product - 25000
Order - 55000

**Comment by npatki** [comment]
Hi @himanshu034 this is hard to assess without knowing the details of your data. 

Would you be comfortable sharing your full metadata with us? You can message it to us privately too. The team is thinking about some improvements to optimize the speed, so any examples will be useful to us.

I'm also curious how long the modeling phase took.

**Comment by npatki** [comment]
Hi @himanshu034, I'm closing this issue since we successfully resolved the first problem of the combined relation. Please feel free to re-open if you'd like to continue discussing the speed or able to provide the metadata.
