### ISSUE TITLE
About the PAR Model: Is there a paper on this, comparing it to other methods, with a description of how it works

### ISSUE THREAD

**Issue by MarkTensenSgt** [sdv-dev/SDV#762]
I haven't tried the PAR model yet, but I was wondering about its efficacy. 
Is anything written on this specific implementation, and how effective it is? 
I googled a bit, but couldn't find a straightforward article about it. 
Thanks!

**Comment by npatki** [comment]
Hi @MarkTensenSgt, there isn't any paper on the PAR model but the team is actively working on putting together a detailed description and providing more resources. I can reach out to you when it's ready.

**Comment by MarkTensenSgt** [comment]
Thanks for the update. And if you can reach out by then, that'd be nice!

**Comment by npatki** [comment]
I'm consolidating issues related to PAR Model description and documentation. I'll close this one off in favor of #840 .
