### ISSUE TITLE
Rounding constraint is not working with np.nan

### ISSUE THREAD

**Issue by tssbas** [sdv-dev/SDV#770]
### Environment details

* SDV version: 0.14.0
* Python version: 3.8.13
* Operating System: Ubuntu 20.04.3 LTS

### Problem description

I am using `Rounding` constraint to limit the number of digits of a certain column. My problem is that the column also includes missing values (e.g. `np.nan`). The `Rounding` constraint seem to validate these missing values as "invalid" and the `Table._validate_data_on_constraints` consequently raises a `ConstraintsNotMetError`. I am not sure if this is a bug or a feature, but my suggestion would be, that the `Rounding` constraint also validates `np.nan` as "valid" and perhaps some other constraint (like `NotNull` or something) is implemented for the purpose of validating whether or not `np.nan` is present.

### What I already tried

The following is the working version of `is_valid` method (only the last line is changed) from the `Rounding` constraint class, so that it also treats `np.nan` as valid entries.

```
    def is_valid(self, table_data):
        """Determine if the data satisfies the rounding constraint.

        Args:
            table_data (pandas.DataFrame):
                Table data.

        Returns:
            pandas.Series:
                Whether each row is valid.
        """
        columns = table_data[self._columns]
        rounded = columns.round(self._digits)
        valid = (columns - rounded).abs() <= self._tolerance
        
        return np.logical_or(valid, columns.isnull()).all(1)
```

**Comment by katxiao** [comment]
Hi @tssbas, thanks for the issue! I believe you are correct that we should consider columns with nulls as valid for the `Rounding` constraint. If you have time, please feel free to create a PR with your proposed fix + a unit test to verify that it's working as expected. Otherwise, I will put it on our queue.

**Comment by npatki** [comment]
Hi @tssbas,

We plan to modify the `Rounding` constraint in the next release and have accounted for the missing value case thanks to your issue!

Issue #818 has the details for the new functionality. I'm closing this off in favor of the new issue..
