### ISSUE TITLE
Key Error while fitting model

### ISSUE THREAD

**Issue by biased-ai** [sdv-dev/SDV#773]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:0.14.0
* Python version:3.8.5
* Operating System: Windows

### Problem description

I am getting a Key Error 'C' while fitting the data but the problem is there is no such column as C in my dataframe

```
model=PAR(entity_columns=entity,sequence_index=sequence)   

where entity referred to a univariate time series entity and sequence represents week no of the series

when i am fitting the data i am getting the key error



```

**Comment by npatki** [comment]
Hi @biased-ai -- thanks for filing this issue. Are you able to paste the exact Error message and any other details that get printed (Stack trace)?
