### ISSUE TITLE
Expand/limit the variance of specific columns

### ISSUE THREAD

**Issue by Ishita-0112** [sdv-dev/SDV#780]
### Problem Description

Unavailability of flags to limit or expand the variance of data for columns such as city name and area code. For example, while the seed data might be restricted to particular regions, users might expect the generated synthetic data to have different area codes that were not part of the seed data to ensure better data privacy.

The proposed feature could include understanding trends related to demography from the synthetic data and then abstraction of the address/area code information in the synthetic data.

### Expected behavior

The flag can be added as a part of the additional constraints that SDV already allows us to define for any generative model. 

For example, say variable `Col1` contains office area code of employees of an organization and variable `Col2` contains the area codes of homes of the same employees, which could be in different states/countries. We might want to retain the office area codes in the generated synthetic data but not those of home area codes, to protect employee data privacy.

Proposal:
Syntax usage: flag: ["Col1": True, "Col4": False]
Syntax description: Use case having office addresses to belong to similar area code (Hence, Col1 is set to `True`) while home area codes are to be abstracted (Hence, Cole4 is set to `True`).

```
s = generate(d){
		model: ‘gc’;
		epochs: ‘300’;
		batch_size: ‘500’;
		log_frequency: ’true’;
		embedding_dim: 128;

	        generator_lr: ‘2e-4’;
		generator_decay: ‘1e-6’;
		generator_dim: (256,256);

		discriminator_lr: ‘2e-4’;
		discriminator_decay: ‘1e-6’;
	        discriminator_steps: ‘1’;
		discriminator_dim: (256,256);

	        verbose: ‘false’;
                flag: ["Col1": True, "Col4": False];
}
```

**Comment by npatki** [comment]
Hi @Ishita-0112, nice to meet you!

If I am understanding the request correctly, you'd like the ability to specify the granularity of particular regions and areas in the synthetic data? Right now, the SDV offers an integration with the Faker library:
- Marking a column as `pii` will anonymize the values using Faker
- Using the `locales` parameter, you can control the regions. So if you know the areas ahead-of-time, you can use this.

The [Anonymization Discussion Page](https://github.com/sdv-dev/SDV/discussions/667) has more information.

Would this work for your use case?

(BTW I'm not quite sure what the code is referring to. Is the `generate` function your own implementation?)
