### ISSUE TITLE
Predefined data for common columns such as area code and contact number

### ISSUE THREAD

**Issue by Ishita-0112** [sdv-dev/SDV#781]
### Problem Description

If we want to generate 10,000 rows of synthetic data from real data of, let's say, 200 rows having 3 columns consisting of complete address, area code and street names, but instead of randomizing the addresses in the upsampled data, we would essentially want them to fall under similar area codes or countries as that of the real data. The idea is to have a dummy dataset in the background consisting of meaningful address information of specific countries (and preferably, even cities) and a flag parameter which the user can select to let the generative model understand the type of data to be generated for the defined address columns based on the flag value and the area selected.

### Expected behavior

- Forming a database consisting of dummy addresses/street names/zip codes of different countries and states
- Providing an option to the users to select the country/area for specific data columns
- SDV would essentially fill up the specified column with addresses/area codes from its existing database

Proposal:
```
Syntax usage: flag: ["Col1": "USA"] ["Col2": "Pennsylvania, USA"]
Syntax description: Home addresses in col1 should belong to Pennsylvania region.
```

**Comment by npatki** [comment]
Hi @Ishita-0112, I left a suggestion in #780 that may work for this case too. 

Another option may be to use [Contextual Anonymization](https://docs.sdv.dev/rdt/transformers-glossary/premium-add-ons/contextual-anonymization), a new feature we have added in our RDT library. 

For a concrete example, you can refer to the [Phone Number Guide](https://docs.sdv.dev/rdt/transformers-glossary/premium-add-ons/phone-number-data/anonymizedgeoextractor). I believe this is doing something similar to what you are suggesting: It's pulling out the geo information for modeling and then recreating the original data within similar regions.

I understand the example is for phone numbers, not addresses. But is this something similar to what you had in mind?

**Comment by npatki** [comment]
Hi @Ishita-0112, I'm closing off the issue since it's been inactive for a few weeks. Please feel free to re-open if there's anything more to discuss, or if you'd like to explore the Contextual Anonymization techniques for addresses.
