### ISSUE TITLE
Update ColumnFormula constraint

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#794]
### Problem Description

As a user, it is not obvious or clear when `drop` should be set to `Ture` or `False`.

### Expected behavior

- Replace the `column` init param with the following to parameters:
    - `input_column_names`: A list of column names that are inputted to the formula
    - `output_column_name`: The column name that is computed by the formula
- Remove the `drop_column` parameter
- During `transform`:
    - If the `output_column_name` is also in the `input_column_names`, then we cannot drop the output column before modeling
    - If the `output_column_name` IS NOT in the `input_column_names`, then we can drop the output column before modeling
- During `reverse_transform`:
    - Formula should be given only the `input_column_names` → `formula(data[input_column_names])`

**Comment by npatki** [comment]
Update: Per the newest, spec, we will be removing the `ColumnFormula` constraint because the same functionality can be implemented in `CustomConstraint` (which we'll rewrite). 

Closing this off and marking as `won't fix`.
