### ISSUE TITLE
Warn the user if the requested samples can't be generated

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#798]
When the generated number of samples is smaller than the requested value, we should at least warn the user. For example, if we use the `Unique` constraint, but the original dataset contains less unique values than the requested number of samples, it's impossible to generate as many samples as requested. The current behavior is to just generate as many as we can without warning, like the example below:

```python3
from sdv.constraints import Unique
import pandas as pd
from sdv.tabular import GaussianCopula

data = pd.DataFrame({
    'a': [1, 1, 1, 2, 3, 2],
    'b': [1, 2, 3, 4, 5, 6],
    'c': [False, False, True, False, False, True]
})

model = GaussianCopula(constraints=[Unique('b')])
model.fit(data)
print(model.sample(100))
```
which generates only 6 samples, instead of the requested 100
```
   a  b      c
0  1  1  False
1  2  6   True
2  1  3  False
3  2  5  False
4  1  2   True
5  1  4   True
```

**Comment by npatki** [comment]
+1 the user should be warned for this case. But the warning should come from the sampling methods, as they handle this same logic in other places (eg. conditions)

Our current sampling logic doesn't factor in cases where reject sampling is used. I filed #809 to track it, and will close this issue off in favor of that one.
