### ISSUE TITLE
Single table metrics documentation erratum

### ISSUE THREAD

**Issue by johntmyers** [sdv-dev/SDV#810]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.14.0
* Python version: 3.9.10
* Operating System: OS X

### Error Description

The single table metrics mention this:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/9696606/169611001-c6cc7f6f-33c1-4d36-8a04-dcbf98e0ecfb.png">

In practice, a `IncomputableMetricError` is raised instead of a `nan` being "output" - so the docs make it a little unclear

### Steps to reproduce

Attempt a metric test using `KSTest` or `CSTest` that does not have the expected types

**Comment by npatki** [comment]
Thanks for filing! Marking as a documentation update.

**Comment by npatki** [comment]
Closing this issue off as `obsolete`. Over the past few iterations of the SDV, we have moved away from applying all the metrics and instead apply a quality report during the evaluation phase. 

For more information, see the new [**SDV 1.0** docs](https://docs.sdv.dev/sdv), in particular the section for [evaluation](https://docs.sdv.dev/sdv/single-table-data/evaluation).
