### ISSUE TITLE
CTGAN loss values documentation

### ISSUE THREAD

**Issue by petercoppensdatylon** [sdv-dev/SDV#812]
Hello

I am fitting a ctgan on a simple table (3 continuous variables) in verbose mode. 

The image shows the evolution over epochs of G (blue) and D(red) loss values

Is there some documentation available describing the meaning of these values (and evolution) in more detail. Also why the D loss seems to oscillate around 0 while the G loss decreases to some negative value (I understand the decreasing part :) )

I also had some fit runs where the G loss started increasing after a number of epoch's. What would be the meaning of that?

All tips welcome!

Wkr

Peter

![gan_epochs](https://user-images.githubusercontent.com/79080548/169685954-1740d584-2d5e-4d64-ab63-646c9f589880.png)

**Comment by npatki** [comment]
Hi @petercoppensdatylon, [this older comment](https://github.com/sdv-dev/CTGAN/issues/28#issuecomment-591524889) might be helpful to understand where the loss values are coming from.

The discriminator's loss oscillating at 0 indicates that it's having a hard time distinguishing between the real and synthetic data. This isn't necessarily a bad thing. It can still be getting better but if the generator is also getting better, it's able to continue to fool the discriminator.

BTW There are some other relevant discussions on loss [here](https://github.com/sdv-dev/SDV/issues/222) and [here](https://github.com/sdv-dev/CTGAN/issues/66). If you're generally looking to see if your synthetic data is "good enough", I'd suggest applying some [evaluation metrics](https://sdv.dev/SDV/user_guides/evaluation/single_table_metrics.html) on the synthetic data directly.

**Comment by npatki** [comment]
Closing this issue off since the question has been answered. Feel free to re-open if there is more to discuss!

**Comment by 1Biaohe** [comment]
hi,

I wonder how you plot the loss image here.
Is there a function/method in CTGAN?

Thanks!

**Comment by npatki** [comment]
Hi @1Biaohe, there isn't yet any function/method in CTGAN related to this. If this is something that interests you, it would be great if you could file a feature request.

I suspect many people are using `verbose=True` and then writing their own scripts that parse the output and graph them.

**Comment by pgp44** [comment]
>I suspect many people are using verbose=True and then writing their own scripts that parse the output and graph them
True. Although I just used a few vim commands to get a csv from the log. No need for a script.
Peter

**Comment by 1Biaohe** [comment]
> > I suspect many people are using verbose=True and then writing their own scripts that parse the output and graph them
> 
> True. Although I just used a few vim commands to get a csv from the log. No need for a script. Peter

Yes. I used the argument: verbose=True, but I still cannot obtain the values of G loss and D loss. So, could you please tell me how to do to output a .csv file as you said (vim commands)?
Since I'm a new learner in machine learning, so I don't understand it. 

Many thanks!

**Comment by 1Biaohe** [comment]
> 

Thanks for your reply!
so, I'd like to know where I can do it (feature request). At the SDV project?

**Comment by pgp44** [comment]
@1Biaohe 
- Copy the log in some file, e.g. loss.csv
- Open it in vim
- Execute the following vim commands

```
%s/Epoch //g
%s/ Loss G: //
%s/Loss D: //
```
- write the file back

This should give you a csv that can be used in most viz tools
(I used https://insights.datylon.com/stories/o0oZZXV9buJlYEs06sBBxA  but that is just because I work there...drink your own champagne as they say :) )

**Comment by npatki** [comment]
@1Biaohe, you can file a feature request directly in the SDV repo. [Here's the link](https://github.com/sdv-dev/SDV/issues/new?assignees=&labels=feature+request%2C+new&template=feature_request.md&title=). Fill out as much as you need and we can take it from there.

**Comment by 1Biaohe** [comment]
> @1Biaohe
> 
> * Copy the log in some file, e.g. loss.csv
> * Open it in vim
> * Execute the following vim commands
> 
> ```
> %s/Epoch //g
> %s/ Loss G: //
> %s/Loss D: //
> ```
> 
> * write the file back
> 
> This should give you a csv that can be used in most viz tools (I used https://insights.datylon.com/stories/o0oZZXV9buJlYEs06sBBxA but that is just because I work there...drink your own champagne as they say :) )

Thanks a lot for your sharing!
I'll do it based on your comments.

**Comment by 1Biaohe** [comment]
> @1Biaohe, you can file a feature request directly in the SDV repo. [Here's the link](https://github.com/sdv-dev/SDV/issues/new?assignees=&labels=feature+request%2C+new&template=feature_request.md&title=). Fill out as much as you need and we can take it from there.

Thanks for your reply!
I've already submitted a feature request. Hopeful you can solve it.

**Comment by npatki** [comment]
Thanks! Let's continue any discussion on the feature request, which we'll keep open for tracking. I'll close this issue since we've answered the question.
