### ISSUE TITLE
The `Handling Constraints` tutorial needs to be rerun

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#824]
The `tutorials/single_table_data/05_Handling_Constraints` notebook is out of sync with the `docs/user_guides/single_table/handling_constraints.rst` file and should be rerun.

**Comment by npatki** [comment]
In the latest version of SDV 0.16.0, we made significant updates to the constraints API and updated the [tutorial notebook](https://github.com/sdv-dev/SDV/blob/master/tutorials/single_table_data/05_Handling_Constraints.ipynb) to match. 

Marking this as closed.
