### ISSUE TITLE
Problem with timeseries sequence generation

### ISSUE THREAD

**Issue by faridasabry** [sdv-dev/SDV#825]
I am using the PAR model to fit a dataset of timeseries sequences with the 'sequence_index' a timestamp column with timestep of 1s for each sample of a subject. The generated dataset by SDV using model.sample(..) doesn't follow this pattern, instead timestamps are generated without any uniform pattern as in the sample below:  
```
2021-11-01 20:41:58       y          y  1911.011498   
2021-11-02 09:25:52       y          y  1890.021213   
2021-11-02 14:09:13       y          y  1878.813698   
2021-11-02 15:45:54       y          y  1861.095320   
2021-11-02 19:27:48       y          y  1837.509757
```

Is this the normal behaviour of SDV, or do I miss something? Are the other variables generated based on this generated timestamp column timestep or can I treat the other generated variables as timeseries following the input 1s timestep and ignore this generated timestamp col?

I tried a workaround to replace the timestamp column with a serial data for each sequence, i.e. 0,1,2,3... and then to generate a  timestamp column with a random start for the generated synthetic data by SDV. However, I received a KeyError for the serial column I added with the trace error below. Can't the 'sequence_index' be a sequential integer series?

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3080             try:
-> 3081                 return self._engine.get_loc(casted_key)
   3082             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'ser'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_5716/4054875235.py in <module>
----> 1 data_samples = model.sample(num_sequences=50)

~/.local/lib/python3.8/site-packages/sdv/timeseries/base.py in sample(self, num_sequences, context, sequence_length)
    265 
    266         sampled = self._sample(context, sequence_length)
--> 267         return self._metadata.reverse_transform(sampled)
    268 
    269     def save(self, path):

~/.local/lib/python3.8/site-packages/sdv/metadata/table.py in reverse_transform(self, data)
    712                 field_data = pd.Series(Table._get_fake_values(field_metadata, len(reversed_data)))
    713             else:
--> 714                 field_data = reversed_data[name]
    715 
    716             reversed_data[name] = field_data[field_data.notnull()].astype(self._dtypes[name])

~/.local/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3022             if self.columns.nlevels > 1:
   3023                 return self._getitem_multilevel(key)
-> 3024             indexer = self.columns.get_loc(key)
   3025             if is_integer(indexer):
   3026                 indexer = [indexer]

~/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3081                 return self._engine.get_loc(casted_key)
   3082             except KeyError as err:
-> 3083                 raise KeyError(key) from err
   3084 
   3085         if tolerance is not None:

KeyError: 'ser' 

```

**Environment:**
Ubuntu 20.04
python 3.8
SDV 0.14.0

**Comment by npatki** [comment]
Hi @faridasabry, thanks for filing! The PAR model does take the `sequence_index` values into account. The synthetic data should have the following properties: 

- The rows for each entity should be in order; that is, the `sequence_index` should increase
- The other variables should capture correlations with the `sequence_index` (it is not ignored)
- The entire row (aka all variables) should also capture correlations with the row before it

The PAR model is not yet optimized to work for the case of fixed intervals. You are welcome to file a new issue so that we can track this!

> I tried a workaround to replace the timestamp column with a serial data for each sequence, i.e. 0,1,2,3... and then to generate a random timestamp column for the generated synthetic data by SDV. However, I received a KeyError for the serial column I added with the trace error below. Can't the 'sequence_index' be a sequential integer series?

The intention is to allow this case, but there is currently a bug. You can follow #808 for updates.

**Comment by faridasabry** [comment]
Thanks a lot @npatki.
I will file a new issue with the fixed interval time sequence issue as it is important for the model to handle this and learn the sequence pattern in the sequence_index to generate a sequence_index with similar time-step interval or impute the missing rows if the sequence doesn't record all the time steps and thus more accurate synthetic data will be generated for the variables.
