### ISSUE TITLE
Provide a description for the PARModel (including evaluation & benchmarking)

### ISSUE THREAD

**Issue by mabotti** [sdv-dev/SDV#840]
Hi There,

I have a question. 
In the PAR Model guide it is written that "The PAR class is an implementation of a Probabilistic AutoRegressive model". 
Which one in particular? Is there a documentation regarding the theoretical aspects of that model?

Thanks.

**Comment by npatki** [comment]
Hi @mabotti, the bad news is that we don't have any published papers or other technical references yet. The good news is that we are working on it and will share it with the SDV community as soon as we do!

I know there has been an interest in this from multiple users, so I'll label this issue as `docs` and retitle it.

In the meantime, you are welcome to go through the code (though I know this is not ideal).
- The core components of the PARModel are implemented in the [DeepEcho library](https://github.com/sdv-dev/DeepEcho/blob/master/deepecho/models/par.py)
- Then, there is an [integration with the SDV library](https://github.com/sdv-dev/SDV/blob/master/sdv/timeseries/deepecho.py#L148)

**Comment by mabotti** [comment]
Thank you!

**Comment by vandreslime** [comment]
Hi @npatki , Can you roughly say what time scope can be expected for the release of the PAR model description?

**Comment by kveerama** [comment]
@vandreslime we have an initial version up [at this link ](https://arxiv.org/pdf/2207.14406.pdf)

**Comment by vandreslime** [comment]
@kveerama Amazing, thank you so much!! 👍

**Comment by npatki** [comment]
Hi @mabotti and @vandreslime, as @kveerama mentioned, we've published the initial version of the PAR Model documentation:

https://arxiv.org/pdf/2207.14406.pdf

I'll mark this issue as closed. If you have any questions or feedback, feel free to open new issues or [join our Slack](https://bit.ly/sdv-slack-invite) to ask there.

**Comment by mabotti** [comment]
Hi @npatki and @kveerama,
thank you !
