### ISSUE TITLE
pip install sdv failed

### ISSUE THREAD

**Issue by lcheng61** [sdv-dev/SDV#844]
### Environment details
Linux
If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: Latest(if possible)
* Python version:3.7
* Operating System:Linux

### Problem description

Can't install sdv
### What I already tried
pip install failed saying the required version can't be found and no matching distribution found for sdv.

```
pip install  --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --user sdv

ERROR: Could not find a version that satisfies the requirement sdv (from versions: none)
ERROR: No matching distribution found for sdv
```
I also tried
```
pip install  --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --user sdv==0.14.0

ERROR: Could not find a version that satisfies the requirement sdv==0.14.0 (from versions: none)
ERROR: No matching distribution found for sdv==0.14.0
```

**Comment by npatki** [comment]
Hi @lcheng61, the latest version of SDV is `0.15.0`. Is there a particular reason you want to use the older `0.14.0`?

I am, unfortunately, not able to replicate this issue on a Mac, but the main thing that comes to mind is that you're trying to install to `--user`. Do you have any other conflicting libraries already installed? I'd strongly recommending using a fresh virtual environment to avoid conflicts. I use [virtualenv](https://virtualenv.pypa.io/en/latest/).

Here are the steps I used to get it to work:
```
> virtualenv -p python3.7 env
> source env/bin/activate
(env)> pip install sdv

Alternatively this also works:
(env)> pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org sdv

```

**Comment by npatki** [comment]
Hello, this issue has been inactive for a few weeks. I'll close it since we discussed some solutions above.

Please feel free to reply if you're continuing to have installation problems and I can reopen the issue.
