### ISSUE TITLE
HMA1 when sampling: ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by itsmeale** [sdv-dev/SDV#852]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.15.0
* Python version: 3.8.2
* Operating System: Debian GNU/Linux 10 (buster)

### Error Description

Exception raised when calls `model.sample()` for HMA1 fitted model.

### Steps to reproduce

I have 3 tables:
`people`: containing personal data
`person_place`: containing places where people go (unique combinations)
`events`: containing events realized by people when they go to some place

```python
from sdv import Metadata

metadata = Metadata()

metadata.add_table(
    name="people",
    data=people_df,
    primary_key="person_id",
)

metadata.add_table(
    name="person_place",
    data=person_place_df,
    parent="people",
    primary_key="id",
    foreign_key="person_id",
)

metadata.add_table(
    name="events",
    data=events_df,
    parent="person_place",
    foreign_key="person_place_id",
)

 model_kwargs = {
      "field_distributions": {
          "__person_place__person_id__num_rows": "gaussian_kde",
          "__events__person_place_id__num_rows": "gaussian"
      }
  }

hma1 = HMA1(metadata=metadata, model=GaussianCopula, model_kwargs=model_kwargs)
hma1.fit(tables)
hma1.save("...")
```

Here is the traceback
```
ValueError                                Traceback (most recent call last)
... Cell 18' in <cell line: 1>()
----> [1](...) t = gaussian_model.sample(num_rows=10)

File ~/.cache/pypoetry/virtualenvs/synth78-PFKju1_X-py3.8/lib/python3.8/site-packages/sdv/relational/base.py:185, in BaseRelationalModel.sample(self, table_name, num_rows, sample_children, reset_primary_keys)
    182 if reset_primary_keys:
    183     self._reset_primary_keys_generators()
--> 185 return self._sample(table_name, num_rows, sample_children)

File ~/.cache/pypoetry/virtualenvs/synth78-PFKju1_X-py3.8/lib/python3.8/site-packages/sdv/relational/hma.py:594, in HMA1._sample(self, table_name, num_rows, sample_children)
    592 for table in self.metadata.get_tables():
    593     if not self.metadata.get_parents(table):
--> 594         self._sample_table(table, num_rows, sampled_data=sampled_data)
    596 return self._finalize(sampled_data)

File ~/.cache/pypoetry/virtualenvs/synth78-PFKju1_X-py3.8/lib/python3.8/site-packages/sdv/relational/hma.py:553, in HMA1._sample_table(self, table_name, num_rows, sample_children, sampled_data)
    550 sampled_data[table_name] = table_rows
    552 if sample_children:
--> 553     self._sample_children(table_name, sampled_data, table_rows)
    555 return sampled_data

File ~/.cache/pypoetry/virtualenvs/synth78-PFKju1_X-py3.8/lib/python3.8/site-packages/sdv/relational/hma.py:428, in HMA1._sample_children(self, table_name, sampled_data, table_rows)
    425     self._sample_child_rows(child_name, table_name, row, sampled_data)
    427 child_rows = sampled_data[child_name]
...
--> 488     raise ValueError(
    489         "array must not contain infs or NaNs")
    490 return a

ValueError: array must not contain infs or NaNs
```

**Comment by npatki** [comment]
Hi @itsmeale, thanks for reporting this bug including the detailed steps. To replicate the error, it would be helpful if you could provide us with the full metadata. You can get this by running:

```python
metadata.to_dict()
```

BTW there are a few other times users have reported this error -- see #342 and #650. It has usually been caused by inconsistencies in the primary/foreign key relationships. Could you confirm whether all of the following are true in your dataset?

- There are no missing values in any primary key columns
- There are no missing values in any of the foreign key columns
- All primary keys values are unique within the table
- All foreign keys of a table refer to an existing primary key value 

Note that the SDV only supports one-to-many relationships. The parent = the primary key column, and the child = the foreign key column.

**Comment by itsmeale** [comment]
The `metadata.to_dict()` output
```json
{
    "tables":{
       "people":{
          "fields":{
             "age":{
                "type":"numerical",
                "subtype":"integer"
             },
             "person_id":{
                "type":"id",
                "subtype":"string"
             },
             "address":{
                "type":"categorical"
             }
          },
          "primary_key":"person_id"
       },
       "person_place":{
          "fields":{
             "person_id":{
                "type":"id",
                "subtype":"string",
                "ref":{
                   "table":"people",
                   "field":"person_id"
                }
             },
             "place_id":{
                "type":"categorical"
             },
             "id":{
                "type":"id",
                "subtype":"string"
             }
          },
          "primary_key":"id"
       },
       "events":{
          "fields":{
             "date":{
                "type":"datetime"
             },
             "name":{
                "type":"categorical"
             },
             "person_place_id":{
                "type":"id",
                "subtype":"string",
                "ref":{
                   "table":"person_place",
                   "field":"id"
                }
             }
          }
       }
    }
 }
```

I check the constraints about PKs and FKs, I found one inconsistency on the primary key of people table, there are some duplicated primary keys, I'll make new testes fixing this inconsistency and report the results here.

I noticed that using parametric distributions for the num_rows columns the sampling method works. But in my case, fitting just for the relation `people <> person-place`, the non-parametric gives the best distribution of the number of generated rows on the person_place table for each person. When adding a child table for the `person_place` table the sampling breaks.

**Comment by npatki** [comment]
Thanks for the metadata @itsmeale, I can confirm that the specification is correct and that the SDV should be able to support this overall schema. 

> I found one inconsistency on the primary key of people table, there are some duplicated primary keys

Based on the other issues we've seen, this might solve it.

> When adding a child table for the person_place table the sampling breaks.

Unfortunately, the HMA1 algorithm only supports parametric modeling. We are tracking issue #457 for being able to model multi table datasets using non-parametric modeling techniques. You are welcome to follow and add to it. To help us prioritize, we'd love to hear what kind of datasets you're using (research? enterprise?) and how you plan to use the synthetic data.

**Comment by npatki** [comment]
Hello, it seems we've addressed the root cause of the `ValueError`, so I'll close this issue off since it's been inactive for a few weeks. Please feel free to reply if there is more to discuss and I'll re-open the issue.
