### ISSUE TITLE
How can I synthesise relational (multi-table) data with temporal dependencies?

### ISSUE THREAD

**Issue by vandreslime** [sdv-dev/SDV#863]
### Environment details

* SDV version: 0.15.0
* Python version: 3.8.9
* Operating System: MAC

### Problem description

I want to synthesise a part of the MIMIC IV dataset, which includes electronic heath records that naturally have temporal dependencies (like types of medications AFTER certain diagnosis). I understand that the PAR model should be able to tackle this problem, right?
Furthermore, I have multiple tables that are connected over a subject_id or hosp_id. I understand that this should be treated over a metadata dictionary, right? How can I use metadata info within the PAR model while specifying entity, context and sequence_index for all the the tables? Is this somehow supported?

### What I already tried

I already tried to simply construct the metadata json file and learn a normal SDV model:

```
sdv = SDV()
sdv.fit(metadata, tables)
sampled = sdv.sample_all()
```
I doubt that it really captures the longitudinality (temporal associations) within the data, does it?

**Comment by npatki** [comment]
Hello, I'll close this issue off since we've answered the question. We'll update the related feature request as we make progress on it.
