### ISSUE TITLE
Existing evaluation/benchmarking of the PAR model?

### ISSUE THREAD

**Issue by vandreslime** [sdv-dev/SDV#870]
### Environment details

SDV version: 0.15.0
Python version: 3.8.9
Operating System: MAC

### Problem description

I wonder if you have an existing evaluation and/or benchmarking of the PAR model with results. Amazing would be something with regards to performance in capturing statistical properties, associations between variables, longitudinality, rare indications and especially protection of privacy. But anything in that direction would be already super helpful!

**Comment by npatki** [comment]
Hi @vandreslime, the good news is that the team is actively writing a sharing a technical description of the PAR model, which will include some basic evaluation and benchmarking. We're working hard to get this out as soon as possible!

We do have an open, existing feature request to provide such a description. I'll close this issue in favor of #840, which we're using for tracking. Please feel free to add to that issue if you have any more feedback about this.
