### ISSUE TITLE
Add key related methods to SingleTableMetadata

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#880]
### Problem Description

_As a user, it would be useful to be able to programmatically set primary keys, sequence keys, sequences indices and alternate keys._

### Expected behavior

- Add `set_primary_key(id)` method
    - Parameters:
        - `id`: string of column name that is going to be the primary key, or tuple string column names
    - Should set the `primary_key` attribute in the dict
    - Warnings:
        - If there is already a key raise this warnings
        `Warning: There is an existing primary key 'user_id'. This key will be removed.`
```python
>>> metadata.set_primary_key(id='user_id')

# for a composite key, users can input a tuple
# Note: we chose to make the input a tuple bc it's immutable
>>> metadata.set_primary_key(id=('first_name', 'last_name'))
Warning: There is an existing primary key 'user_id'. This key will be removed.
```

 - Add `set_sequence_key(id)` method
     - Parameters:
        - `id`: string of column name that is going to be the sequence key
     - Updates the `sequence_key` in the dict
 - Add `set_sequence_index(column_name)` method
     - Parameters:
        - `column_name`: string of column name that is going to be the sequence index
     - Updates the `sequence_index` in the dict
- Add `add_alternate_keys(ids)` method
    - Parameters:
        - `ids`: A list of strings or tuples of string that represent column names
        - Updates the `alternate_keys` field in the dict
```python
>>> metadata.add_alternate_keys(ids=['username', 'email'])

# for alternate composite key, users can input tuples inside of lists
>>> metadata.add_alternate_keys(ids=[('first_name', 'last_name'), 'ssn'])
```

### Additional context

- For validation and errors, use the same validation as the `validate` method in #879.

**Comment by fealho** [comment]
@amontanez24 A few questions: 

1. Do we only want to add the `warning` to the `set_primary_key` method? Why not to the others?
2. Could you double check that the argument names are correct (`id`, `ids` and `column_name`)? I'm just not sure why we are calling one of them `column_name` and not `id`.
3. The [validate issue](https://github.com/sdv-dev/SDV/issues/879) has some discrepancies with this file:
    - Are only tuples allowed for the primary_key/add_alternate_keys methods, or can they also be lists?
    - Can sequence_key be a list?

Finally, I'm unsure what the following lines are for:
https://github.com/sdv-dev/SDV/blob/106621fad234e3c7fd1d83c8d565d8e4e7216de2/sdv/metadata/single_table.py#L104-L108

Should the `set_key` methods set these variables as well?
