### ISSUE TITLE
NaNs in Covariance matrix for parent models

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#9]
* SDV version:
* Python version:
* Operating System:

### Description

If you model the database, the parent models receive data with NaNs, and then end up with covariance matrices that have nans. This makes sampling impossible.

Two possible causes:
1. Some parent primary keys are never referenced, so the extension is null.
2. The covariance matrix for different conditional data may have different sizes. This is likely a bug in copulas where numpy.cov is taking the rows as variables instead of the columns.

**Comment by kvrameshreddy** [comment]
Hi @amontanez24 ,

How did you solved the above issue in the model.

**Comment by amontanez24** [comment]
> Hi @amontanez24 ,
> 
> How did you solved the above issue in the model.

Based on the description of the issue, it looks like this commit attempted to fix the 2nd point.
https://github.com/sdv-dev/Copulas/commit/1b8346574b4dd8f2aa6b53c10cb33dd88f3fde1c

**Comment by kvrameshreddy** [comment]
Thank you @amontanez24 . Can you please check this issue #172 . I am unable to solve it.
