### ISSUE TITLE
Generate a part of the data given complete data

### ISSUE THREAD

**Issue by NadeemNicoR** [sdv-dev/SDV#900]
I have two datasets , lets call them as D1 and D2
D1 has only Sensor data while D2 has Sensor data + geometrical data. now D1 size is way more than D2, D2 is around lets say 1000 and D1 is around 15000  examples, I want to use the D2 data to some how generate the geometrical data given Sensor data (use conditional generator). so that i can generate Geometrical data for D1 and associate it with the correspondingly close sensor data.

is this feature already available or is there some adjustment that i can make to have my GAN trained in the above manner. Kindly advice. any response is appreciated

**Comment by npatki** [comment]
Hello, I'm marking this issue as closed since we've answered your question and the feature already exits.

Please feel free to reply if you have more thoughts or if I am misunderstanding the feature request. I can reopen the issue for continued discussion.
