### ISSUE TITLE
even after setting the random seed value constant i still con not produce the same results

### ISSUE THREAD

**Issue by NadeemNicoR** [sdv-dev/SDV#902]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* CTGAN version: 0.13.0
* Python version: 3.8
* Operating System: win10

### Steps to reproduce

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @NadeemNicoR, I'll close this issue off as stale since I'm unable to replicate this on the newer versions of the SDV. 

Please reply if you still observe the randomness and I can reopen for investigation.
