### ISSUE TITLE
IndexError: list index out of range - while fitting the PAR model

### ISSUE THREAD

**Issue by vandreslime** [sdv-dev/SDV#905]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.15.0
* Python version: 3.8.9
* Operating System: MAC

### Error Description

I tried to synthesize event data using the sdv PAR model. However, I get an IndexError when fitting the model.

### Steps to reproduce

I only have the columns subject_id, event, cluster, time and relative_time.
Here are more details about the data:

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 364017 entries, 0 to 364016
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype         
---  ------         --------------   -----         
 0   subject_id     364017 non-null  int64         
 1   event          364017 non-null  object        
 2   cluster        85320 non-null   object        
 3   time           364017 non-null  datetime64[ns]
 4   relative_time  364017 non-null  float64       
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 13.9+ MB
None
```

This is the code I used:

```
data = pd.read_csv("event_data.csv", low_memory=False, parse_dates=['time'])
data['time'] = pd.to_datetime(data['time'])

entity_columns = ['subject_id']
sequence_index = 'time'

print(f"Cuda available: {torch.cuda.is_available()}")

model = PAR(entity_columns=entity_columns,sequence_index=sequence_index)
model.fit(data)
```

I received the following error when running:

```
Traceback (most recent call last):
  File "parmodel copy 2.py", line 22, in <module>
    model.fit(data)
  File "/root/medmodels-dev/.venv/lib/python3.8/site-packages/sdv/timeseries/base.py", line 210, in fit
    self._fit(transformed)
  File "/root/medmodels-dev/.venv/lib/python3.8/site-packages/sdv/timeseries/deepecho.py", line 87, in _fit
    self._model.fit_sequences(sequences, context_types, data_types)
  File "/root/medmodels-dev/.venv/lib/python3.8/site-packages/deepecho/models/par.py", line 318, in fit_sequences
    X.append(self._data_to_tensor(sequence['data']))
  File "/root/medmodels-dev/.venv/lib/python3.8/site-packages/deepecho/models/par.py", line 213, in _data_to_tensor
    if pd.isnull(data[key][i]) or props['std'] == 0:
IndexError: list index out of range
```

**Comment by npatki** [comment]
Hi @vandreslime, seems like we have an existing issue filed for handling sequences of length 1. I'll close off this issue in favor of #350. Feel free to follow along for any updates or discussion.

Please let me know if you are observing this issue with sequences that have a length of 2 or more. In that case, this would be a new bug and we can track it separately.

**Comment by vandreslime** [comment]
Hi @npatki , sorry for the late response. Indeed I have some subject_ids that occur only one time - so the sequence has length 1. Is it planned to fix this issue in the near future? Is there a work around, that you could suggest me to try out now? Thank you very much!

**Comment by npatki** [comment]
Hi @vandreslime, let's continue this conversation in #350.  I just left a comment there with an idea for a workaround.
