### ISSUE TITLE
How to fit a so large dataset?

### ISSUE THREAD

**Issue by Alaskyed** [sdv-dev/SDV#916]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.15.0
* Python version: 3.8.13
* Operating System: Windows 11

### Problem description

Hi, I wonder if I have a big dataset with many values, I cannot fit it in just one time. In this case, how can I do to fit the whole dataset well? Does SDV has a method to fit new data samples more than one time to update the model?

**Comment by npatki** [comment]
Hi @Alaskyed, nice to meet you. I might be able to direct you to some solutions but I need a bit more context.

Could you provide a few more details about your use case?

- How many rows, columns and tables are in your dataset? And what is its overall file size (eg. 10MB)
- You say you cannot fit the dataset in time. Which SDV model(s) have you already tried and how long was the process taking?
- How are you planning to use the synthetic data?

**Comment by Alaskyed** [comment]
Hi, @npatki, thanks for your apply! It's great to see you!
I'm almost a novice so if there are some skills I haven't learned, I hope you can understand 😅.

About the details:

- My dataset is a pretty large table, it's a about 30GB with more than 10k categories in features. It has 300 million rows and about 20 columns in dataset.
- Actually I run a demo and I can fit a sample use 'fit()' method. It's no problem! I'm trying CTGAN model. However my question is that I extracted a sample for fitting model, and then,  I want to use more samples to fit this model many times to improve the model. In a word, using new samples to fit the previous model (not just 1 time). But I found every time I fit a new sample, the model will drop all parameters of the previous fit then start a  new fit (like a new model), instead of updating the parameters based on the previous one.
- About my planning, that's my project in uni, to generate synthetic data about medical recordings.

Thanks for your explanation!

**Comment by npatki** [comment]
Thanks for the details and no problem! I understand that you're trying to generate synthetic data about medical records, but how are you planning to _use_ the synthetic medical records?

Depending on your desired usage, I wonder if the [TabularPreset](https://sdv.dev/SDV/user_guides/single_table/tabular_preset.html) will work for you? The `FAST_ML` preset is especially designed for speed. As a benchmark, consider that 100K rows with around 100 columns takes only a few minutes to model. More info is available [here](https://github.com/sdv-dev/SDV/discussions/786).

BTW Taking a subsample and using it to `fit` a model is a great approach. Your model may not really require all the 300 million examples to effectively learn the trends.

**Comment by Alaskyed** [comment]
Hi! Thanks for your reply.
That's a part of project of my project. I simulate more data providing to other members of my group to do some predict.

Thanks for your advice! I'll try TabularPreset then! 
But for some AI models, I hope it can be trained many times with more data to improve the model in the future😊For example I train a model and save it. When I get more new data, I can load the model and train it twice. That's we awalys do in neural network.

**Comment by npatki** [comment]
Sounds good. 

The SDV models do not yet allow for incremental training. We're using issue #805 to track progress & provide updates on this. Feel free to follow along and join the discussion.

**Comment by npatki** [comment]
Hi @Alaskyed, I'll close off this issue since we've answered your initial question. Let's use #805 for continued discussion around incremental training & dealing with large datasets.
