### ISSUE TITLE
AttributeError 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by yamidibarra** [sdv-dev/SDV#955]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

SDV version: 0.16.0
Python version: 3.8.13
Operating System: Windows 10

### Error Description

I´m trying to use TVAE but I get the error 'NoneType' object has no attribute 'split' in line  model.fit(data)

I have already change the object column by string, I also used the LavelEncoder to turn it into numbers but I still get the same error. I can not see what´s going on. Thanks for your help. 

### Steps to reproduce

Here is attach a little database and the .py file 

```

from sdv.tabular import TVAE
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import re

data = pd.read_pickle('df_PAR.pkl')
label_encoder = LabelEncoder()
data.iloc[:,1] = label_encoder.fit_transform(data.iloc[:,1]) # Transform POM categorical into numerical
df = data.copy()

model = TVAE()

model.fit(data)
new_data = model.sample(num_rows=1000)
```

**Comment by yamidibarra** [comment]
CopulaGAN has the same error..

**Comment by yamidibarra** [comment]
Dear [npatki](https://github.com/npatki),

has this error occurred before? it´s also happening with the demo data available in the SDV library.

**Comment by LiFaytheGoblin** [comment]
Hi @yamidibarra , 

I don't have the answer to your question but I am a fellow beginner in SDV and want to share my thoughts: 

You don't need to do any data type transformations as SDV is able to handle them via https://sdv.dev/SDV/developer_guides/overview.html?highlight=rdt 

My next try would be to create a metadata file where you explicitly tell SDV which column has which type.

Good luck!

**Comment by npatki** [comment]
Hi @yamidibarra,

Yes, I second @LiFaytheGoblin's answer. The SDV has built-in transformations. You can specify the transformations when you create the model -- see [API for TVAE](https://sdv.dev/SDV/api_reference/tabular/api/sdv.tabular.ctgan.TVAE.html), particularly the `field_transformers` parameter..

For what it's worth, I am unable to replicate the data on the demo data.

```python
from sdv.tabular import TVAE
import pandas as pd
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data.iloc[:,1] = label_encoder.fit_transform(data.iloc[:,1])

model = TVAE()
model.fit(data)
new_data = model.sample(num_rows=1000)
```

It would be helpful if you could provide a stack trace.

**Comment by yamidibarra** [comment]
Dear @npatki, I found my error, thank you!.
 I was working in a different environment than the one I installed the library...

**Comment by prashanth1407** [comment]
Hi @yamidibarra could you touch upon how you resolved the issue? I am facing the same issue right now. It would be great if you could share the process of how you resolved it.
