### ISSUE TITLE
The two models cannot be used at the same time.

### ISSUE THREAD

**Issue by Alaskyed** [sdv-dev/SDV#971]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.16.0
* Python version: 3.8.13
* Operating System: Windows 11

### Error Description

If I train two models at the same time, in some cases, the data generated by the first trained model will report an error. After testing, this error occurs when constraints are used.

### Steps to reproduce
For example, if I wanna use TabularPreset and CTGAN:
At first, I train a TabularPreset model, and it works well.

```python
tabular_model = TabularPreset(
    name='FAST_ML',
    constraints=constraints.copy()
    )
tabular_model.fit(train_data)
tabular_model.sample(10)
```
Then I train a CTGAN model, it works as well.
```python
ctgan_model = CTGAN(
    constraints=constraints, 
    cuda=True)
ctgan_model.fit(train_data)
ctgan_model.sample(10)
```
But next, after training CTGAN model, when I used TabularPreset model trained before again. It would show an error:

```python
tabular_model.sample(10)
```
The error is : 
```
loop of ufunc does not support argument 0 of type float which has no callable rint method
```
In this case, the model trained later can be used well, but the model trained earlier has errors.

**Comment by npatki** [comment]
Hi @Alaskyed, unfortunately I am not able to replicate this with the demo data (see code below). It would be helpful if you are able to provide more details about what you're observing.

1. Does the code below work for you?
2. What is the full stack trace of the error message?
3. What kinds of constraints do you have and does it work without the constraints?

### Code Snippet

I tried this and there were no errors.

```python
from sdv.demo import load_tabular_demo
from sdv.constraints import Unique, Inequality
from sdv.lite import TabularPreset 
from sdv.tabular import CTGAN

data = load_tabular_demo()

# create some constraints for the data
# directly borrowed from the user guide
unique_employee_id_company_constraint = Unique(
    column_names=['employee_id', 'company']
)

age_gt_age_when_joined_constraint = Inequality(
    low_column_name='age_when_joined',
    high_column_name='age'
)

constraints = [
    unique_employee_id_company_constraint,
    age_gt_age_when_joined_constraint
]

# run your code
tabular_model = TabularPreset(
    name='FAST_ML',
    constraints=constraints.copy()
    )
tabular_model.fit(data)
tabular_model.sample(10)

ctgan_model = CTGAN(
    constraints=constraints, 
    cuda=True)

ctgan_model.fit(data)
ctgan_model.sample(10)

tabular_model.sample(10) # works just fine -- no errors are thrown
```
