### ISSUE TITLE
HMA KeyError while sampling

### ISSUE THREAD

**Issue by MattNot** [sdv-dev/SDV#999]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.16.0
* Python version: 3.9
* Operating System: W10 

### Error Description

Hi, i got a strange error while sampling with HMA.
The error appears to be a Key_Error in the method _sample_children:

```
        for child_name in self.metadata.get_children(table_name):
            if child_name not in sampled_data:
                LOGGER.info('Sampling rows from child table %s', child_name)
                for _, row in table_rows.iterrows():
                    self._sample_child_rows(child_name, table_name, row, sampled_data)

                child_rows = sampled_data[child_name] <<<<< Here the exception
                self._sample_children(child_name, sampled_data, child_rows)
```

Debugging it i found that in _sample_child_rows when doing this:
`
parameters = self._extract_parameters(parent_row, table_name, foreign_key)
`
parameters .pop('num_rows') in this dict appears to be 0, BUT if you check for self._models[table_name]._num_rows is correct.

Infact, changing the code of _sample_child_rows from this:

```
    def _sample_child_rows(self, table_name, parent_name, parent_row, sampled_data):
        foreign_key = self.metadata.get_foreign_keys(parent_name, table_name)[0]
        parameters = self._extract_parameters(parent_row, table_name, foreign_key)

        table_meta = self._models[table_name].get_metadata()
        model = self._model(table_metadata=table_meta)
        model.set_parameters(parameters)
```

To this:
```
    def _sample_child_rows(self, table_name, parent_name, parent_row, sampled_data):
        foreign_key = self.metadata.get_foreign_keys(parent_name, table_name)[0]
        parameters = self._extract_parameters(parent_row, table_name, foreign_key)

        table_meta = self._models[table_name].get_metadata()
        model = self._models[table_name]
        num_rows = model._num_rows
        model.set_parameters(parameters)
        model._num_rows = num_rows
```
Seems solving the problem. Did I found a bug or what? I can do PRs if needed.

## Steps

The schema is a star-schema, meaning that there's 1 father and 5 children all connected to the PK of the father.

**Comment by npatki** [comment]
Hi @MattNot thanks for filing this issue and the proposed changes. To help me put this into context, could you describe the usage that is triggering the `KeyErorr`? I'm particularly interested in:

- Any relevant details about the data. If it's possible to share your metadata file, that would be great
- The code you're using to create and sample data
- The stack trace of the `KeyError`

That will help me connect the dots between the problem and the proposed fix. Thanks!

**Comment by npatki** [comment]
Hi @MattNot haven't heard from you in a while. Are you still experiencing this error?

I'm going to close this issue off because I wasn't able to replicate it. If you are still seeing the error, feel free to reply and I will reopen the issue for more investigation.
